### ISSUE TITLE
Add compatibility with Blender-geo

### ISSUE THREAD

**Issue by domlysz** [domlysz/BlenderGIS#10]
https://github.com/vvoovv/blender-geo

It use transverse Mercator projection (not UTM) with dynamically calculated central meridian to minimize distortions. The central meridian comes through the center of the imported area.

https://github.com/vvoovv/blender-geo/wiki/Georeferenced-Blender-Scene

proj4 string equivalent:

+a=6378137 +b=6378137 +proj=tmerc +lat_0=0 +lon_0=6 +k_0=1 +x_0=0 +y_0=0 +units=m
with lon_0 = central meridian (here 6°)

To get this compatibility reprojection capability is needed with consequences :
- more dependencies (pyproj, proj4, gdal ...)
- why reimplementing a complex task like reprojection through a Blender addon while dedicated software like QGIS can do it in a more efficient way ?
- need to store projection definition in scene (proj4 string or EPSG code)
- determine input projection from user or from data isn't always an easy task...

**Comment by domlysz** [comment]
In theory fixed with the new  _geoscene_ addon
https://github.com/domlysz/BlenderGIS/commit/4a2f2bd65eb00d31e4899f843a708ab609eeb786

However, user must define manually the crs with the proj4 string described above.

maybee will add special a predefined crs to build this proj4 def with current longitude

**Comment by mirlip** [comment]
Sad that voov doesn't want to change it's plugin, but I can understand his point of view. It's actually good for users. It would be really great to have blender-GIS automatically take the longitude for projection.

**Comment by vvoovv** [comment]
Could you add a compatibility option with _blender-geo_?

If compatibility option with _blender-geo_ is enabled then use the code from [here](https://github.com/vvoovv/blender-geo/blob/master/transverse_mercator.py) to project imported data provided that the data are in WGS84.

**Comment by domlysz** [comment]
There will be no compatibility with blender-geo because design choice are too differents and this feature can't be implemented in a clean and really usable way.

**Comment by mirlip** [comment]
Hi Domlysz,
Is the automatic proj4 string from scene longitude still in plan?

**Comment by domlysz** [comment]
After consideraion, I prefer the second option !

**Comment by mirlip** [comment]
Awesome :) In the BF OSM importer, Campbell added the possibility to import the tags as vertex groups. It's really helpful to be able to know what kind of building/street/open area you have (cafe/theater/hospital, highway/street/pathway, park/forest, etc...). So you still have all in one mesh (also vvoovv's approach to separate building, streets and nature is also great) keeping Blender fast, while retaining the important information. https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/io_scene_open_street_map.py
