### ISSUE TITLE
No module named 'numpy' 

### ISSUE THREAD

**Issue by skarmiglione** [domlysz/BlenderGIS#109]
I cant enable the addon because of that, but i have installed the python-numpy package, it is a bug? or what i am doing wrong.

**Comment by domlysz** [comment]
Are you on linux? using ppa? Blender 2.79 require python 3.6 but some distros actually only provides python 3.5. You can try download binary files directly from blender.org

**Comment by skankingpickle** [comment]
You need to install numpy using pip

install pip : 
sudo apt-get install python-pip python3-pip

Then install numpy using pip:

sudo pip3 install -U numpy

**Comment by domlysz** [comment]
wiki now updated

**Comment by tocom242242** [comment]
I solved this problem by

sudo apt -y install python3-numpy

I use blender on ubuntu
