### ISSUE TITLE
"Get SRTM" creates black/white texture

### ISSUE THREAD

**Issue by apalazzi** [domlysz/BlenderGIS#110]
When I try to use the "Get SRTM" button to get the terrain DEM data the imported texture is only black or white, that is there are no intermediate (gray) colors; so the resulting terrain is completely wrong.

**Comment by domlysz** [comment]
Can you send me a test file ?

**Comment by apalazzi** [comment]
https://www.dropbox.com/s/7xjlitcz4vfkjpc/test_blenderGIS.blend?dl=0

**Comment by domlysz** [comment]
You must apply scale transformation of your plane mesh before using the tool (ctrl+A). The best way to create your plane is to start basemap tool, move to the desired place and then press E to get a new mesh from the background map.

**Comment by apalazzi** [comment]
Ok, it worked, thanks.

**Comment by davix3f** [comment]
Hi, sorry to re-open an old issue but I'm having this exact problem even if I generate the mesh plane using the E key. When I click on "Get SRTM" the mesh disappears (visibile in edit mode), and the srtm texture is just a white picture. [Blender file here](https://gofile.io/d/GwjhDE)
