### ISSUE TITLE
Problem to activate blendergis

### ISSUE THREAD

**Issue by patatedouce2a** [domlysz/BlenderGIS#112]
Hello,

I am a beginner in blender, i try to activate blender gis but i have this error text 
![image](https://user-images.githubusercontent.com/38980896/39627656-e709f1b0-4fa6-11e8-82f2-0e9f41503a13.png)

Thanks to help me !

**Comment by patatedouce2a** [comment]
Salut, merci pour ta réponse ! J'ai beau chercher, je ne trouve pas de fichier stand alone à télécharger sur Blender.org, c'est tout nouveau pour moi.

**Comment by domlysz** [comment]
C'est juste le fichier zip, l'exe est dedans
![selection_005](https://user-images.githubusercontent.com/5639024/39690582-e0d79f50-51da-11e8-997d-f1db3f9c6d96.png)

**Comment by patatedouce2a** [comment]
Super, ça fonctionne ! Merci beaucoup !
