### ISSUE TITLE
Import OSM not working

### ISSUE THREAD

**Issue by mamoonulhaq** [domlysz/BlenderGIS#113]
Hello,

I'm learning this addon and trying to import osm file using it. But when I try to import it gives this error.
![20180510_224309 1](https://user-images.githubusercontent.com/39170871/39891010-faeae766-54b5-11e8-9cd4-1b78dad271b5.jpg)

**Comment by domlysz** [comment]
Hi,

Thank you for pointing this, I've updated the addon now it works as before (there was a recent update on osm query server with a more restrictive query syntax check).
