### ISSUE TITLE
dae file not maintaining terrain data

### ISSUE THREAD

**Issue by welkerCode** [domlysz/BlenderGIS#114]
First off, your plugin is extremely helpful and am happy to have found it.  

My problem is that I have managed to import a GeoTIFF file into Blender as a Mesh, and then use an aerial image to overlay the heightmap.  It looks like so:

![image](https://user-images.githubusercontent.com/17931727/40031844-cd83226a-57ae-11e8-86c5-c6a4be599cb4.png)

However, after I export it to a .dae file (to be used in Gazebo), and then open it again in either Gazebo or Blender, the aerial image is still there, but it is flat like a plane.  It is as if the GeoTIFF information never got saved to the .dae file.

I am new to Blender, do you have any suggestions on how this could happen, and what I could do to fix it?

Thanks!

**Comment by PayamT** [comment]
You should convert the object it to a mesh object before exporting to any software. 
From Viewport’s bottom header > object > convert to > Mesh

Sent from Yahoo Mail for iPhone


On Monday, May 14, 2018, 9:42 PM, welkercode <notifications@github.com> wrote:


First off, your plugin is extremely helpful and am happy to have found it.

My problem is that I have managed to import a GeoTIFF file into Blender as a Mesh, and then use an aerial image to overlay the heightmap. It looks like so:



However, after I export it to a .dae file (to be used in Gazebo), and then open it again in either Gazebo or Blender, the aerial image is still there, but it is flat like a plane.  It is as if the GeoTIFF information never got saved to the .dae file.

I am new to Blender, do you have any suggestions on how this could happen, and what I could do to fix it?

Thanks!

**Comment by welkerCode** [comment]
Thank you for that tip!  I got it working in Gazebo now!

Thanks again!
