### ISSUE TITLE
Error: BigTIFF file not suported

### ISSUE THREAD

**Issue by leonardofmed** [domlysz/BlenderGIS#119]
I'm trying to import a .tif DEM file and I'm getting this error with the option "As DEM".
The file has 500MB, don't even know why it's considering as BigTIFF. I'm already added a larger .tif (Photo mosaic - 800MB - "As plane") and don't get any errors.
Do you know why I'm getting this?

**Comment by domlysz** [comment]
Bigtiff mode can be enable for any file size, even small one. Just make a new copy of the raster with qgis or gdal for producing a version with bigtiff mode disable

**Comment by leonardofmed** [comment]
Can you tell me how to do this with QGIS? I don't find anywhere a option for disable BigTIFF.

**Comment by domlysz** [comment]
Open the raster, right click the layer and select save as... Under "create option",  add a new entry BIGTIFF NO
