### ISSUE TITLE
No textures in exported object

### ISSUE THREAD

**Issue by leonardofmed** [domlysz/BlenderGIS#121]
When I export the file, regardless of the format, it saves without the textures. Only the DEM keeps itself.

Steps I've taken:

1. Import aerial image in .tif format with "As plane" mode
2. Import DEM with the "As DEM" mode and apply to the previous mesh.
3. Convert object to a mesh object. (Object -> Convert to -> Mesh)
4. Cut out parts that are not interesting.

![withtexture](https://user-images.githubusercontent.com/33374703/42588478-5d9d046e-8514-11e8-961a-5a30cc4a175e.png)

5. Export as ... 
6. Open file:
![notexture](https://user-images.githubusercontent.com/33374703/42588550-90f7dbe0-8514-11e8-9c13-928d2c02f926.png)

I'm not very familiar with Blender, sorry for any silly mistake.

**Comment by PayamT** [comment]
Its on solid shading mode. Change to textured or material mode.


Sent from Yahoo Mail for iPhone


On Wednesday, July 11, 2018, 1:15 PM, leonardofmed <notifications@github.com> wrote:


When I export the file, regardless of the format, it saves without the textures. Only the DEM keeps itself.

Steps I've taken:
   
   - Import aerial image in .tif format with "As plane" mode
   - Import DEM with the "As DEM" mode and apply to the previous mesh.
   - Convert object to a mesh object. (Object -> Convert to -> Mesh)
   - Cut out parts that are not interesting.


   
   - Export as ...
   - Open file:   


I'm not very familiar with Blender, sorry for any silly mistake.

**Comment by domlysz** [comment]
What format ? Seems some formats does not support texture, some others requires precautions etc. There are lot of talks about this on the web. For example 
https://blender.stackexchange.com/questions/52214/how-to-export-into-3ds-and-keep-materials

It's not an issue related to BlenderGIS addon, so I close it
