### ISSUE TITLE
Importing `building:levels` with `v="1,2"` fails

### ISSUE THREAD

**Issue by roxlu** [domlysz/BlenderGIS#123]
I downloaded "netherlands-latest.bz2" and after extracting (20GB!) I used osmconvert to get a certain area using `osmconvert netherlands-latest.osm --drop-broken-refs --complete-multipolygons --complete-ways -b=4.8528,52.3288,4.8849,52.3494 -o=amsterdam.osm`.  Then when importing the .osm file into Blender it fails because the .osm file has a v="1,2" value for "building:levels".  Changing that value to 1 or 2 works fine.

**Comment by domlysz** [comment]
Fixed 800f6c6

However, "1,2" is not a correct value for building:levels, this tag must represents a number of levels so it must be an unique integer value. It can be useful to fix it in osm database.

Now incorrect values for building levels will be ignored.
