### ISSUE TITLE
ValueError when importing shapefile

### ISSUE THREAD

**Issue by cbworden** [domlysz/BlenderGIS#126]
I'm getting an error when I attempt to import a shapefile. It is: 'ValueError: invalid literal for int () with base 10."' The shapefile imports and exports from QGIS with no problem. Files are attached.
[mi.zip](https://github.com/domlysz/BlenderGIS/files/2329060/mi.zip)

**Comment by cbworden** [comment]
Forgot to mention that "PARAMVALUE" is the field of interest.

**Comment by domlysz** [comment]
fixed c346927

Thanks for the report

**Comment by cbworden** [comment]
Thanks for the quick fix!

**Comment by FFouriauxEveha** [comment]
I have the same error, and it isn't fixed with c346927. ( I try your file "mi.shp", and I use it with Windows 10 and Blender 2.79

**Comment by FFouriauxEveha** [comment]
I think yes, but it works with a blender 2.78.

So it's ok I guess I continue to work with this version. Thank you

2018-09-12 12:25 GMT+02:00 domlysz <notifications@github.com>:
