### ISSUE TITLE
GDAL - 'no module named _gdal'

### ISSUE THREAD

**Issue by Heryx** [domlysz/BlenderGIS#131]
Hi, 
I installed GDAL from powershell. This is the message of the powershell when I tried to install GDAL

`PS C:\Program Files\Blender Foundation\Blender\2.79\python\bin> python.exe -m ensurepip`
`Requirement already satisfied: setuptools in c:\program files\python36\lib\site-packages`
`Requirement already satisfied: pip in c:\program files\python36\lib\site-packages`

The osgeo folder has been installed in python36. So, I copied and pasted it in site-packages folder. Then I finalize the installation adding the path in GDAL Windows environment variable.
![gdal](https://user-images.githubusercontent.com/11267377/46068861-6e917f00-c17a-11e8-8b01-94711c4bdacc.jpg)

Finally I opend Blender Python console and I typed: `from osgeo import gdal`

This is the error:

`>>> from osgeo import gdal
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\site-packages\osgeo\__init__.py", line 31, in swig_import_helper
    fp, pathname, description = imp.find_module('_gdal', [dirname(__file__)])
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_gdal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\site-packages\osgeo\__init__.py", line 41, in <module>
    _gdal = swig_import_helper()
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\site-packages\osgeo\__init__.py", line 33, in swig_import_helper
    import _gdal
ImportError: No module named '_gdal'
`

**Comment by Heryx** [comment]
> I'm curious on what fonction that rely on GDAL you planned to use

Because I work with data like DEM, raster, Shape files ecc. 

> follow the guide step by step

I try to follow step by step the installation... I'll keep you informed.

**Comment by domlysz** [comment]
The Addon can also import DEM raster (in tiff format) and shapefile without GDAL !

**Comment by domlysz** [comment]
I's all explained in the [disclamer ](https://github.com/domlysz/BlenderGIS/wiki/How-to-install-GDAL)

`GDAL is an optional dependency, most of the functionalities of BlenderGIS are available without it. `

Main functionalities of the addon are descripted in the [home page](https://github.com/domlysz/BlenderGIS) : 
-shapefile import / export
-raster import
-DEM import
-basemaps navigation
-OSM import 
...

All of these fonctions works WITHOUT GDAL, just give it a try

Futhermore in the disclamer

`if you want to deal with heterogeneous data formats, projections or extents, the most straightforward strategy is to preprocess your data with QGIS before trying the import into Blender.`
