### ISSUE TITLE
Strange Ondulations

### ISSUE THREAD

**Issue by leonardofmed** [domlysz/BlenderGIS#133]
Hello, I have a problem with some ondulations that appeared on the model. The image I give as an example represents a road alongside several trees. I believe that the problem is not with the data, being that they are very precise (DJI Phantom 4 Advanced). Do you know why this is happening? If so, is there a way to solve or minimize this problem?

![problem](https://user-images.githubusercontent.com/33374703/46558427-6d232d80-c8c3-11e8-8a15-e7f2e6c20245.png)

**Comment by domlysz** [comment]
Hi,
The resolution of your DEM dataset is just too low. For example if you use SRTM data then the resolution is about 90m in Europe, that's mean one pixel have a width of 90m. Aerial photo is then stretched between 2 DEM pixels steps producing this kind of deformation when the altitude difference is too high. Having a more detailled DEM will help to have a better mapping between the aerial photo and the terrain mesh.

**Comment by leonardofmed** [comment]
Thanks for your answer! I made the model with the highest resolution and the error persists. Some more details:
Orto -> Dimensions: X: 19818 Y: 25796 Bands: 4 | Pixel Size: 0.05104,-0.05104 | File Size 801MB
DEM -> Dimensions: X: 19818 Y: 25796 Bands: 1 | Pixel Size: 0.05104,-0.05104 | File Size 559MB

![problem2](https://user-images.githubusercontent.com/33374703/46571386-7b685c80-c94a-11e8-8b6d-1033b02caaf9.png)

**Comment by domlysz** [comment]
If the DEM was imported with the "As DEM" option then maybe you'll need to increase subdivision level in the mesh's modifier stack. If the terrain is very large a second subsurf can be necessary, but it also may drastically slow down the 3d view navigation.

**Comment by leonardofmed** [comment]
Increasing the number of subdivisions from 6 to 8 seems to solve this problem. I really appreciate your help! Incredible tool, congratulations!

**Comment by leonardofmed** [comment]
How can I reference this addon for a paper?

**Comment by domlysz** [comment]
yes of course !

**Comment by leonardofmed** [comment]
Great! Can I ask your name? I will reference this way:
Author's name, BlenderGiS, (2018), GitHub repository, https://github.com/domlysz/BlenderGIS

**Comment by domlysz** [comment]
yes my name is LYSZCZARZ Dominique. I will be happy to have a copy of your paper when it's finished !
