### ISSUE TITLE
The master plugin is not working 2.79 linux mint

### ISSUE THREAD

**Issue by skarmiglione** [domlysz/BlenderGIS#136]
![gis_blender](https://user-images.githubusercontent.com/12539219/47832906-1267df00-dd66-11e8-9349-88631b5b293f.png)

**Comment by domlysz** [comment]
Please follow installation instructions : https://github.com/domlysz/BlenderGIS/wiki/Install-and-usage
You need to update numpy.

**Comment by skarmiglione** [comment]
![captura de pantalla_2018-11-01_15-31-22](https://user-images.githubusercontent.com/12539219/47878007-433e2780-ddeb-11e8-9686-eb7e367ff983.png)
![captura de pantalla_2018-11-01_15-30-50](https://user-images.githubusercontent.com/12539219/47878009-433e2780-ddeb-11e8-844b-c067dc92400c.png)
I did it, you can see it here but it just dont help

**Comment by domlysz** [comment]
no more support for 2.7x, please retry with blender 2.8
