### ISSUE TITLE
ReferenceError: StructRNA of type MAP_VIEWER has been removed

### ISSUE THREAD

**Issue by oxcxsxixbxaxn** [domlysz/BlenderGIS#139]
Freshly installed add-on, seemed to be working but basemap keeps losing itself.  When I look at the console, it is spilling out the following over and over...  It starts throwing this as soon as I open up blender with the add-on enabled.

Traceback (most recent call last):
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 336, in drawZoomBox
    if self.zoomBoxMode and not self.zoomBoxDrag:
  File "C:\stuff\blender\2.79\scripts\modules\bpy_types.py", line 601, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MAP_VIEWER has been removed

Not sure if it helps but I have GDAL/numpy installed already...
GDAL-2.2.4-cp27-cp27m-win_amd64.whl
numpy-1.14.6+mkl-cp27-cp27m-win_amd64.whl

>>> from osgeo import gdal
>>> 
>>> from osgeo import gdalnumeric
>>> from osgeo import osr
>>> 
>>> osr.SpatialReference().ImportFromProj4('+init=epsg:3857')
0

>>>

**Comment by domlysz** [comment]
Can't reproduced the issue.

Seems MAP_VIEWER operator crash for any reason and have no time to be properly closed, then some remaining handler throw an error. I need more clues about what action cause the basemaps crash

**Comment by oxcxsxixbxaxn** [comment]
I wonder if it was some networking issue, the basemap is currently working.
