### ISSUE TITLE
Handle null values when getting object's names from field 

### ISSUE THREAD

**Issue by BenRacicot** [domlysz/BlenderGIS#14]
I must say that this plugin is one of the best I've ever seen. What huge potential here, thank you for working so hard on it. 

I have quite a few attributes in my shapefile (.dbf?) such as building names. Is there anyway to map them to each 3d item as well? If not perhaps this can be another enhancement opportunity to map attributes with to each Blender item created. Thanks again.

**Comment by domlysz** [comment]
Hi,

When *Separate objects* option is checking it's possible to choose a field as object's name. Is that the option you search for ?

**Comment by BenRacicot** [comment]
Hmm Yeah that was the first thing I tried, However it gave a large error message. Also while I'm here, my shp import is missing about 75% of the buildings. Do you know how I can improve or troubleshoot that?

**Comment by domlysz** [comment]
Can you attach the file for test it?

**Comment by BenRacicot** [comment]
Sure thing. Its the city of providence. If I can help please let me know at benjaminracicot@gmail.com
[pvd-shp.zip](https://github.com/domlysz/BlenderGIS/files/200163/pvd-shp.zip)

**Comment by domlysz** [comment]
I must admit shp importer isn't very well optimized right now, especially *extrusion* option is terribly slow, *separate object* option seems also to have a memory leak. I can't process your file with these options because it's too large but I can process a subset of it, and naming the object according to a field work for me. However, in your shp most buildings have no name (null value in the field *name*) and this case isn't really handle in the code so that must be why you have an error message.

I'm sorry that the tool is not really suitable for your case. I'will try to improve it in the next weeks.

**Comment by BenRacicot** [comment]
Thanks for your time with my files, I really appreciate it. It's
relieving to know that it is currently slow when processing, I was waiting
about 20 minutes each time and some options demanded 700% cpu....

I think this plugin is hugely important to many Blender users. I mean it
skips your GIS work! If there's anything I can do to help improve it please
let me know.

On Sunday, April 3, 2016, domlysz <notifications@github.com> wrote:

> I must admit shp importer isn't very well optimized right now, especially
> *extrusion* option is terribly slow, *separate object* option seems also
> to have a memory leak. I can't process your file with these options because
> it's too large but I can process a subset of it, and naming the object
> according to a field work for me. However, in your shp most buildings have
> no name (null value in the field *name*) and this case isn't really
> handle in the code so that must be why you have an error message.
>
> I'm sorry that the tool is not really suitable for your case. I'will try
> to improve it in the next weeks.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/domlysz/BlenderGIS/issues/14#issuecomment-204897425>
>


-- 
-Ben Racicot
(774) 222-1011

G+ <http://plus.google.com/u/0/100363396199779309537/about/p/pub> - Twitter
<http://twitter.com/BenRacicot> - Scientifik <http://Scientifik.com>

**Comment by domlysz** [comment]
fix in latest commit 695146d

null name values are now better handle.

fix also a bug when using *separate objects* along with *extrusion* option and a shapefile that contains  mutipart geometry (I think it's the bug you encounter as described in your second message, the script stop before finished and you got only a subset of building)

**Comment by BenRacicot** [comment]
Wow! Nice work. Where you able to import and extrude the shapefile of PVD I attached above?

**Comment by domlysz** [comment]
more or less !
I added a comment here
https://github.com/domlysz/BlenderGIS/issues/15
