### ISSUE TITLE
Terrain Shapefile not importing

### ISSUE THREAD

**Issue by Alphisto** [domlysz/BlenderGIS#148]
The shp file here doesn't work. https://1drv.ms/f/s!AtmMeBB1cwnzmrZJia4gJlWLeqkcBA

Any idea if it's the shapefile's problem or something in the importer.

Thanks! Greatly appreciate this addon.

Wish there was a donate button:)

**Comment by domlysz** [comment]
Hi,

This is a know issue of the pyshp library : https://github.com/GeospatialPython/pyshp/issues/174

Fortunately, the lib has just been updated few day ago, so I've updated the file in BlenderGIS repo and now it works correctly (this update is available only for the Blender2.8's branch)
