### ISSUE TITLE
Cannot use 'CRAIG WMS' (both 2.7 & 2.8)

### ISSUE THREAD

**Issue by tomtoom1978** [domlysz/BlenderGIS#150]
Hi,
I would use WMS from the CRAIG service, everything looks good inside the servicesDefs.py file, but there is no way the select this source inside the GIS blender menu.
I just discover "BlenderGIS". with the Google map it's working well, but I would use this WMS, because the quality is better, and many WMS use Libre license.
Thanks

**Comment by domlysz** [comment]
Hi, just uncoment this part of the code, 3 double quote at line 221 and at line 316

**Comment by tomtoom1978** [comment]
Thanks,
I did it !
But something happened! (tested with 2.8 et 2.79)

![capture du 2019-02-17 17-59-50](https://user-images.githubusercontent.com/36678395/52916302-f28d0480-32dd-11e9-8425-150f637d07aa.png)

**Comment by domlysz** [comment]
oh sorry you must also delete the brace at line 220

**Comment by tomtoom1978** [comment]
Thank you, now it's working ! :-)
