### ISSUE TITLE
Get SRTM error over 60N latitude

### ISSUE THREAD

**Issue by ErgoProxyPL** [domlysz/BlenderGIS#151]
Hi, when i set basemap (google) over 60N lattitude on map and press SRTM i got message: 
![d9047382-dbe1-4c2f-a907-531b40165c40 png](https://user-images.githubusercontent.com/26378523/53235234-9f2a0600-3691-11e9-82d3-ad20a96c34ff.jpg)

Under this lattitude everything is working.

**Comment by domlysz** [comment]
Hi,

Good catch, unfortunately the issue come from the [opentopography web service](https://opentopography.org/developers), if the south parameter exceed 60° then the request fails. I can't do anything on this, except report the issue at their contact mail.

**Comment by domlysz** [comment]
Just see [that](https://www.jpl.nasa.gov/news/news.php?release=2014-321), so this is a limitation of STRM data.

> SRTM mapping Earth's topography between 56 degrees south and 60 degrees north of the equator. 

TODO : report better error message

**Comment by domlysz** [comment]
c07efc0

**Comment by beboon** [comment]
Hello there. Thanks for this super addon. I just want to add that, this issue is kind of OS dependent. I can't load SRTM data on Windows 10 machine while it downloads data for the same location on Manjaro Linux (arch based linux). Please have a look. Thank you.
