### ISSUE TITLE
Export gltf for Cesium

### ISSUE THREAD

**Issue by Gekk0r** [domlysz/BlenderGIS#152]
I generated 3d model buildings and exported in gltf. Then, I'm importing the georeferenced 3D model in Cesium but when I try to import it (considering the origin information lat - long exported manually from blenderGIS) the model is not placed in the correct place....

The same when I try to export the shape file and try to open in a different software (Qgis)...In order to fix the position I need to move the 3D model and export again...

[Here](https://cesium.com/docs/tutorials/3d-models/) some example that I used to import a gltf in cesium.

It is possible that the coordinate origin that you share in the tool are not correct?

**Comment by domlysz** [comment]
I have no issue on my side, what's your projection system? What's the importance of the shift, meters, kilometers ???

Example of a workflow I've just tested:
- in QGIS, create a new polygon shp in World Mercator (EPSG:3857) load Bing aerial photo and digit a new polygon around a forest zone. 
- Open Blender, load Bing baselayer at same location and then import the shp, The resulting mesh is correctly placed
- Then export the shp from Blender and reopen it in QGIS, again the location is correct

**Comment by Gekk0r** [comment]
the importance of the shift is in km...
the mesh exported doen't keep the georef information when you apply the shift from the center (geo and proj).
In Cesium for example, If I try to load directly the mesh with the georef information from blender doesn't work... 
I found this solution in order to fix this problem
- set the georef system of the shape (example 31255 - Austria)
- force the geo and proj of the scene in 0
- transform in wgs84 the information about the position of the model
- transform the position of the model in x = 0 and y = 0
- then export the model in gltf and import the model in cesium with rotation in 90 degree and the position in wgs84 in the step before
(there is still shift meters problems but at least is not km :D )

regarding shape export the same issue solved in this way:

- set the georef system of the shape (example 31255 - Austria)
- move the model in position x/2 and y/2
- export the shape and open it in QGIS
(no shift problems)

Maybe you should try to try the same thing that you tested but not in the georef web mercator :)
I tried with these georef system:
5659
3912
31255
2180
3765

let me know if I can help you in someway :+1:

**Comment by domlysz** [comment]
gltf exporter as all other Blender's exporter does not care about BlenderGIS's custom properties for georeferencing. Maybe it can be a feature request for some format for whom it can be interesting to deal with geographic data.

On an another hand, the shapefile exporter is a tool provided by BlenderGIS and so it uses scene's geoferencing properties, I've no issue with this operator  in regards to georeferencing management whereas the projection system is. I can't reproduce your issue and I suspect some missuses when dealing with projection.
