### ISSUE TITLE
Blank plane when using WMS Auvergne example

### ISSUE THREAD

**Issue by Eggbird86** [domlysz/BlenderGIS#153]
Hi,

Im experimenting a bit with the WMS feature of BLenderGIS but Im having some issues.

The WMS of OSM works fine, but I cant get the example working that is provided of the Auvergne. I uncommented that WMS in the servicesDefs.py and its a available to choose. But after clicking OK I just keep seeing a blank plane in the viewport. There does seem to be a connection because in the bottom of the viewport it displays info about "Get chache database...'. I can imagine it has something to do with actual data being out of view and being relatively small, but zooming and panning doesnt show me anything. Any idea what the problem might be and how to fix it? Testing this WMS service (http://wms.craig.fr/ortho?) with QGIS works fine.

![image](https://user-images.githubusercontent.com/12492506/53524116-e162a580-3ade-11e9-911b-fd4e791182e1.png)

![image](https://user-images.githubusercontent.com/12492506/53524135-e9224a00-3ade-11e9-9dd9-678d6da839be.png)

Im actually asking this because Im also testing a different WMS service which seems to have the same issue, but because this WMS service is mentioned as a working example I thought I'd just ask about this one. When connecting to the other WMS service that has a similar issue it also mentions its downloading tile data but the screen remains blank. A solution for the auvergne example might also work for this other WMS service :)

Greetings,
Egbert

**Comment by domlysz** [comment]
Hi,

There is a small error in the url template of CRAIG WMS CRS parameter. In serviceDefs.py line 236, remove _EPSG:_, the line must look like this:

`"CRS" : '{CRS}',`

Also this WMS cover only a small part of France, so to see some data you must be in an available location. For testing, after started basemap press G and search for _Clermont Ferrand zoom 6_

**Comment by Eggbird86** [comment]
Hi there,

Thx a lot for the help! I got it working now. Also got the other WMS service working I mentioned. I didnt realise there was a search function, very helpful :)
