### ISSUE TITLE
blenderGIS (2.80) crashes when trying to load base maps 

### ISSUE THREAD

**Issue by TJRL** [domlysz/BlenderGIS#154]
Hi, I get an instant crash and these errors when trying to load a base map in Blender 2.80:

![error1](https://user-images.githubusercontent.com/22885764/53892158-0e0d4480-402c-11e9-9d63-c5366963104b.PNG)

**Comment by domlysz** [comment]
Hi,

Thanks for reporting this issue, it's now fixed.
