### ISSUE TITLE
workflow to project basemap image onto SRTM data

### ISSUE THREAD

**Issue by TJRL** [domlysz/BlenderGIS#155]
On the main BlenderGIS page you can find this animated example:

https://raw.githubusercontent.com/wiki/domlysz/blenderGIS/Blender27x/images/srtm_demo.gif

It suggests that the image data from google maps can be directly projected on the SRTM elevation data. However, due to the fact the basemap is loaded as an image empty (using 2.80), you need to first export the image, then import it again as a plane, and scale it to the right dimensions, select it, and load SRTM data. 

My issue is the scaling. I do this manually, eyeballing while using the basemap image empty as a reference. Since this image empty is no mesh, no snapping can be used, and its scaling cannot simply be transferred to the plane with the image.

Is there a better (more precise) workflow for this?

**Comment by domlysz** [comment]
As explained in the [quick start guide](https://github.com/domlysz/BlenderGIS/wiki/Quick-start), you can directly convert the basemaps to a new textured mesh by pressing **E** shortcut. It works both with blender 2.7x and 2.8.

Also, the basemaps image is automatically saved in the same place as the blend file, and this file is associated with a worldfile (*.wld) that store the georeferencing informations. So, it's possible to reimport this image at correct location and scale with the import georaster tool.

**Comment by TJRL** [comment]
Ah sorry for asking an obvious question. I'll do better reading next time. Thanks for answering!

**Comment by domlysz** [comment]
you're welcome !
