### ISSUE TITLE
Scale openstreetmap import is ca. 163 % too big (!)

### ISSUE THREAD

**Issue by sanderboer** [domlysz/BlenderGIS#156]
I located a site I need to model and I noticed the scale of the imported geometry is generously off.
I downloaded the same site model via cadmapper.com and compared it to the imported blendergis OSM.
I measured in the OSM 377.399m and in the corresponding cadmapper model I measured the same element to be 230.983m I doublechecked the measurement in google maps and the cadmapper one is correct. The scale factor is that I need to rescale the OSM by 0.61203924 (i.e. the osm is 163.38 % too big)

It seems the factor is constant, but I have no clue where this scale factor error originates from as it is not the usual mm/inch conversion.

**Comment by domlysz** [comment]
Please read the [FAQ](https://github.com/domlysz/BlenderGIS/wiki/FAQ),  Web Mercator projection causes distortions depending on latitude.

**Comment by domlysz** [comment]
By curiosity I've just asked cadmapper to know what's the projection they use to delivering osm data in meters, and what's the expected linear distortion. I suspect some on the fly transverse mercator projection centred to exported extent origin.

On another hand webmapping application that serve data in Webmercator implement special methods to yield correct measurement : it can be computed directly from angular coordinates (longitude, latitude) knowing ellipsoid parameters, or by applying a correction factor.
