### ISSUE TITLE
3DView:BlenderGIS error

### ISSUE THREAD

**Issue by geoblender** [domlysz/BlenderGIS#157]
Hi,
I´m using Blender under Windows. Trying to install the 3DBlenderGis addon I receive an error message: 
![Captura1](https://user-images.githubusercontent.com/48584016/54417292-091e5400-4702-11e9-9bcb-7f29d8d6a2b0.PNG)

Any clue what´s going on?

Thanks

**Comment by domlysz** [comment]
#132

**Comment by domlysz** [comment]
Not sure how to solve this old issue, it look like there are 2 installations of the addon. #112 was solved using Blender's standalone zip file. I think the issue will no longer remains on Blender 2.8 because classes registering method now use a bit different approach.

**Comment by tsloan1377** [comment]
I have received this error on Blender 2.80 Beta using Windows 10.
After downloading the BlenderGIS from Git, I moved the folder to the Blender 2.80 Addons folder. 
Now it appears in the list of addons, but gives the same ValueError (albeit resulting from different lines). 

![BlenderGIS_error](https://user-images.githubusercontent.com/26436062/64076715-44074a80-cc96-11e9-95a9-8d91ee50596f.png)

**Comment by domlysz** [comment]
#212
