### ISSUE TITLE
can't get custom WMS service to work

### ISSUE THREAD

**Issue by TJRL** [domlysz/BlenderGIS#158]
Using Blender 2.80

I'm trying to add a wms service to the servicesDefs.py file. But I get the same result as described here (https://github.com/domlysz/BlenderGIS/issues/153), a white plane. The example wms service with the map of auvergne works fine.

Probably I'm making a mistake with filling the parameters, but I can't find out which it is..

So I added a custom grid (the dutch national grid):

"RD" : {
		"name" : 'RD_Nieuw',
		"description" : 'RD Nieuw',
		"CRS": 'EPSG:28992',
		"bbox": [13014, 306243, 286599, 623492], #w,s,e,n
		"bboxCRS": 'EPSG:28992',
		"tileSize": 256,
		"originLoc": "NW", #North West or South West
		"resFactor" : 2
	},

And this WMS:

	"AHN2_WMS" : {
		"name" : 'AHN2 WMS',
		"description" : 'Actueel Nederlands Hoogtebestand 2 WMS',
		"service": 'WMS',
		"grid": 'RD',
		"layers" : {
			"5M" : {"urlKey" : '', "name" : 'AHN2_5m', "description" : '', "format" : 'png', "style" : '', "zmin" : 0, "zmax" : 20}
		},
		"urlTemplate": {
			"BASE_URL" : 'https://geodata.nationaalgeoregister.nl/ahn2/wms?',
			"SERVICE" : 'WMS',
			"VERSION" : '1.3.0',
			"REQUEST" : 'GetMap',
			"CRS" : '{CRS}', #EPSG:xxxx
			"LAYERS" : '{LAY}',
			"FORMAT" : 'image/{FORMAT}',
			"STYLES" : '{STYLE}',
			"BBOX" : '{BBOX}', #xmin,ymin,xmax,ymax, in "SRS" projection
			"WIDTH" : '{WIDTH}',
			"HEIGHT" : '{HEIGHT}',
			"TRANSPARENT" : "False"
			},
		"referer": "http://www.ahn.nl/index.html"
	},

If I enter the wms request in my browser window it works fine:

http://geodata.nationaalgeoregister.nl/ahn2/wms?service=WMS&version=1.3.0&request=GetMap&layers=ahn2_5m&bbox=12014,306243,286599,623492&width=400&height=500&format=image/png&crs=EPSG:28992&styles=none

So what am I doing wrong?

**Comment by domlysz** [comment]
Hi,

You forgot to setup layer's `urlKey` parameter, it's the name provided in the WMS request, here `ahn2_5m` (be careful it's case sensitive), the `name` parameter is the name displaying in the list box, it can be more explicit for the user.

```
"layers" : {
		"5M" : {"urlKey" : 'ahn2_5m', "name" : 'AHN2_5m', "description" : '', "format" : 'png', "style" : '', "zmin" : 0, "zmax" : 20}
	},
```

Works for me

**Comment by TJRL** [comment]
Thanks, how could I have overlooked that...

Follow up question: this wms service gives access to a detailed elevation model of the netherlands (called 'AHN'). Is there a way to easily modify the script for 'Get SRTM' to work with other elevation data?

**Comment by domlysz** [comment]
Not really, WMS or WMTS serve image data in jpg or png that mean 3 or 4 bands RGB(A) of 8 bits (values from 0 to 255). Elevation model are typically distributed in geotiff with one unique band of 16 or 32bits because 256 values are not enough. In others words OGC web service are not designed to serve elevation model at all. I know there is an experimentation for encoding elevation value using RGB channel : https://github.com/tilezen/joerd/blob/master/docs/formats.md
But I don't think it's the case here, your wms only serve colored data. You might have better luck download raw geotiff data if available.

**Comment by TJRL** [comment]
I realised that also. The raw geotiffs are available as well, so there's no problem of getting the data. I thought it would just be convenient to have it import the same way as SRTM data. So how does that work with SRTM in BlenderGIS?

**Comment by domlysz** [comment]
SRTM importer use a non standard web service that serve directly geotiff data : https://www.opentopography.org/developers#SRTM

**Comment by TJRL** [comment]
Thanks for exp

**Comment by TJRL** [comment]
Thanks for explaining. Your quick responses are much appreciated!
