### ISSUE TITLE
Import failed for attached file

### ISSUE THREAD

**Issue by VaclavC** [domlysz/BlenderGIS#16]
When I try to import shp file from this archive:
[BD3_Bero00_polygonZ.zip](https://github.com/domlysz/BlenderGIS/files/231504/BD3_Bero00_polygonZ.zip)
script crashes with following error:

```
Traceback (most recent call last):
  File "/home/disnel/.config/blender/2.77/scripts/addons/io_shapefile/op_import_shp.py", line 300, in execute
    for i, feat in enumerate(shpIter):
  File "/home/disnel/.config/blender/2.77/scripts/addons/io_shapefile/shapefile.py", line 437, in iterShapes
    yield self.__shape()    
  File "/home/disnel/.config/blender/2.77/scripts/addons/io_shapefile/shapefile.py", line 357, in __shape
    (mmin, mmax) = unpack("<2d", f.read(16))
struct.error: unpack requires a bytes object of length 16

location: <unknown location>:-1

location: <unknown location>:-1
```

When I try to comment out lines 356 - 364, file is imported fine, but it probably breaks something else.

Also, I experienced Blender crashes on files imported from SHP, here is related bugreport:

https://developer.blender.org/T48239

Don't know, if it is related to SHP importer or not. These crashes occurs with or without commented lines in script, however.

UPDATE: Importer produces inccorect mesh for this (and similar) file. Instructed by Campbell Barton from BF I added mesh validation into script as temporary fix. Will make pull request for it. This does not solve original problem, however.

UPDATE 2: According to SHP spec on wiki (https://en.wikipedia.org/wiki/Shapefile#Shapefile_shape_format_.28.shp.29), M range values are optional but import script is expecting them in all cases. Will try to fix it.

**Comment by domlysz** [comment]
Thanks reporting theses issues.

*shapefile.py* come from pyshp lib : https://github.com/GeospatialPython/pyshp

This issue must be reported in pyshp repository. However I will try to improve pyshp errors handle in the importer.

**Comment by domlysz** [comment]
Can you join me an example of shapefile that produce a corrupted mesh ? I would like investigate the problem.

Thanks again

**Comment by VaclavC** [comment]
It is in first post here: https://github.com/domlysz/BlenderGIS/files/231504/BD3_Bero00_polygonZ.zip

**Comment by domlysz** [comment]
ok sorry I thought it was another file. Note that, exporting the file in a new shp with QGIS fix the pyshp issue.

**Comment by VaclavC** [comment]
No problem.

I fixed it locally by commenting out mentioned lines in shapefile.py. It will not work for files with M range values defined, but this fine for me right now (and I can change it back).

**Comment by domlysz** [comment]
https://github.com/GeospatialPython/pyshp/issues/55
