### ISSUE TITLE
Can't install BlenderGIS on Blender 2.80.51 (build March 26, 2019)

### ISSUE THREAD

**Issue by taufikp** [domlysz/BlenderGIS#162]
I got this message:

File: nodes_terrain_analysis_reclassify.py, line 961, in register bpy.utils.register_class(cls)
RunTimeError: Error: 'reclass_panel' doesn't contain _PT_ with prefix & suffix

BlenderGIS branch: blender28
BlenderVersion: 2.80.51, build March 26, 2019

The BlenderGIS blender28 was working in Blender 2.80.51 build March 17, 2019

**Comment by domlysz** [comment]
Are you sure you are using the latest version of Blender28 branch? Classes names has been updated in january d27530

**Comment by taufikp** [comment]
I just redownloaded the ZIP file, then reinstall, and it still failed to install with the same error message.

Do I have to clone the source instead of downloading the ZIP file?

**Comment by domlysz** [comment]
ok you're right it was broken with last Blender 2.8, I've just fixed it, give it a try. Download "Blender28" branch zip is fine.

**Comment by taufikp** [comment]
Ohh great! I'll give it a try now

**Comment by taufikp** [comment]
Yes, it's installed without problem now. Thanks for fixing this so quickly! 👍
