### ISSUE TITLE
Image library not downloadable

### ISSUE THREAD

**Issue by mach0** [domlysz/BlenderGIS#165]
I am getting:
OSError: Unable to download 'libfreeimage-3.16.0-linux64.so'. Perhaps there is a no internet connection? If there is, please report this problem.

I definitely have an internet connection (otherwise this message would not be possible ;) ) and therefor report this problem here.

I downloaded the file manually but could not find the place where to put it.. any hint?

**Comment by domlysz** [comment]
Hi thanks for reporting this issue, I think it's now fixed for Blender28 branch. It was linked to a failed SSL certificate verification. Since Python 3.7 a certificate is required for https requests. I think it also solve these 2 issues encounter on Mac OS : #159 and #149

**Comment by mach0** [comment]
thank you for fast fixing and the hint where to put the file.
Just tested Blender28 branch and everything worked.
Closing the issue
