### ISSUE TITLE
Applying georeference too early

### ISSUE THREAD

**Issue by rossoe** [domlysz/BlenderGIS#166]
If I load in an .asc after already setting the georeferencing to it's CRS  - in this case UTM 30N

I get the following:
![GIS](https://user-images.githubusercontent.com/28996048/56341961-9431b480-61ae-11e9-9c25-aa03745972e6.JPG)

However if Import it without setting georeference (defaults to WGS84) - 
![GIS2](https://user-images.githubusercontent.com/28996048/56342120-fee2f000-61ae-11e9-8192-69c0876990eb.JPG)
It comes in as expected:
![GIS3](https://user-images.githubusercontent.com/28996048/56342178-25089000-61af-11e9-87dc-14d22649b0ff.JPG)

Should I not be able to set project CRS prior to import?

**Comment by domlysz** [comment]
What's the projection system of your asc ?

You can setup the scene crs before an import, When importing data, if the crs is not setup then it will we automatically set accordingly to the input data crs.

At each import you must define what is the crs of the input data. If the input data's crs does not match the scene crs (if already set) then a repojection task will be triggered.

So you must detemine in what projection system you want to work with, and what is the projection system of your input data and then carefully indicate these parameters to the addon however you will get unexpected results.

In the second case of your example, scene crs and asc crs are both set to wgs84, so there is no reprojection task. As it's up to the user to define the crs, it can be the wrong CRS at all... In your case I think the file is not in WGS84 latlon however you will get something like the first sreenshoot ( see [FAQ](https://github.com/domlysz/BlenderGIS/wiki/FAQ) about longitude latitude system vs projected systems)

**Comment by rossoe** [comment]
The .asc was straight out of QGIS project where it was converted to UTM 30N, so I was surprised to see it not play nice with the same UTM 30N 'scene' setting set within BlenderGIS. I'm perhaps getting a re-projection triggered when not expecting it - so I'll double check settings tonight.

When you say:
"if the crs is not setup then it will we automatically set accordingly to the input data crs"
Is that only if the .asc file has an associated .prj file linked to it?

I'm only getting the first distorted raster when I preset the scene to UTM 30N before loading .asc

**Comment by domlysz** [comment]
>  I preset the scene to UTM 30N before loading .asc

But what's is the projection system you indicate for the input data ?

> Is that only if the .asc file has an associated .prj file linked to it?

No you should always indicate yourself what's is the crs of your input data, the addon will never determine that by itself whatever the data is associated to prj files

here a little schema that may help you to understand :


![schema](https://user-images.githubusercontent.com/5639024/56358653-92341980-61df-11e9-8baf-863b4ec26f16.png)

**Comment by rossoe** [comment]
Fantastic explanation - thank you, all working as you explained. my mistake not adding the CRS on import of .asc
