### ISSUE TITLE
basemap not loading 2.79 PC

### ISSUE THREAD

**Issue by Redsam121** [domlysz/BlenderGIS#167]
When I click basemap, the map does not load up. Also no gpkg are present in the cache file.
![MSIAfterburner_2019_04_18_20_13_04_465](https://user-images.githubusercontent.com/49752963/56360274-be1ec180-6216-11e9-8645-22ddec04d1be.png)

**Comment by domlysz** [comment]
any error message in the system console ?

**Comment by Redsam121** [comment]
> 
> 
> any error message in the system console ?

No error messages were present.

**Comment by domlysz** [comment]
error messages are not always reported directly on screen, you must check the system console. Menu Window/console

**Comment by Redsam121** [comment]
OK yes I did get an error.
![MSIAfterburner_2019_04_19_18_43_52_423](https://user-images.githubusercontent.com/49752963/56421029-334fcc80-62d3-11e9-9b22-13f2c27b55fd.png)

**Comment by Redsam121** [comment]
Apparently there is a problem with the getTM at line 475 mapservice.py.

**Comment by domlysz** [comment]
just update the addon, this bug was fixed last year : 0f044dc

**Comment by Redsam121** [comment]
It worked, but now I'm getting a white screen with basemap (OSM WMS)

**Comment by domlysz** [comment]
does not others services works ? this one is just an example of wms setup, standard tiled osm service is a better way to go. It seems this wms server for osm data is down, don't know if it's temporary or not, but the issue does not come from the addon itself, this service setup example will be removed if it not available anymore.

**Comment by Redsam121** [comment]
OK I've tried OSM on it's own and it works perfectly, thank you so much for all your help.
