### ISSUE TITLE
Add new CRS using PROJ.4

### ISSUE THREAD

**Issue by jdarras** [domlysz/BlenderGIS#171]
Hello,

I'm using Blender on one station without internet, I would like to used CRS 3857 ( http://epsg.io/3857 ) I found the code Proj4 but can you explain how can I install it ?

Thanks
Julien

**Comment by domlysz** [comment]
Hi,

EPSG 3857 is already defined by default, it's the web mercator projection

![image](https://user-images.githubusercontent.com/5639024/57544871-ec487a80-7358-11e9-952b-959b45783740.png)

Internaly the addon can convert coordinates from WGS84 longitude/latitude (EPSG 4326) to/from EPSG 3857. Conversion involving other projections systems is supported through epsg.io web service (slow and require internet connection), GDAL (if installed) or pyproj (if installed).

A Proj4 definition is different from EPSG codes, for example the proj4 definition for 3857 is _+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m_ Proj4 allows definition of custom projection which may not exist in EPSG database.

**Comment by jdarras** [comment]
Thanks for your answer, I succed to export from qgis and import in blender with the good projection.
