### ISSUE TITLE
Mesh combined

### ISSUE THREAD

**Issue by danksky** [domlysz/BlenderGIS#174]
When importing .osm files, the main layer combines the buildings and terrain as one mesh called "Areas." Is it possible to import the OSM file so that buildings are discrete and uniquely identifiable?

![image](https://user-images.githubusercontent.com/10901068/58445981-becb3300-80b3-11e9-8874-0965231d811f.png)

**Comment by domlysz** [comment]
yes, just check Separate objects" option

![image](https://user-images.githubusercontent.com/5639024/58508139-a92d3a80-8193-11e9-98ee-50f53078c798.png)

**Comment by rossoe** [comment]
I didn't think the height data came through from OSM with current implementation in BlenderGIS? or is that just a random height being applied?

**Comment by danksky** [comment]
![image](https://user-images.githubusercontent.com/10901068/59571296-36a7d000-9058-11e9-99ed-3701e1882e66.png)
I'm unable to recreate the problem because the import of my OSM model doesn't work. 

![image](https://user-images.githubusercontent.com/10901068/59571337-68b93200-9058-11e9-8bbb-1f9dac71df62.png)

**Comment by domlysz** [comment]
uncheck "elevation from object" because, as I can see, you don't have any object in the scene to get the elevation from.

**Comment by domlysz** [comment]
https://github.com/domlysz/BlenderGIS/commit/4123c2663529a9688e33f82484c900e58491002c
