### ISSUE TITLE
Shapefiles imported to Blender losing styling

### ISSUE THREAD

**Issue by daniellehoo** [domlysz/BlenderGIS#175]
Hello,

When I am attempting to bring in a shapefile from QGIS to Blender (2.79), I am losing styling preferences (i.e. line width and color). The line will show up georeferenced, but without styling.
I am right clicking on a layer > Save Vector Layer as..., saving and then importing to Blender.

Is there any way to preserve these settings for import?

Thank you.

**Comment by domlysz** [comment]
no, styling files are not standardized in the shapefile specification, each GIS software had it's own styling file format.

Futhermore, styling vector features in a GIS software is a very different concept from the setup of material shaders for a 3d rendering. Technically it should be possible to parse QGIS style file and affect the good color to each face when importing but by default Blender does not render edges and don't care about line width or color, there is on way to set line color of the viewport displaying.
