### ISSUE TITLE
Got error when enable BlenderGIS in Version 2.80 (2.80 2019-07-11)

### ISSUE THREAD

**Issue by kevinjay123** [domlysz/BlenderGIS#179]
I did checkout latest code from branch "blender28". 
The Blender 2.8 RC version is **(2.80 2019-07-11)**. 

I got error when enable BlenderGIS after I installed it.

the error message as below:
![螢幕快照 2019-07-15 下午3 09 04](https://user-images.githubusercontent.com/18675372/61200140-13357b00-a713-11e9-98f3-566f8db8f0d9.png)

**Comment by s-leger** [comment]
This is a known issue with RC1 on mac, either re download rc1 or setup a nighty build.

**Comment by kevinjay123** [comment]
Got it. Thanks!
