### ISSUE TITLE
Basemaps plugin giving an error

### ISSUE THREAD

**Issue by jdathela** [domlysz/BlenderGIS#18]
when I try to enable the Basemaps plugin from the add-ons panel, i get an error (see attached image). I'm running 2.77. 

![image](https://cloud.githubusercontent.com/assets/5731211/15155919/abb7c40e-16b2-11e6-9cba-19c3ff190e9d.png)

Thanks all.

**Comment by BenRacicot** [comment]
Here is a screenshot of mine which is working. Although I know updated have been made to BlenderGIS;
![screen shot 2016-05-10 at 1 39 55 pm](https://cloud.githubusercontent.com/assets/1815385/15156392/d34564b6-16b4-11e6-86f8-b8cdf00569fc.png)

**Comment by domlysz** [comment]
As explained [here](https://github.com/domlysz/BlenderGIS/wiki/Basemaps) basemaps addon depends on PIL / Pillow you must install this dependency to use it

**Comment by domlysz** [comment]
On Windows use the following commands to install Pillow:

 `blender_install_folder\2.7x\python\bin\python.exe -m ensurepip`

 `blender_install_folder\2.7x\python\bin\python.exe -m pip install pillow`

**Comment by domlysz** [comment]
I added a more understandable error message

![selection_001](https://cloud.githubusercontent.com/assets/5639024/16231822/375e1810-37c8-11e6-8630-679a13a86abb.jpg)

**Comment by Macintosher** [comment]
What is the command on a Mac??

**Comment by domlysz** [comment]
sorry I can't provide much help for this, I nerver used a mac in my life.

However Python is cross platform, so in theory try to find the python executable used by your Blender installation then run ensurepip and pip install through this exe

**Comment by kikislater** [comment]
@Macintosher you have to use homebrew and install python

**Comment by Macintosher** [comment]
o.k. I take the PC/XT


Am 23.06.16 um 16:56 schrieb domlysz:
>
> sorry I can't provide much help for this, I nerver used a mac in my life.
>
> However Python is cross platform, so in theory try to find the python 
> executable used by your Blender installation then run ensurepip and 
> pip install through this exe
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/domlysz/BlenderGIS/issues/18#issuecomment-228076616>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AS6xVExbPnKYC6M28f5KXIRVTLTHow7tks5qOp6SgaJpZM4IbUM3>.
>

-- 



Bernhard Knab
Sebastian-Münster-Straße 3a
67549 Worms
Telefon: +49(0)6241-970020
Telefax: +49(0)6241-970749
bk@bknab.de
