### ISSUE TITLE
GDAL on portable Blender ?

### ISSUE THREAD

**Issue by ChameleonScales** [domlysz/BlenderGIS#180]
🇬🇧 Hey,
First off, your add-on is amazing and it helps me a great deal at work so thank you very very much.

The wiki says to "install Blender from a repository instead of ready to use tarballs from blender.org."

Problem is, I use Debian at work and the Blender package from the repositories is undoubtedly very far from being upgraded to 2.8, and this new version is such an advancement that it has become indispensable for me.
Isn't there a way to force BlenderGIS to use the GDAL installed on my system while using Blender 2.8 downloaded from blender.org?

Thanks in advance for your help.

**Comment by ChameleonScales** [comment]
Traduction 🇫🇷 :
Bonjour,
Premièrement, votre add-on est génial et il m'aide déjà beaucoup donc un grand merci pour ce beau travail !
Le wiki ditd'installer Blender depuis les dépôts pour que GDAL fonctionne correctement plutôt que de télécharger un tarball depuis blender.org.

Le problème c'est que Debian n'est vraiment pas prêt de mettre Blender 2.8 dans ses dépôts (et cette version de Blender est une telle avancée qu'elle est indispensable pour moi)

N'y a-t-il pas un moyen de forcer BlenderGIS à utiliser le GDAL installé sur mon système tout en utilisant Blender 2.8 téléchargé depuis blender.org?

Merci par avance pour votre aide.

**Comment by domlysz** [comment]
Oui c'est possible mais c'est potentiellement galère car il faut que la version de GDAL installée colle avec celle attendue par la lib Python qui elle-même doit être adaptée à la version de Python utilisée par Blender (qui est packagé dans le tarball). 

A priori il faut installé python gdal avec pip depuis le binaire python inclus dans le tarball en spécifiant [la version ciblée](https://pypi.org/project/GDAL/#history)

par ex: `blenderFolder/2.8x/python/bin/python -m pip install GDAL==2.4.2`

si pip n'est pas dispo il faut faire `python -m ensurepip`

**Comment by ChameleonScales** [comment]
Back to :gb: so others don't feel left out.
I still didn't succeed. When trying `pip install GDAL` the way you suggested, I got a
```No module named 'lib2to3'```
So I tried `pip install 2to3` but after it the GDAL install was still saying the same
So I tried `pip install python3-lib2to3` but it didn't find this one:
```No matching distribution found for python3-lib2to3```

still looking...

**Comment by domlysz** [comment]
As lib2to3 is normally bundle with Python, this package is not available through pip. Seems like the only way to go is by making a hard copy of the package from the Python install of your system to the Blender's one.

`cp -r /usr/lib/python3.7/lib2to3 2.8x/python/lib/python3.7/lib2to3`

Also, installing python-gdal involves a compilation step that needs Python c++ headers files. So you need to install the package python3.x-dev to your system beforehand and then specify the headers folder when installing GDAL through pip

` ./python3.7m -m pip install --global-option=build_ext --global-option="-I/usr/include/python3.7m" GDAL`

Unfortunately I still encounter compilation error, don't know what's wrong. One again, this is a hard way to go.

**Comment by ChameleonScales** [comment]
I see. For my work place I don't see an alternative (other than what I'm currently doing which is switch between QGIS and Blender every few seconds).
That said, I just tried the GDAL implementation on manjaro (since this distro provides a system install for blender 2.82) and it works but is so slow compared to the same reprojection in QGIS that I actually wonder if solving this will save me any time when working.
Is it also much slower than QGIS on your side?

**Comment by domlysz** [comment]
What kind of reprojection task ?

**Comment by ChameleonScales** [comment]
I reprojected Google Satellite from Web Mercator to Lambert93 (ESPG 2154) and noticed a major delay at all zoom levels.

**Comment by domlysz** [comment]
If you seed a cache following a tilematrix different from the source, yes currently is slow. Not specifically because of reprojection tasks but the whole algorithm used for transposing from a tile matrix to another is not well optimised : each tile is processed separately involving a set of transformations chain (download, mosaic, repro, cut... ).  But once the cache is seeding then it's fast.

The second option is just to keep the original tile matrix of the source but setting the scene crs to Lambert 93, this solution is as fast as QGIS.
