### ISSUE TITLE
WMTS feed with credentials?

### ISSUE THREAD

**Issue by ChameleonScales** [domlysz/BlenderGIS#181]
I use a WMTS feed which requires credentials but I'm not sure I implemented them properly in my code snippet in servicesDefs.py:
```
    "IGN-L93" : {
		"name" : 'IGN-L93',
		"description" : 'ign.fr',
		"service": 'WMTS',
		"grid": 'LB93',
		"matrix" : 'lambert93',
		"layers" : {
			"ORTHO" : {"urlKey" : 'ORTHOIMAGERY.ORTHOPHOTOS.BDORTHO.L93&username=<my_username>&password=<my_password>', "name" : 'Orthophotos', "description" : '',
				"format" : 'jpeg', "style" : 'normal', "zmin" : 5, "zmax" : 18},
		},
		"urlTemplate": {
			"BASE_URL" : 'http://wxs.ign.fr/<my_key>/geoportail/wmts?',
			"SERVICE" : 'WMTS',
			"REQUEST" : 'GetTile',
			"VERSION" : '1.0.0',
			"LAYER" : '{LAY}',
			"TILEMATRIXSET" : 'LAMB93',
			"TILEMATRIX" : '{Z}',
			"TILECOL" : '{X}',
			"TILEROW" : '{Y}',
			"STYLE" : '{STYLE}',
			"FORMAT" : 'image/{FORMAT}',
			
			},
		"referer": "ign.fr"
	},
```

The map stays blank and in debug mode the terminal says:
`Invalid tile data for request http://wxs.ign.fr/<my_key>/geoportail/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTHOIMAGERY.ORTHOPHOTOS.BDORTHO.L93&username=<my_username>&password=<my_password>&TILEMATRIXSET=LAMB93&TILEMATRIX=11&TILECOL=932&TILEROW=869&STYLE=normal&FORMAT=image/jpeg`

**Comment by domlysz** [comment]
Salut,

En fait le problème est qu'actuellement pour utiliser un service WMTS s'appuyant sur une grille personnaliée, il est nécessaire de configurer manuellement la grile car il n'y a pas de de fonction pour parser le GetCapabilities. Les exemples de grilles en Lambert 93 proposés dans le fichier Python ne sont pas compatibles avec la grille utilisée par les services Lambert93 du Geoportail, voici les bons paramètres :

```
	"LB93_IGN" : {
		"name" : 'Fr Lambert 93 IGN',
		"description" : 'Local grid in French Lambert 93 projection',
		"CRS": 'EPSG:2154',
		"bbox": [0, -80000000, 135000000, 12000000], #w,s,e,n
		"bboxCRS": 'EPSG:2154',
		"tileSize": 256,
		"originLoc": "NW",
		"initRes": 104579.224549894,
		"resFactor" : 2
	}
```
Dans la définition de la source la paramètre "grid" fait référence au nom de la grille préalablement défini dans le code et le paramètre "matrix" fait référence au nom de grille défini au niveau du service WMTS.

Concernant la clé, cela ne devrait pas poser de problème à partir du moment ou l'IP de la machine est authorisée ou, le cas échéant, le rerefer dont la valeur peut être forcée si besoin.

```
	"GEOPORTAIL_LB93" : {
		"name" : 'Geoportai Lambert 93',
		"description" : 'Geoportail.fr',
		"service": 'WMTS',
		"grid": 'LB93_IGN',
		"matrix" : 'LAMB93',
		"layers" : {
			"ORTHO" : {"urlKey" : 'ORTHOIMAGERY.ORTHOPHOTOS.BDORTHO.L93', "name" : 'Orthophotos', "description" : '',
				"format" : 'jpeg', "style" : 'normal', "zmin" : 6, "zmax" : 18},
			"SCAN" : {"urlKey" : 'GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN25TOPO.L93', "name" : 'Scan', "description" : '',
				"format" : 'jpeg', "style" : 'normal', "zmin" : 5, "zmax" : 15},
			"CAD" : {"urlKey" : 'CADASTRALPARCELS.PARCELS.L93', "name" : 'Cadastre', "description" : '',
				"format" : 'png', "style" : 'normal', "zmin" : 0, "zmax" : 18}
		},
		"urlTemplate": {
			"BASE_URL" : 'https://wxs.ign.fr/mykey/geoportail/wmts?',
			"SERVICE" : 'WMTS',
			"VERSION" : '1.0.0',
			"REQUEST" : 'GetTile',
			"LAYER" : '{LAY}',
			"STYLE" : '{STYLE}',
			"FORMAT" : 'image/{FORMAT}',
			"TILEMATRIXSET" : '{MATRIX}',
			"TILEMATRIX" : '{Z}',
			"TILEROW" : '{Y}',
			"TILECOL" : '{X}'
			},
		"referer": "BlenderGIS"
	}
```

Autre point à prendre en compte, lorsque l'on lance pour la première fois l'outil basemap est que la scene n'a pas été géoréféencée par un précédent import, la carte s'initialise aux coordonnées (0,0) or en Lambert 93 cette coordonnée tombe dans l'océan Atlantique, il n'y a donc pas de données valides à cet endroit et rien ne s'affichera. De la même façon la carte est initialisée au niveau de zoom zéro or rien ne garanti qu'il s'agit d'un niveau de zoom valide pour la couche requêtée. Il est donc préférable d'initialiser au préalable l'origine de la scene à une coodonnée valide pour la France (par ex. lon 3° lat 46°).

conclusion : ça fonctionne mais il faut bidouiller, des améliorations sont à prévoir pour faciliter ce genre de configuration.

**Comment by ChameleonScales** [comment]
Merci pour ces infos.
En revanche le `"grid": 'LB93_IGN',` ne semble pas fonctionner. Le pop menu Basemap indique *Tile matrix : Web mercator* et si je change la ligne en `"grid": 'LB93',` il indique bien lambert 93 mais la carte est vide (même si je me positionne au préalable en utilisant le CRAIG WMTS93 au niveau de zoom 7 au centre de la France).

**Comment by domlysz** [comment]
La grille 'LB93" ici présentée en exemple n'est pas compatible avec la grile IGN, c'est bien 'LB93_IGN' qu'il faut indiquer, cette dernière devant être ajoutée au préalable dans le dictionnaire des grilles au début du fichier serviveDefs.py, à minima il faut donc ces deux entrées pour que ça fonctionne :
```

# -*- coding:utf-8 -*-

import math

####################################
#        Tiles matrix definitions
####################################

GRIDS = {

	"LB93_IGN" : {
		"name" : 'Fr Lambert 93 IGN',
		"description" : 'Local grid in French Lambert 93 projection',
		"CRS": 'EPSG:2154',
		"bbox": [0, -80000000, 135000000, 12000000], #w,s,e,n
		"bboxCRS": 'EPSG:2154',
		"tileSize": 256,
		"originLoc": "NW",
		"initRes": 104579.224549894,
		"resFactor" : 2
	}

}


####################################
#        Sources definitions
####################################

SOURCES = {

	"GEOPORTAIL_LB93" : {
		"name" : 'Geoportai Lambert 93',
		"description" : 'Geoportail.fr',
		"service": 'WMTS',
		"grid": 'LB93_IGN',
		"matrix" : 'LAMB93',
		"layers" : {
			"ORTHO" : {"urlKey" : 'ORTHOIMAGERY.ORTHOPHOTOS.BDORTHO.L93', "name" : 'Orthophotos', "description" : '',
				"format" : 'jpeg', "style" : 'normal', "zmin" : 6, "zmax" : 18},
			"SCAN" : {"urlKey" : 'GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN25TOPO.L93', "name" : 'Scan', "description" : '',
				"format" : 'jpeg', "style" : 'normal', "zmin" : 5, "zmax" : 15},
			"CAD" : {"urlKey" : 'CADASTRALPARCELS.PARCELS.L93', "name" : 'Cadastre', "description" : '',
				"format" : 'png', "style" : 'normal', "zmin" : 0, "zmax" : 18}
		},
		"urlTemplate": {
			"BASE_URL" : 'https://wxs.ign.fr/k/geoportail/wmts?',
			"SERVICE" : 'WMTS',
			"VERSION" : '1.0.0',
			"REQUEST" : 'GetTile',
			"LAYER" : '{LAY}',
			"STYLE" : '{STYLE}',
			"FORMAT" : 'image/{FORMAT}',
			"TILEMATRIXSET" : '{MATRIX}',
			"TILEMATRIX" : '{Z}',
			"TILEROW" : '{Y}',
			"TILECOL" : '{X}'
			},
		"referer": "myref.fr"
	}

}

```

**Comment by ChameleonScales** [comment]
Allelujah! Merci et désolé pour mon débutantisme.
C'est assez long à charger comparé à QGIS mais c'est déjà génial.

**Comment by domlysz** [comment]
Quand basemap est lancé appuyer sur O et décocher l'option "keep latlon in synch", cela devrait être plus rapide car par défaut des requêtes ont envoyées au service epsg.io pour convertir les coordonnées lambert de l'origine de la scene en longitude latitude, manière d'avoir un géoréférencement plus universel mais ça n'est pas indispensable au bon fonctionnement de l'addon, Par ailleurs si GDAL est dispo ces lenteurs disparaissent car la conversion ne passe plus par un service web.

**Comment by ChameleonScales** [comment]
intéressant, je m'attendais à ce qu'une reprojection locale soit plus longue qu'en utilisant le service web.
Je n'arrive pas à utiliser GDAL bien qu'il soit installé, comme je l'explique dans #180

**Comment by domlysz** [comment]
Mise à jour des paramètres de la grille : #204
