### ISSUE TITLE
Error after installation / Blender 2.80 / Mac Mojave

### ISSUE THREAD

**Issue by j-c-c** [domlysz/BlenderGIS#182]
After install this won't run. Screengrab attached of error message. Thanks.

![BlenderGIS](https://user-images.githubusercontent.com/5588125/62333426-4faafa00-b4bb-11e9-8b6f-4aa7b09224a3.png)

**Comment by domlysz** [comment]
Seems like the sqlite python module is not available in your Blender installation which is anormal because it's a standard python module. The issue is related to Blender itself not BlenderGIS. I think there is a missconfig when the Blender team compiling this MacOS binary and it must be reported into Blender bugs tracker.

**Comment by j-c-c** [comment]
Okay, thanks. Will post to Blender, though that file apparently not found is in the Blender package, and the path correct?? Clearly the second path is someone's local drive (highlighted), so would never work, so no idea why that's there. This is all over my head, but hopefully will get to a fix soon. Thanks!

**Comment by j-c-c** [comment]
As a final follow up it seems I'll just abandon Blender and this add-on as it's impossible to post a bug at Blender. After trying to register two different e-mails and details to post the report, no verification e-mails have been received. This is nothing to do with e-mails ending up in junk, or similar. Unfortunately there is no other way of progressing this, the end. Shame!

**Comment by domlysz** [comment]
Finally you're were to open a new issue

https://developer.blender.org/T68243

Thanks

**Comment by j-c-c** [comment]
Yes, I nearly gave up trying. All seems very professional in approach, so fingers crossed... though I’m about to open another as my Blender crashes on every attempt to render, on all engines... ??!! It may not get in to my workflow after all.
