### ISSUE TITLE
ImportError BlenderGIS MacOs

### ISSUE THREAD

**Issue by AnnalisaRomano** [domlysz/BlenderGIS#183]
![Screenshot 2019-08-07 at 17 23 26](https://user-images.githubusercontent.com/53872632/62640068-a770b780-b938-11e9-9d3a-4ce3e9bfb32b.png)
Hi,

I am trying to activate BlenderGIS but I am facing this error. Does anyone know to solve it? Thank you in advance

**Comment by domlysz** [comment]
Same as #182 
https://developer.blender.org/T68243
Blender's issue for mac recent build
