### ISSUE TITLE
Blender stuck after installing plugin and adding basemap

### ISSUE THREAD

**Issue by vjjan91** [domlysz/BlenderGIS#186]
I am only able to zoom in and zoom out after adding a basemap and the entire program gets stuck.  I have to close it and restart it. Is this an issue anyone else is facing? I am using Blender 2.8

**Comment by s-leger** [comment]
Hit "ESC" to stop the zoom tool

**Comment by domlysz** [comment]
Basemaps shortcuts : https://github.com/domlysz/BlenderGIS/wiki/Basemaps

**Comment by vjjan91** [comment]
Thank you!

**Comment by MikeDabrowski** [comment]
The error that goes with this 
![image](https://user-images.githubusercontent.com/17836911/70849811-c9002380-1e83-11ea-9da5-2eea3621f608.png)
