### ISSUE TITLE
Unable to install GDAL for windows

### ISSUE THREAD

**Issue by vjjan91** [domlysz/BlenderGIS#187]
I have tried following your instructions, inspite of gdal already installed on this system. It appears that Blender is not recognizing the current version of gdal installed.

PS C:\Program Files\Blender Foundation\Blender\2.80\python\bin> python.exe -m ensurepip
PS C:\Program Files\Blender Foundation\Blender\2.80\python\bin> 

I don't get any message saying requirements fulfilled etc. What might be going on here?

**Comment by farukahmet** [comment]
Same here. First I thought it might be because I was using the 2.81 portable Alphas, but trying it in the stable 2.80 version didn't make a difference.

**Comment by domlysz** [comment]
any error message after installing the wheel file ?
sorry I can't test the installation on windows for now

**Comment by farukahmet** [comment]
No message of any kind at all. I just now used the installer from https://trac.osgeo.org/osgeo4w/ and that fixed things--though I don't know how, and there is still no /osgeo folder in /site-packages, but as long as it works, right? :)

**Comment by Swahhillie** [comment]
You probably figured it out already but I ran in to this. You could be doing what I was accidentally doing. If you have another python installation in your path, windows will take that one instead of the one in the current folder. Try it with **./**python.exe.
