### ISSUE TITLE
Getting started in 2.8

### ISSUE THREAD

**Issue by PCdurham** [domlysz/BlenderGIS#189]
I used BlenderGIS in 2.79 but I can't seem to even get started in 2.8.  Is the 'dedicated GIS menu' supposed to be in object mode / layout view?  All I need to do is display an georeferenced image draped on a DEM, both files are pre-processed and ready to go.  

Any chance of a screenshot of that GIS menu in 2.8 which is zoomed out to show where we are supposed to find it?

**Comment by domlysz** [comment]
This menu is available in the top of the 3d view (object mode)
![ss](https://user-images.githubusercontent.com/5639024/64063805-9ba3a880-cbf9-11e9-82c5-0cf555b3f270.jpg)

**Comment by PCdurham** [comment]
That wasn't there.  I tried removing and re-downloading the zip source code.  Now I get a bug at installation:
![image](https://user-images.githubusercontent.com/47110600/64066257-3a86cf80-cc0f-11e9-8ebe-cf6d6e3787ba.png)

**Comment by domlysz** [comment]
Have you downloaded the last version of the addon?

**Comment by PCdurham** [comment]
Blender re-install seems to have worked, it somehow located the add-on and now it works.
Thanks!
P
