### ISSUE TITLE
Problem with instalation

### ISSUE THREAD

**Issue by aneriw** [domlysz/BlenderGIS#19]
When testing the instalation runing "from osgeo import gdal", i get this error (see image). Also when i try to enable the Add-ons "3D View: [bigs] Basemaps" & "Node Editor: [bigs] Terrain analysis" i get an error (also shown in image at the top).

I'm running 2.77 on windows 7
![error blender](https://cloud.githubusercontent.com/assets/19408069/15321911/e971cb98-1c0f-11e6-8e1f-eef556492cf2.PNG)

Thanks!

**Comment by domlysz** [comment]
It seems gdal isn't properly installed and you also have tried to update numpy but it don't work.

I need more details on the steps you followed, have you tried to install GDAL-2.0.2-cp35-none-win_amd64.whl ?

**Comment by aneriw** [comment]
Thanks. I installed following the instructions here (BlenderGIS wiki). I did it in 4 computers, all windows7, Blender 2.77. In one of them worked well, the other 3 still getting the same error. During the instalation everything seems to work well. I have installed GDAL-2.0.2-cp35-none-win_amd64.whl in the same way in the 4 computers, only one works.

**Comment by domlysz** [comment]
Hi,

I make a test this morning with Blender 2.77 and have also this error, maybe some sort of incompatibility between the precompiled packages from http://www.lfd.uci.edu/~gohlke/pythonlibs and the Python executable bundle with Blender. But in this case it's surprising that it has worked for one computer.

As workaround, try the installation with Blender 2.76 and GDAL-2.0.2-cp34-none-win_amd64.whl, this combination worked for me.

**Comment by aneriw** [comment]
Thanks domlysz, I finally installed 2.76 and it works well.
