### ISSUE TITLE
Activation error : already registered class

### ISSUE THREAD

**Issue by domlysz** [domlysz/BlenderGIS#190]
I have received this error on Blender 2.80 Beta using Windows 10.
After downloading the BlenderGIS from Git, I moved the folder to the Blender 2.80 Addons folder. 
Now it appears in the list of addons, but gives the same ValueError (albeit resulting from different lines). 

![BlenderGIS_error](https://user-images.githubusercontent.com/26436062/64076715-44074a80-cc96-11e9-95a9-8d91ee50596f.png)

_Originally posted by @tsloan1377 in https://github.com/domlysz/BlenderGIS/issues/157#issuecomment-526916946_

**Comment by domlysz** [comment]
I can't reproduce this issue, can you try with a fresh install of last Blender 2.8 build (no beta) and last version of BlenderGIS addon (current master).

thx

**Comment by tsloan1377** [comment]
I can confirm that using Blender 2.80 (non-beta) has this working properly, thanks!
