### ISSUE TITLE
Error while activating BlenderGIS in Blender 2.8 2019-07-29

### ISSUE THREAD

**Issue by Neeestoor** [domlysz/BlenderGIS#191]
Installation had no problems, buy when activating the plug in the program send me an error message.
This happened in osx and in windows 10.
Any idea why this is happening?
<img width="770" alt="Captura de Pantalla 2019-09-06 a la(s) 9 26 20" src="https://user-images.githubusercontent.com/50637804/64435739-a42c3100-d088-11e9-8d06-1ce735e4db78.png">

**Comment by domlysz** [comment]
same as #183 
update to  Blender 2.8.1

**Comment by luanluan-l** [comment]
相同的问题
