### ISSUE TITLE
Blender 2.81 - Get SRTM Error

### ISSUE THREAD

**Issue by StephenStrand** [domlysz/BlenderGIS#192]
This isn't the previous error regarding dropping an S from the request URL as I checked the python to make sure that was correct and it was. Below is the error I am getting:

> \addons\BlenderGIS-master\operators\io_get_srtm.py", line 112, in execute
> 
> log.error('Http request fails url:{}, code:{}, error:{}'.format(url, err.cod
> e, err.reason))
> AttributeError: 'URLError' object has no attribute 'code'
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1
> Traceback (most recent call last):
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 1317, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 1244, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 1290, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 1239, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 1026, in _send_output
>     self.send(msg)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 966, in send
>     self.connect()
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 938, in connect
>     (self.host,self.port), self.timeout, self.source_address)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\socket.py", line 727, in create_connection
>     raise err
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\socket.py", line 716, in create_connection
>     sock.connect(sa)
> TimeoutError: [WinError 10060] A connection attempt failed because the connected
>  party did not properly respond after a period of time, or established connectio
> n failed because connected host has failed to respond
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\strands\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
> \addons\BlenderGIS-master\operators\io_get_srtm.py", line 108, in execute
>     with urlopen(rq) as response, open(filePath, 'wb') as outFile:
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 531, in open
>     response = meth(req, response)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 641, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 563, in error
>     result = self._call_chain(*args)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 503, in _call_chain
>     result = func(*args)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 755, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 525, in open
>     response = self._open(req, data)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 543, in _open
>     '_open', req)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 503, in _call_chain
>     result = func(*args)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 1345, in http_open
>     return self.do_open(http.client.HTTPConnection, req)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 1319, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt fail
> ed because the connected party did not properly respond after a period of time,
> or established connection failed because connected host has failed to respond>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\strands\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
> \addons\BlenderGIS-master\operators\io_get_srtm.py", line 43, in invoke
>     return self.execute(context)#context.window_manager.invoke_props_dialog(self
> )
>   File "C:\Users\strands\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
> \addons\BlenderGIS-master\operators\io_get_srtm.py", line 112, in execute
>     log.error('Http request fails url:{}, code:{}, error:{}'.format(url, err.cod
> e, err.reason))
> AttributeError: 'URLError' object has no attribute 'code'
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1
> Traceback (most recent call last):
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 1317, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 1244, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 1290, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 1239, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 1026, in _send_output
>     self.send(msg)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 966, in send
>     self.connect()
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 938, in connect
>     (self.host,self.port), self.timeout, self.source_address)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\socket.py", line 727, in create_connection
>     raise err
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\socket.py", line 716, in create_connection
>     sock.connect(sa)
> TimeoutError: [WinError 10060] A connection attempt failed because the connected
>  party did not properly respond after a period of time, or established connectio
> n failed because connected host has failed to respond
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\strands\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
> \addons\BlenderGIS-master\operators\io_get_srtm.py", line 108, in execute
>     with urlopen(rq) as response, open(filePath, 'wb') as outFile:
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 531, in open
>     response = meth(req, response)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 641, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 563, in error
>     result = self._call_chain(*args)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 503, in _call_chain
>     result = func(*args)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 755, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 525, in open
>     response = self._open(req, data)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 543, in _open
>     '_open', req)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 503, in _call_chain
>     result = func(*args)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 1345, in http_open
>     return self.do_open(http.client.HTTPConnection, req)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 1319, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt fail
> ed because the connected party did not properly respond after a period of time,
> or established connection failed because connected host has failed to respond>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\strands\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
> \addons\BlenderGIS-master\operators\io_get_srtm.py", line 43, in invoke
>     return self.execute(context)#context.window_manager.invoke_props_dialog(self
> )
>   File "C:\Users\strands\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
> \addons\BlenderGIS-master\operators\io_get_srtm.py", line 112, in execute
>     log.error('Http request fails url:{}, code:{}, error:{}'.format(url, err.cod
> e, err.reason))
> AttributeError: 'URLError' object has no attribute 'code'
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1
> Traceback (most recent call last):
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 1317, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 1244, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 1290, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 1239, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 1026, in _send_output
>     self.send(msg)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 966, in send
>     self.connect()
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\http\client.py", line 938, in connect
>     (self.host,self.port), self.timeout, self.source_address)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\socket.py", line 727, in create_connection
>     raise err
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\socket.py", line 716, in create_connection
>     sock.connect(sa)
> TimeoutError: [WinError 10060] A connection attempt failed because the connected
>  party did not properly respond after a period of time, or established connectio
> n failed because connected host has failed to respond
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\strands\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
> \addons\BlenderGIS-master\operators\io_get_srtm.py", line 108, in execute
>     with urlopen(rq) as response, open(filePath, 'wb') as outFile:
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 531, in open
>     response = meth(req, response)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 641, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 563, in error
>     result = self._call_chain(*args)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 503, in _call_chain
>     result = func(*args)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 755, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 525, in open
>     response = self._open(req, data)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 543, in _open
>     '_open', req)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 503, in _call_chain
>     result = func(*args)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 1345, in http_open
>     return self.do_open(http.client.HTTPConnection, req)
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\python\lib\urllib\request.py", line 1319, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt fail
> ed because the connected party did not properly respond after a period of time,
> or established connection failed because connected host has failed to respond>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\strands\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
> \addons\BlenderGIS-master\operators\io_get_srtm.py", line 43, in invoke
>     return self.execute(context)#context.window_manager.invoke_props_dialog(self
> )
>   File "C:\Users\strands\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
> \addons\BlenderGIS-master\operators\io_get_srtm.py", line 112, in execute
>     log.error('Http request fails url:{}, code:{}, error:{}'.format(url, err.cod
> e, err.reason))
> AttributeError: 'URLError' object has no attribute 'code'
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1
> Traceback (most recent call last):
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\scripts\modules\bpy_types.py", line 736, in draw_ls
>     def draw_ls(self, context):
> KeyboardInterrupt
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1
> Traceback (most recent call last):
>   File "C:\Program Files\Blender Foundation\blender-2.81-8f55794c0e80-windows64\
> 2.81\scripts\startup\bl_ui\space_statusbar.py", line 26, in draw
>     def draw(self, context):
> KeyboardInterrupt
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1

**Comment by seristee** [comment]
im getting the same error as well. Can anyone give some advice on a possible fix

**Comment by hcw70** [comment]
Gives timeout for me also.

Looks like `http://opentopo.sdsc.edu/otr/getdem?demtype=SRTMGL3&west=-120.168457&south=36.738884&east=-118.465576&north=38.091337&outputFormat=GTiff` gives an timeout 
while `http://opentopo.sdsc.edu` works as an url....

**Comment by aerialoperator** [comment]
I am receiving the same error:

Traceback (most recent call last):
  File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 43, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 108, in execute
    with urlopen(rq) as response, open(filePath, 'wb') as outFile:
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\urllib\request.py", line 1320, in do_open
    r = h.getresponse()
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by wilsimar** [comment]
same here

**Comment by matsromblad** [comment]
Also here :(

**Comment by damaleiding** [comment]
looks like I also have it

**Comment by domlysz** [comment]
see #305
