### ISSUE TITLE
Library not loaded error on 2.8

### ISSUE THREAD

**Issue by jrue** [domlysz/BlenderGIS#195]
I have a fresh Blender 2.8 install and was trying to install this add-on. I'm on a Mac. This error comes up when activating it. 

![screenshot](https://user-images.githubusercontent.com/283022/65002485-e2a3c600-d8a8-11e9-9835-c0690ce4cbfb.png)

If it's too small, the end of the traceback says 

```
ImportError: dlopen(/Applications/Blender.app/Contents/Resources/2.80/python/lib/python3.7/lib-dynload/_sqlite3.cpython-37m-darwin.so, 2): Library not Loaded: /Users/brecht/dev/build_darwin/deps/Release/sqlite/lib/libsqlite3.0.dylib
Referenced from: /Applications/Blender.app/Contents/Resources/2.80/python/lib/python3.7/lib-dynload/_sqlite3.cpython-37m-darwin.so
Reason: image not found
```

**Comment by jrue** [comment]
Updating to Blender 2.81 solved this issue. Thanks.

**Comment by annalisasnow** [comment]
Had the same issue (Blender 2.81a), updated to Blender 2.83 alpha, all works but the error is a bit weird

**Comment by domlysz** [comment]
It's a Blender issue, cannot do anything on my side
https://developer.blender.org/T68243

duplicate #224
