### ISSUE TITLE
OSM Web Map Service: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by wolfgangvonludwigsburg** [domlysz/BlenderGIS#196]
GIS > Web geodata > Basemap
Source: OSM
Layer : Mapnik

yields

**ERROR:BlenderGIS-master.core.basemaps.mapservice:588:Can't download tile x0 y0. Error HTTP Error 403: Forbidden**

Faked browser headers, like
BlenderGIS-master\core\basemaps\mapservice.py
393:	#Fake browser header
..

are recently refused by OSM, according to OSM usage politics,
see developer reasons and discussion
https://lists.openstreetmap.org/pipermail/dev/2019-May/thread.html#30629
https://github.com/radioman/greatmaps/issues/132

Extracted comment:

> The tile.openstreetmap.org CDN is at breaking point.
> 
> We now frequently push more than
> 3TB per second of traffic, with over
> 22.000 requests per second/
>
> We are reaching the limit of what our current stack/config can handle.

Do we have any Workaround .. ?

**Comment by domlysz** [comment]
seems the referer in serviceDefs.py must be updated to https

**Comment by wolfgangvonludwigsburg** [comment]
That solved it! - 1000 x thanks!!

Concerning **"OSM_WMS" Web Map Service ..**

I get

> ERROR:BlenderGIS-master.core.basemaps.mapservice:588:Can't download tile x0 y0.
> Error <urlopen error [WinError 10061]
> Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte>
> 

Requesting Call is:

> ERROR:BlenderGIS-master.core.basemaps.mapservice:589:http://129.206.228.72/cached/osm?
> 
> SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:3857&LAYERS=osm_auto:all&FORMAT=image/png&STYLES=&BBOX=-20037508.342789244,-
> 
> 20037508.34278924,20037508.342789244,20037508.342789248&WIDTH=256&HEIGHT=256&TRANSPA

**Comment by domlysz** [comment]
https://github.com/domlysz/BlenderGIS/commit/cdb415e69bfbfcce14afdb3f2039035f8149da12
