### ISSUE TITLE
Some ways/relations segments are missing when using "Get OSM"

### ISSUE THREAD

**Issue by wolfgangvonludwigsburg** [domlysz/BlenderGIS#198]
**On one Hand:**
```
GIS > Web geodata > Basemap
Source: OSM
Layer : Mapnik

G #Goto
Red Cliff Bridge, Co
16

E #Export

```

```
GIS > Web geodata > Get OSM

[X] buildings
[X] highway
[X] railway
[X] waterway

OK
```

Zoom towards the "Red Cliff Bridge",
and toogle visability of "EXPORT_OSM_MAPNIK_WM"-Plane

You see, that -among other way segments- the **northern part of the way/relation
"Highway US 24" is missing**

**On the other Hand:**
I've exported this same region from

> https://www.openstreetmap.org/search?query=Red%20Cliff%20Bridge
> %2Cco#map=17/39.50741/-106.37738
> 

to file "Red Cliff, Colorado.osm"

then

> GIS > Import > Open Street Map xml (osm)
> "Red Cliff, Colorado.osm"
> 

brings up the complete "Highway US 24" way/relation

Additionally, "Get OSM" (using Overpass-API) obviously delivers
a different set of ways/relations (segments) then direct "Import" ..

Do we have an error in the Overpass-XML response, or in the Blender-GIS XML Parser ? ..

**Comment by wolfgangvonludwigsburg** [comment]
**Third Hand: Direct Import of previous Overpass Response**

In BlenderGIS-master\operators\lib\osm\overpy\__init__.py

around line 84, I traced the overpass response to a file "overpass.osm",
then

```
GIS > Import > Open Street Map xml (osm)
"overpass.osm"

```
Now the nothern part of "Highway US 24" is present,
but the bridge itself, and the southern part of "Highway US 24" is missing

**Comment by domlysz** [comment]
Note that it's possible to trace the overpass query by setting the log level to "debug" in addon's preferences. Then the query can be tested directly in [overpass turbo webservice](https://overpass-turbo.eu/#)

Here the Query
`
[out:xml][bbox:39.4999458924883,-106.39700708101053,39.516611089231674,-106.35873022204491];(((way[railway];way[building];way[highway];);>;););out;`

Seems the output include the highway, so the query is correct. I need to investigate more to understand why the highway is filtered out when parsing the xml.

**Comment by wolfgangvonludwigsburg** [comment]
Thanks for your response!
**First of all, my appreciation for this outstanding project, thank you so much!!**

I tested some (smaller) ways, these were all correct,
so I guess the issue comes in the context of relations

You get reproduceable errors with **relation id="121136"**
concering **GIS > Import > Open Street Map xml (osm)**

Steps:

(1) Overpass Turbo query:
```
[out:xml];
(
  relation(121136);
);
(._;>;);
out;

```
(2) I stored query result XML as file: relation(121136)-US 24 (CO).osm

(3) Import this file into Blender
```
GIS > Import > Open Street Map xml (osm)
relation(121136)-US 24 (CO).osm

```
(4) After Import, in Blender Orthographic View + TOP/BOTTOM/FRONT/RIGHT/../ View => there are **distortions in the 3D-View Window**, which I can't explain .. ?
    If I change to Perspective View, the distortions vanish ..

(5) Merge "Double Nodes" ..
```
Ways > Edit Mode > Mesh > Clean Up > Merge by Distance
Set Merge Distance = 0.1

```
(6) Select any node of the mesh .., then > Select > Select Linked > Linked # or Ctrl L

You see, that only part of the mesh edges are linked together ..
=> i.e. there are gaps in the mesh

Btw, are these "Double Nodes" intensional .. ?

**Comment by wolfgangvonludwigsburg** [comment]
I found a (maybe) simpler testcase ..

(1) Administrative Boundary of Ludwigsburg, City

```
[out:xml];
(
  relation(405292);
);
(._;>;);
out;
```
![relation(405292) - Stadtgrenze Ludwigsburg](https://user-images.githubusercontent.com/9339385/67534226-7600c000-f6cd-11e9-9f67-e0475921f36f.jpg)

=> Missing edges in Blender GIS OSM-Import mesh <=> missing way id=238132494


(2) Complete/Supplement/Repair the Boundary with missing way ..

```
[out:xml];
(
  way(238132494);
);
(._;>;);
out;
```

**Comment by domlysz** [comment]
Thanks for your help on this, I'm very disapointed with this issue ! I found there are at less 2 issues both related to the parser [overpy](https://github.com/DinoTools/python-overpy)

1. the parser sometimes does not report the tags list of an object. For exemple in your first query, the northern part of highway 24 is missing because the parser return no tags for this way, if you uncheck all filter in the operator parameters then the highway appears.
![image](https://user-images.githubusercontent.com/5639024/67561921-0666f100-f71e-11e9-9dac-1b3365836d40.png)

2. the parser sometimes return only a subset of a way's nodes. For exemple, in your last query the way 238132494 is not missing, you can see it if you check the _separate objects_ option, but the way contains only one node.
![image](https://user-images.githubusercontent.com/5639024/67562156-84c39300-f71e-11e9-8ced-31906dd2726b.png)

Surprisingly this second issue appears only when importing from an xml file not when parsing directly the overpass result. But under the hood these 2 operators use the same functions !

**Comment by wolfgangvonludwigsburg** [comment]
I'am in a hurry now, I'll investigate your last post later!

With my last test case **"Administrative Boundary of Ludwigsburg, City"**,
I tried to find the error,
here I report the analytics so far ..

In /operators/io_import_osm.py
I traced the seed(..) parameters, like so:

`
       print( "seed(", id, tags, pts, ")" )
`

which logs like so:

    ..
    Processing way.id 238132494
    seed( 238132494 {} [(9.2226617, 48.9271464)] )
    ..

=> Missing tags, only 1 node location (lon, lat),
which refers to

`    node id="2459890622" lat="48.9271464" lon="9.2226617"
`

But in reality (OSM-level) we have tags, and many nodes ..

    <relation id="405292">
        ..
        <member type="way" ref="238132494" role="outer"/>
        ..

      <way id="238132494">
        <nd ref="2459890622"/>  <==
        <nd ref="2459890614"/>
        <nd ref="2459890580"/>
        <nd ref="2459890578"/>
        <nd ref="2459890563"/>
        <nd ref="2459890561"/>
        <nd ref="2459890568"/>
        <nd ref="2459890582"/>
        <nd ref="2459890587"/>
        <nd ref="2459890589"/>
        <nd ref="2459890591"/>
        <nd ref="2459890601"/>
        <nd ref="2459890598"/>
        <nd ref="2459890594"/>
        <nd ref="2459890596"/>
        <nd ref="2459890607"/>
        <nd ref="2459890616"/>
        <nd ref="2459890618"/>
        <nd ref="2459890620"/>
        <nd ref="2459890627"/>
        <nd ref="2459890635"/>
        <nd ref="2459890642"/>
        <nd ref="2459890662"/>
        <nd ref="2459890698"/>
        <nd ref="2459890719"/>
        <tag k="admin_level" v="7"/>
        <tag k="boundary" v="administrative"/>
        <tag k="source" v="LGL, www.lgl-bw.de"/>
      </way>

**Comment by domlysz** [comment]
ok found the incriminate part of code, I used a workaround function and now it's fixed

**Comment by wolfgangvonludwigsburg** [comment]
**Many thanks for this fast fix!!**
All of my test cases now fully functional!

(btw, before getting your fix, I continued doing some testing ..
- I found out, that in the ET.iterparse for loop,
ONLY the falsy **overpy.Way (238132494)** did had this value: **child.tail = None** !)
