### ISSUE TITLE
Basemap is 1.477x to big?

### ISSUE THREAD

**Issue by mirlip** [domlysz/BlenderGIS#20]
Hi Domlysz,
First of all, your addon is really impressive and useful!
I tried to get the basemap align with the 3D DTM from maperitive. But somehow, there is a light scale difference. The 3D model from maperitive aligns perfectly with .osm datas downloaded from the overpass API of openstreetmap.
What I've tried so far to solve the problem:
- set blender to metric system
- Set the right CRS system for the location
But even with those 2 options, the basemap is bigger. I tried to find the factor by scaling the OSM import and I found it to be around 1.477.
Would it be possible to have the basemap have the real scale?

**Comment by domlysz** [comment]
Hi,

Do you import OSM data with BlenderGEO ?

**Comment by mirlip** [comment]
I tried both with BlenderGeo and with the official BF plugin (from addon_contrib). The DTM from maperitive is imported with the default collada importer.

**Comment by domlysz** [comment]
I think is just a CRS issue. BlenderGeo use it's own CRS (transmerse mercator centered to scene origin). Basemap CRS depends on the source, for Google, Bing or OSM it's a Web Mercator projection. Web Mercator causes lot of [distortion](https://en.wikipedia.org/wiki/Mercator_projection#/media/File:Tissot_mercator.png) : the further away from the equator, the more the map will be scale up.

For now there is no compatibility between BlenderGIS and BlenderGeo, I'm currently working on a whole refactoring on how BlenderGIS handle georef infos and I hope to able to fix this compatibility issue.

Maybee a workaround if GDAL is working 
- after importing osm data, look the longitude in scene custom properties
- start basemaps and set the CRS to _Custom (as Scene)_ and put this CRS : 
`+a=6378137 +b=6378137 +proj=tmerc +lat_0=0 +lon_0=LONGITUDE +k_0=1 +x_0=0 +y_0=0 +units=m` **(replace LONGITUDE with the current one set into scene properties)**

**Comment by mirlip** [comment]
Tried it but Blender crashes, will try again after https://github.com/domlysz/BlenderGIS/issues/22 is resolved

**Comment by mirlip** [comment]
ok, now I can use it. But it then doesn't download the maps and any pan or zoom action brings me very near from 0,0,0 and I can't zoom out anymore.

**Comment by domlysz** [comment]
try to run first basemaps with CRS set to "as tile matrix", then zoom a little, level 5 for example and then press spacebar and now switch the CRS to custom

**Comment by mirlip** [comment]
Yes it works when done through spacebat after "as tile matrix" :)

**Comment by domlysz** [comment]
#10

**Comment by mirlip** [comment]
In the latest version, after importing a dxf and recalculating the origin, if I start the basemap, it makes the bug mentioned above again: no image displayed, zoom locked. Problem is the sollution above doesn't work anymore. There is no "as tile matrix" anymore. And when I press spacebar, I don't have a custom option anymore. Where those options renamed?

**Comment by domlysz** [comment]
These old options was just a way to define the scene CRS, now use the new dedicated layout.
- if you your scene crs is the same that the tile matrix crs then the situation is like the old "as tile matrix" option
- if your scene crs is different then it's like the custom option

![selection_015](https://cloud.githubusercontent.com/assets/5639024/16124609/f0fd81f2-33ef-11e6-9133-d2ebbf894d49.jpg)

The problem is that when you start basemap for the first time there isn't any zoom level reference, so it set the zoom level at zero and draw a map of the whole world but not all projection can draw a map of the whole world. When you import a dxf you also set the scene crs and if gdal can't build a world map using this crs then all become broken.

I have already planned to add an option to directly zoom to existing objects when starting basemaps.
A workaround when all seems broken, press G then just increase the zoom level and press ok

**Comment by mirlip** [comment]
After importing this dxf: https://github.com/domlysz/BlenderGIS/files/313506/test1.zip (I modified my dxf importer do.py to have correct lat and long), I started basemap with default parameters:
![problem basemap after dxf import](https://cloud.githubusercontent.com/assets/12851284/16127178/9b213db2-33fb-11e6-907a-5acbea05da32.PNG)
It gives this view, near from cube actually:
![view after basemap start](https://cloud.githubusercontent.com/assets/12851284/16127256/f43dc366-33fb-11e6-8eaf-b3d7e74c2f23.JPG)
and then I pressed G and modified the zoom from 0 to 10, but it didn't work either. So I set on 20, it downloaded tiles, zoom was working again, but it was all grey
![view after zoom 20](https://cloud.githubusercontent.com/assets/12851284/16127285/142b90c2-33fc-11e6-96a2-c64a3fbd5b3e.JPG)

**Comment by domlysz** [comment]
The problem come from the source OSM WMS, there was a bug now it's fixed

**Comment by domlysz** [comment]
just added a new option for automatically center to existing objects
https://github.com/domlysz/BlenderGIS/commit/8ad41946e340346722d30fb075a8f74b3ebcab0a

**Comment by mirlip** [comment]
awesome, it works really good now now and in a very user friendly way :)
