### ISSUE TITLE
Error while trying to load a DEM file

### ISSUE THREAD

**Issue by leonardofmed** [domlysz/BlenderGIS#201]
Some time ago I could generate a 3D model by relating an orthophoto and a DEM, simply by following the steps described in the wiki of this repository. Now while trying the same way I've been having some issues, am I forgetting something? Was something changed in this new version? Is this a file problem?

Tried to open the .tif as "Raw DEM" and got:
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\BlenderGIS-master\operators\io_import_georaster.py", line 434, in execute
    grid = GeoRaster(filePath, subBoxGeo=subBox, useGDAL=HAS_GDAL)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\BlenderGIS-master\core\georaster\georaster.py", line 69, in __init__
    self._fromTIFF()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\BlenderGIS-master\core\georaster\georaster.py", line 125, in _fromTIFF
    tif = Tyf.open(self.path)[0]
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\BlenderGIS-master\core\lib\Tyf\__init__.py", line 479, in open
    elif first in [0x4d4d, 0x4949]: obj = TiffFile(fileobj)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\BlenderGIS-master\core\lib\Tyf\__init__.py", line 310, in __init__
    next_ifd = from_buffer(i, fileobj, next_ifd, byteorder)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\BlenderGIS-master\core\lib\Tyf\__init__.py", line 99, in from_buffer
    _read_IFD(obj, fileobj, offset, byteorder)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\BlenderGIS-master\core\lib\Tyf\__init__.py", line 83, in _read_IFD
    else: tt.value = unpack(fmt, fileobj)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\BlenderGIS-master\core\lib\Tyf\__init__.py", line 11, in <lambda>
    unpack = lambda fmt, fileobj: struct.unpack(fmt, fileobj.read(struct.calcsize(fmt)))
struct.error: unpack requires a buffer of 4 bytes
```

After sucessfully opened an orto raster "As plane" and then tried to import the DEM as "On mesh", selecting the orto as "Object", got the same error.

Converted the DEM .tif to JPG, tried to import as Raw DEM again, got the following traceback:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'label'
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\BlenderGIS-master\operators\io_import_georaster.py", line 447, in execute
    mesh = exportAsMesh(grid, dx, dy, self.step, reproj=rprjToScene, subset=self.clip, flat=False, buildFaces=self.buildFaces)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\BlenderGIS-master\operators\utils\georaster_utils.py", line 117, in exportAsMesh
    if z == georaster.noData:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Using Blender 2.8 in Windows 10.

I can open this file in QGIS normally, without any errors. Unfortunately I can't share this file, but I can share some info related to it:
Type: float-32
SRC: EPSG 31982

**Comment by domlysz** [comment]
Can you try to convert the original tiff file to a new tiff copy with QGIS ?

The second error message is a bit tricky, but in fact it's just because a jpg file always has 3 bands (RGB) but a DEM file is expected to have only one band. Also jpeg compression algorithm will alter pixels elevation values

**Comment by leonardofmed** [comment]
> The second error message is a bit tricky, but in fact it's just because a jpg file always has 3 bands (RGB) but a DEM file is expected to have only one band. Also jpeg compression algorithm will alter pixels elevation values

Very informative, thank you!

I exported the DEM from QGIS as a new TIFF file. I can see that the size is changed, from 200MB to 350MB.

First I tried to import the new DEM as "Raw DEM", not getting any errors, but Blender just stuck at loading. I waited 30 minutes, but nothing happened, I remember that before the load of the file last 5 minutes. I see that the memory usage was quite high in the end, using 5GB (my machine has 8).

Then I tried to load as "On mesh", after loading the orto raster, but the result was basically the same, Blender having a hard timing and "Not responding" anymore.

Then I tried to lower the DEM resolution while export another copy, now with a 50MB file. Again tried to import as "Raw DEM" and the same thing happen, with the strange memory usage included. The tried as "On mesh", now the file loads, but nothing changes in the 3D view, the flat plane continues the same, but in console I received this:

> TIFFReadDirectory: Warning, Unknown field with tag 33550 (0x830e) encountered.
> TIFFReadDirectory: Warning, Unknown field with tag 33922 (0x8482) encountered.
> TIFFReadDirectory: Warning, Unknown field with tag 34735 (0x87af) encountered.
> TIFFReadDirectory: Warning, Unknown field with tag 34736 (0x87b0) encountered.
> TIFFReadDirectory: Warning, Unknown field with tag 34737 (0x87b1) encountered.
> TIFFReadDirectory: Warning, Unknown field with tag 42113 (0xa481) encountered.
> TIFFReadDirectory: Warning, Unknown field with tag 33550 (0x830e) encountered.
> TIFFReadDirectory: Warning, Unknown field with tag 33922 (0x8482) encountered.
> TIFFReadDirectory: Warning, Unknown field with tag 34735 (0x87af) encountered.
> TIFFReadDirectory: Warning, Unknown field with tag 34736 (0x87b0) encountered.
> TIFFReadDirectory: Warning, Unknown field with tag 34737 (0x87b1) encountered.
> TIFFReadDirectory: Warning, Unknown field with tag 42113 (0xa481) encountered.

**Comment by leonardofmed** [comment]
Tried again, now in a more "stronger" computer with 16GB of RAM and a different DEM file. Sadly the same thing occurred, including the strange memory usage, now reaching 10GB of RAM to load a 60MB DEM file. Waited 30 min again.

**Comment by domlysz** [comment]
do you mean this file worked with Blender 2.7x?

Your file is huge, the high RAM usage is not surprising, are you sure blender itself can load the file when opening in the image editor? The raw DEM option have very poor performance, avoid using it with large file. Using the DEM as displace texture is more memory friendly but you will need to subdivide the mesh to see the deformation, I suspect your file cover a very large extent and maybe the subsurf does not give enough vertices to see any displacement.

It's hard to investigate without the file...

**Comment by leonardofmed** [comment]
Yes, in 2.7x version I uploaded even slightly larger files, usually a 100MB orthophoto and a DEM ranging from 10-200MB, depending on the project.

But it's good to know that this use of RAM is not unexpected. I remember before, to achieve the desired strain level, I had to adjust the level of subdivisions as you said.

Unfortunately I have no way to make the file available because it is a confidential project of the company I work for, but if you have any public DEM .tif files I can test without problems.

I tried try to shrink this file a little more.

- Could load a 1MB DEM as Raw DEM, but Blender crashed after tried to load a 30MB orto "As DEM texture";
- Loaded a 1MB DEM as Raw DEM, but Blender crashed after tried to load a 10MB orto "As DEM texture";
- Loaded a 1MB DEM as Raw DEM, but Blender crashed after tried to load a 2MB orto "As DEM texture";
- Loaded a 30MB orto as "On plane", then loaded the DEM as "On mesh", but it won't merge correctly, looked like the "On plane" with some cutted borders. [image]

**Comment by domlysz** [comment]
You don't follow the right workflow
- For importing a DEM you must use the option _Raw DEM_ or _As DEM texture_. The first option will create one vertice per pixel, the second just use the DEM as displacement texture (modifier). Do not trying to load an RGB orthophoto with the option _As DEM texture_, it will crash.
- For importing a basemap like an orthophoto you can use the options _On plane_ if you want a single plane mesh or _On mesh_ if you want to apply the image to an existing mesh like a previously imported DEM. Do not try to load a DEM with _On Mesh_ option, it will remain flat.

So for combining A DEM with an Ortho there are 2 possible ways :
1. Import the DEM with _Raw DEM_ or _As DEM texture_ and then import the ortho with the option _On mesh_
2. Import the ortho _As Plane_ and then import the DEM with the mode _As DEM texture_ and the option _Apply on existing mesh_

**Comment by leonardofmed** [comment]
I can't believe this. I did this so many times 6 months ago that I wasn't even considering that the input options could be wrong. I apologize for your time and thank you for all the help and information.

Both options worked perfectly. many times 6 months ago that
