### ISSUE TITLE
Import OSM missing objects

### ISSUE THREAD

**Issue by KrzysztofTrojan** [domlysz/BlenderGIS#203]
Hello,
I am using Blender 2.82. When I try to get some OSM data (buildings) it appears that some of them are missing. I suppose that this may refer to more complex shapes. These buildings actually exist in OSM, because they can be seen in other viewers and I've managed to convert .osm to .obj and then imported to Blender. Here all buildings look fine, but here is the problem to place them in a right scale, in accurate place and on the surface of loaded DEM.
I will appreciate any help here, thanks!

**Comment by domlysz** [comment]
duplicate #198, need to investigate

**Comment by domlysz** [comment]
What's the location ?

**Comment by domlysz** [comment]
#198 fixed
