### ISSUE TITLE
Imprécision avec Lambert93 ?

### ISSUE THREAD

**Issue by ChameleonScales** [domlysz/BlenderGIS#204]
Bonjour,
J'ai un souci avec mon fond IGN lambert 93 : il semble très imprécis.

Par exemple si je crée 2 empties dans ma scène placés au même endroit sur la Terre, l'un avec des coordonnées Web Mercator (X=506396;Y=6231271) et l'autre avec des coordonnées L93 (X=813900;Y=6850263), si je navigue vers le premier en utilisant le fond par défaut Google Satellite Web Mercator, l'empty associé tombe pile au bon endroit (au milieu d'un rond point). Mais si je navigue vers l'autre empty en utilisant un fond IGN BDORTHO L93 (conçu d'après [ces paramètres proposés](https://github.com/domlysz/BlenderGIS/issues/181#issuecomment-515891589)), l'empty associé est à 2.5 km du rond point!
Est-ce moi qui m'y prend mal ou est-ce une limitation de l'add-on?

**Comment by domlysz** [comment]
ok mystère résolu, j'avais peur que le problème provienne des fonctions cœurs mais finalement c'est juste la définition de la grille qui n'était pas tout à fait correct. Après vérification des échelles fournies par le WMTS je me suis rendu compte que le facteur d'échelle pour passer d'un niveau de zoom à l'autre n'était pas constant. Habituellement il vaut 2, ici il varie plus ou moins autour de 2, ce qui est très surprenant par ailleurs. Comme dans la définition de la grille je l'avais fixé à deux, l’accumulation des erreurs créé un décalage conséquent à la fin. J'ai donc calculé les résolutions exactes à indiquer dans les paramètres de la grille.
```
	"LB93_IGN" : {
		"name" : 'Fr Lambert 93 IGN',
		"description" : 'Local grid in French Lambert 93 projection',
		"CRS": 'EPSG:2154',
		"bbox": [0, -80000000, 135000000, 12000000], #w,s,e,n
		"bboxCRS": 'EPSG:2154',
		"tileSize": 256,
		"originLoc": "NW",
		"resolutions" : [104579.224549894, 52277.5323537905, 26135.4870785954, 13066.8913818, 6533.2286041135, 3266.5595244627, 1633.2660045974, 816.629554986, 408.3139146768, 204.1567415109, 102.0783167832, 51.0391448966, 25.5195690743, 12.7597836936, 6.379891636, 3.1899457653, 1.5949728695, 0.7974864315, 0.3987432149, 0.1993716073, 0.0996858037]
	}
```
Avec cette config les décalages disparaissent.

**Comment by domlysz** [comment]
TODO implémenter une fonction pour obtenir les paramètres du WMTS directement depuis le service

**Comment by ChameleonScales** [comment]
Merci ! ça fonctionne très bien

**Comment by domlysz** [comment]
#222
