### ISSUE TITLE
Map moves when viewport is vertical

### ISSUE THREAD

**Issue by ChameleonScales** [domlysz/BlenderGIS#206]
If the 3D viewport has a "portrait" aspect ratio, navigating the map causes it to change position and scale :
![gif](https://i.imgur.com/nsZdy9N.gif)

**Comment by domlysz** [comment]
fixed https://github.com/domlysz/BlenderGIS/commit/593ef102f3ea9c0b67eb64ea95f7dd04b05b9e57

**Comment by ChameleonScales** [comment]
Awesome, thank you! it works fine now
