### ISSUE TITLE
zoom to mouse + unlock objects + unlock origin breaks alignment

### ISSUE THREAD

**Issue by ChameleonScales** [domlysz/BlenderGIS#210]
When I use these settings:
![](https://i.imgur.com/kekL4mi.png)
Zooming and unzooming displaces the map and the further away my mouse is from the area's center, the more the map gets displaced.

**Comment by domlysz** [comment]
There is no issue here, it's an expectable behavior
- checking zoom to mouse option and unchecking lock origin will uptate the origin's geolocation at each zoom
- lock objects is the option that dynamically readjust objects location to maintain their georeferencing accordingly to the new geolocation of the scene origin, so without this option georeferencing will be break. Depending of what kind of objects you have in your scene, sometimes it can be useful to not move objects with the origin

**Comment by ChameleonScales** [comment]
It's an understandable behavior. However, I'm not sure why there couldn't be a way so that the point you zoom on with your cursor would still stay under your cursor. Might be tricky but seems possible to me.

**Comment by domlysz** [comment]
ok I understand now the problem : while the new image is not fully loaded the map appears missaligned. I think it will be not so hard to fix.

**Comment by domlysz** [comment]
fixed https://github.com/domlysz/BlenderGIS/commit/f6317a377a75ff63083aafc78f8a092765413daf

**Comment by ChameleonScales** [comment]
Yay, thank you!
