### ISSUE TITLE
project basemap image onto ARCGIS asc grid import

### ISSUE THREAD

**Issue by perthvr** [domlysz/BlenderGIS#211]
Hi
thanks for this great blender addon. Just wondering how to combine/project  basemap onto the arcgis asci grid. the image and SRTM combine automatically  and work fine . Just not sure how to do it when using a surface/mesh derived from the asc grid file. the asc grid file comes from from an Australian elevation data set.
![flinders_ter_sat](https://user-images.githubusercontent.com/34245172/67925602-d2dd0880-fbee-11e9-9e22-2bcd1addcef6.jpg)
cheers and thanks Sally

**Comment by domlysz** [comment]
It will be easiest if you convert your asc to tiff file. Then follows these steps
1. start basemaps and navigate to your location, when your happy with the map extent press E to export the maps to a new plane mesh
2. import your geotiff DEM with theses options
 - mode _As DEM Texture_
 - check _apply on existing mesh_ and select the exported basemap

Alternatively if you really don't want to convert your asc file you can run this workflow:
1. save your blend file
2. same as before : start basemaps, navigate to your location and press E to export. You will see in your blend folder a new tiff file corresponding to the exported basemap. You can delete the new generated plane mesh (this background map will be reimported later)
3. import your asc file for generate the DEM mesh
4. import the basemap tiff with the mode _On mesh_ with the imported DEM mesh selected in the drop down list

**Comment by perthvr** [comment]
hi 
thanks heaps that worked a treat.
Sally
