### ISSUE TITLE
Blender 2.8 cannot install BlenderGIS

### ISSUE THREAD

**Issue by willjnz** [domlysz/BlenderGIS#212]
I download source archive from github and in Blender 2.8 I navigate to Edit > Preferences > Add-Ons > Install...
When I select the zip Blender shows a success message in the bottom right corner however the add-on cannot be found in the addons sections (official, community, and testing).
These options are different to the way it is described in the install part of the wiki which I assume refers to an old version.

![image](https://user-images.githubusercontent.com/28743123/67952985-81cd1480-fbee-11e9-849c-062ecb9ef947.png)

Thanks.

**Comment by domlysz** [comment]
any error message in the system console ?

**Comment by czarmanu** [comment]
I had the same problem, but, when I manually pasted BlenderGIS folder in blender*/2.80/scripts/addons/ folder, the addon apppeared in edit->preferences->addons in the GUI

**Comment by willjnz** [comment]
![image](https://user-images.githubusercontent.com/28743123/68936725-6f7cda00-079b-11ea-8458-e2431680fb1a.png)

**Comment by domlysz** [comment]
seems like the addon is now installed twice, delete the one into C:\Users\[profile]\AppData\Roaming\Blender Foundation\...

**Comment by domlysz** [comment]
please retry with a fresh and clean Blender install
the addon now deal better with already registered class https://github.com/domlysz/BlenderGIS/commit/472e51f8ba6c4e4095f627397ded7f378a7e8325 but I'm not sure about the origin of this problem and if it will be enough to fix
