### ISSUE TITLE
[MAC] Issue installing BlenderGIS

### ISSUE THREAD

**Issue by alicegrenie** [domlysz/BlenderGIS#213]
Hello there, 
I'mI' not sure if this has already been resolved before. 
I'm on Blender 2.8. I can see the add-on in the user preference. But on I tick it, I see the attached and it doesn't want to work. 

I hope you can help. 

Cheers

![Screenshot 2019-11-06 at 15 07 47](https://user-images.githubusercontent.com/39518232/68310224-8d658300-00a7-11ea-9fc5-7e5341f9fe2e.png)
,

**Comment by domlysz** [comment]
duplicate #182 #183

**Comment by alicegrenie** [comment]
Thank you!

**Comment by infun8** [comment]
I'm having the same issue. 
Mac OSX 10.15.1
Python 2.7.15

If there is anything I can do (very basic command line) to help to find, or chack a solution, please let me know.

**Comment by domlysz** [comment]
try a daily build : https://builder.blender.org/download/

**Comment by infun8** [comment]
Works using latest build!!!!

**Comment by BROADY0RR01** [comment]
I have the same problem, I just see folders in Download?
