### ISSUE TITLE
Crash when changing the spatial reference system

### ISSUE THREAD

**Issue by moumoualt** [domlysz/BlenderGIS#214]
Hello,

Blender crashs when i want to change the spatial reference system. Precisely, the button "add" for enter a new reference system works but the research of a specific spatial system stops Blender. 

hopefully you'll get a solution,

**Comment by domlysz** [comment]
works correctly for me, do you have some web restrictions ?

**Comment by moumoualt** [comment]
I don't think so. I check my antivirus software, and when it's disabled, the same result. As a last resort, i can use Blender 2.79. This version (and blenderGis) works on my computer.

Thanks for the reply

**Comment by domlysz** [comment]
try to start blender through a system terminal and check if any error message is reported

**Comment by moumoualt** [comment]
no messages, everithing is normal at thirst sight.

**Comment by domlysz** [comment]
if the search function is broken, you can enter yourself the definition, this is just an EPSG code (EPSG:XXXX)

**Comment by moumoualt** [comment]
Yes, it's the solution at this time. 

Thanks a lot
