### ISSUE TITLE
"EPSG:21781" not found

### ISSUE THREAD

**Issue by czarmanu** [domlysz/BlenderGIS#215]
I get the following error:

TypeError: Converting py args to operator properties:  enum "EPSG:21781" not found in ('EPSG:4326', 'EPSG:3857')

when import a georeferenced raster using following line:
bpy.ops.importgis.georaster(filepath=DEM_PATH, importMode="DEM_RAW", subdivision="mesh", rastCRS="EPSG:21781")

I found the solution to fix this issue using GUI by adding the "EPSG:21781" in GIS->Preferences->Add (Spatial reference systems). However, I would like to do the same via bpy since I need to run this on a UNIX cluster where no GUI is possible.

i tried adding the following line before importing the raster via bpy:
bpy.ops.bgis.add_predef_crs("EPSG:21781") but did not work

 What is the solution?

I use blender v2.80 with latest BlenderGIS build

**Comment by domlysz** [comment]
bpy.ops.bgis.add_predef_crs(crs="EPSG:21781", desc="projection description")

**Comment by czarmanu** [comment]
This solved the issue. thanks
