### ISSUE TITLE
DTM has the median Z value it's NaN

### ISSUE THREAD

**Issue by GiulioDonatiSarti** [domlysz/BlenderGIS#216]
Hi there, 

when I import my DTM and I go to 'Edit Mode' the median Z value it's NaN (not a number). That suggests there’s at least one vertex with coordinate(s) that somehow fell out of range of values that can be represented...
There is a way to import the DTM without this issue?

Many thanks.
Giulio

**Comment by domlysz** [comment]
any screenshoot? how do you import your DEM ? Is this DEM contain Nodata values ?

**Comment by GiulioDonatiSarti** [comment]
Hi @domlysz, thank's for your replay!

This is a screenshot with the proprieties of my DTM:
![1](https://user-images.githubusercontent.com/57560074/68529949-27c20280-0304-11ea-8968-aafd7f1f5462.PNG)
So, no, there isn't any Nodata values...

In Blender I imported my DTM with this setting:
![2](https://user-images.githubusercontent.com/57560074/68530018-a6b73b00-0304-11ea-88ff-b1ebc679b4b1.PNG)

And when I switch to 'Edit mode' these are the coordinate median value:
![3](https://user-images.githubusercontent.com/57560074/68530031-d49c7f80-0304-11ea-9037-e04733f32db8.PNG)

**Comment by domlysz** [comment]
check the transparency tab instead
![image](https://user-images.githubusercontent.com/5639024/68530297-60afa680-0307-11ea-9c6d-61f85815c937.png)

uncheck the checkbox and then assign a color to nodata to see regions concerned

![image](https://user-images.githubusercontent.com/5639024/68530379-fb0fea00-0307-11ea-8113-b8a8b87abf56.png)

**Comment by GiulioDonatiSarti** [comment]
Thanks for spend time to answer me! 

Yes, I have the border with NoData Value. I'll fix it and I'll let you know how is the result!

Giulio

**Comment by GiulioDonatiSarti** [comment]
As you said the presence of NoData value was the problem.

Many thanks,
Giulio
