### ISSUE TITLE
GPU rendering issue v2.80

### ISSUE THREAD

**Issue by czarmanu** [domlysz/BlenderGIS#217]
This was the code i used in v2.79 (which worked without issues) to select GPU rendering via command line:

print("Default rendering mode : ", bpy.context.scene.cycles.device)
bpy.context.scene.cycles.device = 'GPU'
print("Rendering mode is now set to : ", bpy.context.scene.cycles.device)
bpy.context.user_preferences.addons['cycles'].user_preferences.compute_device_type = 'CUDA'
print("Compute device type is now set to : ", bpy.context.user_preferences.addons['cycles'].user_preferences.compute_device_type)
for card in bpy.context.user_preferences.addons['cycles'].user_preferences.devices:
    print("Available computing device:",card.name)

and it succesfully rendered using the available GPU

However, when I used the same code (with 'user_preferences' changed to 'preferences', as the following) with v2.80 it renders using CPU only. It completely skips the for loop and the corresponding print command

v2.80 version of the code:
print("Default rendering mode : ", bpy.context.scene.cycles.device)
bpy.context.scene.cycles.device = 'GPU'
print("Rendering mode is now set to : ", bpy.context.scene.cycles.device)
bpy.context.preferences.addons['cycles'].preferences.compute_device_type = 'CUDA'
print("Compute device type is now set to : ", bpy.context.preferences.addons['cycles'].preferences.compute_device_type)
for card in bpy.context.preferences.addons['cycles'].preferences.devices:
    print("Available computing device:",card.name)

Could you suggest a solution?

**Comment by domlysz** [comment]
This question is not related to blenderGIS addon, please ask on blenderartists.org or blender.stakexhange boards

**Comment by czarmanu** [comment]
https://blender.stackexchange.com/questions/149655/blender-on-google-colab-not-finding-graphics-card/150108#150108

FYI.. The above link solved it
