### ISSUE TITLE
[MAC] Empty menu

### ISSUE THREAD

**Issue by e5k** [domlysz/BlenderGIS#219]
Hi,

Probably doing something wrong but wondering if anyone else has had the same issue. I installed following instructions but I get an empty menu (see attached). Mac OS 10.14, both 2.8 and 2.8.1.

Thanks!

 
<img width="414" alt="Screenshot 2019-11-12 at 1 32 10 PM" src="https://user-images.githubusercontent.com/16320236/68645227-5c2afe00-0552-11ea-98b0-2ce3cd6ba2ed.png">

**Comment by domlysz** [comment]
how do you enable the addon ??? there is no new workspace expected but a new menu in the 3view

![image](https://user-images.githubusercontent.com/5639024/68649486-23bffb80-0523-11ea-97a4-c8b43abf68fe.png)

**Comment by e5k** [comment]
It's my bad, I was totally out of my element! Thanks for the answer @domlysz !
