### ISSUE TITLE
gdal and basemap make blender crash on windows 7 x64

### ISSUE THREAD

**Issue by mirlip** [domlysz/BlenderGIS#22]
With latest buildbot and Gdal installed as you say in the docs (really good quality doc, I hope more plugins devs would document their addon like you). But I get following error and crash: http://www.pasteall.org/69995
I took gdal 2.0.2 and had to update numpy to 1.10.4, just like in your doc also. Note that the crash also happened before updating Numpy, so it's not due to Numpy I guess.
The tests `from gdal import ...` all work correctly in the python console without error.

**Comment by mirlip** [comment]
It says the CRS is wrong, but It works in QGIS and it's the officially recommended one for the region I work in.

**Comment by domlysz** [comment]
It's not a problem from GDAL install, how do you submit this CRS, in what form ?

**Comment by mirlip** [comment]
I have given the code in the user pref/addon options:
short name: Google
description: Google
EPSG code: 3857

For the basemap, it crash whenever I use the defaults or specify this custom "google" CRS. Before I installed GDAL, it didn't crash because it didn't do any projection I guess.

**Comment by domlysz** [comment]
3857 is the code for Web Mercator projection, the one used by Google, OSM ... So unless you define a custom source in another CRS, you can let "Same as tile matrix" option, it will use this projection.

If gdal is not installed, the addon have it's own function to transform coords from 3857 to latlon and vice versa. But as soon as gdal is working it'll take this task. So you're right it's a problem with  GDAL install. 

I don't see this a first time:
`ERROR 4: Unable to open EPSG support file gcs.csv.`

Seems it can't found gdal-data folder. If you following the wiki for install GDAL, the folder must be in `blender_install_folder\2.7x\python\lib/python3.x/site-packages/osgeo`, can you check this ?

**Comment by mirlip** [comment]
In my case, after following the wiki steps (installing pip, downloading the .whl and installing it with your command) gcs.csv is in 2.77\python\lib\site-packages\osgeo\data\gdal
The installation worked as the `from gdal import ...` commands are working. But path is different from yours somehow.

**Comment by domlysz** [comment]
Sorry for the mistake, I wrote this path as I remember it (currently I don't have any Windows computer to check it ).

So if the file is here and GDAL cannot found it, try to set GDAL_DATA environement variable

See [here](http://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows) for an example, but use the path  `2.77\python\lib\site-packages\osgeo\data\gdal`

**Comment by mirlip** [comment]
yep, setting GDAL_DATA works :) I had it pointing to the osgeo directory on C and somehow it didn't work. 
As I have Osgeo with Qgis and gdal installed on C, would it be possible to use those with Blender? It would avoid duplicates and would allow to not change the GDAL_DATA variable every time I switch from Blender to QGIS.

**Comment by domlysz** [comment]
more or less, it can be very tricky.

For example you can try to just copy paste python osgeo folder from OSGeo4W install tree to blender install tree (if the version of Python match, not sure Python 3 is delivered with OSGeo4W because QGIS run Python 2.7), but even with the same Python version you can raise some incompatibility because regular installation of this module need some compilation.

Same, if you set GDAL path in environment variable, you must ensure that GDAL version match the one used to compile the Python binding.

Installing GDAL for Blender is really a pain

**Comment by mirlip** [comment]
It's sad we can't make it portable with this path that has to be set. I use to take Blender on a stick/dropbox with me. And I can't use it at work because we don't have admin privilege. If you find a way to make it work without environment variables, please let us know :) Your help is really appreciated.
