### ISSUE TITLE
Error message when enabling Add-on - Blender 2.81

### ISSUE THREAD

**Issue by Copperplate** [domlysz/BlenderGIS#223]
Hello, I just discovered this add-on and it looks very useful. I wasn't able to activate it in Blender 2.81 though. Is it not configured to use with Blender 2.81? [Here is a link to the error message](https://drive.google.com/open?id=1eMTIK1O9bI-lYWPgrRu9SYDjFDaf_GnP). I believe the first error message was different (something about 3D view) but I haven't been able to regenerate that error.

Thanks so much for your time.

**Comment by domlysz** [comment]
can you please download again the addon and retry, it must be fixed now

**Comment by Copperplate** [comment]
Hi, thank you for your reply. I just re-downloaded and tried again. This time it gave the 1st error message upon activating it in Blender's preferences. [Please see screenshot.](https://drive.google.com/open?id=1wT9um_q8RY7TYKUT5xKVxYuxOxquCw5G) Thank you again.

**Comment by Copperplate** [comment]
Hi I got it to work. For some reason, the add-on was not allowing me to activate while my custom keymap was active. I switched back to the default keymap and then it worked. Thanks!

**Comment by domlysz** [comment]
interesting, i've updated the code to bypass this step if the  _3d view_ keymap does not exist

**Comment by Copperplate** [comment]
Thank you! Great add-on by the way. On a side note, have you researched about the legality of using the SRTM topographic data the add-on accesses? Is it free from legal issues? I haven't tried it yet, so I don't know if it actually creates textured terrain (as shown in your GIF example) or if it's just the heightmap, but as far as I know, Google doesn't permit using its images to create 3D models, which is really unfortunate for artists (but understandable)... :-(

**Comment by domlysz** [comment]
Only commercial, non-free resale, or redistribution are prohibited for srtm data. Attribution is mandatory, derived products or services are allowed. This addon use opentopograhy web service : https://www.opentopography.org/developers

**Comment by Copperplate** [comment]
Ah, okay, thank you for the info. :-)
