### ISSUE TITLE
Enable error on Mac

### ISSUE THREAD

**Issue by Jacqueskct** [domlysz/BlenderGIS#224]
Hi Traceback error on mac - what should i do?

<img width="912" alt="Screenshot 2019-12-04 at 09 53 17" src="https://user-images.githubusercontent.com/58505588/70124026-8e74da80-167c-11ea-9ea2-dd6b197b23bc.png">

**Comment by domlysz** [comment]
duplicate #182 #183 #191 #195 #213

please search closed issues before open a new one

**Comment by Jacqueskct** [comment]
How is it a duplicate if the problem was fixed in Blender previous versions? This is from 2.81. This must now be a local issue?

**Comment by domlysz** [comment]
No it's the same issue from Blender itself: missing sqlite lib witch is a standard Python lib. It's easy to isolate the problem : open Blender's python console and write `import sqlite3`, this statement will raise an error
That's strange that this issue remain for you with 2.81 as for most of mac users fixed it by uptading to 2.81.
Please report again in Blender bug tracker
https://developer.blender.org/T68243

**Comment by Redo-From-Start** [comment]
I'm also having this issue

**Comment by juergenfurrer** [comment]
I found a solution, see the answer here:
https://developer.blender.org/T68243#867904
Happy hacking ;)

**Comment by Redo-From-Start** [comment]
this issue still happens in 2.82

**Comment by zhaiduo** [comment]
2.83alpha is work now.

**Comment by Redo-From-Start** [comment]
> 2.83alpha is work now.

how do you get alpha versions?

**Comment by ahurig** [comment]
Hey guys, I used this exact method to resolve the problem (coming from the blender bug tracker, not my idea):

sudo mkdir -p /Users/azo/Code/blender/blender_build/build-libs/Release/sqlite/lib/
sudo chmod -R 777 /Users/azo/
cd /Users/azo/Code/blender/blender_build/build-libs/Release/sqlite/lib/
ln -s /usr/lib/libsqlite3.0.dylib libsqlite3.0.dylib


What it does is that it creates a shortcut to the dylib in the folder that is requested by blender. Seems that the guys forget to make it relative. 
Hope it will help. (@domlysz sorry for the duplicate)

**Comment by domlysz** [comment]
will be solved with 2.83
