### ISSUE TITLE
Feature Request - Define Extraction Area

### ISSUE THREAD

**Issue by tcheng00** [domlysz/BlenderGIS#226]
Hi, I would like to request that we are able to define exact extraction area by using coordinates or drawing a rectangle.  This can help with tiling. Thank you.

**Comment by domlysz** [comment]
Please be more precise, what is the functionality of the addon you are talking about ?

**Comment by tcheng00** [comment]
I like to type in the Coordinate  in degrees to get a specific area.  For example. I want Shanghai China with these coordinates. Image attached below. 

![Capture](https://user-images.githubusercontent.com/5704055/71102044-c05e6480-2185-11ea-8d10-21aff9ad3078.JPG)

**Comment by domlysz** [comment]
did you read the quick start guide ????
https://github.com/domlysz/BlenderGIS/wiki/Quick-start

Typical workflow is to start basemaps and search for the area of interested. Then your 3dview will be georeferenced and you will be able to grab OSM or SRTM data (if this is the data you are referring to) for your area, no need to write coordinates yourself

**Comment by tcheng00** [comment]
Yes, but it doesn't give me precision. I like to manually write in the exact points that needs to be extracted.  Right now, it captures based on my Blender viewport shape.

**Comment by domlysz** [comment]
you can define yourself the longitude and latitude of the scene's origin
![image](https://user-images.githubusercontent.com/5639024/71103965-58c30c00-21bb-11ea-9617-7176dc446844.png)

Then create a new plane mesh with the desired dimensions (and apply scale if needed). Get OSM and get SRTM tools set the requested extent from the active selected object or from the 3d view if there is no object selected. So just select your mesh beforehand to define the request extent .

**Comment by tcheng00** [comment]
Ok, great I'll give that a shot.  Thanks.
