### ISSUE TITLE
Feature Request - Ability to Tile Multiple Extracted Areas

### ISSUE THREAD

**Issue by tcheng00** [domlysz/BlenderGIS#227]
Hi, I would like the ability to tiled mulitple define areas for high resolution texture extraction and to created a larger geometry set without getting the "too many request error".  Thanks.

**Comment by domlysz** [comment]
Idem please be more precise, I can't understand what do you talking about, is it about OSM importer, basemaps or maybe DEM import ????

**Comment by tcheng00** [comment]
Sorry, I try to be clearer.  I would to use Web GeoData - Get BaseMap, Get OSM, and Get SRTM. With the ability to get multiple areas and put the area next to each other.  Here is a example below.

![Capture_Tiled](https://user-images.githubusercontent.com/5704055/71102877-2b5c6b00-2187-11ea-821b-dba9dfe4c752.jpg)

**Comment by domlysz** [comment]
for basemaps, if you need a large extent with high resolution use the L key to lock the zoom, then when zooming with your mouse wheel the extent area will be maintained as it but the addon will download tiles from highest zoom level increasing the map resolution.

OSM and SRTM requests are limited to a maximum extent in respect to their respective web service policy. If you need largest data then you need to download raw data from a more suitable provider like NASA FTP for SRTM data or geofabrick for OSM data.

be aware creating a tiled terrain in Blender is very tricky
https://github.com/domlysz/BlenderGIS/issues/172

**Comment by tcheng00** [comment]
Great man, thanks for this infomation.  It's very helpful.  I plan to use your great tool to extract a few sets and move it to another program by Collada (support curves/splines) to compile a bigger scene.
