### ISSUE TITLE
import shape not selectable

### ISSUE THREAD

**Issue by bluelemonade** [domlysz/BlenderGIS#229]
hello, I tried to import shape file, but I dind't see the option in the File > Import > Plugin is active.
on blender 2.81a windows 64bit

regard

**Comment by domlysz** [comment]
All tools are available in a dedicated GIS menu
https://raw.githubusercontent.com/wiki/domlysz/blenderGIS/Blender28x/images/bgis_menu.jpg

**Comment by bluelemonade** [comment]
hmm, where is this menu on windows?

**Comment by domlysz** [comment]
![image](https://user-images.githubusercontent.com/5639024/71241143-2a544680-230b-11ea-9ef9-cf93098f9698.png)

**Comment by bluelemonade** [comment]
oh, yes there it is. thanks.
