### ISSUE TITLE
Place the Georef Cam higher

### ISSUE THREAD

**Issue by turban** [domlysz/BlenderGIS#23]
Sometimes I get black holes when I render the image: 

![screen shot 2016-05-30 at 21 25 32](https://cloud.githubusercontent.com/assets/548708/15657005/4ae2b4bc-26ad-11e6-84a2-0f0922e70383.png)

This happens when there is a single peak that is higher than surrounding terrain. Is it possible to have the camera higher by default, so it's above all parts of the DEM?

**Comment by domlysz** [comment]
Thanks, fixed it in latest update. Please give it a try to confirm it's correct now

**Comment by turban** [comment]
The black hole is slightly smaller, but it is still present with the latest version: 

![blenderbug](https://cloud.githubusercontent.com/assets/548708/16171902/5679c0f4-357b-11e6-8ab6-8c73509b1d15.png)

**Comment by domlysz** [comment]
That strange the camera is placed 10 meters above the highest point of the mesh...

Maybee the subdivision level for the render is higher than the one for the 3view and there is no enough points around the pic to correctly estimate the maximum elevation of the rendering mesh.

I'will try to find a cleanest way to set the camera offset (I want avoid just setting an arbitrary value).

**Comment by kikislater** [comment]
I think it just a blender basic tip. Under Camera > Lens, Set clipping start = 0

**Comment by turban** [comment]
The clipping start is already 0 (or 0.001 to be exactly - if I try to change it to 0, Blender will change it back to 0.001):

![screen shot 2016-06-19 at 12 56 42](https://cloud.githubusercontent.com/assets/548708/16176922/7d53ccf4-361d-11e6-96e0-a6d5d907fc84.png)

**Comment by turban** [comment]
The clipping end value is 951.700 in Blender, but in my GeoTIFF it is 961.400 (retrieved with gdalinfo).

**Comment by kikislater** [comment]
Could you give us the blend or part of the blend ?

**Comment by turban** [comment]
This zip contains the GeoTIFF, the blend-file and the rendered image with the small black hole:
https://dl.dropboxusercontent.com/u/2306934/MasterMaps/tile_13_09.zip

**Comment by kikislater** [comment]
Camera is very close to terrain in this part.
Modifiers : subdivision surface is set to 11, if you apply modifier or set to 9 black artefact disappear.

Place camera a little bit higher do the trick

**Comment by turban** [comment]
Seems to be the same issue as here: https://wanderingcartographer.wordpress.com/2014/11/14/shaded-relief-with-blendergis-part-2/

**Comment by domlysz** [comment]
So the problem come well from subdivision. Actually the script compute the mesh bounding box and place the camera 10 meters higher, but if the view subdivision is lower than render subdivision then in some case the computing bounding box will not reflect the final bounding box because view subdivision don't provides enough points to get a displacement in "full resolution"

In your blend file, higher point of the mesh is under the camera
![selection_020](https://cloud.githubusercontent.com/assets/5639024/16177340/d6b33fd0-3629-11e6-88b6-109dfc954cbf.jpg)
![selection_021](https://cloud.githubusercontent.com/assets/5639024/16177372/f4fe583e-362a-11e6-812b-cf9d4dbc4643.jpg)

But if I set view subdivision to 11 then the mesh is above the camera

![selection_022](https://cloud.githubusercontent.com/assets/5639024/16177377/1657851e-362b-11e6-9427-8a87fe8f76b8.jpg)

**Comment by turban** [comment]
What about adding a camera height of 100 m rather than 10?

**Comment by domlysz** [comment]
yes but it's not a clean and general way to solve the problem, the difference between view bounding box and render bounding box can be of any value, most of the time it will be few meters or decade of meters but potentially it can be lot of more.

However, I'm afraid that it's not possible to estimate the resulting bounding box without increase the view subdivision value (witch involve lot of ram). So, I think I will add an option to edit the offset when the user create the camera. Also, expressed this value as percentage of z dimensions will be probably better than raw meters.

**Comment by turban** [comment]
Sounds like a good plan :-)

**Comment by domlysz** [comment]
fixed 9bfbcb8f5637882ba9bb180aa462f0730373ad25

**Comment by turban** [comment]
Hi @domlysz, thanks for the fix - did you add an offset value and where can I edit it?

**Comment by turban** [comment]
Hi @domlysz, thanks for the fix - did you add an offset value and where can I edit it?

**Comment by domlysz** [comment]
You're right, I forgot to add a property for editing the value

Thanks

**Comment by domlysz** [comment]
Finally fixed this one !
49130af
