### ISSUE TITLE
QGIS GeoTiff and SHP Import Scale Problem

### ISSUE THREAD

**Issue by mj-saunders** [domlysz/BlenderGIS#230]
I have read through other issues and found similar but not quite the same problem.
No solutions as yet though.

Using QGIS to create geotiff dem and shapefile contours.
Both are suffering from the same issue, which makes me think it's a projection problem.

Using WGS84 EPSG:4326 in QGIS and same in Blender.

The heights are correctly positioned in meters.

However, x and y coords are stored in degrees in QGIS (as far as I can tell)
And when BlenderGIS does its' georeferencing, it aligns the worlds correctly, but uses the coordinates in degrees as though they were meters.

As such my x/y scale is tiny.

![scale-problem](https://user-images.githubusercontent.com/34356259/71623927-19ec7780-2bf9-11ea-908f-260cdc88bd8a.png)

**Comment by domlysz** [comment]
https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-after-the-import-of-my-data-the-resulting-mesh-is-extremely-small-on-x-and-y-axis-but-seems-correct-on-z-axis-

**Comment by mj-saunders** [comment]
@domlysz Thanks. How did I not notice that in the FAQ...oops

I had previously tried with WGS84 UTM Southern Hemisphere, to no avail.
Not sure why it didn't work. But tried again with more localised datum and all is mostly well.
Any idea why the above didn't work?

The GeoTiff loads fine now.
Still having some trouble with SHP. Seems to load in different location.
Will dig deeper.

Thank you again, much appreciated.

**Comment by mj-saunders** [comment]
Ok. All good now. In the Shapefile, some of the contours went beyond the bounds of the GeoTiff, and looks like it re-centred the world.

When I import the GeoTiff after the SHP, all seems to be behaving nicely.
