### ISSUE TITLE
Blender 2.78c add-ons invalid syntax error

### ISSUE THREAD

**Issue by taniavs90** [domlysz/BlenderGIS#231]
Hi
I am working with version Blender 2.78c for windows 64, I am trying to activate blenderGIS but I get a syntax error.
Could someone help me solve the problem?
Thanks

![invalid syntax](https://user-images.githubusercontent.com/59429879/71652978-7d58d100-2cef-11ea-9bf6-ce4f3207fa3d.png)

**Comment by domlysz** [comment]
Use the old branch

![image](https://user-images.githubusercontent.com/5639024/71658919-e8cd8d80-2d45-11ea-913d-ea7d6f8115c0.png)

**Comment by taniavs90** [comment]
Thanks that solved it

**Comment by Aminshadow** [comment]
hi domlysz . I am working with version Blender 2.78c for windows 64, I am trying to activate blenderGIS but I get a syntax error.
 im try the old branch and not allow to adds on the gis blendedr 279

[](url)
![photo_2021-11-10_18-21-30](https://user-images.githubusercontent.com/47476479/141134630-c5826187-ef13-438f-9ef2-88fb4ca0a7e2.jpg)

**Comment by domlysz** [comment]
Hi, the addon requires at least Blender 2.83 (v2.79 is very outdated now)

**Comment by Aminshadow** [comment]
thanks domlysz . i installed the v2.83 and adds on the last gis blender  on your accaoun tin github . but this message shown after command the web geo data . plz guide me

![image](https://user-images.githubusercontent.com/47476479/141209843-9522a7bb-2a5f-4e28-96f0-b878a5aa5a6e.png)
