### ISSUE TITLE
Can't enable BlenderGIS addon

### ISSUE THREAD

**Issue by Dirma** [domlysz/BlenderGIS#232]
Hi!

I'm quite new to Blender (and to the Blender addons), so sorry for this probably very simply to solve question: I downloaded the zip file from github and installed it in the addons, but when I wanted to enable it, I got the following error message (see attachment). I tried everything, does anyone know what I'm doing wrong here?

Dirma

<img width="653" alt="Screenshot 2020-01-06 at 12 18 05" src="https://user-images.githubusercontent.com/4143829/71815282-4122c900-307f-11ea-8394-7926cd7dda84.png">

**Comment by domlysz** [comment]
duplicate #182 #183 #191 #195 #213 #224 

Please update to blender 2.81

**Comment by c-vradis** [comment]
Hi, I got the same error with Blender Version 2.81a (2.81a 2019-12-04) on macOS (mojave 10.14.6) screenshot included.

Chris
<img width="1392" alt="Screenshot 2020-01-06, 18 55 19" src="https://user-images.githubusercontent.com/45768179/71833810-70086180-30b6-11ea-8e2b-e454f9db5bc0.png">

**Comment by Dirma** [comment]
Thanks, it's fixed!:) 
I downloaded the latest Blender version: https://builder.blender.org/download/, after that it was working.
