### ISSUE TITLE
Import shapefile line

### ISSUE THREAD

**Issue by GiulioDonatiSarti** [domlysz/BlenderGIS#233]
Hi there, 
I would like to import a shapefile line in Blender with BlenderGIS add-on and represent it on my project. When I import it the line shows in the project (as you can see below), but in the render it's not visible at all.
![1](https://user-images.githubusercontent.com/57560074/72220405-a7f92400-3550-11ea-9ab0-d2d179a5f257.PNG)

Dou you have some ideas to solve it?

Thanks in advance,
Giulio

**Comment by domlysz** [comment]
There is no issue here, the addon works as expected here : importing a shp of lines. 

For edge rendering look at Freestyle non-photorealistic engine.
https://docs.blender.org/manual/en/latest/render/freestyle/introduction.html

If you want a mesh of faces, you can try to perform a Delaunay triangulation from your lines vertices.
https://github.com/domlysz/BlenderGIS/wiki/Make-terrain-mesh-with-Delaunay-triangulation
