### ISSUE TITLE
Size Reality

### ISSUE THREAD

**Issue by jdarras** [domlysz/BlenderGIS#236]
Hello,
I model my apartment in blender and when I want to superimpose an import shp from osm, the size between my modeling and the imported elements diverges by around 40% as you can see on the attached image. I measured my apartment and my modeling is good. How to configure map projections to be well placed and at the right size?

Thanks for your help.
Julien

![size osm](https://user-images.githubusercontent.com/35170258/72680393-961c0180-3ab9-11ea-95fc-821e9973c9d9.PNG)

**Comment by domlysz** [comment]
OSM import use Web Mercator projection which is not suitable for precision modelling.
https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-my-measurements-on-basemaps-reference-seems-wrong-

Use French Lambert 93 projection instead.

**Comment by jdarras** [comment]
Merci beaucoup pour l'info, en effet c'est parfaitement ajusté.
