### ISSUE TITLE
Import attributes of shapefile and keep them at the object

### ISSUE THREAD

**Issue by mholthausen** [domlysz/BlenderGIS#238]
Is it possible with the current BlenderGIS for Blender 2.81 to import shapefiles with its geometry and assigned attributes from the attribute table and keep them in Blender?

**Comment by domlysz** [comment]
yes just check the s_eparate objects_ option, then attributes data will be assigned as custom properties of the object.

**Comment by mholthausen** [comment]
That sounds good. However, for geological layers consisting of several hundreds of million triangles each with several attributes, this approach seems to be very time-consuming.

**Comment by ChameleonScales** [comment]
@domlyz That's awesome!
In the case of @mholthausen , a solution could be to store the attributes as bmesh data layers, which can be assigned per vertex, edge or face.
https://blender.stackexchange.com/questions/7094/python-assign-custom-tag-to-vertices?answertab=active#tab-top

These layers can be of any type such as integer, float, string and more:

https://docs.blender.org/api/2.82/bmesh.types.html?highlight=layers%20string#custom-data-layer-access

I'm personally satisfied with the "separate objects" option but I can imagine it become a performance problem when you have a large number of elements, so I'm just throwing the idea out there.
