### ISSUE TITLE
Off by half pixel when importing geo-referenced raster images

### ISSUE THREAD

**Issue by thmxv** [domlysz/BlenderGIS#24]
Hi,

Thanks for developing this add-on, it helped me a lot.

The issue is I think related that the export code of QGIS (and maybe other programs) specifies the world coordinates for the center of the corner pixels, not the corners of the image. It is particularly visible when importing images that should tile perfectly (and do tile perfectly when importing in QGIS), when importing them in Blender there is a small gap between each tile image.

**Comment by domlysz** [comment]
Hi, 

Thanks reporting this issue. Can you try the lastest version https://github.com/domlysz/BlenderGIS/commit/608dd69cf06e0d481f423698194c4a9207b98fad not sure if it will fix the problem.

**Comment by domlysz** [comment]
Need more infos here: is it a geotiff ? with a worldfile ? can you join a test file ?

It seems the geotiff can define the top left coords as pixel corner or pixel center; see [standard](http://www.remotesensing.org/geotiff/spec/geotiff2.5.html). But for now the addon consider it as corner only.

**Comment by thmxv** [comment]
Hi,

Sorry for the delay, my motherboard burned because of a power surge :(

I tested with latest git version and there is still a gap of about 1 pixel. The files are TIF or PNG but not geo-referenced, they have corresponding world files. 

I attached a few test files.

**Comment by thmxv** [comment]
The files went missing from previous message:
[batch_google_sat.zip](https://github.com/domlysz/BlenderGIS/files/301103/batch_google_sat.zip)

**Comment by domlysz** [comment]
Thanks, what is the coordinate system for these files ?

**Comment by domlysz** [comment]
ok found the problem now it's fixed

https://github.com/domlysz/BlenderGIS/commit/67312c074e1ef9d7a0cc2ed0f600391d1f4f3ae5#diff-31ad8cd2ce33c360db73ef9a5340aeca

**Comment by thmxv** [comment]
Hi,

CRS is EPSG:32632 (WGS84 / UTM Zone 32N) and I can confirmed the issue is now fixed.

Thank you very much

**Comment by domlysz** [comment]
Great !
