### ISSUE TITLE
Usage instructions for 2.8 interface

### ISSUE THREAD

**Issue by ethicalfive** [domlysz/BlenderGIS#240]
How do I find these tools in the 2.8 interface? If you've updated to 2.8, why haven't the instructions been updated to match?

**Comment by domlysz** [comment]
https://github.com/domlysz/BlenderGIS/wiki/Install-and-usage

**Comment by ethicalfive** [comment]
Thanks, I found it now. I think the issue still remains on the main page that the instructions are now outdated to the new version. Many of the features I still had to find by context menu.

**Comment by domlysz** [comment]
I aware of it, contributions are welcome as uptading the wiki is very time-consuming.

**Comment by samuel905** [comment]
Hi, how can add luxcore addons in my blender 2.8
