### ISSUE TITLE
cannot convert float NaN to integer

### ISSUE THREAD

**Issue by TJRL** [domlysz/BlenderGIS#241]
I reinstalled BlenderGIS with Blender 2.81, and now I'm getting this when trying to load a basemap (which doesnt load as a result):
![image](https://user-images.githubusercontent.com/22885764/73660311-3bc59800-4698-11ea-91fa-d747f2aa14a7.png)

**Comment by domlysz** [comment]
must be solved with lasted master version

https://github.com/domlysz/BlenderGIS/issues/228

**Comment by TJRL** [comment]
Great. Thanks!
