### ISSUE TITLE
installing GDAL on win10

### ISSUE THREAD

**Issue by lalberts** [domlysz/BlenderGIS#242]
Hello,
I have troubles installing GDAL..
the osgeo folder is going to
C:\Users\alberts\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\osgeo\data\gdal
instead of  C:\Program Files\Blender Foundation\Blender 2.81\2.81\ or C:\Users\alberts\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons

setting the env.variable to the first brings no success.
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
ImportError: cannot import name 'gdal' from 'osgeo' (unknown location)

has it to do with the pip tool, which installs overthere and not into the main blender install folder?
also numpy.-.whl went there.
how to change this behaviour of pip?
Thanks 
Lukas

**Comment by domlysz** [comment]
As [explained in the wiki](https://github.com/domlysz/BlenderGIS/wiki/How-to-install-GDAL#windows) you must execute pip with the python executable bundle with Blender.

`blender_install_folder\2.7x\python\bin\python.exe -m pip install gdal.whl`
