### ISSUE TITLE
Enable Blender GIS on Mac not working

### ISSUE THREAD

**Issue by highkoji** [domlysz/BlenderGIS#243]
Hi,

I've read all the previous relative issues on enabling blender GIS on Mac.
I have the most up-to-date version which is 2.81a but I'm still unable to install GIS addon.
I have tried 2.81a, 2.82, and 2.83 and nothing worked.
This is the error message I got.
![image](https://user-images.githubusercontent.com/60722250/73899416-91e23900-485a-11ea-9629-1cfa416e0428.png)

This is GIS requires 2.8x to install GIS.
![image](https://user-images.githubusercontent.com/60722250/73899437-a4f50900-485a-11ea-9d26-c9e90057ecfc.png)

This shows which version I have.
![image](https://user-images.githubusercontent.com/60722250/73899503-df5ea600-485a-11ea-996b-eb0b177b507b.png)

Any ideas I can fix this problem?

Thank you.

**Comment by hub3iii** [comment]
Me to. 
Same error, MAC, os 10.14.6, tested 2,80 and 2.81a

**Comment by domlysz** [comment]
Duplicate #224

**Comment by Avikingman** [comment]
Doesn't work. Please fix it. I am using latest Mac osx Catalina 10.15.3. I just dl BlenderGIS_master.zip. Installs ok, but clicking the little box throws the error we all seem to be getting.
Thank you.
Alan

**Comment by domlysz** [comment]
please read the duplicates reports #224 and others. I can't fix it, it's linked to Blender Mac build itself : https://developer.blender.org/T68243
