### ISSUE TITLE
Error on Import of OSM with GDAL Installed

### ISSUE THREAD

**Issue by Flimsy-Fox** [domlysz/BlenderGIS#245]
I have no problems downloading map data, exporting to planes, and (presumably) downloading OSM data, such as building and highway paths. No errors at all occur when GDAL is not installed. However, when GDAL is installed, using any tile matrix viewing method, this error occurs when downloading OSM data:
`File "C:\Users\flims\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\io_import_osm.py", line 666, in execute
    result = api.query(query)
  File "C:\Users\flims\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\lib\osm\overpy\__init__.py", line 111, in query
    msgs=msgs
BlenderGIS-master.operators.lib.osm.overpy.exception.OverpassBadRequest: Error: line 1: static error: Latitudes in bounding boxes must be between -90.0 and 90.0.`

I assume that data is downloaded just fine because it pauses, as if downloading, and then gives the error, which seems to be unrelated to the completion of the OSM data download. I'm using Blender 2.81, on Windows 10 64-bit. The file versions of the required files for GDAL, as described by the wiki on installing it, are: 

> GDAL-3.0.4-cp37-cp37m-win_amd64.whl
> numpy-1.18.1+mkl-cp37-cp37m-win_amd64.whl

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/commit/b6861910e5ca567c76785c0cb614fda0dbd40bea
