### ISSUE TITLE
OSM query http 451 error

### ISSUE THREAD

**Issue by Kohtla** [domlysz/BlenderGIS#249]
Traceback (most recent call last):
  File "C:\Users\Kohtla\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\io_import_osm.py", line 666, in execute
    result = api.query(query)
  File "C:\Users\Kohtla\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\lib\osm\overpy\__init__.py", line 120, in query
    raise exception.OverpassUnknownHTTPStatusCode(f.code)
BlenderGIS-master.operators.lib.osm.overpy.exception.OverpassUnknownHTTPStatusCode: Unknown/Unhandled status code: 451

location: <unknown location>:-1

System: Win10
How to repeat:
1) On the new fresh Blender 2.81 pick GIS
2) Web Geodata
3) Get SRTM (works fine)
4) Get OSM (error occures)

**Comment by domlysz** [comment]
https://en.wikipedia.org/wiki/HTTP_451

**Comment by Flimsy-Fox** [comment]
> 
> 
> https://en.wikipedia.org/wiki/HTTP_451

Well don't know what to tell ya, seems like OSM is illegal in your country.

**Comment by natadali** [comment]
Hi, I have same problem, and I'm from Russia, just wondering do I have any chance to avoid this like-vpn-solve-it-way?

**Comment by domlysz** [comment]
I've pushed a new update that now force the user agent when querying for osm data. Not sure if it will solve the issue, but give it a try

**Comment by natadali** [comment]
> I've pushed a new update that now force the user agent when querying for osm data. Not sure if it will solve the issue, but give it a try

The problem is government blocking osm server for a some reason, lets imagine they know why, but mirror https://overpass.openstreetmap.fr/api/interpreter - working quite good. I just replaced line - self.url..... in the file __init__.py

**Comment by ATNeo** [comment]
> > I've pushed a new update that now force the user agent when querying for osm data. Not sure if it will solve the issue, but give it a try
> 
> The problem is government blocking osm server for a some reason, lets imagine they know why, but mirror https://overpass.openstreetmap.fr/api/interpreter - working quite good. I just replaced line - self.url..... in the file **init**.py

please tell more info on how to add a mirror to init.

i cant find the self.url line

**Comment by ATNeo** [comment]
> > I've pushed a new update that now force the user agent when querying for osm data. Not sure if it will solve the issue, but give it a try
> 
> The problem is government blocking osm server for a some reason, lets imagine they know why, but mirror https://overpass.openstreetmap.fr/api/interpreter - working quite good. I just replaced line - self.url..... in the file **init**.py

Didn’t work

**Comment by ATNeo** [comment]
I’ve figured out:
C:\Users\Kohtla\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlenderGIS-master\operators\lib\osm\overpy_init_.py
The ini file here. I set the url and everything works!

**Comment by domlysz** [comment]
I've added a new parameter in the addon options to setup the overpass server url
![image](https://user-images.githubusercontent.com/5639024/74681991-1458ea00-51c5-11ea-97bd-02d3074038ee.png)
