### ISSUE TITLE
Cant install gdal

### ISSUE THREAD

**Issue by daniloulf** [domlysz/BlenderGIS#250]
![2020-02-09 15_38_05-Window](https://user-images.githubusercontent.com/46490254/74104237-e7685f80-4b52-11ea-8bc7-20f97feb02b9.png)

There is no osgeo drawer in my blender python folder. Whats going wrong?

**Comment by lalberts** [comment]
https://blender.stackexchange.com/questions/139718/install-pip-and-packages-from-within-blender-os-independently

**Comment by daniloulf** [comment]
I could solve my trouble I set up only a new cache folder in the Plugin setup, and the issue doest appears anymore.
