### ISSUE TITLE
Are those white clouds supposed to be there on the terrain?

### ISSUE THREAD

**Issue by tgmueller** [domlysz/BlenderGIS#254]
Are there supposed to be the clouds on this 3d models brought in with blendergis.  I have the 3d model below and the original flat image.  There are a couple of clouds in the original but not like in the 3d model

![2020-02-09 23_32_52-](https://user-images.githubusercontent.com/9053330/74123510-abee8500-4b94-11ea-8280-036b0142ba6b.png)

![2020-02-09 23_35_30-waukee3 tif - Windows Photo Viewer](https://user-images.githubusercontent.com/9053330/74123581-ee17c680-4b94-11ea-8236-85d770d3fe39.png)

**Comment by domlysz** [comment]
not sure to understand the question, I see the same cloud in both image. Cloud level depends on the weather conditions at the date of the aerial photo, this has nothing to do with the addon.
