### ISSUE TITLE
enable error

### ISSUE THREAD

**Issue by hamza00555** [domlysz/BlenderGIS#255]
<img width="1288" alt="Screen Shot 2020-02-10 at 12 42 13 PM" src="https://user-images.githubusercontent.com/60875566/74138982-9f554580-4c03-11ea-83f2-6818c024c02f.png">

Can't install the plugin ... I'm using mac

**Comment by RonB** [comment]
+1

**Comment by domlysz** [comment]
duplicate #224 

Please read the warning at the home page !!!

> Mac users warning : currently the addon does not work anymore on Mac because of an issue relative to Blender Mac build itself. Please do not report the issue here. It should be fixed by the Blender team soon. Check the bug report to follow the progress on it.
