### ISSUE TITLE
Problem install complements os x 10.10 blender 

### ISSUE THREAD

**Issue by faustinotopia** [domlysz/BlenderGIS#26]
Hi, i'm new in this.
When i try install complements in blender i can't, and appear a message saying Traceback (Most recent call last):

File"/" applications/blender.app/contents/MacOs/2.71/scripts/addons/basemaps/_init_.py",line 45,in <module form.mapviewer import*>

and other similar messages, i don`t know, any help me please?.

 Operate System: Os X 10.10
Blender 2.7

Thanks!

**Comment by domlysz** [comment]
Hi

I think it's duplicate the issue https://github.com/domlysz/BlenderGIS/issues/18

For enable basemaps addon you must install [python pillow ](https://pypi.python.org/pypi/Pillow/3.2.0) 

Other addons works ?

**Comment by domlysz** [comment]
On Windows use the following commands to install Pillow:

 `blender_install_folder\2.7x\python\bin\python.exe -m ensurepip`

 `blender_install_folder\2.7x\python\bin\python.exe -m pip install pillow`
