### ISSUE TITLE
Texture Error when export from Basemap.

### ISSUE THREAD

**Issue by ammarofficial11** [domlysz/BlenderGIS#261]
![Screenshot (10)](https://user-images.githubusercontent.com/48865033/74587185-79c4a380-502a-11ea-8060-745cd8839996.png)
After I've located my area for export. This error pop-up and no texture shown on the mesh. I couldn't figure out why.

**Comment by domlysz** [comment]
can you try with a more recent version of Blender? seems you're using a dev. version of 2.80 branch that not include all Python api modification.

**Comment by ammarofficial11** [comment]
yes!. ive downloaded latest blender. Problem solved! Thank you master!
