### ISSUE TITLE
No imageIO module

### ISSUE THREAD

**Issue by nijiushi1** [domlysz/BlenderGIS#265]
No imaging library available. ImageIO module was not correctly installed.			Please reinstall it or try to install Python GDAL or Pillow module

this is my problem,when i start BlenderGIS
reinstall it 3 times
thank you

**Comment by enzyme69** [comment]
Try using Blender 2.83 alpha~

**Comment by domlysz** [comment]
@nijiushi1 please report logging informations. Start Blender through a system console and report back the messages printed.

**Comment by wushuanger** [comment]
i have the same problem. here is the log:

Modules Installed (BlenderGIS-master) from 'C:\\Users\\HP\\Desktop\\BlenderGIS-master.zip' into 'C:\\Users\\HP\\AppData\\Roaming\\Blender Foundation\\Blender\\2.81\\scripts\\addons'
bpy.data.window_managers["WinMan"].addon_search = "node"
bpy.ops.object.editmode_toggle()
No imaging library available. ImageIO module was not correctly installed.			Please reinstall it or try to install Python GDAL or Pillow module

thanks.

**Comment by domlysz** [comment]
Python logs as reported in the system console not Blender one, on Windows os you can open the console through the window menu of Blender, more specific information about the error will be reported here

**Comment by nijiushi1** [comment]
thanks
how can i find the log in windos os.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"domlysz"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月17日(星期一) 上午7:52
收件人:&nbsp;"domlysz/BlenderGIS"<BlenderGIS@noreply.github.com&gt;;
抄送:&nbsp;"周华"<nijiushi1@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [domlysz/BlenderGIS] No imageIO module (#265)




Python logs as reported in the system console not Blender one, on Windows os you can open the console through the window menu of Blender, more specific information about the error will be reported here

**Comment by nijiushi1** [comment]
Read prefs: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.82\config\userpref.blend
found bundled python: E:\blender-2.82-windows64\2.82\python
Imageio: 'freeimage-3.15.1-win64.dll' was not found on your computer; downloading it now.
Error while fetching file: <urlopen error [WinError 10054] 杩滅▼涓绘満寮鸿揩鍏抽棴浜嗕竴涓幇鏈夌殑杩炴帴銆?.

is this?@domlysz

**Comment by domlysz** [comment]
When the addon is enabled for the first time, it download an extra library named ImageIO. If the download fails then the basemap function will not be usable and will raise the 'Non ImageIO' error. There are many  reasons that can cause the download failure. In this case the download fails with the Windows Sockets Error Codes 10054 : Connection reset by peer.

_An existing connection was forcibly closed by the remote host. This normally results if the peer application on the remote host is suddenly stopped, the host is rebooted, the host or remote network interface is disabled, or the remote host uses a hard close. This error may also result if a connection was broken down (using a proxy or a firewall may be in cause here)_

So it's hard to determine precisely what's wrong here, but the binaries files needed by ImageIO are available here : https://github.com/imageio/imageio-binaries/tree/master/freeimage

So you can download the right version and paste the file into your_addons_folder/BlenderGIS/core/lib/imageio/resources

**Comment by nijiushi1** [comment]
i try it,but it's the same problem.

**Comment by nijiushi1** [comment]
#

**Comment by nijiushi1** [comment]
i try it,but it's the same problem.
thanks.

**Comment by nijiushi1** [comment]
![3](https://user-images.githubusercontent.com/61105631/74792362-32733700-52f8-11ea-9bfa-e22830765e52.png)
![4](https://user-images.githubusercontent.com/61105631/74792363-343cfa80-52f8-11ea-86d4-7b3f0d276f45.png)
![1](https://user-images.githubusercontent.com/61105631/74792364-343cfa80-52f8-11ea-8695-6754229d4a22.png)
![2](https://user-images.githubusercontent.com/61105631/74792367-356e2780-52f8-11ea-9aba-561c0740cd96.png)

**Comment by ReekyStive** [comment]
I have the same problem.
Here is the error:
```
No imaging library available. ImageIO module was not correctly installed.
Please reinstall it or try to install Python GDAL or Pillow module.
```
Thanks.

**Comment by ReekyStive** [comment]
> I have the same problem.
> Here is the error:
> 
> ```
> No imaging library available. ImageIO module was not correctly installed.
> Please reinstall it or try to install Python GDAL or Pillow module.
> ```
> 
> Using Blender v2.82.7 on Steam.
> Thanks.

I just restarted Blender and it automatically installed ImageIO. problem solved.

**Comment by nijiushi1** [comment]
@ReekyStive Thanks,i try it,it's still not work.

**Comment by cyhunter** [comment]
I have the same problem.     Try it,it's still not work.

**Comment by nijiushi1** [comment]
i  restart it 10min a time,lasted 10hour,and it's work.thanks alot.@domlysz

**Comment by jeff-song1122** [comment]
I have the same problem. it's still not work

**Comment by domlysz** [comment]
The workaround is now detailled into the FAQ
https://github.com/domlysz/BlenderGIS/wiki/FAQ#How-to-resolve-the-No-ImageIO-error-

**Comment by HarikalarKutusu** [comment]
This happened to me as my firewall popped-up. While I was allowing it, it was too late. The suggested method worked.

**Comment by KudriavtsevAlex** [comment]
Download your version from https://github.com/imageio/imageio-binaries/tree/master/freeimage
and put it to 
C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\imageio\resources\freeimage
if there is no freeimage folder - creat it
restart blender
good luck!

**Comment by GianniGi** [comment]
manual install solves nothing... no error message, but blendergis still doesn't load any image

**Comment by GianniGi** [comment]
Even if you could, manually downloading often solves nothing

Il sab 8 mag 2021, 03:03 StelleLee ***@***.***> ha scritto:

**Comment by AntoniWooo** [comment]
> Download your version from https://github.com/imageio/imageio-binaries/tree/master/freeimage and put it to C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\imageio\resources\freeimage if there is no freeimage folder - creat it restart blender good luck!

Put it to: 
C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderGIS-master\core\lib\imageio\resources 
Don't create freeimage folder!
