### ISSUE TITLE
Basemap whitescreen

### ISSUE THREAD

**Issue by domlysz** [domlysz/BlenderGIS#267]
I also tried this, .The map is not loading, A kind of white screen appears.
**Action performed:** 
->Enabled  Blender GIS in preference(set cache folder location)
->on the main screen selected GIS>>Web geodata>>basemap
->selected Google and satellite option and clicked ok
-> a white screen appeared
**Observation:**
->As I move the mouse,  latitude and longitude displayed on top of screen changes but latitude and longitude value do not contain the point. Eg instead of a latitude value 14.0888 it shows 140888(May it is just a display string).
->Latitude is changing as you move the mouse to select options like file or edit. So I can not select any option as the click is detected as a click on the map(my assumption)
->a cache file(GOOGLE_SAT_WM.gpkg,size 48kb) is getting created in cache folder.

**other details**
Blender version 2.82
Os: windows 10
(These are my observations,, maybe wrong as I am not a regular user of Blender and this is my first time.)

_Originally posted by @appitiza in https://github.com/domlysz/BlenderGIS/issues/262#issuecomment-586648641_

**Comment by domlysz** [comment]
@appitiza please report logging informations. Start Blender through a system console and in the addon preference set the logging level to debug. Then start basemap et report back the messages printed in the console.

**Comment by appitiza** [comment]
ERROR:BlenderGIS-master.core.basemaps.mapservice:589:Can't download tile x0 y0. Error <urlopen error timed out>

**Comment by Q338** [comment]
I have same problem with loading WGS84 Basemap. Mercator works fine, but when i change to WGS84   is nothing loading and only the gray square is displayed. ( screen here https://i.imgur.com/bQDNYoK.jpg )
and error pops up when zooming
```
bpy.ops.view3d.map_start(grd='WGS84', dialog="MAP")
Traceback (most recent call last):
  File "...AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 672, in modal
    moveFactor = (dst - dst2) / dst
ZeroDivisionError: float division by zero

location: <unknown location>:-1
```

**Comment by f3z** [comment]
@appitiza the error you describe is a network issue. Please check your firewall/proxy settings.
