### ISSUE TITLE
Get SRTM TimeoutError: [WinError 10060]

### ISSUE THREAD

**Issue by Rhrode** [domlysz/BlenderGIS#271]
I got this error loading the SRTM file, i try another locations but is the same error.

![2020-02-18 (2)](https://user-images.githubusercontent.com/61208662/74774841-b2929180-5251-11ea-96f2-c57b02b78a62.png)

TimeoutError: [WinError 10060]An error occurred during the connection attempt since the connected party did not respond properly after a period of time, or an error occurred in the established connection since the connected host could not respond.

**Comment by MinkOWar** [comment]
Just adding the note that I experience the same error through the regular windows installer version as of today as well.  I had used the Blender GIS addon yesterday with no issue.  Tried it in the office, timed out, so I thought it must be a security or firewall issue.  Came back home to test it and it doesn't work here either.  (Blender 2.80, 2.81a, and 2.82 tested)

**Comment by comporell** [comment]
First time user here, just manually added the addon. I am getting the same error

**Comment by SB97** [comment]
`with urlopen(rq) as response, open(filePath, 'wb') as outFile:` the Error points to this line (108) in [https://github.com/domlysz/BlenderGIS/blob/40c6a213a8ee7d635917a2fc4c796543660604a4/operators/io_get_srtm.py](url)

the link in the comment in line `#http://opentopo.sdsc.edu/otr/getdem?demtype=SRTMGL3&west=-120.168457&south=36.738884&east=-118.465576&north=38.091337&outputFormat=GTiff` also dosn´t work

opening http://opentopo.sdsc.edu/otr/ gives me a 404 so the Service is online at least. 

My guess is there are problems with the Service or they changed how the Service works. But i can´t find new about it on there Site

**Comment by comporell** [comment]
Yeah looks like the service is down. I'll check again tomorrow

**Comment by Renderbrandt** [comment]
Same here, hopefully this is just a glitch...

**Comment by aarensan** [comment]
Ok guys, found a temporary solution. Change the url code in **io_get_srtm.py** from

**This**
`url = 'http://opentopo.sdsc.edu/otr/getdem?demtype=SRTMGL3' + '&'.join([w, e, s, n]) + '&outputFormat=GTiff'`

**To This**
`url = 'http://www.marine-geo.org/services/GridServer?' + '&'.join([n, w, e, s]) + '&layer=topo&format=geotiff&resolution=high'`

Just search for the 'url' variable and after changing it - go to PREFERENCES - and uncheck & check the BlenderGIS AddOn to make the changes available.

The **io_get_srtm.py** file is located on Mac OS X under `/Users/YOURUSER/Library/Application Support/Blender/2.83/scripts/addons/BlenderGIS-master/operators/io_get_srtm.py`

Works on Mac OS X fine and fast.

**Comment by Rhrode** [comment]
> Ok guys, found a temporary solution. Change the url code in **io_get_srtm.py** from
> 
> **This**
> `url = 'http://opentopo.sdsc.edu/otr/getdem?demtype=SRTMGL3' + '&'.join([w, e, s, n]) + '&outputFormat=GTiff'`
> 
> **To This**
> `url = 'http://www.marine-geo.org/services/GridServer?' + '&'.join([n, w, e, s]) + '&layer=topo&format=geotiff&resolution=high'`
> 
> Just search for the 'url' variable and after changing it - go to PREFERENCES - and uncheck & check the BlenderGIS AddOn to make the changes available.
> 
> The **io_get_srtm.py** file is located on Mac OS X under `/Users/YOURUSER/Library/Application Support/Blender/2.83/scripts/addons/BlenderGIS-master/operators/io_get_srtm.py`
> 
> Works on Mac OS X fine and fast.

I do what you suggest, i still having the same error.

**Comment by aarensan** [comment]
> > Ok guys, found a temporary solution. Change the url code in **io_get_srtm.py** from
> > **This**
> > `url = 'http://opentopo.sdsc.edu/otr/getdem?demtype=SRTMGL3' + '&'.join([w, e, s, n]) + '&outputFormat=GTiff'`
> > **To This**
> > `url = 'http://www.marine-geo.org/services/GridServer?' + '&'.join([n, w, e, s]) + '&layer=topo&format=geotiff&resolution=high'`
> > Just search for the 'url' variable and after changing it - go to PREFERENCES - and uncheck & check the BlenderGIS AddOn to make the changes available.
> > The **io_get_srtm.py** file is located on Mac OS X under `/Users/YOURUSER/Library/Application Support/Blender/2.83/scripts/addons/BlenderGIS-master/operators/io_get_srtm.py`
> > Works on Mac OS X fine and fast.
> 
> I do what you suggest, i still having the same error.

Maybe restarting Blender can help? And which version are you using? Also important to cahnge the io_get_srtm.py in the 2.83a version.

**Comment by douglasdaquino** [comment]
At first this sollution @aarensan didn't worked, but when I restarted Blender, as he suggested in the last comment, it worked perfectly, thank you so much man :)

**Comment by Renderbrandt** [comment]
So is this the PC fix as well then?

**Comment by MinkOWar** [comment]
> So is this the PC fix as well then?

Yes.  I used the installer version, so edited the file under appdata/roaming/blender foundation.../addons. and it was able to pull from the other site just fine.  (Replying on my phone, excuse the truncated path).

**Comment by Renderbrandt** [comment]
Yes sir(s) it works now, thank you all!

**Comment by domlysz** [comment]
seems the web service is back to normal now

**Comment by Renderbrandt** [comment]
Ok, do i need to change it back, or leave it as is?

**Comment by miguelbg04** [comment]
Well is working right now

**Comment by tkeajax** [comment]
This issue is still persisting for me

**Comment by domlysz** [comment]
There is now an option to change the web service if the first is down: 
![Sans titre](https://user-images.githubusercontent.com/5639024/76170461-623c8e80-6182-11ea-8174-17cfbfe263bc.jpg)
