### ISSUE TITLE
SRTM Error

### ISSUE THREAD

**Issue by northernlite69** [domlysz/BlenderGIS#272]
I get a fatal error on

GET
SRTM

I can't copy the text trace, so screenshot instead :/

Thank you for this amazing addon!
![Screenshot (137)](https://user-images.githubusercontent.com/16082320/74780268-89005700-529f-11ea-95b9-242619dc944f.png)

**Comment by aarensan** [comment]
Same issue here on Mac OS X while retrieving SRTM.

![Screenshot](https://user-images.githubusercontent.com/13258343/74789821-1cdd1d80-52b6-11ea-8567-6a901f644dbe.png)

**Comment by aarensan** [comment]
Here is a workaround [https://github.com/domlysz/BlenderGIS/issues/271#issuecomment-587984616](url)

**Comment by domlysz** [comment]
duplicate #271
