### ISSUE TITLE
Error while getting SRTM

### ISSUE THREAD

**Issue by pedroLNL** [domlysz/BlenderGIS#273]
Hi,

I just tryed to use the BlenderGIS in Blender 2.81 and I got an error messege while Getting SRTM so I updated my blender to the new 2.82 and I´m still getting the same error.
To be clear, I can install it properly (through the zip file) and can inset a Basemap from Google with no problem. The issue happens when I press the buttom "Get STRM".
I searched the wiki and older issues here but could not find the same problem. I´ll say that my search was limited to the specific terms because I knowk nothing of python or coding, so sorry if the info was out there and I could not find it. 
Here´s a image of the error:
![blenderGIS_error](https://user-images.githubusercontent.com/61231017/74826505-9fd89500-5303-11ea-8dad-5d043f5a6908.png)

Thanks a lot!

**Comment by aarensan** [comment]
Watch this one #271

**Comment by domlysz** [comment]
duplicate #271
