### ISSUE TITLE
Goes Blackout

### ISSUE THREAD

**Issue by GoradiaNishant** [domlysz/BlenderGIS#274]
**Blender and OS versions**

**Describe the bug**
Here in blender the map goes to the grey screen while zooming

![image](https://user-images.githubusercontent.com/48113680/74904649-49865780-53d2-11ea-960c-aed76a8595ad.png)

**Error message**

**How to Reproduce**

**Comment by domlysz** [comment]
Please respect the issue report template

> If the addon crash, report here the complete error message. Most of time it will not be possible to solve the issue without any error message.
> 
> Error messages are reported into the system console/terminal. Windows users can open the console at any time from the windows menu, Linux or Mac users must start Blender through a new terminal.
> 
> To maximize the number of informations that will be reported by the addon you should increase the log level beforehand. To do this, go to BlenderGIS addon preferences and set the system logging level to "debug"

**Comment by domlysz** [comment]
closed as no more informations has been provided
