### ISSUE TITLE
Wont install on Blender 2.8 & 2.82

### ISSUE THREAD

**Issue by MWDUSER7** [domlysz/BlenderGIS#275]
**Blender and OS versions**

**Describe the bug**

**Error message**

**How to Reproduce**

**Comment by domlysz** [comment]
Please follow the issue template, no error can be solved without detailed informations.

Issue closed until there is enough information

**Comment by MWDUSER7** [comment]
Hi 
This is the error message that comes up when I try to enable the add on within Blender 
*See attached 
I have this message come up when I try to install within 2.8 & 2.82
Thanks 

Mike Wright

 

    On Thursday, 20 February 2020, 16:27:03 GMT, domlysz <notifications@github.com> wrote:  
 
 
Please follow the issue template, no error can be solved without detailed informations.

Issue closed until there is enough information

**Comment by nic0711** [comment]
Hi! 
Please reopen the Issue. Same problem here.
--> unable to  activate the plugin

Mac OSX Mojave
Blender 2.82
BlenderGIS 1.0

![image](https://user-images.githubusercontent.com/4477547/75336909-4a186580-588c-11ea-8eed-23213d38a0a3.png)

Thanks!

**Comment by domlysz** [comment]
nothing attached, please answer from gihub not by mail
