### ISSUE TITLE
Blender Menus Stop Working

### ISSUE THREAD

**Issue by vsheffer** [domlysz/BlenderGIS#277]
**Blender and OS versions**
Blender 2.82
Ubuntu 19.10

**Describe the bug**
I installed the plugin with no errors.  After that, I choose the GIS->Web geodata->Basemap option.  After clicking "OK" on the BlenderGIS dialog, the Blender Menus stop working.  The only way out of it is to click the "X" in the top right to exit the entire app.

**Error message**

I started in the terminal and there are no errors.

**How to Reproduce**

I've attached screencast showing the steps I used to reproduce the behavior.   Well, I tried to attach a .webd screencast, but Github won't accept it.  I have it available if I can get it to you some other way.

**Comment by vsheffer** [comment]
This is not an issue.  I didn't get far enough into the docs before submitting the issue.

**Comment by etienne1911** [comment]
same mistake :)
