### ISSUE TITLE
Suggestion: Elevation from Nasa SRTM

### ISSUE THREAD

**Issue by mirlip** [domlysz/BlenderGIS#28]
Hi,
The nasa with it's SRTM data is I think the best source of elevation data that is freely accessible. Would it be possible to download the right SRTM data for the zone we work on and use the greyscale data in the displace modifier?

**Comment by domlysz** [comment]
It's really the idea behind the basemaps addon when I started it : having reference map to quickly go somewhere and define a working area then add a set of utilities to pick up from the web data which covering this zone.

I was thinking about SRTM and also a tool for directly download and import OSM data. However for now the priority is to polishing the existing tools, not sure I'll have time in the next months to add a new feature like this.

**Comment by mirlip** [comment]
Polished tools is a must. Streamlined UI and workflow bring at least as much than new features, so I agree with you. Only knowing it's on the plan makes happy, take your time :)

**Comment by domlysz** [comment]
implemented
