### ISSUE TITLE
SRTM is not available beyond 60 degrees north

### ISSUE THREAD

**Issue by doomgitdoom3** [domlysz/BlenderGIS#280]
So this message pops up when i try to generate a height map through the SRTM button in the add-on. I notice that the location i want to depict with this addon, has a heightmap in google maps and other map services so how come i cant import it with the add-on? also is there a way around this, say manually downloading the height info and importing it?

**Comment by domlysz** [comment]
With the addon, you can import any kind of Digital Elevation Model (DEM) in Geotiff format. The NASA SRTM datasource is free but have had it's limits : low resolution and does not cover high latitudes, but again it's an open datasource, Google certainly uses other proprietary data. Some country provides national DEM in opendata, some other not. The Get SRTM button is a nice shortcut to import the really common SRTM datasource, but the core functionnality of the plug-in is to add the ability to import commons spatial data formats, not to provides datasource.
