### ISSUE TITLE
Precision between BlenderGIS and google Earth is wrong

### ISSUE THREAD

**Issue by GuillaumeHumanitas** [domlysz/BlenderGIS#281]
Hello,
I need be perfectly 1:1 scales when I create map, because I will use the map create with BlenderGIS as a guide for creating a level inside Unreal engine.

For exemple the Airport road width is 70m inside blender, but when I check inside Google Earth Pro, the width is 45m.
![googleearth_TQW21Xy6Uq](https://user-images.githubusercontent.com/61807494/75929086-c9cea300-5e3d-11ea-8838-c43474903119.png)

They are any way to able to have the sames measurement inside google earth pro? It very important, because we use unreal as a simulator at my jobs. It would help me a lot to have the good scale inside Blender, because our simulation depend heavily to have good GPS Data.

Thank You

**Comment by kikislater** [comment]
It looks like a bad projection setup. Which CRS do you use ?

**Comment by domlysz** [comment]
Please read the FAQ about WM projection : 
https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-my-measurements-on-basemaps-reference-seems-wrong-

**Comment by GuillaumeHumanitas** [comment]
I was using the Web Mercator

**Comment by domlysz** [comment]
yes, for example your measurement of 70 m can be corrected like this :
70 * math.cos(math.radians(48.33)) = 46.53

so multiplying the mesh dimensions by cos(lat) can be a way to approximatively correct the distortions

but I suggest to just forget the Web Mercator projection, it's not suitable for your use case, use a local projection instead, like UTM
