### ISSUE TITLE
BlenderGIS crash - Pbl GDAL ?

### ISSUE THREAD

**Issue by jdarras** [domlysz/BlenderGIS#282]
Bonjour,
L'addon crash systematiquement lorsque j'utilise Basemap. 
J'ai installé GDAL mais avec un logiciel qui se nomme QGIS. J'essaie de l'installer avec la procédure mais sans résultat, j'obtiens les messages d'erreur ci-dessous :

Depuis la fenêtre de command windows :
![Capture](https://user-images.githubusercontent.com/35170258/76146381-80c35c80-6092-11ea-8a82-faf6fc42cd6d.PNG)
Ma version de python Blender 2.82 :
![Capture2](https://user-images.githubusercontent.com/35170258/76146382-815bf300-6092-11ea-9e75-b095bb19c3ae.PNG)
La console Blender :
![Capture3](https://user-images.githubusercontent.com/35170258/76146383-815bf300-6092-11ea-908b-2e4b90ae2aef.PNG)
Mon installation de gdal avec qgis :
![Capture4](https://user-images.githubusercontent.com/35170258/76146442-1b23a000-6093-11ea-8480-d3f5d9f43f93.PNG)

**Comment by domlysz** [comment]
Installer GDAL ne solutionnera jamais un problème avec l'addon car il ce dernier est conçu pour fonctionner sans. Pas la peine donc de s'engager dans cette procédure plutôt réservées aux utilisateurs avancés. 

Ici le message d'erreur est clair : permission denied. Il faut des droits d'écriture dans le dossier où l'addon est installé pour écrire le fichier où sont sauvegardées les préférences utilisateurs. En temps normal cela ne pose pas de problème car l'addon s'installe automatiquement dans le dossier utilisateur lorsqu'on utilise la fonction install from zip. Ici il semble que l'installation ait été faite par copier coller dans C: ce qui a du nécessiter des privilège élevés.

**Comment by jdarras** [comment]
Merci beaucoup domlysz, en effet, c'était bien un problème de droits d'accès ! Ca fonctionne maintenant. 
Merci beaucoup
