### ISSUE TITLE
Can't activate the add-on once installed. - MacOS Catalina Blender 2.82

### ISSUE THREAD

**Issue by ahurig** [domlysz/BlenderGIS#283]
Hi guys, 

I use the add-on on blender 2.81 at work on a Hacktintosh running High Sierra. Works like a charm.

Tried to use it at home on my macbook retina running blender 2.82 on Catalina and I can't activate it once installed. 
I tired on 2.81 as well on the macbook and same issue. Tried to delete it from the computer, re download it... same issue.
Maybe this log would help you to understand what is going on.
Thank you for the amazing work anyway!

<img width="899" alt="Capture d’écran 2020-03-07 à 18 09 25" src="https://user-images.githubusercontent.com/61915327/76147646-cdad3000-609e-11ea-96aa-16a8f78ac1da.png">

**Comment by domlysz** [comment]
duplicate #224. Please read all the warnings at home page & in the issue template
