### ISSUE TITLE
Get SRTM/OSM fails with GDAL

### ISSUE THREAD

**Issue by jdarras** [domlysz/BlenderGIS#284]
Bonjour,
Je teste actuellement BlenderGis, le WebGeoData BaseMap fonctionne très bien mais visiblement pas le get OSM et le get SRTM. Y-a-t'il une unité à respecter dans Blender comme se mettre en kilomètre ? 

Quand je fais un get OSM, mon Mesh se retrouve bien en dessous de la grille alors que l’endroit que je sélectionne, à côté de Versailles est au dessus de la mer si cela à son importance ? 

Quand je fais un get SRTM, rien, aucun création de Mesh.

Je précise que je reste en projection Web Mercator. (Quand je passe en Lambert 93, j'ai un écran gris !)
J'ai également passé les droits en écriture, lecture... au plus haut pour tous les dossiers de ma version Blender 2.82. 
J'ai toujours un doute sur la version de gdal que j'ai installé sachant que j'ai installé la version GDAL ‑ 3.0.4 ‑ cp37 ‑ cp37m ‑ win_amd64.whl pour une version python 3.7.4. Même chose pour le paquet de roues Numpy de Christoph Gohlke, j'ai installé la version : numpy ‑ 1.18.1 + mkl ‑ cp37 ‑ cp37m ‑ win_amd64.whl

J'ai lu la FAQ ainsi que le BlenderGis Wiki mais je ne trouve pas la solution.

Merci pour votre aide
Julien

**Comment by domlysz** [comment]
Pour projeter les données OSM sur le terrain, il faut cocher l'option "elevation from object". Pour les données SRTM, si le mesh (plan) texturé avec le fond de carte est sélectionné alors il sera déformé par l'application de la texture de relief. En revanche, si rien n'est sélectionné, un nouveau mesh apparait. Quel que soit la méthode, au niveau du bassin parisien, cela devrait être assez subtile vu la pauvreté du relief, on peut se mettre en vue ortho de côté pour voir la déformation ou tout simplement vérifier les dimensions du mesh en Z. il est possible d'exagérer la déformation en modifiant la valeur strenght du modifier displace.

**Comment by jdarras** [comment]
Bonjour Domlysz, merci encore pour votre réponse. Je viens de tester à nouveau mais je n'y arrive toujours pas ! J'ai essayé sur une partie montagneuse sans résultat. J'ai passé l'ensemble de mon dossier d'installation Blender avec des droits en lecture, écriture au plus haut mais visiblement ce n'est pas ça. Je vais continuer à tenter de trouver une solution...
Merci
Julien

**Comment by domlysz** [comment]
Difficile d'aider sans plus d'information. S'il n'y a pas de message d'erreur, il faut vérifier si la texture à bien été téléchargée : si le .blend est sauvegardé, le fichier tiff doit apparaitre dans le même dossier. Ensuite vérifier que le fichier est valide, en l'ouvrant dans QGIS par exemple. A ce stade là s'il y a un problème alors cela viendrait de la configuration dans Blender : vérifier que la texture a bien été chargée dans Blender puis contrôler la configuration du displacer.

Comme vous avez installé GDAL, il est possible que le problème vienne de là (je n'ai pas testé avec des versions récentes de GDAL). Dans les preferences de l'addon il y a deux variables : imaging engine et projection engine. La valeur par défaut est à AUTO, si la librairie GDAL est installée alors elle prioritaire sur les autres. Si GDAL apparait comme option dans ces deux listes déroulantes c'est que l'installation est correcte. Dans ce cas changer les valeurs : choisir imageIO pour imaging engine et builtin pour projection engine pour contourner l'utilisation de GDAL et tester à nouveau.

**Comment by jdarras** [comment]
Domlysz, une fois de plus merci pour ton message, une fois de plus tu cibles parfaitement le problème et tu y réponds ! Merci beaucoup. Ca fonctionne lorsque je passe sur imageIO et builtin. Par contre, je ne comprend pas pourquoi je n'ai pas une image en niveau de gris mais une image qui ressemble à çà dans Blender :
![Capture](https://user-images.githubusercontent.com/35170258/76201501-a74cd900-61f3-11ea-87e3-5460d5c5dfb4.PNG)

**Comment by domlysz** [comment]
C'est lié au fait que le raster est codé en float32 et que les valeurs d'altitudes sont très faibles au regard de la valeur maximale que peut porter un pixel. Dans l'image editor de Blender le raster doit apparaitre tout noir.  Généralement les logiciel conçus pour manipuler des DEM appliquent automatiquement un dégrader de gris calculer sur la base des valeurs min et max effectivement présentent dans le raster.

Pour en revenir au problème initial, il semble qu'une mise à jour soit nécessaire pour rétablir le fonctionnement avec les dernières versions de GDAL.

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/commit/b6861910e5ca567c76785c0cb614fda0dbd40bea
