### ISSUE TITLE
strm precision 

### ISSUE THREAD

**Issue by 00khaled11** [domlysz/BlenderGIS#285]
hallo guys , when i create the strm elevation map about any area worldwide the precision is very bad , i get the elevation\height between 20 meters to 100 meters away from each other points, depending on how was the zoom on that area of the map  .... how to get elevation\height of the terrain every like one meter or two meter even if the produced file would be big ! is there any option to modify the precision ,,, i tried to subdivide the picture itself before i click strm , but that didnt work too .

thanks

**Comment by domlysz** [comment]
SRTM data is about 90 meters per pixels. A solution is to activate the texture interpolation to smooth the relief :
![Sans titre](https://user-images.githubusercontent.com/5639024/76170289-d83ff600-6180-11ea-917f-c5347ab03209.jpg)

**Comment by 00khaled11** [comment]
@domlysz sorry maybe , u didnt understand me ,,,, first i used to create the stl model by using dgm height map that have certain precision ... it is a text file that has x y z ... so the height Z was corrosponding to different x & y ...  the precision is what is the distance between x and y ... for a very good precision i used to get the heights for every one meter distance .. so in case of strm i want to define the precision ,,, is the height is taken for every 1 meter or 2 or 90 meter for every pixel as u said ... its so critical to me to have a very high precision .. so if i would work with pixels ... how i can make that every pixel would correspond to 1 meter distance or more or 1*1 m  rectangle ??
i hope that you got my point

thanks alot for help

**Comment by domlysz** [comment]
one pixel represents one points. For SRTM dataset, the distance between each point is equals to 90m (30m for US only). If you need an elevation model in high resolution you will certainly have to pay for. In the other hand SRTM is free but low res. That's all

**Comment by 00khaled11** [comment]
@domlysz okay thanks alot!

**Comment by kikislater** [comment]
@domlysz 30m resolution is now available worldwide.
There is another one from Japan : alos => 5m resolution but for free version you will have 30m better than srtm

**Comment by domlysz** [comment]
Yes you're right this is also the ASTER GDEM available worldwide at 30m. Don't know if there exits any web service API to easily grab it.

**Comment by kikislater** [comment]
Sorry, I'm not talking about ASTER GDEM, which is not that good, but ALOS :

https://www.eorc.jaxa.jp/ALOS/en/aw3d30/index.htm

https://wiki.openstreetmap.org/wiki/AW3D30

**Comment by domlysz** [comment]
ok interesting thanks !
