### ISSUE TITLE
activate/access scale parameter

### ISSUE THREAD

**Issue by xyleme** [domlysz/BlenderGIS#288]
**Blender 2.82 and 2.79 | OS : Debian 10**

Hello Domlysz,

I've been using your nice addon on a daily basis for a long time. And I've never figured out how to acces the "scale" property of the geoscene, besides SRID, crs x and so on...

Right now I would appreciate my blender workflow to be downscaled right from the beginning by 2 or 3 orders of magnitude, in order to make things easier when it comes to export a scene to gltf format (yes, I finally deliver my 3d scenes in three.js web pages).
Sorry, I probably missed something about this property, but I don't know what and where.

Oh, I forgot to say: I essentially work within projected coordinate systems.

Yours,
Vincent

**Comment by domlysz** [comment]
You can change the scale when running the basemap function using the shortcut alt + mousewheel [as descripted in the wiki](https://github.com/domlysz/BlenderGIS/wiki/Basemaps)

But, unfortunately this property is not well implemented for now. Most of the others tools of the addon does not take it into account. So, I discourage using it for the moment.

**Comment by xyleme** [comment]
Thank you for this prompt reply,

ok, I'll keep working at scale 1, then rescale at final export step.
V.
