### ISSUE TITLE
Basemap download never ends

### ISSUE THREAD

**Issue by MattGPowell** [domlysz/BlenderGIS#291]
# **Blender and OS versions**

Blender 2.81, Windows 10 1903

# **Describe the bug**

Not a bug, at my company we are operating behind a proxy/firewall and upon creating a basemap it gets stuck at 24/25 while downloading. I suspect it is a firewall blocking issue, but without knowing what urls that the data is being downloaded from I cannot request urls to be unblocked. 

# **How to Reproduce**

Be on a highly secured network that blocks most web traffic and use the GIS Basemap option. 

# **Error message**

There is no error message, can only see in the console that it gets stuck downloading, always 1 less than it is trying to retrieve, such as 24/25

**Comment by domlysz** [comment]
Seems like a bug for me. If the firewall block the domain then the requests just fail and will get a white image. I think in this case, all map tiles have been downloaded (with success or not) but something went wrong after. Is the operator completely freezing Blender at this point ? That can explain why the progress report does not reach the 25th tiles.

Anyway, in the addon preferences make sure to set the logs level to DEBUG, then in the system console you will see the urls requested and check if it's a firewall issue.

**Comment by MattGPowell** [comment]
Hello

In response, no blender does not lock up completely, I can escape out of the process and keep working Some blender interface elements are still updating, some are not accessible. We do get a white square with nothing (with my settings it is a gray square). 

The system console isn't showing any URL information and it is set to DEBUG level logging. 

Attached are screenshots. 

Thanks

Matt
![Blender](https://user-images.githubusercontent.com/62124682/76711352-6c065900-6763-11ea-8b89-9c7712a01740.PNG)
![SysCon](https://user-images.githubusercontent.com/62124682/76711355-6f014980-6763-11ea-8f14-a88cea440dbf.jpg)

**Comment by AMGA45** [comment]
I'm just the same as you

**Comment by byeage** [comment]
Need the ability to set the http proxy 😂

**Comment by MattGPowell** [comment]
Yes, correct, but I need to know the addresses to request to be bypassed. Now that we are working from home, on our work machines, off the work network, we have no issue with the basemap downloading.

**Comment by domlysz** [comment]
Debug log does not report url if the basemaps tiles are already in the cache, if you zoom to a location far away your area interest you'll see the url reports.

Anyway here the urls templates for each default basemaps :
http://mt0.google.com/vt/lyrs={LAY}&x={X}&y={Y}&z={Z}
http://tile.openstreetmap.org/{Z}/{X}/{Y}.png
http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/{QUADKEY}?it={LAY}
https://server.arcgisonline.com/ArcGIS/rest/services/{LAY}/MapServer/tile/{Z}/{Y}/{X}

For SRTM providers :
http://opentopo.sdsc.edu/otr/getdem?demtype=SRTMGL3&west={W}&east={E}&south={S}&north={N}&outputFormat=GTiff
http://www.marine-geo.org/services/GridServer?west={W}&east={E}&south={S}&north={N}&layer=topo&format=geotiff&resolution=high

For OSM providers
https://lz4.overpass-api.de/api/interpreter
http://overpass.openstreetmap.fr/api/interpreter
https://overpass.kumi.systems/api/interpreter

And the web service for reprojection tasks
http://epsg.io/trans?x={X}&y={Y}&z={Z}&s_srs={CRS1}&t_srs={CRS2}

**Comment by ForceConstant** [comment]
> Need the ability to set the http proxy 😂

Did anyone find a way to set the http proxy? I have the problem that I can't get the python dependencies installed either.

**Comment by domlysz** [comment]
#345
