### ISSUE TITLE
Georender Camera

### ISSUE THREAD

**Issue by ericyuart** [domlysz/BlenderGIS#292]
# **Blender and OS versions**

I'm on Blender 2.82.7 and I am working on Windows 10.

# **Describe the bug**

I've been trying to use the Georender camera, and have been looking for the Pixel Size attribute so that I can set my resolution to be related to the pixel size and dimensions of the terrain.  Is this the mapRes attribute under the camera's Object Data Properties?  If so, when I modify this attribute, nothing happens, and the resolution remains the same as before?

# **How to Reproduce**

![blender_issue](https://user-images.githubusercontent.com/16598226/76790094-8efd3100-6794-11ea-8fa4-d6a5779618b2.jpg)

# **Error message**

**Comment by domlysz** [comment]
Setting the pixel size is an option of the operator. You can update the pixel size by starting again the operator with the camera and the mesh selected.

Please read the wiki, it's all explained :
https://github.com/domlysz/BlenderGIS/wiki/Make-a-georef-render
