### ISSUE TITLE
Import .obj mesh model but in wrong position 

### ISSUE THREAD

**Issue by ky1218** [domlysz/BlenderGIS#295]
# **Blender and OS versions**

Blender version 2.83a, MacOS High Sierra

# **Describe the bug**

More of asking for help instead of reporting an issue (please remove if not following guidelines). 
Aim is to import obj file (3D mesh model) and shapefiles into Blender. Both are georeferenced with the same Coordinate Reference System. Shapefiles work well and they are in their correct positions as I expected. But obj model is not. It is misaligned, not in terms of X,Y,X orientations, but it is located at the wrong place. 

# **How to Reproduce**

1. I set up and defined my preferred CRS in the GIS add-on settings and also defined a CRS in the Geoscene panel- crs x and crs y are automatically filled in by Blender when I import my first data (a shapefile). 

2. Imported shapefile and obj file. Found that shapefile was in place, but obj was not in correct position (reference to illustration below, it should at least be "within" the area of shapefile. Due to sensitivity issue, I am unable to attach a screenshot. 
![Slide1](https://user-images.githubusercontent.com/62316727/76917635-fdf69900-68fe-11ea-9399-c04f5c38de8b.jpeg)
![Slide2](https://user-images.githubusercontent.com/62316727/76917639-0058f300-68ff-11ea-9254-58a1bd3cb1d5.jpeg)

Both of their Scene properties are the same.
Checked the reference system used when obj was created- it was the same as shapefile's CRS. Wondering could it be that obj does not actually store real-world coordinates? 

Any help would be greatly appreciated. I'm a beginner in using Blender, so if this does not follow community's or the thread's guidelines, please remove.

**Comment by domlysz** [comment]
Hi

The obj format does not contains the geolocation of the model. However it's possible the obj store coordinates as longitude/latitude or in a projection system, but in this case the format does not inform about the eventual coordinate system in use. Also the obj importer is not a part of the BlenderGIS addon and so, it does not take into account the georeferencing information of the scene used by BlenderGIS.

**Comment by ky1218** [comment]
Hi, 

Many thanks for the quick reply! 

Adding to this, wonderful work on the BlenderGIS add-on. Certainly opened doors to bridging Blender and GIS.
