### ISSUE TITLE
SRTM displacement doesn't match google earth elevation

### ISSUE THREAD

**Issue by carmandale** [domlysz/BlenderGIS#299]
blender 2.83 MacOS

SRTM data doesn't match google earth. Mountain is not as tall as in google earth

 go to 48°57'21.33"N and 114° 4'45.39"W and compare to google earth

#

**Comment by domlysz** [comment]
altitudes values are corrects. For example the [Chapman Peak has an elevation of 2868m](https://en.wikipedia.org/wiki/Chapman_Peak), on the mesh I found 2816 which is very close considering SRTM data have a pixel width of 90m.

![Capture du 2020-03-19 23-33-22](https://user-images.githubusercontent.com/5639024/77121021-8594f280-6a3a-11ea-989c-524e9d4b3428.png)

**Comment by carmandale** [comment]
This is how it looks in google earth

https://www.dropbox.com/s/xut5fbo0auypz8r/Screen%20Recording%202020-03-19%20at%205.59.11%20PM.mov?dl=0 <https://www.dropbox.com/s/xut5fbo0auypz8r/Screen%20Recording%202020-03-19%20at%205.59.11%20PM.mov?dl=0>

And this is how the same place looks in blender

https://www.dropbox.com/s/jvgco1k53u687k7/Screen%20Recording%202020-03-19%20at%206.01.13%20PM.mov?dl=0 <https://www.dropbox.com/s/jvgco1k53u687k7/Screen%20Recording%202020-03-19%20at%206.01.13%20PM.mov?dl=0>

It feels a lot flatter.

**Comment by domlysz** [comment]
Depending of the location Google use a range of elevation data sources in higher resolution than SRTM. That's why the model look nicer in Earth. Especially in areas with very high slope, low resolution data will tend to smooth the reality of the slope. However the model in Blender is correct with true elevation values, but the resolution is just too low for mapping high mountain slope with precision.

**Comment by carmandale** [comment]
Do you know of any way to get the higher detail data?
Thanks,
Dale

**Comment by domlysz** [comment]
BlenderGIS can import any kind of Digital Elevation Model in Geotiff format, this is one the core functionnality, but I can't provide datasource for you (SRTM is common, worldwide and free, that's an exception). Available datasource depends on your location and the price you're willing to pay. Maybe start by looking at USGS productions.
