### ISSUE TITLE
Warning on console in windows

### ISSUE THREAD

**Issue by mirlip** [domlysz/BlenderGIS#30]
When Blender starts, their is a warning regarding geoscene:

> Warning: addon-module 'geoscene' found module but without __addon_enabled__ field, possible name collision from file: 'C:\\Users\\test\\AppData\\Roaming\\Blender Foundation\\Blender\\2.77\\scripts\\addons\\geoscene\\__init__.py'
> module changed on disk: C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\geoscene\__init__.py reloading...

**Comment by domlysz** [comment]
know that, not a problem. A solution will be regrouping all addon into one unique and I think it's time to do this now, keeping the modular aspect does not make sense while shared code between addons growing up.

**Comment by domlysz** [comment]
https://github.com/domlysz/BlenderGIS/commit/15bf2969890df860fc105d74adc315bb29de8daa
