### ISSUE TITLE
No raster re projection support

### ISSUE THREAD

**Issue by Temo10** [domlysz/BlenderGIS#301]
Hi, hope someone can help. I just started usin GIS, when first clicking on GIS i see in parentheses ( No raster reprojection support). I did not put attention but when trying to get RSTM data i get error message about raster. I tried on laptop same issue.
![Error](https://user-images.githubusercontent.com/40782409/77134161-6478d580-6a2b-11ea-81af-e227bcc6dbf2.PNG)
![Error2](https://user-images.githubusercontent.com/40782409/77134172-75c1e200-6a2b-11ea-9104-72aa870564b0.PNG)

Please help

**Comment by domlysz** [comment]
duplicate #300

**Comment by Zefaloners** [comment]
Apple M2 Pro Ventura, Blender 3.6.5

I have the same problem, can anyone help me fix it?
replacing SRTM servers or API key requests did not help
 
<img width="346" alt="Zrzut ekranu 2023-11-2 o 13 45 19" src="https://github.com/domlysz/BlenderGIS/assets/148060275/c67b8577-44a3-4160-b9a5-5b1743116ac4">
<img width="953" alt="Zrzut ekranu 2023-11-2 o 13 50 44" src="https://github.com/domlysz/BlenderGIS/assets/148060275/c3dfd82c-73a6-4cae-a0fc-9af4a2415bb9">
