### ISSUE TITLE
Fracture appeared on surface

### ISSUE THREAD

**Issue by Mcphere** [domlysz/BlenderGIS#303]
# **Blender and OS versions**

Platform: WIN10 X64
Blender: 2.82

# **Describe the bug**

First of all, appreciate your work, it really helps!
I imported a pretty large shp file (about 18k+ lines, some are not enclosed). After generated polymeshes, there are some fractures on the surface, and image texture cannot apply appropriately.
I write a program to enclose all the line feature in shp file. However, the fratures still appear at the very place.

# **How to Reproduce**

1. Import line feature shp, mercator projection, unit: meter.
2. GIS-->mesh-->delaunay
![image](https://user-images.githubusercontent.com/35681779/77155619-c3485880-6ad8-11ea-9d22-c198718a010c.png)
![image](https://user-images.githubusercontent.com/35681779/77155734-ee32ac80-6ad8-11ea-93f9-ca3e53dccc7a.png)

# **Error message**

No error message.

**Comment by Mcphere** [comment]
Seems the pictures failed to load. Here they are.
![IFG Q1U07HVUX 15C5YJS](https://user-images.githubusercontent.com/35681779/77156953-67330380-6adb-11ea-94ef-9ae11ccff548.jpg)
![GOO(G)CE@~A_BA)`6_RNC(5](https://user-images.githubusercontent.com/35681779/77156962-6b5f2100-6adb-11ea-80c8-ea6e97a9ae05.jpg)

**Comment by domlysz** [comment]
Can you share the dataset (or at least the incriminate part) ?

Sound like the Delaunay triangulation fails here.

**Comment by Mcphere** [comment]
Thank you for your time! The dataset is a bit large. I'm not sure if I cut it into pieces the problem shall remain. So, I'll try to send the original file to your mailbox tomorrow, please check.

**Comment by domlysz** [comment]
Sound like the contours were extracted from a raster, I suggest using the raster DEM directly, you should have better results and a smoother workflow:
https://github.com/domlysz/BlenderGIS/wiki/Import-DEM-grid

I'm not sure what to say about the issue : when extracting the incriminated part and running a new triangulation the fracture does not appears. It seems some points are connected to a bad far away candidate causing these long edges. I need to investigate more, but the resulting model is too huge for my computer.

**Comment by Mcphere** [comment]
Thank you very much!
You are right, the shp file was extracted from a geotiff figure using ArcGIS. Geotiff is the only kind of file I can get currently. 
I tried to import the geotiff (pixel value is absolute elevation), but no matter the raster was in decimal degrees (WGS84) or in meters (mercator), the results were flat with no texture. But in ArcMap, the raster looks fine. Can you help me finding what's wrong?
![image](https://user-images.githubusercontent.com/35681779/77276028-a4261280-6cf4-11ea-9498-da7f91f9926a.png)
![image](https://user-images.githubusercontent.com/35681779/77276122-d9326500-6cf4-11ea-8848-25142d2f0963.png)
By the way, I read an article that shows how to create real terrain by the built-in tools of blender using the DEM raster as UV texture. I wonder if it is an actural model or just a visual effect randered by cycles. I need a actual model like the one generated by shp to run a hydrodynamic simulations on.

**Comment by domlysz** [comment]
Did you select one of the right mode in the operator option ?

![](https://raw.githubusercontent.com/wiki/domlysz/blenderGIS/Blender28x/images/georaster_import_modes_dem.jpg)

**Comment by Mcphere** [comment]
Here is how I oprate:
1. GIS -> import -> Georeferenced raster
2. Choose the tif contains the absolute elevation. The raster contains only one grayscale channel.
3. Set mode as "Basemap on a new plane"
4. Since the original projection is WGS84, so I set the CRS as "WGS84 latlon" (now the plane is totally blank)
5. However, I want the coordinate to be more easy to understand, "meter" is better than "degree" for my future works. So I delete the plane and import the raster again. This time I set "CRS" in "Scene georeferencing" as "Web Mercator".
Now the area of the plane looks right, distence measure  is right, but texture is white, and there is no bump. I upload the terrain raster, you can try to import it.
[terrain_raster.zip](https://github.com/domlysz/BlenderGIS/files/4367686/terrain_raster.zip)

**Comment by domlysz** [comment]
> 3. Set mode as "Basemap on a new plane"

This is where your wrong, you must select one of the 2 mode that I highlighted in my previous post.

Please read carefully the wiki, It's all explained. It's not fair to me if your are asking for documented things.

https://github.com/domlysz/BlenderGIS/wiki/Import-DEM-grid
https://github.com/domlysz/BlenderGIS/wiki/Import-georef-raster

**Comment by Mcphere** [comment]
OMG...I dont know how I ignored the "DEM raw data build" option. It was my carelessness. Problem solved, much obliged!
