### ISSUE TITLE
WGS84 maybe not working...

### ISSUE THREAD

**Issue by tarnis** [domlysz/BlenderGIS#307]
Trying to merge this into a visual database created for a simulator in Presagis Creator along with terrain generated by another tool from the simulators manufacturer...I need the two to match up as that tool also generated files for depths, and radar in WGS-84 projection with a specific lat/long for the origin.

# **Blender and OS versions**
2.82 Windows 64 bit

# **Describe the bug**
Model is being distorted when I try importing WGS-84 projection

# **How to Reproduce**
I hit the Space bar in the map view and change CRS to WGS84, and enter the lat/long to match the origin of my terrain which is generated by another tool that I need to use as it generates other files for depths and radar as well.  When I hit OK I no longer see a map.  If I hit E though it does export a map and I can see it again.

So I go and import my .OSM file the map 'disappears, and I get a weirdly distorted bunch of polys that look something like this:

![image](https://user-images.githubusercontent.com/22822314/78076823-c6f79d00-736c-11ea-9350-64125886d4c7.png)

# **Error message**

**Comment by tarnis** [comment]
I hope this helps some, but this is the terrain I'm trying to match up to.  

WGS 84, Origin:
![image](https://user-images.githubusercontent.com/22822314/78077804-a4668380-736e-11ea-96d6-9027ef48f5f0.png)

[terraindepth.zip](https://github.com/domlysz/BlenderGIS/files/4411712/terraindepth.zip)

**Comment by domlysz** [comment]
Unfortunatly for various reason it's generally not recommended to work in WGS84 in Blender.
[See FAQ](https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-after-the-import-of-my-data-the-resulting-mesh-is-extremely-small-on-x-and-y-axis-but-seems-correct-on-z-axis-)

I think I'will disable this default CRS because it suggests that there is nothing wrong with it.

**Comment by tarnis** [comment]
Is there a way outside of blender to convert a model?  Presagis creator
doesn't support web Mercator at all.

**Comment by tarnis** [comment]
I was walking...took a better read and I get what you're saying.  Before I close the book here, hoping maybe you can help?  I've never really delt with much of this in Creator...  

First is Web Mercator now my only option?  That and WGS84 are all that are in the dropdown.

Would any of these work?  and how would I get the data over to one of these projections if possible:
![image](https://user-images.githubusercontent.com/22822314/78091534-bd812b80-7392-11ea-9b59-88a923cb85d2.png)

![image](https://user-images.githubusercontent.com/22822314/78091593-eef9f700-7392-11ea-886b-e7e99e38368c.png)

Thanks again!
Matt

**Comment by domlysz** [comment]
You can add new CRS to the dropdown, you just need to know its EPSG code. 
Read the wiki : https://github.com/domlysz/BlenderGIS/wiki/Georeferencing-management#geoscene-management

The EPSG database is a public registry of CRS, almost every software who need to deal with geographic data use EPSG code as projection identifier. But it seems Presagis does not support this... That will make the task harder.

I think UTM can be a good start, each UTM zone has it's corresponding ESPG code. 326xx for north hemisphere and 327xx for south, where xx is the zone number from 1 to 60. You must fist determine whats your UTM zone : https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system

Then check the parameters of the projection, for example : https://epsg.io/32631 and try to fill the corresponding values in Presagis

**Comment by tarnis** [comment]
Thankyou...some hardcore elipsoid gymnastics on the creator side to the likes of which I've never done before but in the end voila!  Perfect-o
![image](https://user-images.githubusercontent.com/22822314/78134778-4a090980-73e6-11ea-9b31-7a24c319c105.png)

From a usability standpoint, rather then the plus on the side, would it be possible to just have "Add New" as a menu option?  Not sure if it interferes with how blender would be able to handle things but it might be a bit clearer.  

Very amazing stuff!  Glad I found this, was in the process of reverse engineering the same process in a much more pain in the neck fashion.  Blender has scared the hell out of me for years but finally managing to embrace it in our new stay at home world :)
