### ISSUE TITLE
Devision by zero

### ISSUE THREAD

**Issue by Dampfwalze** [domlysz/BlenderGIS#308]
Blender 2.82 Win10 64bit

It is only a devision by zero error in script io_import_osm.py on line 233 where the length of the array that was created one line before could possibly be 0. 

I got this issue when i was trying to import the OSM data with the elevation of Object setting. (I choose all import possibilities) 

I don't have the Error message anymore, because I made a little fix by my self, by adding a condition for when the value is 0.

a quick fix would be nice!

**Comment by Dampfwalze** [comment]
I forgot to say, that I wanted to get the data from Sydney (I don't know, if this information could realy reproduce the bug, but it is worth to say)

**Comment by domlysz** [comment]
Thanks for report, it's fixed now b3fcedd4a2f540f94bc79e47422daabd36562911
