### ISSUE TITLE
Traceback error(s) when trying to enable

### ISSUE THREAD

**Issue by Mustemynd** [domlysz/BlenderGIS#309]
# **Blender and OS versions**

Blender Version: 2.82 | Operating system: Darwin-18.7.0-x86_64-i386-64bit

# **Describe the bug**

Greetings, 

I'm getting the following Traceback Error messages (as shown in attached image)
![Traceback_err](https://user-images.githubusercontent.com/63205735/78506809-ef283700-7784-11ea-92d2-10bce86b3857.jpg)
 when trying to activate addon (right after installation - never worked)

Please advice,
Thank you.

# **How to Reproduce**

# **Error message**

**Comment by domlysz** [comment]
First sentence of the homepage :

> Mac users warning : currently the addon does not work on Mac with Blender 2.80 to 2.82. Please do not report the issue here, it's already solved with Blender 2.83.

**Comment by Mustemynd** [comment]
Thank you for the quick reply. Didn't find anything relevant on a fast search i performed.
