### ISSUE TITLE
Report Error

### ISSUE THREAD

**Issue by ValentinFleckenstein** [domlysz/BlenderGIS#311]
Reports error when trying to activate the plugin
<img width="649" alt="Bildschirmfoto 2020-04-07 um 04 30 08" src="https://user-images.githubusercontent.com/55495095/78623737-9fcb2f00-7888-11ea-93ff-e8cc83be2414.png">

**Comment by mithilp** [comment]
Got the same thing

**Comment by domlysz** [comment]
![image](https://user-images.githubusercontent.com/5639024/78707490-f8460f00-7910-11ea-9caf-c341e398d033.png)
