### ISSUE TITLE
Weird GeoTiff import

### ISSUE THREAD

**Issue by anaezes** [domlysz/BlenderGIS#312]
Hi,

I'm trying to import the attached geotiff (area_of_interest.zip) so that I can convert it into glb but I get an object with weird geometry.

![area_of_interest](https://user-images.githubusercontent.com/17862764/78812303-179d7480-79c3-11ea-904c-43eb84c714c7.png)

[area_of_interest.tif.zip](https://github.com/domlysz/BlenderGIS/files/4451796/area_of_interest.tif.zip)

I have tried with other and everything seems correct.

Thank you.

**Comment by domlysz** [comment]
No projection system & bad unit, see [FAQ](https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-after-the-import-of-my-data-the-resulting-mesh-is-extremely-small-on-x-and-y-axis-but-seems-correct-on-z-axis-)
