### ISSUE TITLE
Get SRTM doesn't read elevation data no matter what server

### ISSUE THREAD

**Issue by LexvdN** [domlysz/BlenderGIS#318]
# **Blender and OS versions**

Blender 2.82 (sub 7)
Windows 10, version 1909

# **Describe the bug**

Using the Get SRTM menu option gives an error message after several seconds. No difference in using OpenTopography or Marine-geo.org as server. Also no difference when choosing another part of the world or another computer.

# **How to Reproduce**

Search for (e.g.) Mount Buller Australia after choosing GIS-module - Web Geodata - Basemap. Zoom factor 15. Then choose GIS - Web Geodata - Get SRTM.
[bgis.log](https://github.com/domlysz/BlenderGIS/files/4497122/bgis.log)

# **Error message**

DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (16188197.446351776, -4498711.008598304, 16309426.573212067, -4430376.305311357)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:28 tiles requested, 28 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.io_get_srtm:95:http://www.marine-geo.org/services/GridServer?west=145.36909377219453&east=146.60356246605403&south=-37.441974065367006&north=-36.87762059977353&layer=topo&format=geotiff&resolution=high
ERROR:BlenderGIS-master:74:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\lex\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\lex\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute
    fillNodata = False)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties:  enum "EPSG:4326" not found in ('EPSG:3857')

**Comment by domlysz** [comment]
duplicate #316, please reinstall the addon i've just fixed it

**Comment by LexvdN** [comment]
Thanks for your swift reply!

 

Removed the addon, downloaded it again from github and reinstalled it. Unfortunately: the same error.

I even uninstalled Blender, restarted the computer en installed Blender from scratch and the addon. No joy. This is in the log file:

 

DEBUG:BlenderGIS-master.core.checkdeps:9:GDAL Python binding unavailable

DEBUG:BlenderGIS-master.core.checkdeps:20:PyProj unavailable

DEBUG:BlenderGIS-master.core.checkdeps:31:Pillow unavailable

DEBUG:BlenderGIS-master.core.checkdeps:46:ImageIO Freeimage plugin available

DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-124138625.90493649, -69974736.16583431, 124138625.90493649, 69974736.16583431)

DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 1 already in cache, 34 remains to download

DEBUG:BlenderGIS-master.operators.lib.osm.nominatim:26:Nominatim search request : https://nominatim.openstreetmap.org/search?format=json&q=mount+buller&limit=10

DEBUG:BlenderGIS-master.operators.view3d_mapviewer:1010:Nominatim search results : ['Mount Buller, Mt Buller Village, Victoria, Australia', 'Mount Buller, Victoria, 3723, Australia', 'Mt Buller, Athletes Walk, Mount Buller, Mt Buller Village, Victoria, Australia']

DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (16181603.328377184, -4526553.370152362, 16424061.582097761, -4389883.963578466)

DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:28 tiles requested, 28 already in cache, 0 remains to download

DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (16128709.144783434, -4532056.811558612, 16371167.398504011, -4395387.404984716)

DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:28 tiles requested, 28 already in cache, 0 remains to download

DEBUG:BlenderGIS-master.operators.io_get_srtm:95:http://opentopo.sdsc.edu/otr/getdem?demtype=SRTMGL3&west=144.84175003250107&east=147.3066874904009&south=-37.72059032102954&north=-36.595889147757624&outputFormat=GTiff

ERROR:BlenderGIS-master:74:Uncaught exception

Traceback (most recent call last):

  File "C:\Users\lex\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke

    return self.execute(context)#context.window_manager.invoke_props_dialog(self)

  File "C:\Users\lex\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute

    fillNodata = False)

  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 199, in __call__

    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)

TypeError: Converting py args to operator properties:  enum "EPSG:4326" not found in ('EPSG:3857')

DEBUG:BlenderGIS-master.operators.io_get_srtm:95:http://www.marine-geo.org/services/GridServer?west=144.84175003250107&east=147.3066874904009&south=-37.72059032102954&north=-36.595889147757624&layer=topo&format=geotiff&resolution=high

ERROR:BlenderGIS-master:74:Uncaught exception

Traceback (most recent call last):

  File "C:\Users\lex\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke

    return self.execute(context)#context.window_manager.invoke_props_dialog(self)

  File "C:\Users\lex\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute

    fillNodata = False)

  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 199, in __call__

    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)

TypeError: Converting py args to operator properties:  enum "EPSG:4326" not found in ('EPSG:3857')

 

As you can see, also tried another server.

Kind regards,

Lex

 

Van: domlysz <notifications@github.com> 
Verzonden: zaterdag 18 april 2020 19:31
Aan: domlysz/BlenderGIS <BlenderGIS@noreply.github.com>
CC: LexvdN <lexvdn@icloud.com>; Author <author@noreply.github.com>
Onderwerp: Re: [domlysz/BlenderGIS] Get SRTM doesn't read elevation data no matter what server (#318)

 

duplicate #316 <https://github.com/domlysz/BlenderGIS/issues/316> , please reinstall the addon i've just fixed it

**Comment by domlysz** [comment]
go to the addon preferences and under spatial ref system click the button reset
![reset](https://user-images.githubusercontent.com/5639024/79669589-d4aa8080-81bc-11ea-8929-f1153fac91ba.jpg)

**Comment by LexvdN** [comment]
Hi,

 

That didn’t help either. But… In your screenshot I saw that you use WGS84 as Spatial Reference System which uses EPSG:4326. 

In the log file I saw the line:

TypeError: Converting py args to operator properties:  enum "EPSG:4326" not found in ('EPSG:3857')

 

My BlenderGIS Preferences says it uses Web Mercator as spatial reference system, which uses EPSG:3857. So I added WGS84 as spatial reference system and selected that one, which did the trick!

 

Thanks for your help. Maybe you can use this explanation somehow.

 

Kind regards,

Lex

 

Van: domlysz <notifications@github.com> 
Verzonden: zaterdag 18 april 2020 21:38
Aan: domlysz/BlenderGIS <BlenderGIS@noreply.github.com>
CC: LexvdN <lexvdn@icloud.com>; Author <author@noreply.github.com>
Onderwerp: Re: [domlysz/BlenderGIS] Get SRTM doesn't read elevation data no matter what server (#318)

 

go to the addon preferences and under spatial ref system click the button reset
 <https://user-images.githubusercontent.com/5639024/79669589-d4aa8080-81bc-11ea-8929-f1153fac91ba.jpg>
