### ISSUE TITLE
Vertice coordinates incorrect?

### ISSUE THREAD

**Issue by jimmy82** [domlysz/BlenderGIS#322]
Blender 2.82

I imported OSM building shapefile with WGS84 Lat/Lon projection. I then proceed to extract each shape vertices using Python script. I notice the coordinates are in a different coordinate system.

Is this the default or could be addressed by correcting BlenderGIS settings?

Also, when re-exporting modified building shapefile with textures as gITF format, is there any way to set back the original WGS84 Lat/Lon projection system?

Thanks.

**Comment by domlysz** [comment]
Depending on how you setup the scene coordinate system, imported data can be reproject accordingly. Especially, if you have loaded some basemaps which are most of case in Web Mercator projection, then the scene will be automatically setup to this projection.

Futhermore to compute the true coordinates you need to take the scene offset properties into account (ie the coordinate of the center of the scene in its projection system)

More information on how georeferencing is handle by the addon : https://github.com/domlysz/BlenderGIS/wiki/Georeferencing-management

Also working directly with longitude/latitude is not a good practice and may cause lot of trouble. See the [FAQ](https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-after-the-import-of-my-data-the-resulting-mesh-is-extremely-small-on-x-and-y-axis-but-seems-correct-on-z-axis-).

Web Mercator is also not a good choice if you need precision.

**Comment by jimmy82** [comment]
Thanks for the explanation!
