### ISSUE TITLE
Satellite raster not included in gITF export file.

### ISSUE THREAD

**Issue by jimmy82** [domlysz/BlenderGIS#329]
Blender 2.82

Can I get some advise on why the satellite raster (pulled automatically by OSM) is not found in gITF export file?

The building shape and textures appear in the gITF export file though.

Thanks.

**Comment by domlysz** [comment]
I don't know never trying this kind of export, are you sure this image is a mesh and not a reference image. If the image come from the basemaps addon, you need to press E to convert it to a new textured plane mesh. Anyway, it's a bit off topic here, please ask  blender.stackexchange if you need more help.
