### ISSUE TITLE
Problem importing raster DEM

### ISSUE THREAD

**Issue by Wiscmapper** [domlysz/BlenderGIS#33]
I highly doubt this is a bug, but I hope somebody can give me guidance.  When I attempt to import a 16-bit raster DEM in tif format, I get very unusual results.  See graphic at this link:
http://www.sco.wisc.edu/images/stories/download/blender2.png

However, the DEM looks as expected in QGIS:
http://www.sco.wisc.edu/images/stories/download/qgis.png

The process I used in Blender after installing BlenderGIS: file... import... georeferenced raster... Mode as DEM.  Did not apply on an existing mesh.

Any thoughts on where I am going wrong?  The process to import a DEM seems very straightforward.

**Comment by domlysz** [comment]
Can you join me the file ? it must be work...

Anyway you can try to cast the data type to float 32. It's easiest in Blender to deal with float32 raster than 16bits, especially signed 16 bits raster must be converted to float by the script which is slow.

**Comment by Wiscmapper** [comment]
Browse to the following location:

http://www.sco.wisc.edu/images/stories/download/dem/

44w090_13.tif = Float32
44w090_13_16bit.tif = UInt16

I have not tried the Float32 file yet, but I will do so now.  Thanks for the suggestion, I rarely working with floating point elevation data.

**Comment by domlysz** [comment]
It seems Blender cannot correctly open this tiff, don't know why. If I try to open it directly in Blender I can see lot of glitch.

![selection_005](https://cloud.githubusercontent.com/assets/5639024/16843703/acb9547c-49e2-11e6-911e-95dd45abe232.jpg)

After just re-exporting the tiff with QGIS, it work.

Also remember Blender is not designed to handle large data like a GIS software. I was able to import that file but it's really slow on my machine. You must consider to crop or resample the file beforehand to get something more usable

**Comment by Wiscmapper** [comment]
I was able to get the Float32 version to load without any problems.  I likely need to change my expectations of what Blender can do for rendering large areas.

Thanks for your assistance.

**Comment by domlysz** [comment]
You're welcome.
