### ISSUE TITLE
Where is "Angular coords" option?

### ISSUE THREAD

**Issue by ForceConstant** [domlysz/BlenderGIS#332]
# **Blender and OS versions**
2.82

# **Describe the bug**
There are a few wiki pages that state: "All import/export tools provide an option named Angular coords", though I don't see that option. 

# **How to Reproduce**
I am trying to import as a DEM, a file that the units are degrees, but comes blenderGIS needs meters. I don't see that option.
![image](https://user-images.githubusercontent.com/26015318/81965291-d9106080-95e5-11ea-937a-d4341f80e3dc.png)

# **Error message**
None.

**Comment by domlysz** [comment]
This option does not exists anymore. You need to determine what is the better projection system for you area of interest and reproject you data beforehand. You can also set  a projection system for a scene and then import the data specifying WGS84 as input coordinate system, but by default the reprojection is computed through a web service, so it's slow. Working directly in degrees is not very useful at all and have lot of side effects (see FAQ)
