### ISSUE TITLE
error with get SRTM

### ISSUE THREAD

**Issue by ChronosUnHold** [domlysz/BlenderGIS#334]
**blender version:** 2.82
**OS:** windows 10 64

the error doesn't let me get the SRTM, I click on GIS -> Web Geodata -> Get SRTM and the error shown is in the picture.

# **Error message**
TypeError: bpy_struct: item.attr = val: enum "Non-Color" not found in ('AppleP3 Filmic Log Encoding', 'AppleP3 sRGB OETF', 'BT.1886 EOTF', 'BT.1886 Filmic Log Encoding', 'Filmic Log Encoding', 'Linear', 'Non-Colour Data', 'sRGB OETF')

location: D:\universita terzo anno\programmi per universita\Blender\2.82\scripts\modules\bpy\ops.py:199

![Screenshot (93)](https://user-images.githubusercontent.com/65681537/82490102-09269a80-9ae3-11ea-83ff-923c2f5899e5.png)

**Comment by domlysz** [comment]
duplicate #268
