### ISSUE TITLE
SRT cannot open, but download OSM roads and buildings works.

### ISSUE THREAD

**Issue by gabarh** [domlysz/BlenderGIS#335]
bpy.ops.object.delete(use_global=False, confirm=False)
Deleted 1 object(s)
Please define a valid cache folder path in addon's preferences
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\startup\bl_operators\userpref.py", line 773, in execute
    shutil.rmtree(path)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ruxan\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\BlenderGIS-master\\bgis.log'

location: <unknown location>:-1

bpy.context.space_data.system_folders_active = 0
Modules Installed () from 'C:\\BLENDER SCRIERE\\BlenderGIS-master.zip' into 'C:\\Users\\ruxan\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons'
bpy.context.space_data.system_folders_active = 0
bpy.ops.object.delete(use_global=False, confirm=False)
Deleted 2 object(s)
bpy.ops.view3d.map_start(src='OSM', dialog="MAP")
bpy.ops.view3d.map_start(src='OSM', grd='WM', lay='MAPNIK', dialog="MAP", query="londra", zoom=13)
Cannot reach OpenTopography web service, check logs for more infos
Cannot reach OpenTopography web service, check logs for more infos
Please define the query extent in orthographic top view or by selecting a reference object
bpy.ops.object.shade_smooth()
bpy.ops.object.shade_flat()
bpy.context.space_data.shading.type = 'MATERIAL'
bpy.context.space_data.context = 'MODIFIER'
Cannot reach OpenTopography web service, check logs for more infos
Cannot reach OpenTopography web service, check logs for more infos

**Comment by gabarh** [comment]
![1](https://user-images.githubusercontent.com/65650891/82544995-a83ca800-9b5e-11ea-9cb5-719f4c410262.JPG)

**Comment by gabarh** [comment]
Please help!

**Comment by domlysz** [comment]
#305
