### ISSUE TITLE
log file premission error

### ISSUE THREAD

**Issue by johan2857** [domlysz/BlenderGIS#336]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

![Captura](https://user-images.githubusercontent.com/65795413/82718258-12d90b00-9c67-11ea-97a6-bf66ae31c6b0.PNG)

**Comment by johan2857** [comment]
No se porque no me deja utilizarlo y me sale ese error

**Comment by domlysz** [comment]
Do you really expect for help without making the effort to write in english? This not my native tong too but spanish even less...

**Comment by domlysz** [comment]
Should be fixed as the logs are now written in the home directory
