### ISSUE TITLE
Questions on automized georef render and getting 3D coordinates

### ISSUE THREAD

**Issue by qiyan98** [domlysz/BlenderGIS#340]
# **Blender and OS versions**
Blender v2.83.0
Ubuntu 18.04

# **Describe the bug**
This is **not** really a bug but I stick with the template to avoid being removed. 

I'd like to know if BlenderGIS supports python code for automatic georef render, given a set of camera poses and parameters. This of interest to efficiently generate a large number of images. 

Another question is if BlenderGIS supports getting 3D coordinates (e.g. longitude, latitude and height) for each pixel in case of georef render. The coordinates could be dependent on terrain model. Some other tools like Cesium Ion can do this, but its accuracy is not very reliable.

For these questions, I cannot find much descriptions in the Wiki page so I am asking here. Thanks for your understanding.

# **How to Reproduce**

# **Error message**

**Comment by domlysz** [comment]
Hi,

> I'd like to know if BlenderGIS supports python code for automatic georef render, given a set of camera poses and parameters. This of interest to efficiently generate a large number of images.

No, you must create your own script to do this

>  is BlenderGIS supports getting 3D coordinates (e.g. longitude, latitude and height) for each pixel in case of georef render.

The operator used to setup a new georender camera also create a worldfile giving all the parameters for computing pixel coordinnates (in 2D only) : https://github.com/domlysz/BlenderGIS/wiki/Make-a-georef-render
If needed you can then resuse this Python classe : https://github.com/domlysz/BlenderGIS/blob/master/core/georaster/georef.py

**Comment by qiyan98** [comment]
Thanks for your helpful response!
