### ISSUE TITLE
how to make a square map

### ISSUE THREAD

**Issue by samuelbrunner** [domlysz/BlenderGIS#342]
simple question about how to make a square map

**Comment by domlysz** [comment]
be more precise, what is the functionnality you're talking about? If it's about the basemap operator, the extent of the request is defined by the 3d window

**Comment by samuelbrunner** [comment]
> 
> 
> be more precise, what is the functionnality you're talking about? If it's about the basemap operator, the extent of the request is defined by the 3d window

hello, i added a cube as reference and scaled the 3d window, however, the size of the 3d window has to be a bit widther than the reference cube to have a square result.
