### ISSUE TITLE
How to import characters in KML into blender GIS

### ISSUE THREAD

**Issue by vikingsailor** [domlysz/BlenderGIS#343]
How to import characters in KML into blender GIS? I use global mapper to convert points and lines into shp files, which can be imported into blender GIS, but characters cannot be imported. Is there any other way

**Comment by domlysz** [comment]
what do you mean by _characters_ ?

**Comment by vikingsailor** [comment]
![QQ截图20200614092104](https://user-images.githubusercontent.com/21963831/84582634-3f74e280-ae21-11ea-9d57-cc51a598dcee.jpg)
![QQ截图20200614092424](https://user-images.githubusercontent.com/21963831/84582640-4865b400-ae21-11ea-92b6-0fe1fb72d4c5.jpg)


Yes, I want to add the name of the placemark file in the kml file to blender. Currently I can only import coordinates into blendergis

**Comment by domlysz** [comment]
If the names are correctly reported as shapefile attributes data by the conversion process, then after the import, you can retreive these data in Blender as object's custom properties. Also, when importing a shapefile you can check the option "separate object" and then the option "object name from field" to automatically name each object using attributes data from a specified field.

however if you want to automatically labelling each objects with the object name or some custom properties, this fonctionnalty is not implemented in the BlenderGIS addon. The only workaround is to check the option 'viewport display name' in the object properties. But the style of the text is not settable  and there is no callout line.

![image](https://user-images.githubusercontent.com/5639024/85112970-ce656e80-b216-11ea-8446-ff48f4015320.png)
