### ISSUE TITLE
Wrong size in blender

### ISSUE THREAD

**Issue by discodzen** [domlysz/BlenderGIS#346]
# **Blender and OS versions**
Windows 8.1 Blender 2.83

# **Describe the bug**
<a target="_blank" href="http://radikal.ru/big/12e2piz6phkbq"><img src="https://c.radikal.ru/c11/2006/d4/661348a01044.jpg" ></a>

# **How to Reproduce**

# **Error message**

**Comment by domlysz** [comment]
https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-my-measurements-on-basemaps-reference-seems-wrong-
