### ISSUE TITLE
A lot of empties with images in outliner

### ISSUE THREAD

**Issue by romkas27** [domlysz/BlenderGIS#349]
Blender 2.8, 2,83, 2,9 / Windows 10
***
A lot of empties with images appear in outliner during navigation in basemap mode.  I have been using your addon for a very long time but never noticed it. Is it correct? Can I disable it because it is useless data that should be deleted?
***
![Blender_GIS_outliner](https://user-images.githubusercontent.com/42959731/85945501-84e8f200-b981-11ea-993d-14fa83245f49.jpg)

**Comment by domlysz** [comment]
Cannot reproduce this issue

**Comment by romkas27** [comment]
Can I upload my blender file for you? So this is incorrect? Earlier I had only one empty ((

**Comment by domlysz** [comment]
yes this is incorrect, don't know what's wrong so you can send me the blend file however I'm not sure if it will give me a clue

**Comment by romkas27** [comment]
I sent you a file with errors but addon is working well. Error in my startup file but I can`t understand what exactly causes the error.
I went to C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.90\config and delete STARTUP.blend. Then start Blender and now addon is working correctly.
But what I made uncorrectly I don`t know.

**Comment by romkas27** [comment]
))))))) I finally understood what I doing wrong - I like to pack all textures into blender file so I save startup file with this setting (External Data - Automatically pack into Blend.file) - so Blender save each downloading picture as a texture during my navigation )))) just uncheck this box and everything will be OK
Now we know the answer ))

**Comment by domlysz** [comment]
good to know !
