### ISSUE TITLE
Import Shapefile with elevation

### ISSUE THREAD

**Issue by afloramaps** [domlysz/BlenderGIS#350]
Hello people,

I'm new to blender. I use the Blender Gis Add-on. I can generate a 3D model with the satellite image and the SRTM image. But I would like to put thematic maps (flora, fauna, rocks and others) on top using shapefiles that I have. How do I do that?

**Comment by domlysz** [comment]
https://github.com/domlysz/BlenderGIS/wiki/Shapefile-import
