### ISSUE TITLE
PNG import fails with no error in logs

### ISSUE THREAD

**Issue by Overruler** [domlysz/BlenderGIS#352]
# **Blender and OS versions**
version: 2.83.1, branch: master, commit date: 2020-06-25 09:47, hash: 8289fc688b3e, type: Release
build date: 2020-06-25, 08:30:56
Windows 10 version 2004 (OS Build 19035.1)

# **Describe the bug**

Trying to import a PNG file from the addon fails with message suggesting to see the logs for more information. However, there are no error messages in the bgis.log file:
INFO:BlenderGIS-master:76:###### Starting new Blender session : 2020-06-30 17:54:24
DEBUG:BlenderGIS-master.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:31:Pillow unavailable
DEBUG:BlenderGIS-master.core.checkdeps:46:ImageIO Freeimage plugin available

Having worked around this bug earlier, I happen to know that this bug is caused by the addon trying to load a .wld file that is not found, and then crashing. If there is no .wld file to accompany the .png file, the addon could pretend a trivial .wld should be used instead:
1
0
0
-1
0
0
This would be fine, as it's the best the user could do anyway when there is no .wld file.

# **How to Reproduce**

1) Click GIS->Import->Georeferenced raster (.tif .jpg .jp2 .png)
2) In the file selection dialog, navigate to a folder which contains 1 PNG file only.
3) Select the only file (the png file) in the folder and click "Import georaster" button.
4) Observe that the status line displays in red the message "Unable to open raster, check logs for more infos".

# **Error message**

"Unable to open raster, check logs for more infos"

There is no more information.

**Comment by geoendemics** [comment]
I have the same use after installing blender 2.90. 1 on on  ubuntu 18 machine.
Read prefs: /home/home/.config/blender/2.90/config/userpref.blend
/run/user/0/snap.blender/gvfs/ non-existent directory
found bundled python: /snap/blender/47/2.90/python
DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:Pillow unavailable
DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available


any idea how to solve this ..?

**Comment by Terkwood** [comment]
I was trying to do the same with a geo-referenced JPG file that did not include a matching WLD file.

So for `myimage.jpg` I created a six-line `myimage.wld` file which matches the data suggested by @Overruler:

```text
1
0
0
-1
0
0
```

This worked for me!  Thanks for posting the workaround.

**Comment by domlysz** [comment]
To be clear, there is no issue here. The purpose of the georaster operator is to import a georeferenced image. The only way to georeference a png or jpg is with a worldfile, so if the worldfile is missing it's perfectly normal that the import fails. Writing a `1 0 0 -1 0 0` wordfile is non-sense because the georefencing parameters do not match the true picture geolocation. This is pointless as you can import a non-georef image as you want in Blender (menu > add > image). 

The proposed fix improve the error message as the backtrace was't correctly reported to the logs file.
