### ISSUE TITLE
Problème import shp web mercator

### ISSUE THREAD

**Issue by jdarras** [domlysz/BlenderGIS#353]
Bonjour,

Impossible d'importer un shp avec la projection web mercator, le calque s'importe bien mais il a une dimension de 0 en X,Y,Z. Avez-vous une dée du problème que je peux rencontrer ?
Je suis sur la version Blender 2.83

Merci
Julien D.

**Comment by domlysz** [comment]
Possible d'avoir le shp ?

**Comment by jdarras** [comment]
Bonjour Domlysz,

Vous pouvez trouver le shp en pièce jointe. Je travaille avec des fichiers natural earth, avec la projection WGS84 EPSG 4326 que j’exporte en shp avec la projection Web mercator 3857. Impossible d’ouvrir ces fichiers, je ne sais pas pourquoi. 

Voici également l’intégralité de ma console :

Read prefs: C:\Users\Julien\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.83\2.83\python
DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding available
DEBUG:BlenderGIS-master.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:Pillow unavailable
DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
measureit_arch: Imported multifiles
Warning: class CAMERA_OT_add_pixel_res_preset contains a property which should be an annotation!
C:\Users\Julien\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MeasureIt-ARCH-83853e4acd32c2cf1dda8cb1e5a4804616c96061\auto_load.py:28
    assign as a type annotation: CAMERA_OT_add_pixel_res_preset.name
    assign as a type annotation: CAMERA_OT_add_pixel_res_preset.remove_active
register_class(...):
Warning: 'CAMERA_PAPER_SCALE_Presets' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'CAMERA_PX_SCALE_Presets' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'CAMERA_PX_Presets' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'MeasureitArchRenderPanel' doesn't contain '_PT_' with prefix & suffix
Warning: class CAMERA_OT_add_paper_res_preset contains a property which should be an annotation!
C:\Users\Julien\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MeasureIt-ARCH-83853e4acd32c2cf1dda8cb1e5a4804616c96061\auto_load.py:28
    assign as a type annotation: CAMERA_OT_add_paper_res_preset.name
    assign as a type annotation: CAMERA_OT_add_paper_res_preset.remove_active
Warning: class CAMERA_OT_add_paper_scale_preset contains a property which should be an annotation!
C:\Users\Julien\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MeasureIt-ARCH-83853e4acd32c2cf1dda8cb1e5a4804616c96061\auto_load.py:28
    assign as a type annotation: CAMERA_OT_add_paper_scale_preset.name
    assign as a type annotation: CAMERA_OT_add_paper_scale_preset.remove_active
Warning: class CAMERA_OT_add_pixel_scale_preset contains a property which should be an annotation!
C:\Users\Julien\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MeasureIt-ARCH-83853e4acd32c2cf1dda8cb1e5a4804616c96061\auto_load.py:28
    assign as a type annotation: CAMERA_OT_add_pixel_scale_preset.name
    assign as a type annotation: CAMERA_OT_add_pixel_scale_preset.remove_active
register_class(...):
Warning: 'CAMERA_PAPER_Presets' doesn't contain '_MT_' with prefix & suffix
Info: Deleted 1 object(s)

INFO:BlenderGIS-master.operators.io_import_shp:Read shapefile...
INFO:BlenderGIS-master.operators.io_import_shp:Feature type : Polygon
DEBUG:BlenderGIS-master.operators.io_import_shp:DBF fields : ['scalerank', 'featurecla', 'LABELRANK', 'SOVEREIGNT', 'SOV_A3', 'ADM0_DIF', 'LEVEL', 'TYPE', 'ADMIN', 'ADM0_A3', 'GEOU_DIF', 'GEOUNIT', 'GU_A3', 'SU_DIF', 'SUBUNIT', 'SU_A3', 'BRK_DIFF', 'NAME', 'NAME_LONG', 'BRK_A3', 'BRK_NAME', 'BRK_GROUP', 'ABBREV', 'POSTAL', 'FORMAL_EN', 'FORMAL_FR', 'NAME_CIAWF', 'NOTE_ADM0', 'NOTE_BRK', 'NAME_SORT', 'NAME_ALT', 'MAPCOLOR7', 'MAPCOLOR8', 'MAPCOLOR9', 'MAPCOLOR13', 'POP_EST', 'POP_RANK', 'GDP_MD_EST', 'POP_YEAR', 'LASTCENSUS', 'GDP_YEAR', 'ECONOMY', 'INCOME_GRP', 'WIKIPEDIA', 'FIPS_10_', 'ISO_A2', 'ISO_A3', 'ISO_A3_EH', 'ISO_N3', 'UN_A3', 'WB_A2', 'WB_A3', 'WOE_ID', 'WOE_ID_EH', 'WOE_NOTE', 'ADM0_A3_IS', 'ADM0_A3_US', 'ADM0_A3_UN', 'ADM0_A3_WB', 'CONTINENT', 'REGION_UN', 'SUBREGION', 'REGION_WB', 'NAME_LEN', 'LONG_LEN', 'ABBREV_LEN', 'TINY', 'HOMEPART', 'MIN_ZOOM', 'MIN_LABEL', 'MAX_LABEL']
0%, 10%, 20%, 30%, 40%, 50%, 60%, 70%, 80%, 90%, 100%
INFO:BlenderGIS-master.operators.io_import_shp:Build in 2.085824 seconds
ERROR:BlenderGIS-master:Uncaught exception
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\BlenderGIS-master\operators\io_import_shp.py", line 736, in execute
    adjust3Dview(context, bbox)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\BlenderGIS-master\operators\utils\bgis_utils.py", line 84, in adjust3Dview
    dst = round(max(bbox.dimensions))
ValueError: cannot convert float NaN to integer
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\BlenderGIS-master\operators\io_import_shp.py", line 736, in execute
    adjust3Dview(context, bbox)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\BlenderGIS-master\operators\utils\bgis_utils.py", line 84, in adjust3Dview
    dst = round(max(bbox.dimensions))
ValueError: cannot convert float NaN to integer

location: C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py:199

location: C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py:199
Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\BlenderGIS-master\operators\io_import_shp.py", line 736, in execute
    adjust3Dview(context, bbox)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\BlenderGIS-master\operators\utils\bgis_utils.py", line 84, in adjust3Dview
    dst = round(max(bbox.dimensions))
ValueError: cannot convert float NaN to integer

location: C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py:199

ERROR:BlenderGIS-master.operators.io_import_shp:Shapefile import fails
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\BlenderGIS-master\operators\io_import_shp.py", line 290, in execute
    extrusionAxis=self.extrusionAxis, separateObjects=self.separateObjects)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\BlenderGIS-master\operators\io_import_shp.py", line 736, in execute
    adjust3Dview(context, bbox)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\BlenderGIS-master\operators\utils\bgis_utils.py", line 84, in adjust3Dview
    dst = round(max(bbox.dimensions))
ValueError: cannot convert float NaN to integer

location: C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py:199


Merci beaucoup pour votre aide.
Cordialement

Julien Darras

**Comment by domlysz** [comment]
La reprojection se fait en amont avec QGIS ou bien directement via BlenderGIS et dans ce dernier cas avec quel moteur de reprojection ?

**Comment by jdarras** [comment]
Bonjour,
Je fais la reprojection avec QGIS. Voici mon fichier shp
[world.zip](https://github.com/domlysz/BlenderGIS/files/4879221/world.zip)

Merci pour ton aide
Julien

**Comment by domlysz** [comment]
Le problème avec la projection Mercator est qu'elle ne permet pas de représenter la latitude 90° car les valeurs tendent vers l'inifini. La reprojection dans QGIS attribue donc la valeur NaN (not a number) aux points trop proches des 90° et ces valeurs NaN font logiquement planter l'addon. Traditionnellement on applique donc un seuil de latitude maximum pour éviter d'avoir à traiter des points retournant des valeurs infinies. Pour la cas de la projection Web Mercator, cette valeur de cutoff n'est pas choisie au hasard, elle est déterminée de façon a voir une projection carré et vaut approximativement 85°

Détail des calculs : https://github.com/domlysz/BlenderGIS/blob/master/core/basemaps/servicesDefs.py#L17

Il faut donc prévoir un traitement préalable pour couper la couche Natural Earth aux latitudes 85 et -85°.

**Comment by jdarras** [comment]
Merci domlysz pour ta réponse, malheureusement j'ai peur de ne pas savoir comment appliquer un seuil de latitude aux fichier shp sur qgis ? 
Je suis un peu perdu, je ne souhaite pas passer par du svg dans illustrator avant de continuer mon workflow via blender vers unreal !

**Comment by domlysz** [comment]
Tu peux utiliser l'outil _clip by extent_

![image](https://user-images.githubusercontent.com/5639024/87036658-743f4400-c1eb-11ea-990c-1cc248438438.png)

**Comment by jdarras** [comment]
Oh ça fonctionne, génial ! Merci beaucoup.
