### ISSUE TITLE
Strange spikes appearing in generated 3D model

### ISSUE THREAD

**Issue by leonardofmed** [domlysz/BlenderGIS#354]
# **Blender and OS versions**

- Blender 2.83
- Windows 10

# **Describe the bug**

When loading a DEM (DSM), some plane areas present strange spikes on them. Even with high steps (30) when loading the DEM as "DEM Raw data build" I can see these spikes. If I load the basemap first and then the DEM as "DEM as displacement texture" the spikes disappear, but the model loses too much detail. I remember that when I used this plugin with this same DEM file, in Blender 2.79 or 2.80, these spikes don't appear. Is this a know issue? Do you have any suggestion on how to fix this?

![spikes](https://user-images.githubusercontent.com/33374703/86472681-ef00ee80-bd15-11ea-8af9-54c26f7da9db.png)
_Here is a image of the generated model with steps = 10 (left) and the older model created in the past with the same plugin and file (right)_

---

I tried with another more recent DSM and the same error persisted. I believe that the problem is related to the reflective surface (pond), however, as I said earlier, this problem did not occur in previous versions.

# **How to Reproduce**
 
- Load a DEM as "DEM Raw data build" with low steps

# **Error message**

- No errors

**Comment by domlysz** [comment]
Are these outlier values exists in the source raster ? you can check this with QGIS for example.

**Comment by leonardofmed** [comment]
Okay, didn't notice this earlier, this is definitely a problem with the raster and maybe it is indeed because of the reflection of the pond. The strangest thing is that older versions didn't create the model with those spikes, at least I don't remember. Well, I can soft this spikes manually with some Blender tools, thank you anyway.
