### ISSUE TITLE
Bigger High Quality Map Selection Possible?

### ISSUE THREAD

**Issue by janausis** [domlysz/BlenderGIS#355]
# **Blender and OS versions**

Windows 10 1909
Blender 2.81.6

# **Describe the bug**

Is it possible to select a big chunk of high quality Satellite data rather than multiple small ones via the basemap so that i could select a bigger part of e.g. a city and have a big high quality selection instead of just the big lower quality selection 

# **How to Reproduce**

# **Error Message**

**Comment by domlysz** [comment]
yes use the L shortcut to lock the zoom as specified in the wiki
https://github.com/domlysz/BlenderGIS/wiki/Basemaps

**Comment by SephReed** [comment]
This doesn't seem to work anymore

**Comment by LaskosVirtuals** [comment]
This function would be useful, but I couldn't get it to work. Does anyone have a workaround?
