### ISSUE TITLE
settings.json permission error

### ISSUE THREAD

**Issue by MaximeDerhore** [domlysz/BlenderGIS#357]
Bonjour à tous,
Je viens d'essayer d'installer BlednerGIS et,
J'ai cette erreur, je ne comprends pas pourquoi.
Merci pour votre aide

![2020-07-06 16_07_47-Blender](https://user-images.githubusercontent.com/52073937/86637206-3059fe00-bfa3-11ea-872c-1771c5595231.png)

**Comment by domlysz** [comment]
Le programme n'arrive pas à écrire le fichier settings.json, soit parce-que vous n'avez pas les droits sur ce dossier soit parce que le fichier est occupé par un autre processus

**Comment by domlysz** [comment]
A présent (v2.2.5) ce fichier ne nécessite plus d'être mis à jour par l'addon, et il n'est donc plus nécessaire d’avoir des droits en écriture. Cette erreur ne devrait donc plus se reproduire.
