### ISSUE TITLE
importing OSM fails

### ISSUE THREAD

**Issue by mirlip** [domlysz/BlenderGIS#36]
Hi Domlysz,
"path to long for windows, overpass request failed" is printed in the console output.
Regards

**Comment by domlysz** [comment]
is it possible to have the blend for testing ?

**Comment by domlysz** [comment]
fixed by s-leger thanks to him 
https://github.com/domlysz/BlenderGIS/commit/d93d789868da56fc0e4275e8c2328650d93a3994

**Comment by mirlip** [comment]
It works awesome :) but I can't zoom in anymore. 
Near clip is left to 0.1, but far clip distance is set to something huge (like 1200000000). Setting it back to something more reasonable like 4km doesn't help.
I started from the default scene and zoomed to a town in Germany (near Basel in the south west corner), then hit escape to quit the map viewer mode and then clicked on import OSM. It worked, but zooming in was impossible, only out was.

**Comment by domlysz** [comment]
it seems you have already an object far away the osm import (maybee the default cube), after the import the scipt adjust the 3d view setting (clip distance & grid floor) so if you have very distant objects then you get huge value for clip end and grid floor scale. Reducing grid floor scale fix the zoom problem but its better to delete unnecessary objects before running basemap

**Comment by mirlip** [comment]
Works really good, thank you. Is there a benefit to change the grid scale (like maybe improved numerical precision) ? It makes all newly added objects really big.
The tag import is really helpful :)
