### ISSUE TITLE
crashing on zoom out, with Blender 2.8.3

### ISSUE THREAD

**Issue by bleve97** [domlysz/BlenderGIS#362]
# **Blender and OS versions**
Blender 2.83.3
Windows 10 pro -  64 bit

When zooming out after zooming in, Blender crashes

My example - 
go to "yering"
zoom in, to eg level 11
zoom out.  Crash.

No error message

Where is the log stored?

**Comment by domlysz** [comment]
# **Error message**

If the addon crash, report here the complete error message. Most of time it will not be possible to solve the issue without any error message.

Error messages are reported into the system console/terminal. However the addon now include a special operator that allows displaying logs directly in Blender.

![bgis_logs](https://user-images.githubusercontent.com/5639024/76417934-123a1380-639e-11ea-8714-61536efabbc2.jpg)

If the addon cannot be enabled, you can check the logs file inside your BlenderGIS folder. Also, Windows users can open the sytem console at any time from the windows menu.

![windows_sys_console](https://user-images.githubusercontent.com/5639024/76417946-16663100-639e-11ea-814c-c023fb49d9eb.jpg)

**Comment by domlysz** [comment]
lack of informations, please comment with logs if you still encounter this issue
