### ISSUE TITLE
GIS get SRTM errors with ACES OCIO

### ISSUE THREAD

**Issue by B4adle7** [domlysz/BlenderGIS#363]
# **Blender and OS versions**
Blender 2.83.3
Windows 10 x64
# **Describe the bug**
Elevation data breaks when ACES OCIO is active.
Recently had been applying and getting used to the ACES OCIO colorspace environment.
When attempting to "get SRTM", application function errors out due to "Non-Color" colorspace no longer is available.
BlenderGIS-master/operators/utils/georaster_utils.py, line 275 in _load
self.bpyImg.colorspace_settings.name = "Non-Color"
TypeError bpy_struct item.attr = val: enum "Non-Color" not found in ('aces", "ACES.... [list of ACES colors spaces]

# **How to Reproduce**
Install ACES.  
Can be downloaded from
https://github.com/colour-science/OpenColorIO-Configs/tree/feature/aces-1.2-config
(Every config version is available, 1.2 is the latest)
Save the config somewhere the computer Blender can access.
Create or set your "OCIO" environment variable to the config of your choice.
e.g.
OCIO = "R:\colorspace\aces_1.2\config.ocio"
Open Blender
Use GIS to locate and set up a landscape.
Attempt to "get SRTM"

# **Error message**
`Error: Traceback (most recent call last):
  File "C:\Users\#\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 44, in invoke
    return self.execute(context)#context.window_manager.invoke_props_dialog(self)
  File "C:\Users\#\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\operators\io_get_srtm.py", line 143, in execute
    fillNodata = False)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\#\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\operators\io_import_georaster.py", line 384, in execute
    grid = bpyGeoRaster(filePath, subBoxGeo=subBox, clip=self.clip, fillNodata=self.fillNodata, useGDAL=HAS_GDAL, raw=True)
  File "C:\Users\#\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\operators\utils\georaster_utils.py", line 259, in __init__
    self._load()
  File "C:\Users\#\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlenderGIS-master\operators\utils\georaster_utils.py", line 275, in _load
    self.bpyImg.colorspace_settings.name = 'Non-Color'
TypeError: bpy_struct: item.attr = val: enum "Non-Color" not found in ('aces', 'ACES - ACES2065-1', 'ACES - ACEScc', 'ACES - ACEScct', 'ACES - ACEScg', 'ACES - ACESproxy', 'acescc', 'acescc_ap1', 'acescct', 'acescct_ap1', 'acescg', 'acesproxy', 'acesproxy_ap1', 'adx10', 'adx16', 'canonlog2_cgamutday', 'canonlog2_cgamuttung', 'canonlog2_rec2020day', 'canonlog2_rec2020tung', 'canonlog3_cgamutday', 'canonlog3_cgamuttung', 'canonlog3_rec2020day', 'canonlog3_rec2020tung', 'canonlog_cgamutday', 'canonlog_cgamuttung', 'canonlog_dcip3day', 'canonlog_dcip3tung', 'canonlog_rec2020day', 'canonlog_rec2020tung', 'canonlog_rec709day', 'canonlog_rec709tung', 'crv_canonlog', 'crv_canonlog2', 'crv_canonlog3', 'crv_dolbypq1000nitsshaper', 'crv_dolbypq108nitsshaper', 'crv_dolbypq2000nitsshaper', 'crv_dolbypq4000nitsshaper', 'crv_dolbypq48nitsshaper', 'crv_dolbypq_10000', 'crv_lmtshaper', 'crv_log21000nitsshaper', 'crv_log2108nitsshaper', 'crv_log22000nitsshaper', 'crv_log24000nitsshaper', 'crv_log248nitsshaper', 'crv_logc3ei800', 'crv_protuneflat', 'crv_rec1886', 'crv_rec2020', 'crv_rec709', 'crv_rl3g10', 'crv_rlf', 'crv_slog1', 'crv_slog2', 'crv_slog3', 'crv_srgb', 'crv_vlog', 'dolbypq1000nitsshaper_ap1', 'dolbypq108nitsshaper_ap1', 'dolbypq2000nitsshaper_ap1', 'dolbypq4000nitsshaper_ap1', 'dolbypq48nitsshaper_ap1', 'g18_rec709', 'g22_rec709', 'Input - ADX - ADX10', 'Input - ADX - ADX16', 'Input - ARRI - Curve - V3 LogC (EI800)', 'Input - ARRI - Linear - ALEXA Wide Gamut', 'Input - ARRI - V3 LogC (EI1000) - Wide Gamut', 'Input - ARRI - V3 LogC (EI1280) - Wide Gamut', 'Input - ARRI - V3 LogC (EI160) - Wide Gamut', 'Input - ARRI - V3 LogC (EI1600) - Wide Gamut', 'Input - ARRI - V3 LogC (EI200) - Wide Gamut', 'Input - ARRI - V3 LogC (EI2000) - Wide Gamut', 'Input - ARRI - V3 LogC (EI250) - Wide Gamut', 'Input - ARRI - V3 LogC (EI2560) - Wide Gamut', 'Input - ARRI - V3 LogC (EI320) - Wide Gamut', 'Input - ARRI - V3 LogC (EI3200) - Wide Gamut', 'Input - ARRI - V3 LogC (EI400) - Wide Gamut', 'Input - ARRI - V3 LogC (EI500) - Wide Gamut', 'Input - ARRI - V3 LogC (EI640) - Wide Gamut', 'Input - ARRI - V3 LogC (EI800) - Wide Gamut', 'Input - Canon - Canon-Log - Cinema Gamut Daylight', 'Input - Canon - Canon-Log - Cinema Gamut Tungsten', 'Input - Canon - Canon-Log - DCI-P3 Daylight', 'Input - Canon - Canon-Log - DCI-P3 Tungsten', 'Input - Canon - Canon-Log - Rec. 2020 Daylight', 'Input - Canon - Canon-Log - Rec. 2020 Tungsten', 'Input - Canon - Canon-Log - Rec. 709 Daylight', 'Input - Canon - Canon-Log - Rec. 709 Tungsten', 'Input - Canon - Canon-Log2 - Cinema Gamut Daylight', 'Input - Canon - Canon-Log2 - Cinema Gamut Tungsten', 'Input - Canon - Canon-Log2 - Rec. 2020 Daylight', 'Input - Canon - Canon-Log2 - Rec. 2020 Tungsten', 'Input - Canon - Canon-Log3 - Cinema Gamut Daylight', 'Input - Canon - Canon-Log3 - Cinema Gamut Tungsten', 'Input - Canon - Canon-Log3 - Rec. 2020 Daylight', 'Input - Canon - Canon-Log3 - Rec. 2020 Tungsten', 'Input - Canon - Curve - Canon-Log', 'Input - Canon - Curve - Canon-Log2', 'Input - Canon - Curve - Canon-Log3', 'Input - Canon - Linear - Canon Cinema Gamut Daylight', 'Input - Canon - Linear - Canon Cinema Gamut Tungsten', 'Input - Canon - Linear - Canon DCI-P3 Daylight', 'Input - Canon - Linear - Canon DCI-P3 Tungsten', 'Input - Canon - Linear - Canon Rec. 2020 Daylight', 'Input - Canon - Linear - Canon Rec. 2020 Tungsten', 'Input - Canon - Linear - Canon Rec. 709 Daylight', 'Input - Canon - Linear - Canon Rec. 709 Tungsten', 'Input - Generic - sRGB - Texture', 'Input - GoPro - Curve - Protune Flat', 'Input - GoPro - Linear - Protune Native - Experimental', 'Input - GoPro - Protune Flat - Protune Native - Experimental', 'Input - Panasonic - Curve - V-Log', 'Input - Panasonic - Linear - V-Gamut', 'Input - Panasonic - V-Log - V-Gamut', 'Input - RED - Curve - REDLog3G10', 'Input - RED - Curve - REDlogFilm', 'Input - RED - Linear - DRAGONcolor', 'Input - RED - Linear - DRAGONcolor2', 'Input - RED - Linear - REDcolor', 'Input - RED - Linear - REDcolor2', 'Input - RED - Linear - REDcolor3', 'Input - RED - Linear - REDcolor4', 'Input - RED - Linear - REDWideGamutRGB', 'Input - RED - REDLog3G10 - REDWideGamutRGB', 'Input - RED - REDlogFilm - DRAGONcolor', 'Input - RED - REDlogFilm - DRAGONcolor2', 'Input - RED - REDlogFilm - REDcolor', 'Input - RED - REDlogFilm - REDcolor2', 'Input - RED - REDlogFilm - REDcolor3', 'Input - RED - REDlogFilm - REDcolor4', 'Input - Sony - Curve - S-Log1', 'Input - Sony - Curve - S-Log2', 'Input - Sony - Curve - S-Log3', 'Input - Sony - Linear - S-Gamut', 'Input - Sony - Linear - S-Gamut Daylight', 'Input - Sony - Linear - S-Gamut Tungsten', 'Input - Sony - Linear - S-Gamut3', 'Input - Sony - Linear - S-Gamut3.Cine', 'Input - Sony - Linear - Venice S-Gamut3', 'Input - Sony - Linear - Venice S-Gamut3.Cine', 'Input - Sony - S-Log1 - S-Gamut', 'Input - Sony - S-Log2 - S-Gamut', 'Input - Sony - S-Log2 - S-Gamut Daylight', 'Input - Sony - S-Log2 - S-Gamut Tungsten', 'Input - Sony - S-Log3 - S-Gamut3', 'Input - Sony - S-Log3 - S-Gamut3.Cine', 'Input - Sony - S-Log3 - Venice S-Gamut3', 'Input - Sony - S-Log3 - Venice S-Gamut3.Cine', 'lin_adobergb', 'lin_adobewidegamutrgb', 'lin_alexawide', 'lin_ap0', 'lin_ap1', 'lin_canoncgamutday', 'lin_canoncgamuttung', 'lin_canondcip3day', 'lin_canondcip3tung', 'lin_canonrec2020day', 'lin_canonrec2020tung', 'lin_canonrec709day', 'lin_canonrec709tung', 'lin_dgn', 'lin_dgn2', 'lin_p3d60', 'lin_p3d65', 'lin_p3dci', 'lin_prophoto', 'lin_protunegamutexp', 'lin_rc', 'lin_rc2', 'lin_rc3', 'lin_rc4', 'lin_rec2020', 'lin_rec709', 'lin_rimm', 'lin_rwg', 'lin_sgamut', 'lin_sgamut3', 'lin_sgamut3cine', 'lin_sgamutday', 'lin_sgamuttung', 'lin_srgb', 'lin_venice_sgamut3', 'lin_venice_sgamut3cine', 'lin_vgamut', 'lin_xyz_d60', 'log21000nitsshaper_ap1', 'log2108nitsshaper_ap1', 'log22000nitsshaper_ap1', 'log24000nitsshaper_ap1', 'log248nitsshaper_ap1', 'logc3ei1000_alexawide', 'logc3ei1280_alexawide', 'logc3ei1600_alexawide', 'logc3ei160_alexawide', 'logc3ei2000_alexawide', 'logc3ei200_alexawide', 'logc3ei250_alexawide', 'logc3ei2560_alexawide', 'logc3ei3200_alexawide', 'logc3ei320_alexawide', 'logc3ei400_alexawide', 'logc3ei500_alexawide', 'logc3ei640_alexawide', 'logc3ei800_alexawide', 'look_aces10to01emulation', 'look_aces10to02emulation', 'look_aces10to07emulation', 'look_bluelightartifactfix', 'out_dcdm', 'out_dcdmp3d60limited', 'out_dcdmp3d65limited', 'out_p3d60', 'out_p3d65', 'out_p3d65d60simulation', 'out_p3d65rec709limited', 'out_p3d65st20841000nits', 'out_p3d65st2084108nits', 'out_p3d65st20842000nits', 'out_p3d65st20844000nits', 'out_p3dcid60simulation', 'out_p3dcid65simulation', 'out_rec2020', 'out_rec2020hlg1000nits', 'out_rec2020p3d65limited', 'out_rec2020rec709limited', 'out_rec2020st20841000nits', 'out_rec2020st20842000nits', 'out_rec2020st20844000nits', 'out_rec709', 'out_rec709d60sim', 'out_srgb', 'out_srgbd60sim', 'Output - DCDM', 'Output - DCDM (P3D60 Limited)', 'Output - DCDM (P3D65 Limited)', 'Output - P3-D60', 'Output - P3-D65 ST2084 (1000 nits)', 'Output - P3-D65 ST2084 (2000 nits)', 'Output - P3-D65 ST2084 (4000 nits)', 'Output - P3-DCI (D60 simulation)', 'Output - P3-DCI (D65 simulation)', 'Output - P3D65', 'Output - P3D65 (D60 simulation)', 'Output - P3D65 (Rec.709 Limited)', 'Output - P3D65 ST2084 (108 nits)', 'Output - Rec.2020', 'Output - Rec.2020 (P3D65 Limited)', 'Output - Rec.2020 (Rec.709 Limited)', 'Output - Rec.2020 HLG (1000 nits)', 'Output - Rec.2020 ST2084 (1000 nits)', 'Output - Rec.2020 ST2084 (2000 nits)', 'Output - Rec.2020 ST2084 (4000 nits)', 'Output - Rec.709', 'Output - Rec.709 (D60 sim.)', 'Output - sRGB', 'Output - sRGB (D60 sim.)', 'protuneflat_protunegamutexp', 'raw', 'rec2020_camera', 'rec2020_display', 'rec709_camera', 'rec709_display', 'rl3g10_rwg', 'rlf_dgn', 'rlf_dgn2', 'rlf_rc', 'rlf_rc2', 'rlf_rc3', 'rlf_rc4', 'Role - color_picking', 'Role - color_timing', 'Role - compositing_linear', 'Role - compositing_log', 'Role - data', 'Role - default', 'Role - matte_paint', 'Role - reference', 'Role - rendering', 'Role - scene_linear', 'Role - texture_paint', 'role_color_picking', 'role_color_timing', 'role_compositing_linear', 'role_compositing_log', 'role_data', 'role_default', 'role_matte_paint', 'role_reference', 'role_rendering', 'role_scene_linear', 'role_texture_paint', 'slog1_sgamut', 'slog2_sgamut', 'slog2_sgamutday', 'slog2_sgamuttung', 'slog3_sgamut3', 'slog3_sgamutcine', 'slog3_venice_sgamut3', 'slog3_venice_sgamutcine', 'srgb_texture', 'Utility - Curve - Rec.1886', 'Utility - Curve - Rec.2020', 'Utility - Curve - Rec.709', 'Utility - Curve - sRGB', 'Utility - Dolby PQ 1000 nits Shaper', 'Utility - Dolby PQ 1000 nits Shaper - AP1', 'Utility - Dolby PQ 10000', 'Utility - Dolby PQ 108 nits Shaper', 'Utility - Dolby PQ 108 nits Shaper - AP1', 'Utility - Dolby PQ 2000 nits Shaper', 'Utility - Dolby PQ 2000 nits Shaper - AP1', 'Utility - Dolby PQ 4000 nits Shaper', 'Utility - Dolby PQ 4000 nits Shaper - AP1', 'Utility - Dolby PQ 48 nits Shaper', 'Utility - Dolby PQ 48 nits Shaper - AP1', 'Utility - Gamma 1.8 - Rec.709 - Texture', 'Utility - Gamma 2.2 - Rec.709 - Texture', 'Utility - Linear - Adobe RGB', 'Utility - Linear - Adobe Wide Gamut RGB', 'Utility - Linear - P3-D60', 'Utility - Linear - P3-D65', 'Utility - Linear - P3-DCI', 'Utility - Linear - Rec.2020', 'Utility - Linear - Rec.709', 'Utility - Linear - RIMM ROMM (ProPhoto)', 'Utility - Linear - sRGB', 'Utility - LMT Shaper', 'Utility - Log2 1000 nits Shaper', 'Utility - Log2 1000 nits Shaper - AP1', 'Utility - Log2 108 nits Shaper', 'Utility - Log2 108 nits Shaper - AP1', 'Utility - Log2 2000 nits Shaper', 'Utility - Log2 2000 nits Shaper - AP1', 'Utility - Log2 4000 nits Shaper', 'Utility - Log2 4000 nits Shaper - AP1', 'Utility - Log2 48 nits Shaper', 'Utility - Log2 48 nits Shaper - AP1', 'Utility - Look - ACES 1.0 to 0.1 emulation', 'Utility - Look - ACES 1.0 to 0.2 emulation', 'Utility - Look - ACES 1.0 to 0.7 emulation', 'Utility - Look - Blue Light Artifact Fix', 'Utility - Raw', 'Utility - Rec.2020 - Camera', 'Utility - Rec.2020 - Display', 'Utility - Rec.709 - Camera', 'Utility - Rec.709 - Display', 'Utility - sRGB - Texture', 'Utility - XYZ - D60', 'vlog_vgamut')

location: C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py:199

location: <unknown location>:-1
`

**Comment by domlysz** [comment]
Same problem aswith blender-filmic
#268

**Comment by domlysz** [comment]
should be fixed

https://github.com/domlysz/BlenderGIS/commit/f3c7ba4172600d296366f62e9fb73a255ff603aa

**Comment by B4adle7** [comment]
Thank you.
     Greatly appreciated.
     I took your lead and did this additional update to support ACES 
colorspace and it seems to work.


             try:
                 self.bpyImg.colorspace_settings.name = 'Raw'
             except:
                 #   May be ACES
                 try:
                     self.bpyImg.colorspace_settings.name = 'Utility - Raw'
                 except TypeError:
                     log.warning('Cannot set the DEM texture to a raw 
color space, the altitude values ​​may not be exact')
                     pass


This does the change to Raw (Linear) for standard color spaces.
With ACES, that usually fails, so it then checks for the ACES version of 
Raw "Utility - Raw"  (Why they have to be different I do NOT know)

And yes, I should probably do "TypeError", but this is me being lazy.

**Comment by domlysz** [comment]
as I can see in in the error message there is a another raw colorspace but in contrast to the native colorspace name the value is _raw_ without capital letter ! that sucks

**Comment by B4adle7** [comment]
*sigh*
Yeah, dealing with ACES seems overly complicated.  Just is becoming a 
necessity.

**Comment by robertguetzkow** [comment]
@domlysz If you're dealing with data that doesn't need color management, you could try to use  [`is_data`](https://docs.blender.org/api/current/bpy.types.ColorManagedInputColorspaceSettings.html#bpy.types.ColorManagedInputColorspaceSettings.is_data)

**Comment by domlysz** [comment]
interesting, as i can see setting is_data to true set the color space name to "Non-Color" but the original issue come from missing "Non-Color" value. Can anybody test if setting this property to True with blender-Fimic or ACES raise an error or not ?

**Comment by robertguetzkow** [comment]
@domlysz [`is_data`](https://docs.blender.org/api/current/bpy.types.ColorManagedInputColorspaceSettings.html#bpy.types.ColorManagedInputColorspaceSettings.is_data) only requires that one color space in the OCIO config exists that is marked `isdata: true`.

**Comment by domlysz** [comment]
Thank you very much for the tip, this fixes this error for good !

https://github.com/domlysz/BlenderGIS/commit/ef5741a215fdeeaffdbf01716d9579d16596b98f
