### ISSUE TITLE
Keeping database data somehow to reuse them for eg. scaling...

### ISSUE THREAD

**Issue by JakubPelka** [domlysz/BlenderGIS#364]
Hi,
I wonder about keeping somehow value data and reusing them in quite same way as you did with extrusion.

My idea/need is to create vegetation data. I have a shp file with trees (one for coniferous and one for deciduous) with size value. Shapefile is a point geometry file. 
I'd like to exchange all points to the low-poly models of a tree with size value that will be used to scale up a Low-poly model. Now even if I import them as a cylinders (point+small buffer+extrusion) I can't exchange them to low-poly trees with keeping proportional size (as extrusion is influencing dimmension values not a Z-scale value). 

I can imagine solution as it is now with extrude but with one checkbox - extrude in real dimmension / extrude by scaling.

Or maybe there is a way to do it easily that I am missing. 

Will be glad for any help / suggestions.

**Comment by domlysz** [comment]
You can import the points with the _separate objets_ option, then all attributes data will be available as object's cutom properties. Then you can replace each point with an instance of your tree mesh using CTRL+L. The last step is to write a few lines of code to scale your trees using the size custom property

**Comment by JakubPelka** [comment]
Hm.... ok.... it seems a little bit complicated, but will try to solve it! :) thanks for suggestion!

**Comment by domlysz** [comment]
To help you a bit more, bellow a code sample:

```
import bpy

coll = bpy.data.collections['shapefile_name']

for obj in coll.objects:
    scale = obj['size_column']
    obj.scale = (scale, scale, scale)
```

It's very straightforward. Import your shp as separates objects. Each point will be put into a new collection named like the shapefile. If you select an object you can see the attributes data in the properties panel > objet > custom properties.

Then right click the collection > select objects and lastly select you tree object and link object data using CTRL+L shortcut. Now open the blender's text editor, copy paste the script, change _shapefile_name_ and _size_column_, and run it. That's it.

**Comment by JakubPelka** [comment]
IT WORKS!! 👍 Much easier then I expected!! Thank You!! :)

**Comment by domlysz** [comment]
yeah it's because each object share the same mesh instance, so editing the mesh (like applying scale) will affect all objects (try it!). But instance is the best way to have thousands of duplicates without overflow the memory.

**Comment by JakubPelka** [comment]
Sure :) Once again thanks!
