### ISSUE TITLE
Hi, Its keep crashing if i try to upload a map...its just crash out of nowhere.

### ISSUE THREAD

**Issue by MickeyZombish** [domlysz/BlenderGIS#365]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by MickeyZombish** [comment]
I'm using window, Blender just keep crashing if i'm zooming or just searching a place on the map. No one seems having this issue on Youtube or wherever...

**Comment by domlysz** [comment]
Please report the logs as explained here #289

**Comment by domlysz** [comment]
lack of information
