### ISSUE TITLE
Blender 2.83 - Cant install addon

### ISSUE THREAD

**Issue by YoungDref** [domlysz/BlenderGIS#368]
Traceback (most recent call last):
  File "D:\Blender\2.83\scripts\startup\bl_operators\userpref.py", line 622, in execute
    pyfile = self.filepath
  File "D:\Blender\2.83\scripts\modules\bpy_types.py", line 712, in __getattribute__
    return getattr(properties, attr)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 24: invalid continuation byte

location: <unknown location>:-1

**Comment by b-69** [comment]
the file is missing from zip file

**Comment by domlysz** [comment]
Is there non-latin character in the path to the zip file ?

**Comment by YoungDref** [comment]
> Is there non-latin character in the path to the zip file ?

Nope, but i should defenetly try to move zip from desctop to hdd.

**Comment by YoungDref** [comment]
RESOLVED!

I moved downloaded file from desktop to disk D:/, after that plugin installed without any issues.

Ty @domlysz for good idea. Topic can be closed.

**Comment by domlysz** [comment]
great !
