### ISSUE TITLE
[Feature Request] "Get SRMT": Add option to generate a mesh with more nodes

### ISSUE THREAD

**Issue by riccardorocca** [domlysz/BlenderGIS#370]
# **Blender and OS versions**

Blender 2.82
Windows 10

# **Describe the Feature Request**

As I understand, the command "Get SRMT" splits the input image mesh into a grid of 64x64 cells and then assigns a height value to each grid node (see attached image).
![image](https://user-images.githubusercontent.com/54755160/89203243-8a56df00-d5b4-11ea-8ce3-9ce378fd8ca9.png)

Is there a way to choose a different subdivision like 128x128 or 256x256, in order to achieve a more refined altitude map?
If not, would it be possible to add a parameter to set this option?

**Comment by riccardorocca** [comment]
I have found a solution:  I have realized that the mesh split is controlled by the modifier "Subdivision", and specifically by the parameter "Viewport" that can have a maximum value of 6 (2^6 = 64).
So I have added a second modifier "Subdivision", right after the first one (highlighted in red in the image) and now I can increase the number of grid cells up to 4096x4096 (2^12 = 4096), and the relief can be generated with much more details.
![image](https://user-images.githubusercontent.com/54755160/89215749-7c5f8900-d5c9-11ea-85bd-eb372d2a511f.png)

**Comment by domlysz** [comment]
This operator set 2 modifiers : a displacer and a subsurf. If you need more vertices just increase the subsurf level or add another one. The resolution is in fact limited by the SRTM data itself which is about 90m per pixel.

**Comment by riccardorocca** [comment]
Thank you "domlysz". I have actually adde a new post with this solution.

**Comment by domlysz** [comment]
I see that great you found the solution by yourself !
