### ISSUE TITLE
Get SRTM for areas above 60°N

### ISSUE THREAD

**Issue by birgirvilhelm** [domlysz/BlenderGIS#371]
Hi, why is it not possible to get SRTM for areas above 60°N? I cant get it for Iceland for example. Can this be implemented to BlenderGIS?

Best wishes, 
Birgir

**Comment by domlysz** [comment]
Because the data does not exists above 60°N

https://en.wikipedia.org/wiki/Shuttle_Radar_Topography_Mission

**Comment by birgirvilhelm** [comment]
Alright, thanks.
