### ISSUE TITLE
Cant install (WINDOWS)

### ISSUE THREAD

**Issue by NicTanghe** [domlysz/BlenderGIS#372]
# **Blender and OS versions**
Blender
2.83.4

WINDOWS
Major 10       Minor 0  Build 19041     Revision 0

# **Describe the bug**

Adding the .py files in addons does absolutly nothing.

# **How to Reproduce**
Try to install the addon without anny propper instructions

# **Error message**
None
![image](https://user-images.githubusercontent.com/13624265/89720305-c2a15780-d9d0-11ea-9e37-dfd11968c4a3.png)

![image](https://user-images.githubusercontent.com/13624265/89720294-a4d3f280-d9d0-11ea-9de2-a9dde149fd01.png)

**Comment by domlysz** [comment]
https://github.com/domlysz/BlenderGIS/wiki/Install-and-usage

select the zip file not the __init__.py

**Comment by NicTanghe** [comment]
Ok that ws dumb of me.
i shal chck it out when im back on my windows mashin.

**Comment by NicTanghe** [comment]
kj
