### ISSUE TITLE
I cannot import a raster surface into blender version 2.80

### ISSUE THREAD

**Issue by elkoala86** [domlysz/BlenderGIS#373]
I have been trying to add the basemap into blender and it showed me this

![Blender_error](https://user-images.githubusercontent.com/64488293/89726404-d1dbd180-d9df-11ea-8bd5-d4bb2fe0f175.jpg)

I can not add raster files as well.

I hope that somebody can explain me why this happening.

**Comment by domlysz** [comment]
the spatial coordinate system of the scene does not match the basemaps one, so a reprojection task is involved but fails as GDAL is not installed. You can set the scene projection to Web Mercator to avoid raster reprojection or install GDAL if you need to work in another projection system.

It's all explained in the wiki, please read the doc before asking
