### ISSUE TITLE
3D scene export as georefenced .OBJ file

### ISSUE THREAD

**Issue by poprafka** [domlysz/BlenderGIS#374]
Hello,

the addon works perfectly to create the 3D scene, however if I'm trying to export the scene as .obj file, the file is always in local coordinates. I use Blender 2.83 with GDAL.

**Comment by domlysz** [comment]
The obj exporter is completly independant from the BenderGIS addon, so it dos not take into account the geolocation of the scene origin.

**Comment by poprafka** [comment]
sure I accept that. However, is there no known fix / workaround how to export the model keeping the geolocation of the scene? At least an option to export some geolocation file directly from BlenderGIS for the scene would help here.

**Comment by domlysz** [comment]
Georeferencing parameters are explicit, please read the carrefully the wiki :
 https://github.com/domlysz/BlenderGIS/wiki/Georeferencing-management

The geolocation of the scene is just an offset for all coordinates, you can post-process your obj to shift it's location according to this offset.

With the geoscene panel you can also set the scene origin to zero, it will shift you object far away at it's true projected coordinates, but it can break your model as Blender cannot deal with high coordinates values.
