### ISSUE TITLE
  Basemap does not work, grey tiles

### ISSUE THREAD

**Issue by andrewtp32** [domlysz/BlenderGIS#375]
# **Blender and OS versions**

Blender 2.83.4 and Ubuntu 18.04

# **Describe the bug**
 
Basemap does not work.

# **How to Reproduce**

First and foremost, I am about as useful with Blender as a can of paint would be. Despite this, I have used Blender and your wonderful addon for the past few weeks to generate terrains for drone simulations in Gazebo. I had to re-download Blender and your addon onto my computer since I had to reset my entire desktop (I royal messed something up so I just backed up my files and reset). Since then, the map of the earth when I click basemap wont pop up. I have no idea what I am looking at because the screen is just grey. I am still able to create a 2D plane using the "e" key and then get SRTM with no problem. The issue is that I have no idea what I am looking at on the basemap because everything is grey.

# **Error message**

There are no error messages. I just don't see anything when I click basemap anymore.

**Comment by domlysz** [comment]
Please report the log here 

![image](https://user-images.githubusercontent.com/5639024/93571697-1b331f80-f995-11ea-84a2-a34c7224a819.png)

**Comment by domlysz** [comment]
Can be linked to limited permissions of the cache folder as identified in #390. What is your cache folder path? can you try with another one?

**Comment by domlysz** [comment]
merging the issue with #390
