### ISSUE TITLE
GeoTiff import appears to be Flat surface in Blender 2.83

### ISSUE THREAD

**Issue by elkoala86** [domlysz/BlenderGIS#376]
Hello I have been trying to import the raster showed below. It has local coordinate system Magna Medellín and I have modified the file according to the tips defined in the BlenderGis wiki.

# **Blender and OS versions**

# **Describe the bug**
![DEM_EXAMPLE](https://user-images.githubusercontent.com/64488293/90319989-c2d6b100-df02-11ea-8e03-9d20294bdc44.jpg)

# **How to Reproduce**

# **Error message**

When I Imported this file into Blender 2.83, it displays a flat surface. I do not know why this happened. I supposed that it must display an elevation terrain model. I attach the process that I made for importing this file:
![DEM_import_process](https://user-images.githubusercontent.com/64488293/90320179-3d540080-df04-11ea-9c8f-44efe928c636.jpg)

I hope that can help me to solve this issue.

Thanks.

**Comment by domlysz** [comment]
Please read the wiki, you haven't select the right import mode in the importer options
