### ISSUE TITLE
REPORT: ERROR

### ISSUE THREAD

**Issue by Vangelou123** [domlysz/BlenderGIS#377]
I a m using blender 2.79 and windows 7, it was no able to activate the pluggin

![GOOGLE](https://user-images.githubusercontent.com/69665645/90840839-53086200-e318-11ea-9957-2a3149d75b05.png)

# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by domlysz** [comment]
The addon require Blender 2.8x
