### ISSUE TITLE
Unable to open raster

### ISSUE THREAD

**Issue by alejandrojromero** [domlysz/BlenderGIS#379]
_Blender 2.83, Mac OS Catalina_

When importing a .tif file as DEM raw data build (with build faces turned ON), I receive the error "Unable to open raster." I tried with both 16 and 32bit Floating Point versions of the .tif. 

<img width="729" alt="Screen Shot 2020-08-28 at 3 43 51 PM" src="https://user-images.githubusercontent.com/45703767/91609454-78632480-e945-11ea-9a68-34433668cf76.png">

**Comment by Zi7ar21** [comment]
Why did you close this issue?
