### ISSUE TITLE
STRM Depreciating in Open Topography

### ISSUE THREAD

**Issue by allyourbases** [domlysz/BlenderGIS#380]
#V2.83.2

Hi, I am new, but I have found an issue connecting to Opentopography.  It does not seem to be related to your code, but the access granted by Open Topography.  Pants down, firewall off and still no connection with your URI when Opentopography is selected.  The marine one works fine. 
Windows 10, Blender V2.83.2
Open Topography fails due to connection actively refused, I believe due to Opentopography.org depreciating the REST API.  

Any attempt to access data using the URI is refused from Open Topography.  A new API is implemented.

DEBUG:BlenderGIS-master.operators.io_get_srtm:95:http://opentopo.sdsc.edu/otr/getdem?demtype=SRTMGL3&west=35.19819531350241&east=35.27360644618984&south=31.75886695171921&north=31.80022401461781&outputFormat=GTiff
ERROR:BlenderGIS-master.operators.io_get_srtm:112:Http request fails url:http://opentopo.sdsc.edu/otr/getdem?demtype=SRTMGL3&west=35.19819531350241&east=35.27360644618984&south=31.75886695171921&north=31.80022401461781&outputFormat=GTiff, code:None, error:[WinError 10061] No connection could be made because the target machine actively refused it

From https://opentopography.org/developers
>We are deprecating our old RESTful Web service for global raster data access on September 30th, 2020. Please transition to the new API above.
>RESTful Web services for accessing Shuttle Radar Topography Mission GL3 (Global 90m), GL1 (Global 30m), GL1 Ellipsoidal, ALOS World 3D (Global 30m), and ALOS World 3D Ellipsoidal data.

>Output GeoTIFF (Default), Arc ASCII Grid, IMG

>EXAMPLE (GL3 datatset for a given bounding box in GeoTiff format): https://portal.opentopography.org/otr/getdem?demtype=SRTMGL3&west=-120.168457&south=36.738884&east=-118.465576&north=38.091337&outputFormat=GTiff

**Comment by domlysz** [comment]
fixed f6a5db5cf153fcf6a2cfbd915b870a374520c657
