### ISSUE TITLE
OpenTopography API deprecation & update

### ISSUE THREAD

**Issue by cjcrosby** [domlysz/BlenderGIS#382]
Hello,
We understand that you have integrated the OpenTopography Global Datasets API into BlenderGIS. Wanted to give you a heads-up that we’re deprecating the current API (on Sept 30th) and have replaced it with a new one based on the OpenAPI Specification: 

You can find more details here: 
https://opentopography.org/developers#API
https://portal.opentopography.org/apidocs/#/Public/getGlobalDem

# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by domlysz** [comment]
Hi,

Thank you very much for this information, the url has been updated. And thanks to the all team for providing this web service !

https://github.com/domlysz/BlenderGIS/commit/f6a5db5cf153fcf6a2cfbd915b870a374520c657

**Comment by rumitdhamecha** [comment]
> Hi,
> 
> Thank you very much for this information, the url has been updated. And thanks to the all team for providing this web service !
> 
> [f6a5db5](https://github.com/domlysz/BlenderGIS/commit/f6a5db5cf153fcf6a2cfbd915b870a374520c657)

Hi,
Im noob in here. But how did you update the URL ? Im getting SRTM error. Please Guide. As well as I downloaded latest Zip File and same error.
