### ISSUE TITLE
Base Map scale is 1.5x too big?

### ISSUE THREAD

**Issue by CharlieTemplar** [domlysz/BlenderGIS#384]
# **Blender and OS versions**

Blender 2.82 Windows 10

# **Describe the bug**

Base Map scaling seems incorrect by 1.5x

# **How to Reproduce**

Measured 10 yard diameter circle at centre of football pitch.
In google earth and QGIS, this measures as 10 yards, (9.144m)
In extracted BlenderGis Base Map the came centre circle measures as 15.25m
![image](https://user-images.githubusercontent.com/47461175/93836442-b882a200-fc7a-11ea-86f5-c39ed9270b52.png)

Is there something that can be configured to fix this?

**Comment by domlysz** [comment]
See FAQ

https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-my-measurements-on-basemaps-reference-seems-wrong-

**Comment by CharlieTemplar** [comment]
Fair enough, thanks for the explanation.
