### ISSUE TITLE
Elevation data incorrect - Randomly inverts object

### ISSUE THREAD

**Issue by tuomaspap** [domlysz/BlenderGIS#388]
**Blender and OS versions**
Blender 2.82
Windows 10 64bit

**Describe the bug**
When requesting height data from SRTM , the object appears to take on an inverted elevation that has nothing to do with the object

**How to Reproduce**
Pick santorini as island .
Zoom in to appr 2 times before end of zoom. 
Press E to capture . 
Go to SRTM to get elevation data

![Capture](https://user-images.githubusercontent.com/11294289/94429916-002d9000-018b-11eb-8fd0-5df98efad31c.PNG)

**Comment by domlysz** [comment]
Can you share a blend file. Not sure what's wrong on the screenshoot.

**Comment by domlysz** [comment]
closed because of lack of information
