### ISSUE TITLE
DEM as displacement wrong results

### ISSUE THREAD

**Issue by janausis** [domlysz/BlenderGIS#396]
# **Blender and OS versions**

Blender: 2.90.1 OS: Windows 10 Home, newest

# **Describe the bug**

When adding a GEOTiff as Displacement texture, the elevation data makes absolutely no sense and randomly shifts parts up and down and my files are not broken, if i for example open them in Qgis, everything is fine with them, importing the elevation data as basemap on plane also shows the correct outline, the raw build on the other hand not.

# **How to Reproduce**

Use ESPG:102014 (Europe Lambert Conformal Conic) and try to add a displacement mesh onto a georef plane

# **Error message**

Maybe that helps?

```
Info: Total files 4 | Changed 4 | Failed 0
TIFFReadDirectory: Warning, Unknown field with tag 33550 (0x830e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 33922 (0x8482) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 34735 (0x87af) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 34736 (0x87b0) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 34737 (0x87b1) encountered.
```

**Comment by domlysz** [comment]
Can you share the geotiff for testing ?

**Comment by janausis** [comment]
Yeah for sure. Here's the Google Drive [link.](https://drive.google.com/file/d/1m18DuqEtUdTY_JaZqRUZ-gCNYTk7GUX9/view?usp=sharing)

And as a little update, I did eventually solve it by combining multiple tiffs to a bigger one, But i don't know why it didn't work with just that smaller one and i still get the warnings from above.

**Comment by domlysz** [comment]
It's just because there are lot of nodata values in your raster. Nodata is typically represented by a very high or low value that's why these pixels cause a very high displacement. It's not possible to filter nodata when the raster is used as displacement texture.

![image](https://user-images.githubusercontent.com/5639024/95902753-86ee8980-0d95-11eb-8253-e67c5de637f3.png)

**Comment by janausis** [comment]
Thanks, i will remember that next time. That would also explains why it worked with a combination of multiple ones
