### ISSUE TITLE
Unable to import raster image as Basemap on Mesh and DEM displacement texture

### ISSUE THREAD

**Issue by elkoala86** [domlysz/BlenderGIS#398]
# **Blender and OS versions**

# **Describe the bug**

I have been trying to import a raster image (JPG) on a satellite image from google as Basemap on Mesh and DEM displacement texture. But I always obtained an error message that says: Non-overlapdata. I do not know why this is happening. 
![Capture1](https://user-images.githubusercontent.com/64488293/95890898-fc346d00-0d49-11eb-91e4-5f03e25e52e2.JPG)
![Capture2](https://user-images.githubusercontent.com/64488293/95890903-fd659a00-0d49-11eb-88e3-849eaaeea4e4.JPG)
![Capture3](https://user-images.githubusercontent.com/64488293/95890906-fdfe3080-0d49-11eb-9bf7-3ad202726434.JPG)

# **How to Reproduce**

# **Error message**

**Comment by domlysz** [comment]
This error means that the 2 rasters extent have no intersection area. It typically happen when the 2 rasters does not share the same projection system.

**Comment by elkoala86** [comment]
Hello, I have a question. I have changed the reference system of the rasters to WGS84, but it is not working yet. The software shut down immediately.  The basemap loaded from google using the blenderGIS has this reference system (WGS84) or another ?. 
Because I have changed these rasters to web Mercator system, but it does not work too. 

I don't know what is happening.
