### ISSUE TITLE
Addon does not show up in UI after installation

### ISSUE THREAD

**Issue by Mi-Pe** [domlysz/BlenderGIS#399]
**Blender and OS versions**
Blender 2.9
Windows 7 64-bit

As in the title, the add-on does not show up in Tools. I'm in Object mode. Installation went successful, I guess. No error messages.
Anyone had similar issue?

**Comment by domlysz** [comment]
No GIS menu ?

https://github.com/domlysz/BlenderGIS/wiki/Install-and-usage

**Comment by Mi-Pe** [comment]
No GIS menu.
Made sure the add-on is enabled.
Defined cache folder.

**Comment by domlysz** [comment]
Any message in the system console ?
![image](https://user-images.githubusercontent.com/5639024/96347844-ab53aa00-10a4-11eb-9b99-28974e4758bf.png)

**Comment by Mi-Pe** [comment]
![-2020-oct-17-016](https://user-images.githubusercontent.com/73021367/96347986-e4404e80-10a5-11eb-8ba4-f34153c57c4e.jpg)
I don't know if this information is vital but earlier I downloaded Blender OSM plugin and that one works fine.

**Comment by Mi-Pe** [comment]
Oh man, I'm so sorry. I'm blind like hell.
It is there.
It's just not next to "Object" button nor next to any of the Tools but it appeared right under snapping settings. I guess it's due to the changes in UI introduced with Blender 2.9 that some add-ons were moved to a special UI group just under snapping settings. Your add-on has its place there, next to Blender Kit.
I'm a newbie in Blender and still not very familiar with UI, which - to make things harder - changes a bit with every new release, so like every fckn month.
Again, I am sorry for bothering you. I guess I shall close the issue or even remove it if possible?

**Comment by gavinraym** [comment]
Ok, but actually this is exactly what is happening to me! No matter what version I use (2.8, 3.5, 4.0) the GIS menu is not there after install.
