### ISSUE TITLE
Extrusion always occurs along "local" z axis

### ISSUE THREAD

**Issue by geognu** [domlysz/BlenderGIS#4]
As stated,when you set an attribute for "extrusion from field" while importing shapefile, extrusion always happens along the normal of the face (in a polygon). If your polygon has a non-horizontal base but you still want to just extrude it along the global z axis, you can't achieve the result

![screen](https://cloud.githubusercontent.com/assets/7746489/10141764/9598db40-660e-11e5-976b-dcd754d27725.png)
![screen_extr](https://cloud.githubusercontent.com/assets/7746489/10141765/959ca1bc-660e-11e5-8176-5acb84333307.png)

**Comment by domlysz** [comment]
To quickly change this behaviour you can edit line 223 of file *op_import_shp.py*, change "vect=normal*offset" to "vect=(0,0,offset)"

I will add an option to choose between the two behavior.

**Comment by geognu** [comment]
This solution works for me, it will indeed be great to have to option in the configuration window.

**Comment by geognu** [comment]
It will also be cool if you could choose whether the top face of the extruded polygon will be parallel to the base face or if you want it flat (useful if you are extruding buildings footprint and adding roof geometry later)

**Comment by domlysz** [comment]
Hi,

Now there is an option to choose extrusion axis. Handle roof orientation is much more complex, maybe the next time.

**Comment by domlysz** [comment]
https://github.com/domlysz/BlenderGIS/issues/9
