### ISSUE TITLE
Any idea how to get terrain data from Greenland? 

### ISSUE THREAD

**Issue by Goodmorningworld1** [domlysz/BlenderGIS#400]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by domlysz** [comment]
You can import any kind of DEM datasource in Geotiff format, some country provides local DEM for free. You can also try to change the web service to _marine-geo.org_ in addon preferences, it provides [GMRT ](https://www.gmrt.org/about/index.php) dataset. It's possible to setup others DEM web services for the addon, let me know if you aware of free API that provides global DEM from different source than SRTM.

**Comment by Goodmorningworld1** [comment]
Thank you for your reply. 
I am afraid I am not aware of any API that provides global DEM from different source than SRTM. This is all new to me.
