### ISSUE TITLE
BlenderGIS and SRTM not available north of 60°N

### ISSUE THREAD

**Issue by jonket55** [domlysz/BlenderGIS#402]
Is it possible to use other DEM data than SRTM because they do not have it above 60°N or Antartica?

Best regards, Jon

**Comment by domlysz** [comment]
You can import any kind of DEM datasource in Geotiff format, some country provides local DEM for free. You can also try to change the web service to _marine-geo.org_ in addon preferences, it provides [GMRT ](https://www.gmrt.org/about/index.php) dataset. It's possible to setup others DEM web services for the addon, let me know if you aware of free API that provides global DEM from different source than SRTM.

**Comment by aparajita07** [comment]
Hi,

I am trying to create the 3D mesh for a location in Ruskotunturi in Finland, but it throws the same error "STRM not available beyond 60 degrees north". So do I have to import the local DEM from the Finnish Land Survey website and import it in the blender? Could you please elaborate on how to do it?

Thanks in advance,
Aparajita
