### ISSUE TITLE
After Adding addon in blender cant check the box to use the addon

### ISSUE THREAD

**Issue by antonopic1977** [domlysz/BlenderGIS#404]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

![blender addon checkbox error]
![blender addon checkbox error](https://user-images.githubusercontent.com/56094623/97106428-8e643b80-168f-11eb-951f-ba1893834ec6.jpg)

**Comment by antonopic1977** [comment]
error out after adding in blender -> addons, then try to check the box to select and can't this error shows

**Comment by antonopic1977** [comment]
its the latest blender version 2.78

**Comment by domlysz** [comment]
This addon requires Blender >= 2.80
