### ISSUE TITLE
Interface to sample bigger zones with higher granularity

### ISSUE THREAD

**Issue by TheFamousRat** [domlysz/BlenderGIS#411]
# **Blender and OS versions**

Blender 2.9
Ubuntu 18.04

# **Describe the bug**

Not possible to set a specific zone in the interface

# **How to Reproduce**

Not possible to set a specific zone in the interface

# **Error message**

So this is not a bug per say which means no error message. I'm sorry to post this here but I didn't find any answer elsewhere online, and the project is quite big meaning delving into the code is hard.

I come from blender-osm, which among a lot of things allows its users to select a specific zone from which to extract data : you draw a rectangle with a minimum/maximum latitude, and likewise for the longitude. That makes it quite handy to process a large zone to get its texture, heightmap etc.

For a number of reasons I prefer to use blender-GIS however, but I wonder if such a possibility is also present in this addon ? The solution I've used so far was simply panning over the zone I want in the map, sampling many small segments. It allows me to keep the high resolutions images that you get at zoom level 15 from, for example ESRI, but : 1/it is very repetitive, which grows quadratically on bigger zones 2/It is hard to have those smaller zones not overlap, which requires again quadratically more work on bigger zones.

As such, is there a kind of function to which I can feed, say, minimum longitude, maximum longitude, minimum latitude and maximum latitude, and that in return would sample the mesh from those coordinates ? I don't mind having to write a script on my side, I just haven't found where to look yet in the code :) It would allow me to have a big zone made from many smaller meshes, which would guarantee a good quality of the textures/satellite data

Thanks,
TheFamousRat

**Comment by domlysz** [comment]
did you try the L shortcut as explained in the doc ? : https://github.com/domlysz/BlenderGIS/wiki/Basemaps

**Comment by TheFamousRat** [comment]
Brillliant ! It works perfectly. Thanks a lot for the heads-up
