### ISSUE TITLE
[Feature Request] Downloading administratory borders from OSM

### ISSUE THREAD

**Issue by Mi-Pe** [domlysz/BlenderGIS#413]
[Feature Request]
Hello!
Is it possible to download administratory borders with this plugin? I mean city, municipality, district, land, voivodeship etc. borders. If not, could it be added in the future as an option? They are normally available from OSM.

**Comment by domlysz** [comment]
yes just add the tag _boundary_ in addon preferences
https://github.com/domlysz/BlenderGIS/wiki/OSM-import

**Comment by Mi-Pe** [comment]
Ok. It seems I first have to install GDAL library to get things going.
I get this message in Blender when trying to import anything: "please install gdal to enable raster reprojection support".

So I went through instructions at: https://github.com/domlysz/BlenderGIS/wiki/How-to-install-GDAL
I downloaded suitable GDAL package version, put it to python>bin folder, launched system console, typed installation commands and got "an EnvironmentError: [Errno 13] Permission denied" (SIC! It's written "Errno 13")

This is the whole console output after my attempt to install GDAL package:

"C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\bin>python.exe -m p
ip install GDAL-3.1.4-cp37-cp37m-win_amd64.whl
Processing c:\program files\blender foundation\blender 2.90\2.90\python\bin\gdal
-3.1.4-cp37-cp37m-win_amd64.whl
Installing collected packages: GDAL
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permiss
ion denied: 'C:\\Program Files\\Blender Foundation\\Blender 2.90\\2.90\\python\\
Lib\\site-packages\\gdal.py'
Consider using the `--user` option or check the permissions.
WARNING: You are using pip version 19.2.3, however version 20.2.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and."

I think my Windows user account has admin status (it's the only account I have on my computer) but I don't know - maybe there are some access settings that should be turned on. Do you know what I should do?

**Comment by Mi-Pe** [comment]
Actually I'm not sure if I downloaded the right package. There are those with "win32" and "win_amd64" suffixes. I downloaded the "...win_amd64" version. I run Windows 7 64-bit but on Intel CPU. Does that suffix indicate AMD CPU? Should I download the other package, with "win32" suffix?

**Comment by domlysz** [comment]
No you don't need to install GDAL to import data from OSM. Please forget it unless you really need advanced reprojection tasks.

> I get this message in Blender when trying to import anything: "please install gdal to enable raster reprojection support".

No, this message is only triggered by the basemap operator when the scene coordinate system does not match the source coordinate system.

You should learn first about how BlenderGIS handle spatial coordinates system :https://github.com/domlysz/BlenderGIS/wiki/Georeferencing-management

You can start with the Web Mercator projection, this is a worldwide coordinate system but be aware of it's limits https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-my-measurements-on-basemaps-reference-seems-wrong-

**Comment by Mi-Pe** [comment]
Thank you, it now works for me!
I have questions still.
 - Is it possible to increase maximum downloadable area with OSM maps? I mean, I know there are server limits. BlenderOSM addon though lets import far more land from OSM. If I want to only download boundaries, then it doesn't make a lot of data to process.
 - I am struggling with model hierarchy.
In the instructions you wrote that "It's also possible to separate each feature into distinct objects". Shall I do it manually with some Blender native tools or is it performed automatically by the addon?

Staying with the default hierarchy system:
Could you take a look at my model? I posted it on both google drive and wetransfer:
https://drive.google.com/file/d/1HyUswb0yqUYZJsS5ELEZfKAbBuz_ft3-/view?usp=sharing
or there: https://we.tl/t-2rV2d7Jw5A
Turns out that all geometry under "Areas" is stored in a single vertex group called "Tag:wheelchair=yes" but I only have buildings, some greenery and water.
Same goes with imported into "Ways" object. All geometry shares one vertex group called "boudaries" while I have both boundaries and roads.
I don't know if this is a bug but it won't let me separate all this stuff.

**Comment by Mi-Pe** [comment]
Blender has imported lots of vertex groups but apart from these two they are all empty.

**Comment by domlysz** [comment]
> Is it possible to increase maximum downloadable area with OSM maps?

There is no exposed option to set this, but you can still edit the code by yourself : https://github.com/domlysz/BlenderGIS/blob/870e6661f02093d8a3f957a1f591719b6a5fa03c/operators/io_import_osm.py#L655
As you can see the query is limited to 20km²

> In the instructions you wrote that "It's also possible to separate each feature into distinct objects". Shall I do it manually with some Blender native tools or is it performed automatically by the addon?

The option is exposed into the operator's dialog

![Sans titre](https://user-images.githubusercontent.com/5639024/99183662-c49c5480-273d-11eb-83cb-67388ad54e66.jpg)

> Blender has imported lots of vertex groups but apart from these two they are all empty.

That's not what I see, all groups contains vertices, one vertex can fall into many groups depending on it's tags. To select all vertices from a group: go to edit mode > unselect all > select a group in the mesh properties panel > press the button "select" > in the 3d view press the dot shortcut on the keypad to zoom to selected. Don't forget to deselect all verts before selecting another group however the selection will be added to the current one.

![Sans titre](https://user-images.githubusercontent.com/5639024/99183922-d7178d80-273f-11eb-9ca3-d4a95ba9b834.jpg)


> Same goes with imported into "Ways" object.

In OSM there are only nodes and ways, by convention some closed ways can be considered representing an area, depending on their tags, but in the database it's always a way. So if you expect to obtain areas but get only ways then it means that in the OSM database this kind of ways are not designed to be represented as areas.

> all geometry shares one vertex group called "boudaries" while I have both boundaries and roads.

again that's not what I see, I think you don't select the vertex group in the right way

> I don't know if this is a bug but it won't let me separate all this stuff.

If you just need boundary then just request for boundary and you'll get a single object for these features.

![b](https://user-images.githubusercontent.com/5639024/99184242-b5b7a100-2741-11eb-9061-366c0b9fcd95.png)

**Comment by Mi-Pe** [comment]
Thank you for the tips.
You are right, it's just that I'm not too familiar with Blender yet and didn't know how to select vertex groups properly. Now I can see the model is OK and has all vertex groups as expected.

I want to ask something more.
If I add an OSM tag consisting of two words, like "Water related" or "Public transport", should the words be separated with just SPACE or "floor mark" ("_") ? If they are separated with SPACE, I get an error.

Still I have problem with georeferencing. I have added a coordinate system in addon preferences (EPSG:2177 or ETRS89 for Poland, zone 6) and also, after importing basemap I have set scene georeferencing to the same system in View > Geoscene tab. Then I imported some OSM data over the basemap. Yet my map is not properly scaled. Distances are almost twice the real ones. What did I do wrong with georeferencing? Could you take a look at my scene?
https://drive.google.com/file/d/1LHrloHgCcrtFADQxpkmcJt9jG3_EuFzr/view?usp=sharing
https://we.tl/t-DmzXHzezlI

What's more, if I set georef to Web Mercator, I can download all boundaries covering about 100 km2 within a couple seconds. When I change georef system to EPSG:2177, Blender hangs up on loading. What can be wrong with it?

Thank you for your patience.

PS
Would you consider increasing maximum downloadable area for future releases?

**Comment by domlysz** [comment]
> f I add an OSM tag consisting of two words, like "Water related" or "Public transport", should the words be separated with just SPACE or "floor mark" ("_")

These tags use an underscore as words separator : https://wiki.openstreetmap.org/wiki/Key:public_transport
You can also setup a key=value pair as tag request

> after importing basemap I have set scene georeferencing to the same system in View > Geoscene tab. Then I imported some OSM data over the basemap. Yet my map is not properly scaled.

Setting the SRS in the Geoscene tab will not reproject data already imported in Blender. The scene SRS is mainly informative and represents the destination SRS for import tasks. Reprojection tasks are only triggered when the source's SRS differs from the scene's SRS. The scene's SRS should be set only once, at the beginning.

> When I change georef system to EPSG:2177, Blender hangs up on loading

Because in this case, the data is reprojected during the import. To do this task the addon use a web service named epsg.io which is good with few vertices but can quickly become very slow with more verts. Reprojection tasks can be improved by installing GDAL, but as you already tested it can be tricky to have GDAL working with Blender. The most straightforward workflow when you really need to work in a specific SRS is to preprocess the data with a GIS software like QGIS before any import in Blender.

For example, if you need administrative borders of Poland in Blender you can download them from the [Natural Earth database](https://www.naturalearthdata.com/downloads/50m-cultural-vectors/), filter, reproject and export the data to a new shapefile with QGIS, and then just import this shapefile in Blender with the addon.

**Comment by Mi-Pe** [comment]
I get it.
Thank you for this comprehensive explanation!
