### ISSUE TITLE
SRTM Data only applied to one end of plane

### ISSUE THREAD

**Issue by Nokide** [domlysz/BlenderGIS#414]
**Versions**

Blender V2.83.6
macOS Catalina 10.15.7

**Description**

When applying SRTM data to plane, it only gets applied to a small portion and the end of the plane

 **How to Reproduce**

Get Basemap 
Zoom to location
Press E to get plane
Get SRTM from OpenTopography

![Screenshot 2020-11-16 at 14 00 44](https://user-images.githubusercontent.com/15182069/99255652-8cb41080-2814-11eb-812d-cfe7cba92447.png)

# **Error message**

No error message.
![Screenshot 2020-11-16 at 14 01 03](https://user-images.githubusercontent.com/15182069/99255775-b4a37400-2814-11eb-982f-98b502921b42.png)

![Screenshot 2020-11-16 at 14 00 28](https://user-images.githubusercontent.com/15182069/99255790-b9682800-2814-11eb-9386-124347adc860.png)

Blender File:
[error.blend.zip](https://github.com/domlysz/BlenderGIS/files/5546365/error.blend.zip)

**Comment by domlysz** [comment]
The SRTM dataset only cover latitude up to 60°N
https://portal.opentopography.org/raster?opentopoID=OTSRTM.082015.4326.1

You can try the marine-geo.org web server wich provide ASTER dataset
