### ISSUE TITLE
Problem with loading own WMS

### ISSUE THREAD

**Issue by Niki1986** [domlysz/BlenderGIS#416]
# **Blender and OS versions**

### Blender 2.90 with Windows 10

# **Describe the bug**

### I come from the GIS field, but I am pretty new with Blender. Something mus be wrong with my code, but I cannot find the problem. I only get a greay image when trying to import my own WMS with BlenderGIS. Maybe someone can help me?

# **How to Reproduce**

```
GRIDS = {
        "UTM33N" : {
		"name" : 'UTM33N',
		"description" : 'utm33n projection',
		"CRS": 'EPSG:32633',
		"bbox": [166021.4431, 0.0000, 833978.5569, 9329005.1825], #w,s,e,n
		"bboxCRS": 'EPSG:32633',
		"tileSize": 256,
		"originLoc": "NW", #North West or South West
		"resFactor" : 2
	}, 
SOURCES = {
        "Ortho_Stmk" : {
		"name" : 'Ortho',
		"description" : 'Ortho Stmk',
		"service": 'WMS',
		"grid": 'UTM33N',
		"quadTree": False,
		"layers" : {
			"OrthoWMS" : {"urlKey" : 'orthofotos_wms', "name" : 'OrthoWMS', "description" : '', "format" : 'jpeg',"style" : '', "zmin" : 0, "zmax" : 20},
		},
		"urlTemplate": {
			"BASE_URL" : 'https://gis.stmk.gv.at/arcgis/services/wms/orthofotos_wms/ImageServer/WMSServer?',
			"SERVICE" : 'WMS',
			"VERSION" : '1.1.1',
			"REQUEST" : 'GetMap',
			"SRS" : '{CRS}', #EPSG:xxxx
			"LAYERS" : '{LAY}',
			"FORMAT" : 'image/{FORMAT}',
			"STYLES" : '{STYLE}',
			"BBOX" : '{BBOX}', #xmin,ymin,xmax,ymax, in "SRS" projection
			"WIDTH" : '{WIDTH}',
			"HEIGHT" : '{HEIGHT}',
			"TRANSPARENT" : "False"
			},
		"referer": "https://gis.stmk.gv.at/arcgis/rest/services/"
	},
```

# **Error message**

**Comment by domlysz** [comment]
According to the [server capabilities](https://gis.stmk.gv.at/arcgis/services/wms/orthofotos_wms/ImageServer/WMSServer?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities), the layer name is not "orthofotos_wms" but "0".

Urls are reported in BlenderGIS logs, so you can test them in your web browser to understand what could be wrong.

Also when starting the basemaps operator, the scene origin is set to longitude 0 and latitude 0, so you're outside of the wms bounding box. Just press G and search for a location covered by your wms (for exemple in this case you can search for Graz).

Unfortunatly I still have an issue when reading this WMS : although the urls works correctly in the browser, the addon can't extract a valid stream from them. I don't know what's wrong but still investigate.

**Comment by domlysz** [comment]
I've finally found the origin of the issue and made a quick update to fix it. Please reinstall the addon with the updated code and then it should work as expected if you replace `"urlKey" : 'orthofotos_wms'` by `"urlKey" : '0'`

**Comment by Niki1986** [comment]
Awesome. Thank you very much! It finally worked. Btw, your tool is pretty cool! 👍

**Comment by Niki1986** [comment]
I have one last question: Is it also possible to use a WMS as height information instead of the SRTM?
Thanks a lot!

**Comment by domlysz** [comment]
The get SRTM operator is a shortcut to other webservice:
https://www.opentopography.org/developers
https://www.gmrt.org/services/gridserverinfo.php#!/services/getGMRTGrid

As you can see these 2 API are pretty simple and share the same kind of url template, but it's not a WMS. I don't think a WMS can be used to provides DEM data because the protocol is limited to RGB(A) 8bits images but a DEM is typically stored into an one band image coded in 16 or 32bits

**Comment by Niki1986** [comment]
Ok yes, I see the problem. Thanks for your very quick response and the info. It really helped me a lot!
