### ISSUE TITLE
Locked zoom issue, Not exporting

### ISSUE THREAD

**Issue by nccwarp9** [domlysz/BlenderGIS#417]
# **Blender and OS versions**
Blender 2.9 and Windows 10

# **Describe the bug**
If large area is locked (zoom level 13) and then zoomed to level 16 and all tiles are downloaded (mosaic is created) but pressing E does nothing. 
No error messages pop up.

**Comment by domlysz** [comment]
Sound like the texture is too large. By default when you press E the image is then packed into the blend file, I've the feeling it's where it fails especially if it works correctly with smaller images.

A possible workaround : 
- save your blend file
- run the basemaps operator, navigate the map to your area of interest and download extra tiles with the lock zoom option
- do not press E, just escape the basemaps operator
- in the folder of your blend file, you'll see the full mosaic image, this file can then be reimported in blender with the operator Import>Georeferenced raster

This way you can bypass the packing step

**Comment by wisdomware** [comment]
I am having the same issue as @nccwarp9.

@domlysz, thanks for your help. I followed your instructions and was able to import the raster file. However, the image (texture) is much darker than the original map. Do you know how I can brighten up the texture?

**Comment by nccwarp9** [comment]
Thank you for the response, I did it the hard way, importing and merged every block together... Not fun
Looks like this is the solution, I have not tried it but @wisdomware seams to have. Regarding the texture, you can increase its brightness via brightness node or simply increasing it in some external editor.

**Comment by alberoman** [comment]
The solution of reimporting the raster worked great for me! Thanks for this great addon
