### ISSUE TITLE
Unable to Enable Add-on

### ISSUE THREAD

**Issue by jacst20** [domlysz/BlenderGIS#418]
When clicking the box to enable the add-on, I am greeted with this message.
![image](https://user-images.githubusercontent.com/71477369/100034095-12a9fb80-2dc1-11eb-804a-b6452ef76901.png)

**Comment by domlysz** [comment]
![Sans titre](https://user-images.githubusercontent.com/5639024/100061211-05772600-2e2e-11eb-9e55-6adc932e3692.jpg)
