### ISSUE TITLE
Capture a square size basemap 

### ISSUE THREAD

**Issue by mnhan32** [domlysz/BlenderGIS#419]
# **Blender and OS versions**

Windows 10, Blender 2.8.2a

I could not figure out how to control basemap capture size ratio. Is there a way to capture a square size area?

**Comment by domlysz** [comment]
The capture area is defined by 2 factors :
1. the ratio of your 3d view area
2. the number of tiles needed to cover the geographic area (the map is composed of tiles of 256px)

So, you can resize your 3dview, however if the center of your area of interest does not match the center of the tile grid needed to cover this area then you will not able to grab a square area. But who care, just cut your mesh as you want afterwards

**Comment by mnhan32** [comment]
Thanks for the reply.
I will then cut the mesh afterward.
