### ISSUE TITLE
Download not as Zip

### ISSUE THREAD

**Issue by megsKTa** [domlysz/BlenderGIS#420]
# **Blender and OS versions**

 2.90.1

# **Describe the bug**

Sorry I am very beginner at this but I cannot get the GIS zip to download properly- it downloads as a file and then I cannot get that to input as an add-on. Then even when I try to install the components the GIS does not pop up on my blender screen. 
# **How to Reproduce**

**Comment by domlysz** [comment]
If you had downloaded the zip from the [release page](https://github.com/domlysz/BlenderGIS/releases), it sould be fixed now (the previous filename contain an illegal dot character).
