### ISSUE TITLE
2.2.5 questions

### ISSUE THREAD

**Issue by Git-Talking** [domlysz/BlenderGIS#421]
# **Blender and OS versions**

2.2.5 BlenderGIS, Blender 2.9.1 Master branch, KDE Neon Ubuntu 5.4.0-54
# **Describe the bug**
Two things. One, Bing georaster provides a bright purple rectangle. Texture contour is there (SRTM seems to work) but no colors. Just purple. Two, if I extrude the mesh along -Z (identical behavior here for google or bing basemaps) the object goes bonkers. It explodes.

Honestly, I have no idea.
# **How to Reproduce**
1- Find a locale. I'm using a zoom level of 15 (jordan craters).
2 - Push e.
3 - Get SRTM.
4 - Tab to edit-mode.
5 - NUMpad-1, then extrude a small or large amount (it doesn't matter) to -Z.
6 - Select object-mode.
7 - Begin confusion.
![Screenshot_20201125_014004](https://user-images.githubusercontent.com/61361257/100198667-bda1de80-2ec1-11eb-88bc-6b166320f94f.png)

DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13098198.674922382, 5342680.109539707, -13094410.264708, 5345061.600702218)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:12 tiles requested, 12 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13100214.384805575, 5341507.8279191, -13092637.564376809, 5346270.81024412)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13104488.814123964, 5339200.19259918, -13089335.173266428, 5348726.157249221)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:12 tiles requested, 12 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13112551.653656736, 5334511.06611675, -13082244.371941663, 5353562.995416831)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:12 tiles requested, 12 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13128191.313618276, 5325058.957309301, -13067576.75018813, 5363162.815909461)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:12 tiles requested, 12 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13158984.614437353, 5306080.883851811, -13037755.487577062, 5382288.6010521315)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 34 already in cache, 1 remains to download
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://mt0.google.com/vt/lyrs=s&x=351&y=748&z=11
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13124052.941120718, 5323852.506511266, -13063438.377690572, 5361956.365111426)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 24 already in cache, 11 remains to download
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://mt0.google.com/vt/lyrs=s&x=711&y=1499&z=12
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://mt0.google.com/vt/lyrs=s&x=707&y=1499&z=12
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://mt0.google.com/vt/lyrs=s&x=706&y=1503&z=12
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://mt0.google.com/vt/lyrs=s&x=706&y=1499&z=12
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://mt0.google.com/vt/lyrs=s&x=712&y=1499&z=12
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://mt0.google.com/vt/lyrs=s&x=706&y=1500&z=12
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://mt0.google.com/vt/lyrs=s&x=708&y=1499&z=12
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://mt0.google.com/vt/lyrs=s&x=709&y=1499&z=12
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://mt0.google.com/vt/lyrs=s&x=706&y=1501&z=12
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://mt0.google.com/vt/lyrs=s&x=710&y=1499&z=12
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://mt0.google.com/vt/lyrs=s&x=706&y=1502&z=12
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13106587.1044624, 5332738.317840993, -13076279.822747327, 5351790.247141074)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:28 tiles requested, 28 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13097854.213721132, 5337181.231135252, -13082700.572863596, 5346707.195785292)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:28 tiles requested, 28 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13103500.805518007, 5339072.982600096, -13088347.16466047, 5348598.947250136)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:40 tiles requested, 40 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13099635.960901156, 5341294.439247225, -13092059.14047239, 5346057.421572245)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:40 tiles requested, 40 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13099927.33938016, 5341485.507087802, -13092350.518951394, 5346248.489412821)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13097978.202266132, 5342579.524573048, -13094189.79205175, 5344961.015735558)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13097877.91070882, 5342353.8685519295, -13094089.500494437, 5344735.35971444)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13097877.91070882, 5342353.8685519295, -13094089.500494437, 5344735.35971444)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13097877.91070882, 5342353.8685519295, -13094089.500494437, 5344735.35971444)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13097877.91070882, 5342353.8685519295, -13094089.500494437, 5344735.35971444)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.io_get_srtm:97:https://portal.opentopography.org/API/globaldem?demtype=SRTMGL1&west=-117.66557421946511&east=-117.62312207058886&south=43.19516728276294&north=43.219186648190124&outputFormat=GTiff
WARNING:BlenderGIS-master.core.georaster.georaster:145:Cannot extract georefencing informations from tif tags
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-124138625.90493649, -72009795.60689884, 124138625.90493649, 72009795.60689884)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 1 already in cache, 34 remains to download
DEBUG:BlenderGIS-master.operators.lib.osm.nominatim:26:Nominatim search request : https://nominatim.openstreetmap.org/search?format=json&q=jordan+craters&limit=10
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:1013:Nominatim search results : ['Jordan Craters, West Cow Creek Road, Malheur County, Oregon, United States of America']
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13078265.027084922, 5324612.669054486, -13063111.386227386, 5333402.927307282)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13078265.027084922, 5324612.669054486, -13063111.386227386, 5333402.927307282)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13090819.37767086, 5332676.499620892, -13075665.736813324, 5341466.757873688)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:28 tiles requested, 28 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13093752.547836876, 5335351.7044548765, -13078598.90697934, 5344141.962707672)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:32 tiles requested, 32 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13099083.847641563, 5337205.239122845, -13083930.206784027, 5345995.497375641)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:28 tiles requested, 28 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13103536.1513525, 5339326.2942986265, -13088382.510494964, 5348116.552551422)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:40 tiles requested, 40 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13099102.825854912, 5341031.812292001, -13091526.005426146, 5345426.941418399)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:28 tiles requested, 28 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13099814.553638116, 5341590.685705087, -13092237.73320935, 5345985.814831485)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13099862.320605889, 5341313.637334726, -13092285.500177123, 5345708.766461124)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.io_get_srtm:97:https://portal.opentopography.org/API/globaldem?demtype=SRTMGL1&west=-117.68754687713616&east=-117.60664257719048&south=43.18715769612346&north=43.2311951144528&outputFormat=GTiff
WARNING:BlenderGIS-master.core.georaster.georaster:145:Cannot extract georefencing informations from tif tags
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13099862.320605889, 5341129.710735414, -13092285.500177123, 5345892.6930604335)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 0 already in cache, 35 remains to download
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303203?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303300?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303213?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321010?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303312?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303200?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321000?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321011?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303320?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303201?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321100?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303211?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303202?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321101?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303230?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303322?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321110?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303233?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303321?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303330?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303220?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303323?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303232?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303223?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303231?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303303?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303332?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303222?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303210?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303221?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303301?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303310?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303212?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303302?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321001?it=A
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13098161.571690714, 5342247.611696918, -13094373.16147633, 5344629.102859428)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 0 already in cache, 35 remains to download
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032303?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032122?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033022?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033212?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033230?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033221?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032302?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032311?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033222?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032310?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032301?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033200?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032323?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033232?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033203?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032320?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032333?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032312?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032123?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033023?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033202?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032330?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033032?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032321?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032313?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033210?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032132?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033201?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032133?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032322?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033223?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032331?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032300?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223033220?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/0212330223032332?it=A
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13099867.097293511, 5341110.603946779, -13092290.276864745, 5345873.586271798)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13099131.486087456, 5340026.293888185, -13091554.66565869, 5344789.2762132045)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 24 already in cache, 11 remains to download
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321012?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321013?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321003?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303331?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321113?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303333?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321112?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321103?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321102?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303313?it=A
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022321111?it=A
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13098735.020328179, 5340417.982975099, -13091158.199899413, 5345180.965300119)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13098773.23389019, 5340723.691501711, -13091196.413461424, 5345486.67382673)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:35 tiles requested, 35 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13099661.699405327, 5341296.895053957, -13092084.878976561, 5346059.877378976)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:40 tiles requested, 39 already in cache, 1 remains to download
DEBUG:BlenderGIS-master.core.basemaps.mapservice:578:http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/021233022303311?it=A
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13099661.699405327, 5341296.895053957, -13092084.878976561, 5346059.877378976)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:40 tiles requested, 40 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13099666.476016656, 5341306.4485207535, -13092089.65558789, 5346069.430845773)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:40 tiles requested, 40 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.io_get_srtm:97:https://portal.opentopography.org/API/globaldem?demtype=SRTMGL1&west=-117.6875468739835&east=-117.59565625048708&south=43.187157696073484&north=43.23119511440286&outputFormat=GTiff
WARNING:BlenderGIS-master.core.georaster.georaster:145:Cannot extract georefencing informations from tif tags
DEBUG:BlenderGIS-master.operators.view3d_mapviewer:201:Bounding box request : (-13099666.476016656, 5341306.4485207535, -13092089.65558789, 5346069.430845773)
DEBUG:BlenderGIS-master.core.basemaps.mapservice:724:40 tiles requested, 40 already in cache, 0 remains to download
DEBUG:BlenderGIS-master.operators.io_get_srtm:97:https://portal.opentopography.org/API/globaldem?demtype=SRTMGL1&west=-117.6875468739835&east=-117.59565625048708&south=43.187157696073484&north=43.23119511440286&outputFormat=GTiff
WARNING:BlenderGIS-master.core.georaster.georaster:145:Cannot extract georefencing informations from tif tags

**Comment by domlysz** [comment]
About the purple color, sound like your viewport shading is missconfigured

![image](https://user-images.githubusercontent.com/5639024/100207500-f2388900-2f07-11eb-9b23-1f7655ccc196.png)

About the second point; you should apply the modifers (subsurf and displacer) before editing your mesh
