### ISSUE TITLE
CRS information being lost

### ISSUE THREAD

**Issue by olivercrask** [domlysz/BlenderGIS#424]
# **Blender and OS versions**

Blender 2.91
BlenderGIS 2.2.5
Ubuntu Budgie 20.04.1 LTS

# **Describe the bug**

I have been trying to import a shapefile, extrude it and then export as an STL retaining the CRS information, but the CRS details seem to be lost in the process.

In a previous version of BlenderGIS (v1 actually, haven't tried any newer ones until now), this worked fine but does not seem to work anymore.

# **How to Reproduce**

Imported shapefile with the following settings

![image](https://user-images.githubusercontent.com/36341776/101160580-3114c000-3627-11eb-943e-4182fcc21d55.png)

The workspace is also set to the same CRS in the BlenderGIS settings menu as shown:
![image](https://user-images.githubusercontent.com/36341776/101160666-51447f00-3627-11eb-8100-6dadc6f037f2.png)

I then noticed that the location of the object does not match the coordinates of this shapefile in the chosen CRS (not sure if this is the issue?).

![image](https://user-images.githubusercontent.com/36341776/101160765-79cc7900-3627-11eb-8fd5-28a4d1d2e368.png)

Then tried to export as STL using File, Export, STL using the following settings:
![image](https://user-images.githubusercontent.com/36341776/101160826-9668b100-3627-11eb-9770-0f43192e24e7.png)

When viewing the STL in another program (MeshLab), there is no sign of the coordinate reference system.
![image](https://user-images.githubusercontent.com/36341776/101160895-b009f880-3627-11eb-84e5-4c5593513c50.png)

Based on the CRS defined, I would have expected the min max to be around:
384200,345550
385200,346550

**Comment by domlysz** [comment]
https://github.com/domlysz/BlenderGIS/wiki/Georeferencing-management

The origin of the scene is georeferenced but the STL exporter does not take this offset into consideration.

**Comment by olivercrask** [comment]
The georeference of the scene does not match what would be expected though. If I move the object to the correct position in Blender, the STL exporter does retain this information.

**Comment by olivercrask** [comment]
And this was working fine in v1 of BlenderGIS

**Comment by olivercrask** [comment]
From my experience I'm finding that importing shapefiles with the BNG referencing system (British National Grid) is not resulting in the correct georeferencing.

It is not due to any steps following the import (I was only moving the model to correct the wrong georeferenced position.
