### ISSUE TITLE
module unavailiable

### ISSUE THREAD

**Issue by pandabackhome** [domlysz/BlenderGIS#425]
Hi! cool boy!
found bundled python: /snap/blender/50/2.83/python
DEBUG:BlenderGIS-225.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-225.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-225.core.checkdeps:Pillow unavailable
DEBUG:BlenderGIS-225.core.checkdeps:ImageIO Freeimage plugin available
Registered Carver
Registered Power Sequencer with 3 modules
Info: Deleted 3 object(s)

DEBUG:BlenderGIS-225.operators.view3d_mapviewer:Bounding box request : (-119990235.5058434, -72949053.8104671, 119990235.5058434, 72949053.8104671)
DEBUG:BlenderGIS-225.core.basemaps.mapservice:35 tiles requested, 0 already in cache, 35 remains to download
DEBUG:BlenderGIS-225.core.basemaps.mapservice:http://mt0.google.com/vt/lyrs=s&x=0&y=0&z=0
ERROR:BlenderGIS-225.core.basemaps.mapservice:Can't download tile x0 y0. Error <urlopen error timed out>
DEBUG:BlenderGIS-225.core.basemaps.mapservice:Invalid tile data for request http://mt0.google.com/vt/lyrs=s&x=0&y=0&z=0

when using google map,nothing show,and this is terminal shows.
looks like python env do not have gdal,pyproj,pollow module.
so....what should i do to avoid this ..tks.

**Comment by domlysz** [comment]
There is nothing wrong with these missing modules, there are totally optional. This issue duplicate already openned ones about the basemap operator : #367 #390
