### ISSUE TITLE
Basemap overlapped

### ISSUE THREAD

**Issue by CHIAHSUNCHIANG** [domlysz/BlenderGIS#428]
Hi, I would like to know when merging multiple basemaps, is there any way to avoid the map be overlapped?
 Thank you
![1](https://user-images.githubusercontent.com/56967515/101888376-03a4b500-3bd9-11eb-9577-24d9ae975f8a.png)
![2](https://user-images.githubusercontent.com/56967515/101888391-07d0d280-3bd9-11eb-9f57-7a768e07a99a.png)

**Comment by domlysz** [comment]
no but you can use L shortcut to grab a larger area https://github.com/domlysz/BlenderGIS/wiki/Basemaps
