### ISSUE TITLE
No Basemap shows

### ISSUE THREAD

**Issue by PandaBalls** [domlysz/BlenderGIS#431]
After downloading and installed freeimage library manually .  No error reported..
But nothing showed after downloading basemaps, it is downloaded tiles, and .gis got files.
Nothing showed.
![image](https://user-images.githubusercontent.com/22102700/103547851-e5805b00-4edf-11eb-9a77-4011a7d30a32.png)

**Comment by domlysz** [comment]
This issue duplicate #367 and does not respect the issue tempate
