### ISSUE TITLE
not working on blender 2.91.0

### ISSUE THREAD

**Issue by EliottDup** [domlysz/BlenderGIS#436]
# **Blender and OS versions**

blender 2.91.0
windows 10

# **Describe the bug**

when importing web geodata from basemap, no map shows

# **How to Reproduce**

go to GIS -> Web Geodata -> Basemap -> any source -> ok
a map should show but it doesn't

**Comment by beshad** [comment]
i am having the same problem too, doesn't seem to wok in ver2.91.

**Comment by domlysz** [comment]
related to #367 or #390, please report an useful log message to one of this thread instead of open another issue
As far as I an test it work correctly with 2.91
