### ISSUE TITLE
Blender ver. 2.83.12 Base Map from google loads then I am stuck in zooming. I cannot select buttons around the map 

### ISSUE THREAD

**Issue by jfmaps** [domlysz/BlenderGIS#438]
# **Blender and OS version 2.83.12**

Base Map from google loads then I am stuck in zooming. I cannot select buttons around the map the buttons are unresponsive.
https://github.com/domlysz/BlenderGIS/issues/289

#  I am new to this platform but I will try my best to explain. once I got the google map image to load and appear after selecting this button image attached fig 1 
![image](https://user-images.githubusercontent.com/78522445/106845738-8eee7400-6679-11eb-8e14-e8cfb44eb4c2.png) fig.1
I was able to zoom in and out and the google map appeared and worked. However I can no longer select anything within the window. I can only zoom I am not sure how to make this function again. areas I can not selct attached here fig. 2 
![image](https://user-images.githubusercontent.com/78522445/106846046-20f67c80-667a-11eb-8f28-cc158a7b8b7e.png)

# **How to Reproduce**

# **Error message**

no error message received

**Comment by domlysz** [comment]
Like all modal operator in Blender you just need to press echap to exit the tool. Please take a time to read the doc : https://github.com/domlysz/BlenderGIS/wiki/Basemaps
