### ISSUE TITLE
not showing elevated 3d contour shapefile

### ISSUE THREAD

**Issue by di700** [domlysz/BlenderGIS#440]
I am using blender 2.91.2 version with gis blender add on. I am unable to add contour shapefile with elevation..imported file is in 2D..and i want it in 3D.. I have extracted the contours from DEM file in Qgis and saved it as .shp file...I have also changed  the the field name as ELV. I have attached file showing result..I want to do terrain modelling it is my clg project actually so its urgent!! plz help!!and one more doubt...after making terrain model can i put 3D model on specific latitude,logitude or cordinates on that terrain model...how can i check latitude,longitude or cordinates of that terrain?
I tried resizing the scale,zooming in,changing focal length..but didnt get the expected result
![iss2](https://user-images.githubusercontent.com/78613770/107071748-30f19600-680b-11eb-813c-72b339b3e144.JPG)

![issue](https://user-images.githubusercontent.com/78613770/107071655-0dc6e680-680b-11eb-83e0-1e936974d43b.JPG)
![iss1](https://user-images.githubusercontent.com/78613770/107071687-1cad9900-680b-11eb-8460-ea3beea44fd2.JPG)

**Comment by domlysz** [comment]
can you share the shp?

**Comment by domlysz** [comment]
cannot reproduce, no enough info
