### ISSUE TITLE
instant crash when creating delaunay mesh

### ISSUE THREAD

**Issue by lacienega** [domlysz/BlenderGIS#447]
Hello I am really stuck on multiple instant crashes when trying to generate mesh from shp file properly created with qgis. 

Using blender 2.91 on Mac. It won't freeze and become unresponsive, Blender disappears.

Are there any issue with this kind on shp file? Should I reset the transform settings applied during the import?

Please note, Voronoi mesh works fine although i have no use for it
 .

Thank you
<img width="979" alt="Screenshot 2021-02-20 at 09 11 27" src="https://user-images.githubusercontent.com/75408769/108588935-0b60a280-735c-11eb-8b33-9ff79e63c654.png">
<img width="866" alt="Screenshot 2021-02-20 at 09 10 42" src="https://user-images.githubusercontent.com/75408769/108588937-0f8cc000-735c-11eb-92b1-971ff4027fc1.png">
<img width="1358" alt="Screenshot 2021-02-20 at 09 16 31" src="https://user-images.githubusercontent.com/75408769/108588974-57abe280-735c-11eb-9412-2ee5d06c99e8.png">

**Comment by domlysz** [comment]
is it crash with all shp or just this one ?

**Comment by lacienega** [comment]
same crash with any shp coming out of qgis. I tried various landscapes already. This one has 10 levels of contour height

**Comment by domlysz** [comment]
Is it work if you try to triangulate a circle ?
menu add > mesh > circle then menu gis > mesh > delaunay

**Comment by lacienega** [comment]
yes it works [fine.](url) attached is my shp file let me know if you can make a delaunay out of it?
<img width="724" alt="Screenshot 2021-02-20 at 15 10 28" src="https://user-images.githubusercontent.com/75408769/108598437-d0776280-738d-11eb-85f3-72aa05d986eb.png">
[contours ecrins 3d.zip](https://github.com/domlysz/BlenderGIS/files/6015127/contours.ecrins.3d.zip)

**Comment by domlysz** [comment]
It works correctly for me on Linux, but I suggest you to reproject your shapefile into a metric projection system (like Lambert 93 for France), because actually the coordinates of your file are angulars (longitude/latitude in degrees) while altitudes are in meters, see FAQ : https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-after-the-import-of-my-data-the-resulting-mesh-is-extremely-small-on-x-and-y-axis-but-seems-correct-on-z-axis-

**Comment by lacienega** [comment]
brilliant! that now works. I did not know the used CRS was built this way. Many thanks again and bravo for this plugin.
