### ISSUE TITLE
Create/change attributs before exporting shpfile

### ISSUE THREAD

**Issue by omtransfaire** [domlysz/BlenderGIS#449]
Hi,

Can we modify or create attributs before exporting a model in shpfile ?

**Comment by domlysz** [comment]
https://github.com/domlysz/BlenderGIS/wiki/Shapefile-import

> Importing into separate objects also offers the ability to handle attributes data into Blender. For each newly created object, feature's attributes data will be assigned as new custom properties. Then, when re-exporting this collection of objects into a new shapefile, theses custom properties are well taken into account.
