### ISSUE TITLE
cnc

### ISSUE THREAD

**Issue by saode** [domlysz/BlenderGIS#450]
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy_extras\io_utils.py", line 75, in invoke
    if not self.filepath:
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy_types.py", line 720, in __getattribute__
    return getattr(properties, attr)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 24: invalid continuation byte

location: <unknown location>:-1

![problm](https://user-images.githubusercontent.com/79753783/109389222-ad642a00-791c-11eb-9423-60d3ce07f43d.png)

**Comment by domlysz** [comment]
please respect the issue template, how can you expect any help without even explaining what function you're trying to use ???

**Comment by saode** [comment]
![problm11](https://user-images.githubusercontent.com/79753783/109395756-1bb9e400-793f-11eb-9f6e-af177e487e1b.png)


Mount export stl

**Comment by domlysz** [comment]
The STL exporter is not a functionality provided by the BlenderGIS addon.
