### ISSUE TITLE
Cache Folder?

### ISSUE THREAD

**Issue by daniloulf** [domlysz/BlenderGIS#46]
"Please define a valid cache folder path ... " when I try to use this. Serveral path I did enter but the message appears ever.

**Comment by domlysz** [comment]
You must define this path in the addon preferences

![selection_003](https://cloud.githubusercontent.com/assets/5639024/17836210/f4b679a2-6789-11e6-9ee1-6587602ec289.jpg)

**Comment by domlysz** [comment]
is it fixed for you ?

**Comment by domlysz** [comment]
#118

**Comment by Heryx** [comment]
Hi, 
It gives me the same problem, but I don't have the cache folder. I use Windows OS.

**Comment by domlysz** [comment]
Have you choose a path in addon preferences like in the screenshoot above ?

**Comment by Heryx** [comment]
I can not find the path for maps_cache

**Comment by domlysz** [comment]
You can select whatever folder you want. For example you can create a new folder in your desktop named "mapscache" and choose this new folder. The addon will just use this folder destination to store downloaded basemaps images and reuse them when needed for increasing display speed.

**Comment by Heryx** [comment]
Ok thanks, I get it.
