### ISSUE TITLE
shapefile buildings show not good

### ISSUE THREAD

**Issue by skypan** [domlysz/BlenderGIS#468]
i imported the shapefile from blendergis, but the effect is below :
![image](https://user-images.githubusercontent.com/11325807/114151740-04174780-9950-11eb-8813-a03f21448026.png)

i don't know how to do

the shapefile is below 
[房屋面.zip](https://github.com/domlysz/BlenderGIS/files/6284269/default.zip)

Can you help me

**Comment by domlysz** [comment]
Your shapefile should be in a metric projection

https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-after-the-import-of-my-data-the-resulting-mesh-is-extremely-small-on-x-and-y-axis-but-seems-correct-on-z-axis-
