### ISSUE TITLE
field selection options do not show up in Ubuntu 16.04 LTS when importing SHP file

### ISSUE THREAD

**Issue by glw** [domlysz/BlenderGIS#48]
Hi I have blender 2.77a installed on Ubuntu 16.04 along with your great add on. Unfortunately I have not been able to successfully use it on linux (although I have tried on Windows 7 and it worked fine). What Im getting when importing a SHP file is after checking the box next to either "Elevation from field", or "Extrusion from field", no dropdown appears with field options.

Thanks!

**Comment by domlysz** [comment]
I've no problem with Ubuntu, are you sure your shapefile contains some numerical fields ?

Can you start Blender through a terminal and report to me any error message ?

Thanks

**Comment by glw** [comment]
I gave it a shot. Nothing looks abnormal. Here's the output:
    
    Read shapefile...
    Feature type : PolyLineZ
    0%, 10%, 20%, 30%, 40%, 50%, 60%, 70%, 80%, 90%, 100%
    Build in 4.585808 seconds
    Read new prefs: /home/glw/.config/blender/2.77/config/userpref.blend
    Saved session recovery to '/tmp/quit.blend'
    
    Blender quit

I created the shapefile using gdal, which also created the elevation field (which is numerical). 

I was able to successfully import the same shapefile on a Windows 7 installation.

**Comment by domlysz** [comment]
Is the problem appear only with this shapefile or with any shapefiles you tried. If the issue concerns only this shp, can you join me the file ?

**Comment by domlysz** [comment]
ok I get the same bug with Blender 2.78 rc1 (but its ok for me with 2.77a), seems popup update is broken in 2.78 version

**Comment by domlysz** [comment]
https://developer.blender.org/T49246

can you confirm to me the problem come from 2.78 and not 2.77

**Comment by domlysz** [comment]
As explained in the above bug report, you can solve the issue by setting Window Draw Method to Triple Buffer in user Preferences / System.

**Comment by glw** [comment]
@domlysz sorry for the late reply. I just tested blender with the updated setting and it is now working. Thank you for the updates and fix on the issue.
