### ISSUE TITLE
Adding Mac OSX & Linux support in documentation

### ISSUE THREAD

**Issue by kikislater** [domlysz/BlenderGIS#5]
Hi Dominique,

I saw your great Wiki and the installation for gdal python bindings inside blender ont this page : https://github.com/domlysz/BlenderGIS/wiki/How-to-install-GDAL
It's very helpfull but there is windows only installation. I don't use Windows. According to you, I would want to add other plateform to your wiki.

**Mac Osx**
*Tested on Yosemite 10.10 and Blender 2.74*
**1) Install Xcode and Macports from this link :**
 https://www.macports.org/install.php

**2) Install gdal and gdal python bindings**
Open a terminal from spotlight or from Applications => Utilities => Terminal
Then type with administratives rights : 
> sudo port install gdal py34-gdal

**3) Copy osgeo folder from python bindings to blender**
> cp -rf /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/osgeo /**where_you_put_blender_on_your_mac**/Blender/blender.app/Contents/Resources/2.74/scripts/modules/

Replace **where_you_put_blender_on_your_mac** with the path where you run or install Blender

Test it in Blender Python console like windows installation.

---------------
I think there is a mistake in the wiki with this : 
*Finally, to get GDAL working in Blender, just copy osgeo folder in Python tree folder of Blender (C:\Program Files\Blender Foundation\Blender\2.70\python\lib\site-packages).*
If I put the osgeo folder in the same path like you recommand (**python/lib/site-packages**), I'm not able to launch gdal from blender. When I put osgeo in blender's module folder, It works ! 

Sorry for my poor english, I'm french ...

Sincerely,

Sylvain

**Comment by domlysz** [comment]
Bonjour Sylvain on peut parler français pour se faciliter la tache !

Pas de problème pour ajouter ces infos dans le wiki, d'autant plus + que ça fait un moment que je dois également y ajouter la procédure d'installation pour linux.  Je maitrise pas trop github je ne sais pas si tu peux faire directement la modif dans le projet sans faire un fork ?

Pour moi il n'y a pas d'erreur dans le chemin, il s'agit bien de l'installation de Python spécifique à Blender (.../2.7x\python\lib\site-packages). En tout cas cette méthode fonctionne pour window et linux. Cela-dit j'ai déjà vu d'autres script qui installaient les librairies tiers dans le dossier "modules", je dirait que les 2 solutions sont viables mais ça m'étonne que ça ne fonctionne pas avec le dossier site-package. Je vais essayer d'éclaircir tout ça, mais d'une manière générale cette méthode d'instalaltion (copy/paste du dossier osgeo) est une mauvaise partique qu'il faudrait éviter par une alternative plus fiable.

**Comment by kikislater** [comment]
Oui en français c'est mieux du coup :+1: 
Je ne maitrise pas non plus github ... Du moins moins que toi !

Une méthode alternative du copy/paste serait un lien symbolique sous UNIX (Osx et Gnu/Linux) mais sous Windows .... 
De quelle distribution linux vas-tu faire la procédure ?

**Comment by domlysz** [comment]
Salut,

J'ai mis à jour le wiki avec ton texte pour mac. J'ai pas encore rédiger de procédure pour linux, c'était surtout des notes de compilation pour Opensuse mais depuis je suis passé à Mint et les dépôts sont plus à jour ce qui évite de compiler soit même.

Le problème du copier/coller c'est surtout qu'il peut toujours y avoir des incompatibilités, par exemple actuellement sur mon poste j'ai le package python-gdal installé, le tout fonctionne très bien avec mon installation local de python 3.4 (la même version qui est embarqué dans Blender 2.75) et pourtant lorsque je copie le dossier osgeo dans le dossier sites-package ou modules de Blender ça ne fonctionne pas, Python lève une erreur.

J'ai également rencontré ce genre de problème sous Windows, il semble que pour avoir une compatibilité parfaite il faut que la version du compilateur utiliser pour le package gdal-python soit la même que celle utilisée pour compiler Python lui-même ...

**Comment by kikislater** [comment]
Salut,

Ok merci pour l'info. Je repasse un serveur sous Ubuntu 15.04 en ce moment. J'en aurais pas besoin sur le serveur mais je testerais à l'occasion pour voir ce qui ne va pas ... 
Pour la version du compilateur, je l'ai déjà fait, si la version du compilateur est dispo dans les dépôts (ce qui n'est pas toujours le cas) c'est ok. Je regarderais pour recompiler gdal-python.
Tu as installé blender depuis quel source : dépôt ubuntu, site officiel, ppa:irie, ppa:thomas-schiex, une build custom via graphicall.org ?

**Comment by domlysz** [comment]
Je récupere directement le tarball depuis le site de Blender, c'est déjà compilé il suffit d'executer le binaire. Dans cette archive la version de Python livrée avec Blender est compilé via GCC 4.7.1 alors que ma version locale de Python, installée depuis les dépôts officiels, est compilée via GCC 4.8.2. Compiler soit-même Blender j'avais testé une fois j'ai vite capitulé !

**Comment by kikislater** [comment]
Ok, ben je testerais dans ce cas avec les dépôts ppa qui doivent supporter la bonne version du ppa.
Blender je le compilais sans trop de problème ... Je te ferais un retour sur les solutions

**Comment by kikislater** [comment]
Salut Dominique,

J'ai une installation fonctionnelle sous Ubuntu 15.04 de ton addon. Voici la procédure : 
# 1) Ajout du dépôt PPA Blender 
sudo add-apt-repository ppa:thomas-schiex/blender
# 2) On recharge les dépôts : 
sudo apt-get update
# 3) On installe Blender : 
sudo apt-get install blender
# 4) On installe Gdal python 3 bindings : 
sudo apt-get install python3-gdal
# 5) Création du lien symbolique pour linker gdal python 3 bindings dans Blender : 
sudo ln -s /usr/lib/python3/dist-packages/osgeo/ /usr/share/blender/2.76/scripts/modules/
# 6) Test de l'installation comme sous windows dans la console python Blender
from osgeo import gdal
# 7) Téléchargements de l'addon BlenderGIS et copie dans le bon répertoire : 
unzip BlenderGIS-master.zip 
cp -rf BlenderGIS-master/* ~/.config/blender/2.76/scripts/addons/

Note : à tester l'étape 5 doit pouvoir se substituer dans le ~/.config/blender/2.76/scripts/modules au lieu de /usr/share/blender/2.76/scripts/modules mais non testé pour ma part

**Comment by domlysz** [comment]
Merci pour ton retour!

Rien à faire de mon coté même avec un lien symbolique ça ne fonctionne pas. J'essaye de compiler/installer python-gdal avec la version de python de Blender mais sans succés pour le moment.

**Comment by kikislater** [comment]
Étrange, mais avec le dépôt du ppa de thomas schieix, ça ne fonctionne pas dans mint!?
Tu sais que tu peux rajouter le dépôt et recompiler à partir des deb-src du dépôt en question. Tu as les options de compilation, ça évite de te les retaper ...
Enfin je me rappelle, j'avais mint fût un temps, j'avais bien aimé mais j'avais vite déchanté sur des configurations impossible à mettre en place notamment un partage samba alors que sur ubuntu et debian équivalent en terme de version il  n'y avais pas de problèmes. C'est le problème de mint de mon point de vue c'est que des fois on ne sait pas ce qui a été modifié par rapport à la source debian/ubuntu.
Ça te donne quoi comme erreur à la compilation ?

**Comment by domlysz** [comment]
Finalement j'ai réussi à installer le binding python de gdal avec l'interpreteur livré avec Blender et ça fonctionne!

J'ai récupéré les sources du paquet sur pypi : https://pypi.python.org/pypi/GDAL/2.0.0

Comme le module distutils n'est pas livré avec les libs python de blender j'ai fait un lien symbolique
ln -s /usr/lib/python3.4/distutils ~/Blender/2.76/python/lib/python3.4

Idem avec le module lib2to3 nécessaire pour installation
ln -s /usr/lib/python3.4/lib2to3 ~/Blender/2.76/python/lib/python3.4

J'ai ensuite lancé la compilation du module
~/Blender/2.76/python/bin/python3.4 ./setup.py build_ext --include-dirs=/usr/include/gdal:/usr/include/python3.4

puis l'installation
~/Blender/2.76/python/bin/python3.4 ./setup.py install --prefix=~/Blender/2.76/python

Comme quoi, installer un module qui nécessite de la compilation peut donner des résultats differents et incompatibles même avec des interpréteurs Python ayant le même numéro de version.

**Comment by kikislater** [comment]
Intéressant même si ce n'est pas la méthode que j'aurais choisi. Mais pour ceux qui ne veulent pas installer blender via un dépôt ça me paraît une bonne méthode.

**Comment by domlysz** [comment]
Salut,

J'ai essayé via le dépot c'est que c'est assez pratique puisqu'il utilise l'installation Python du syteme, du coup il n'y a même pas besoin de faire un lien symbolique vers le module osgeo! En revanche cette méthode n'est valable que pour les distributions basées sur debian. De mémoire sur OpenSuse c'était assez galere de trouver un rpm à jour de Blender, d'où cette d'habitude d'utiliser le tarball dispo sur blender.org. En tout cas merci j'ai assez d'élèments pour mettre à jour le wiki !

**Comment by kikislater** [comment]
Salut,

Ok je comprends, tu voulais une installation toutes distributions confondues, c'est vrai que je suis plus adepte aux distro debian/ubuntu puisque j'ai longtemps travaillé avec. J'ai une connaissance qui est sous opensuse, je peux lui demander mais de mémoire il existe un site pour chercher les packages et les installer en 1 click. =>  https://software.opensuse.org/package/blender

**Comment by domlysz** [comment]
Oui sous opensuse il y a moyen de faire des installations très simplement, mais vraiment d'une manière générale pour beaucoup de logiciels les mises à jour mettent une plombe à arriver (Blender 2.71 sur le lien précédent!). C'est toujours pénible quand on se retrouve à devoir compiler soit-même et qu'on a pas particulierement la compétence. Enfin c'est ce qui m'a fait changer de distri et sur ce point là en particulier je regrette pas.

**Comment by kikislater** [comment]
De l'expérience perso que j'ai, si on doit tout recompiler, le plus simple c'est de s'inspirer des packages archlinux, c'est assez complet.
Exemple ici : https://www.archlinux.org/packages/community/x86_64/blender/ Il faut ensuite regarder le pkgbuild pour s'en inspirer lors de la compilation https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/blender

**Comment by Guzzman33** [comment]
Hello Dominique,

I get this error in Blender-pythonmode: 

>>> from osgeo import gdal
>>> from osgeo import gdalnumeric
RuntimeError: module compiled against API version a but this version of numpy is 9
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/Applications/blender.app/Contents/Resources/2.76/scripts/modules/osgeo/gdalnumeric.py", line 1, in <module>
    from osgeo.gdal_array import *
  File "/Applications/blender.app/Contents/Resources/2.76/scripts/modules/osgeo/gdal_array.py", line 25, in <module>
    _gdal_array = swig_import_helper()
  File "/Applications/blender.app/Contents/Resources/2.76/scripts/modules/osgeo/gdal_array.py", line 21, in swig_import_helper
    _mod = imp.load_module('_gdal_array', fp, pathname, description)
  File "/Applications/blender.app/Contents/Resources/2.76/python/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: numpy.core.multiarray failed to import

>>> 

Any ideas on this?

Thanks in advance!

**Comment by kikislater** [comment]
Je suis passé sous Archlinux donc je proposes l'installation sous Arch : 
1) yaourt -Syua python-gdal
2) pacman -Syu python3-numpy
Lancer Blender une première fois puis : 
3) ln -s /usr/lib/python3.5/site-packages/osgeo/ ~/.config/blender/2.76/scripts/addons/
4) Placer BlenderGIS dans ~/.config/blender/2.76/scripts/addons/

**Comment by kikislater** [comment]
@Guzzman33 There is a problem with numpy. Try : 
brew install numpy

**Comment by Guzzman33** [comment]
Hello Dominique,

I reinstalled numpy with brew, but no luck! The terminal sends back this message: "Warning: homebrew/python/numpy-1.10.1 already installed". 
When I try to run the python commands in Blender it spells the same message as I posted earlier.

Perhaps numpy is of a too high number?

**Comment by domlysz** [comment]
@Guzzman33 it seems the version of numpy shipped with Blender (v. 1.9) is not the same that the one used to compil gdal python binding (v1.10). I know this annoying problem, try to install numpy 1.9 and compil yourself gdal python with this version.

@kikislater merci pour ce retour sur Arch. Je travail actuellement sur un nouvel addon pour blenderGIS qui permet d'analyser les caractéristiques d'un terrain : altitudes, pente et azimuth. Peu-être que ça t’intéressera !?

**Comment by kikislater** [comment]
Bonjour Dominique,

Oui ça m'intéresse bien sûr ! 
Si tu veux mon retour d'expérience => 
- Actuellement je me sers du calcul de volume présent dans le module impression 3d. Je vais essayer à l'occasion de l'adapter pour qu'il s'affiche en mètres. L'inconvénient c'est qu'il faut générer des faces sous le modèle 3D. Mais ça peut être très intéressant, de connaitre le volume de n'importe quelle partie d'un MNT en le détourant au couteau ou par un contour de shape vu que je fais ça plus rapidement en SIG :D , extraction de la zone puis remplissage automatique de face sous le modèle pour arriver au calcul du volume.
- Modeler le terrain est intéresant sous Blender. L'applatissement automatique d'une zone se fait facilement dans blender. En revanche quand il faut faire l'applatissement en fonction de la pente moyenne pour avoir un résultat plus parlant, j'ai pas trop cherché mais c'est mon axe d'amélioration.

PS : J'ai demandé aux dev's Blender pour le float64, ils sont pas du tout chaud et ont peur des performances en nette baisse. Cependant ça n'a pas l'air compliqué à modifier, c'est juste une variable. Pareil je testerais à l'occasion.

**Comment by domlysz** [comment]
Salut Sylvain, désolé pour le délais de réponse. Merci beaucoup pour les suggestions, terrassement et calcul de cubature : tout un programme!

Dommage pour le float64 mais bon il faut garder à l'esprit que Blender n'est pas un outil à vocation sciences et techniques.

De mon côté, j'ai uploadé le nouveau code et commencé à rédiger le wiki, give it a try !

**Comment by kikislater** [comment]
Pas mal le wiki, ça donne des idées !
