### ISSUE TITLE
Georeferencing

### ISSUE THREAD

**Issue by Archeo3D** [domlysz/BlenderGIS#50]
Hello, sorry if my question sounds easy, but I'm new in this.

I am trying to use BlenderGIS to georefence a 3D model in Blender. I managed to install the addon, but i can't find any CRS in Geoscene preferences. I want to use Lambert-93 (EPSG:2154 with transformation : 1671, according to epsg.io). I tryed to type these different codes in the Query, but keyword searh doesn't seem to work ... 

What can I do ? 
Thank you

**Comment by domlysz** [comment]
Hi,

Do you speak french ?

In the Query text box just type 2154 **and then press enter** in the result listbox you will see RGF93 / Lambert93

**Comment by domlysz** [comment]
also using the search tool is optional you can just write your CRS en the definition text box following the form EPSG:xxxx

![2016-11-08 11_36_30-blender user preferences](https://cloud.githubusercontent.com/assets/5639024/20095889/ad4fad84-a5a7-11e6-8079-667fdab18d96.jpg)

**Comment by Archeo3D** [comment]
Hi, thank you for your answer !
Yes I speak french, why ?

It's working when I directly write the Definition ! But not with the Query text box. 

Then, I have another problem ... Now I am trying to set the Geo Origin : I wrote a value for Longitude, pressed Enter, and the value came back to zero. Why ? 

Thank you for your help !
