### ISSUE TITLE
2.78 map viewer

### ISSUE THREAD

**Issue by s-leger** [domlysz/BlenderGIS#51]
Hi,
Map viewer fails to download background images under windows 10 and 2.78a
Have to setup :
- GDAL-2.0.3-cp35-cp35m-win_amd64.whl
- numpy-1.11.2+mkl-cp35-cp35m-win_amd64.whl

**Comment by domlysz** [comment]
Hi s-leger,

I have no problem for my part, can you report some error message from the console window?

thx

**Comment by s-leger** [comment]
Hi domlysz,
If i recall correctly, gdal complains about missing array type (the one used to store pixel data).
