### ISSUE TITLE
Import point shapefiles as objects and scale by attribute

### ISSUE THREAD

**Issue by BenjiDa** [domlysz/BlenderGIS#52]
Love this plugin!  I'm wondering if it can import shapefiles that are scaled by size to a certain attribute? Right now all i can get is a set of vertices that i cannot seem to convert into objects (see image).  Also see question [here](https://blender.stackexchange.com/questions/67720/blendergis-shapefile-import-convert-to-sphere-objects).

<img width="537" alt="screen shot 2016-11-22 at 12 55 42 pm" src="https://cloud.githubusercontent.com/assets/18178879/20535676/ce2c7656-b0b3-11e6-8d37-c95d60657bf7.png">

**Comment by domlysz** [comment]
Don't know if it can help but I've just added a basic support for attribute data : if you import your points as separate objects then all objects will contains custom properties representing its attributes. Maybe you can then re-use this property in a dedicated script to do your task
