### ISSUE TITLE
Now, I want to download GIS data shapefile on Blender, I need the information on elevation as well in building data how can I do that?

### ISSUE THREAD

**Issue by SuperKatrina123** [domlysz/BlenderGIS#524]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by domlysz** [comment]
NOt sure to correctly understand your problem. If your shapefile of buidings has no information about ground altitude you can drop the objects to an existing relief mesh

https://github.com/domlysz/BlenderGIS/wiki/Shapefile-import#elevation-and-extrusion
