### ISSUE TITLE
Info on front page of repo is out of date.

### ISSUE THREAD

**Issue by shawty** [domlysz/BlenderGIS#528]
The front page of this repo states:

"Minimum Version required 2.8"

By default Ubuntu 20.04 ships with Blender Version 2.82a

When trying to enable the GIS plugin under this version of GIS, a trace back is thrown stating the plug requires

"Version 2.83 of Blender or Higher"

Your front page minimum version needs to be amended so that folks like myself installing direct from UB20.04 don't go ahead and try to install the GIS addon and have problems installing.

Tks.

**Comment by shawty** [comment]
Addendum: If Ubuntu 20.04 install their version of blender using "snap" rather than using "apt install" then they will have no issues, as the base version for that is v2.93

**Comment by domlysz** [comment]
fixed, thanks
