### ISSUE TITLE
SRTM creating new mesh instead of elevating the 2d image into a 3d one 

### ISSUE THREAD

**Issue by Madcatxx** [domlysz/BlenderGIS#536]
# **Blender and OS versions**

Blender 2.93 Windows
# **Describe the bug**

after doing the SRTM, New elevated mesh show up without satellite image
# **How to Reproduce**

# **Error message**

**Comment by domlysz** [comment]
https://github.com/domlysz/BlenderGIS/issues/537#issuecomment-929051749
