### ISSUE TITLE
GIS Missing Material Properties After Get Elevation (SRTM)

### ISSUE THREAD

**Issue by PJBHyperQ** [domlysz/BlenderGIS#537]
Blender 2.92 Windows 10

I have created a GIS basemap. After attempting to generate an elevation mesh with Get Elevation (SRTM) a 3D terrain mesh is generated. The result does not show the terrain image GOOGLE_SAT_WM embedded into the mesh. In previous attempts I successfully generated an EXPORT_GOOGLE_SAT_WM which included Materials Properties. Now all I get is an empty mesh labeled srtm and the GOOGLE_SAT_WM 2 D flat image sitting nearby.

![GIS Capture](https://user-images.githubusercontent.com/91504656/134994332-d57c5381-087e-4a1e-acdf-223a68c8209e.PNG)

# **Error message**

ERROR:BlenderGIS-master.core.basemaps.mapservice:590:Can't download tile x2860649 y1690517. Error HTTP Error 404: Not Found

DEBUG:BlenderGIS-master.core.basemaps.mapservice:600:Invalid tile data for request http://mt0.google.com/vt/lyrs=s&x=2860504&y=1690604&z=22
ERROR:BlenderGIS-master.core.basemaps.mapservice:590:Can't download tile x2860622 y1690504. Error HTTP Error 404: Not Found
DEBUG:BlenderGIS-master.core.basemaps.mapservice:600:Invalid tile data for request http://mt0.google.com/vt/lyrs=s&x=2860622&y=1690504&z=22
DEBUG:BlenderGIS-master.operators.io_get_dem:103:https://portal.opentopography.org/API/globaldem?demtype=SRTMGL1&west=65.49957094395339&east=65.55802523740688&south=32.90843049267729&north=32.94499412531914&outputFormat=GTiff
WARNING:BlenderGIS-master.core.georaster.georaster:145:Cannot extract georefencing informations from tif tags
DEBUG:BlenderGIS-master.operators.io_get_dem:103:https://portal.opentopography.org/API/globaldem?demtype=SRTMGL1&west=65.46818210165357&east=65.58876234494997&south=32.89068996855384&north=32.96440421093734&outputFormat=GTiff
WARNING:BlenderGIS-master.core.georaster.georaster:145:Cannot extract georefencing informations from tif tags
DEBUG:BlenderGIS-master.operators.io_get_dem:103:https://portal.opentopography.org/API/globaldem?demtype=SRTMGL1&west=65.49836163744466&east=65.55858280915889&south=32.90835581919676&north=32.94597587349106&outputFormat=GTiff
WARNING:BlenderGIS-master.core.georaster.georaster:145:Cannot extract georefencing informations from tif tags

**Comment by PJBHyperQ** [comment]
Correction,
Blender Version 2.93.2

**Comment by domlysz** [comment]
If you want to apply the relief on an existing textured plane, you just need to select it before executing the _Get elevation_ operator, otherwise it'll generate a new separate mesh.

The _non overlap data_ error means that your raster does not share a common geographic area with the plane, probably because of a different projection system.

Others messages are just warnings or debug help with no incidence.

**Comment by PJBHyperQ** [comment]
I have repeated this process multiple times. Here are a series of screen shots demonstrating the fault.

The texture plane was most definitely selected prior to the Get elevation process.

Note that no Material Properties were created.

Additionally, no changes were made including any difference with the projection when trying Import - Georeferenced raster. How do I ensure I have a common geographic area?

![Exported GOOGLE_SAT_WM](https://user-images.githubusercontent.com/91504656/135180225-1cffe0b1-f38c-4918-83db-d9171a55d9e0.PNG)

![Exported GOOGLE_SAT_WM Selected](https://user-images.githubusercontent.com/91504656/135180322-2fd0e58b-b034-43d9-b3c8-3436c191cf11.PNG)

![Exported GOOGLE_SAT_WM Selected Get Elevation](https://user-images.githubusercontent.com/91504656/135180341-5836c660-c040-4737-ab17-1325addade64.PNG)

![Exported GOOGLE_SAT_WM and SRTM Elevation Mesh](https://user-images.githubusercontent.com/91504656/135180345-d72009e8-29e6-43c8-bc0b-8dd2d09c1361.PNG)

![Exported GOOGLE_SAT_WM and SRTM Elevation Mesh 2 No Material Properties](https://user-images.githubusercontent.com/91504656/135180365-7746bbd7-a508-45ce-9c14-a070bec3db74.PNG)

**Comment by domlysz** [comment]
You missing a step, you've to export the basemap to a new plane mesh with the E shortcut. Please refer to the quick start guide.

https://github.com/domlysz/BlenderGIS/wiki/Quick-start

**Comment by PJBHyperQ** [comment]
After many trials I have found that the failure only occurs after I lock the file and zoom. In this case the EXPORT_GOOGLE_SAT_WM is not produced, only the GOOGLE_SAT_WM is generated.
Grab Google map
Lock image
Zoom three levels of magnification 
E to export but Blender does not respond. Something fails after tile download. No  EXPORT_GOOGLE_SAT_WM is created.

**Comment by adampann** [comment]
@PJBHyperQ I'm experiencing the same issue when locking the image.

**Comment by PJBHyperQ** [comment]
?Hi Adam,


I eventually found the cause.


There were a couple of vertices at almost identical locations which generated partial and overlapping planes. They almost impossible to see. I went into edit mode and merged or deleted every nearby vertex and recreated each plane. That fixed the problem.


Kind regards

Peter

HYPER Q AEROSPACE
***@***.***
www.hyperqaerospace.com
+61 414 40 5898
0414 40 5898
________________________________

**Comment by adampann** [comment]
@PJBHyperQ Thanks for responding. Can you go into a little more detail on what exactly you had to do to fix it. I have a GOOGLE_SAT_WM but when I lock the map and zoom it and not able to create the exported version. Did you have to edit the GOOGLE_SAT_WM or something else?

**Comment by kefonelove** [comment]
Hi! Maybe this video could help https://youtu.be/rR2W5U_GXwc

**Comment by NeonIndica** [comment]
hi guys, for anyone who runs into this in future - I could not, for the life of me, get this to work when using the locked zoom function with L. But i seem to have found a work around.

Once locked and zoomed to the correct resolution, wait until 'creating mosaic' message disappears. When I press E, nothing happens, and when I press ESC, it creates a TIF but with the original resolution and not the intended resolution. However, if i spam E and ESC at the same time, i get the TIF at the correct resolution.

When i then click 'get STRM' it creates a separate plane that is untextured. Simply create a material, add an image texture, and select the TIF file that is already in your scene. 

Dont ask me why, but you dont have to even plug the damn thing in - it just textures it anyway. Very confusing, this bug plagued me for many months and ive wasted countless hours trying to fix it. Hope this works for someone in future

EDIT: Sometimes it just works. I have no idea why it does sometimes and doesnt other times. FML

<img width="1185" height="846" alt="Image" src="https://github.com/user-attachments/assets/3cc5bbac-94e2-4b5c-a1b3-4e52f4cf45a0" />
