### ISSUE TITLE
i got an error message when trying to use the addon

### ISSUE THREAD

**Issue by thelazerprincess** [domlysz/BlenderGIS#541]
![IMG_0557](https://user-images.githubusercontent.com/91613582/135281054-362e300c-e5c7-4a44-b0eb-21ec50ed516a.jpg)

**Comment by domlysz** [comment]
The error message is explicit : update Blender

**Comment by domlysz** [comment]
![Sans titre](https://user-images.githubusercontent.com/5639024/137350820-7c1c691c-c482-495a-aa60-f268f27e5901.jpg)

![Sans titre2](https://user-images.githubusercontent.com/5639024/137350649-2efc150b-e8df-44a0-82b3-1c8aa5fabfb3.jpg)

2.82 < 2.83 < 2.93

I don't think you tried to figure out the problem on your own for just one second
