### ISSUE TITLE
DLL Load failed when importing _ssl - Win 10 - are my ENV variables confused?

### ISSUE THREAD

**Issue by diopsidedesign** [domlysz/BlenderGIS#564]
# **Blender and OS versions**

2.93.1   Win 10 

# **Describe the bug**

I have suddenly started getting an exception about "DLL Load failed when importing _ssl: The specified module could not be found" and the plugin fails to load.

I hate to raise an issue about this because I'm 90% sure its something I did, but i'm not sure where else to ask. I say that because I have made zero changes to my Blender install or config since the last time I worked with this plugin a few months ago, and it was working great the last time (as it usually does).  

The issue might be some changes I made to my environment variables. In the past few months I have been doing a bunch of workflow automation scripting with GDAL and Saga GIS and during the course of that project I added a bunch of additional paths to my PYTHONPATH , PATH, and related GDAL environment variables - so now there is a lot of redundancy and probably even varying versions of the same python tools in my paths. The only other "significant" change i've made to my system in the last few months is I enabled a "beta feature" in Win 10 that sets the default system-wide encoding to UTF-8. I can't imagine that would have anything to do with this, but i've heard rumors that such a change can cause things to start behaving oddly on windows so i dunno...  

Before i start experimenting with resetting/editing those variables (im afraid to break my fragile Saga GIS setup lol)   I figured i'd ask here to make sure I'm not way off base. 

i checked and my blender\2.93\python\DLLs directory contains _ssl.pyd and libssl-1_1.dll in the right places that the program expects them to be in, so i'm thinking somehow it has been told to not look in the right place.

Thoughts?

If you think it may indeed be the ENV variable changes, should I just tweak PYTHON_PATH or also my system PATH and other GDAL variables?

Traceback points to 
" ((( blender program files directory ))) 2.93\scripts\modules\addon_utils.py" line 351 in enable mod = _import_(modulename)
" ((( my user app data directory ))) 2.93\scripts\addons\BlenderGISMaster\_init_.py   import ssl
" ((( blender program files directory ))) 2.93\python\lib\ssl.py" line 98 in module import _ssl  
 
 I poked around the relevant .py files but couldn't really see any obvious (to me) red flags. 
 
# **How to Reproduce**

Be me on my computer , mess with a bunch of your path settings and forget what changes you made, months later try to enable BlenderGIS add-on,  cry.    :D 

# **Error message**

and thank you for this amazing plugin, it has turned what used to be an incredibly tedious workflow into a breeze and allowed me to make some really amazing stuff

**Comment by domlysz** [comment]
Hi,

Sorry for the late answer. Sound like related to the PYTHONPATH setup, probably a missmatch between the Python version used by Blender the version targeted by your PYTHONPATH from where the DLLs will be loaded.

However this post seems to indicate that pythonpath is now ignored : https://blender.stackexchange.com/questions/172421/pythonpath-ignored

**Comment by diopsidedesign** [comment]
Update - Plugin has been working great after a nuke-from-orbit-and-reinstall-everything approach. It was definitely something screwy with my machine's configuration / paths. I've actually started using the Blender portable version whenever possible, to hopefully avoid these problems in the future. Thanks !
