### ISSUE TITLE
Plane displacement not working

### ISSUE THREAD

**Issue by hellocatfood** [domlysz/BlenderGIS#572]
# **Blender and OS versions**

2.93.3
Ubuntu 21.10

# **Describe the bug**

After importing a basemap I try to get elevation data but it displace the plane. Instead the plane is still flat but is elevated and moved from its original location (see below screenshot).

![Screenshot from 2021-11-16 22-23-01](https://user-images.githubusercontent.com/151947/142240337-c85c3055-669b-4dd8-a9c9-f966c656d508.png)

# **How to Reproduce**

* Open Blender
* Go to GIS > Web geodata > Basemap
* Press `g` and to Birmingham in the `Go to` field. Select Zoom level 19
* Press `e` to export to a plane
* With the plane selected go to GIS > Web geodata > Get elevation (SRTM) and choose any of the options

Here's my blender file for reference

[birmingham.zip](https://github.com/domlysz/BlenderGIS/files/7556289/birmingham.zip)

# **Error message**

None

**Comment by domlysz** [comment]
Strange, it works correctly for me

![image](https://user-images.githubusercontent.com/5639024/142396774-14a3c4be-1a8d-43bd-94a3-7c0e393ffaab.png)

**Comment by Ronaldo04** [comment]
Is there a new version BlenderGIS for blender 3.0? Because, when I installed version 2.6.6 in blender 3.0, I got a warning, "Development version".
![image](https://user-images.githubusercontent.com/79734315/144794715-f2e3aca4-5e34-4278-a06d-8658f4931b45.png)

**Comment by ImAlwaysInFaMouS** [comment]
![image](https://user-images.githubusercontent.com/67481220/149209634-bf0ef39b-3980-48a3-8629-c738aea14a81.png)

This always happens to mine. 

latest release, blender 2.83

**Comment by domlysz** [comment]
Please report any error message, I can't do anything without it 
![image](https://user-images.githubusercontent.com/5639024/170485449-19fdf3d1-f97b-4f2f-b9de-c0ab3329fd81.png)

**Comment by hellocatfood** [comment]
Seems to be working now with 2.2.7.
![Screenshot from 2022-05-28 20-55-52](https://user-images.githubusercontent.com/151947/170841042-d9cb7689-e97c-4364-af85-620ba488d7dc.png)

Attaching my log file just in case there's anything significant

[logfile.txt](https://github.com/domlysz/BlenderGIS/files/8791781/logfile.txt)
