### ISSUE TITLE
Problems with GIS on MBP M1 MAX

### ISSUE THREAD

**Issue by larie438** [domlysz/BlenderGIS#573]
# **Blender and OS versions**

Blender Version 2.93.5 (2.93.5 2021-10-06) 
MacOS 12.0.1 on MBP M1 Max
GIS version 2.2.5
GIS version 2.2.6

# **Describe the bug**

when going to GIS > webgeodata > basemap > leaving all setting stock and pressing ok nothing shows up on the screen 
the only information showing are:
Map View : zoom 0 - scale 1:1 (2,4)
Top Orthographic
(1) collection
10 centimeters

everything else is the normal grey blender grid 

# **How to Reproduce**

See above

# **Error message**

No error message displayed 

![Screen Shot 2021-11-18 at 3 24 23 AM](https://user-images.githubusercontent.com/65664183/142378760-7959b907-235d-4668-8bfc-21a4ea7f2723.png)

![Screen Shot 2021-11-18 at 3 20 31 AM](https://user-images.githubusercontent.com/65664183/142378411-65dc7409-cf00-419f-a323-9394e678705e.png)

![Screen Shot 2021-11-18 at 3 23 40 AM](https://user-images.githubusercontent.com/65664183/142378653-aadac156-ad9b-4eee-965f-bbdd93223ccd.png)

[bgis.log](https://github.com/domlysz/BlenderGIS/files/7561259/bgis.log)

**Comment by flightmansam** [comment]
What was the solution? I have the same problem...

**Comment by larie438** [comment]
> What was the solution? I have the same problem...

If I remember correctly I had to revert to an older version of Blender and it started working again
