### ISSUE TITLE
Does not work on MacBook

### ISSUE THREAD

**Issue by aammrroo** [domlysz/BlenderGIS#588]
Hello, 

I'm using Blender 3.0 and I've tried to add BlenderGIS, however, the GIS tab does not exist at all after installation in the Add-On list.

Thank you

**Comment by Jakke75** [comment]
I had same problem, when I used Safari. Safari opens ZIP-files automatically. When I did same with Chrome I was able to load Zip and add it as quided then the Add-On worked as planned.

**Comment by aammrroo** [comment]
Hi Jakke75, 

I indeed did use Safari before you alluded me to Chrome and now it works so thank you very much! 

Amro
