### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by domlysz** [domlysz/BlenderGIS#59]
* Make first consistent release tagged 1.0

* doc
add gdal_data path info

* ui
update enum index after adding a new crs

* geoscene
ensure scale support
geo append functionnality

* prefs
vector import (shp & osm) >> remove double option

* reproj
epsg.io limit to 100 features or 1000 points
builtin reproj table 3857>4326 & 4326>UTM >> 3857>UTM

* basemaps
add option for setting storage days
background image layer manager >> reorder, view on/off, opacity
when panning, update all existing bkg images location (send a list as parameter)
split getimage() to have a dedicated seedCache(bbox) function

* georaster
reproj via uv mapping or gdal
read crs from geotags

* shp import
attribute data support at ~~import~~ and export
read proj from *.prj using http://prj2epsg.org/apidocs.html service
select & import multiple files
check geom
progress bar
test recent pyshp speed up PR

* shp export
performance tests

* OSM import
extrude or flat option
get height from MNS
interpret roof shape
fix separate objects origin

* terrain analysis
svg ramp parse error (see BA thread)

* georef cam
cam z position parameter

* exif cam

* lib Tyf
read crs from geotags (see georaster)
harmonize jpeg and tiff, implement __iter__, dumps to dict

* Utils tools
drop to ground
display geocoords for selected vertex in edit mode

* SRTM online downloader 
http://www.opentopography.org/developers
http://elevation.bopen.eu/en/stable/quickstart.html

* LIDAR
best lib ?
 pure python laspy (must be updated to py3)
 libLAS python binding
 pylidar, lot of py deps and rely on lastools
 PDAL ?
extrude building footprint with height value from lidar data

**Comment by Symbian9** [comment]
Why you not use check box style?
* [ ] Undone
* [x] Done

**Comment by stuarta0** [comment]
Another one for utils:

* [ ] Numerical digitize to allow addition of point/line features via simple x,y input. See feature in QGIS for reference.
