### ISSUE TITLE
Converting blender coordinate to lat long

### ISSUE THREAD

**Issue by chaserit123** [domlysz/BlenderGIS#596]
# **Blender and OS versions**

Blender 2.83 / Windows 10

# **Describe the bug**

This isn't really a bug more than a question: How would I convert x, y, z to lat, long?

# **How to Reproduce**

N/A
# **Error message**

N/A

**Comment by domlysz** [comment]
You can use this converter
http://epsg.io/transform#s_srs=3857&t_srs=4326

In Blender use the Geo-coordinates tools to obtain correct values according to scene origin offset
![image](https://user-images.githubusercontent.com/5639024/170478482-2788aa61-5af9-4ab5-859e-df18eed84392.png)
