### ISSUE TITLE
Handle missing values when extruding shapes

### ISSUE THREAD

**Issue by ldodds** [domlysz/BlenderGIS#6]
I'm processing a shapefile that has missing values for the variable I'm using to extrude shapes. The values were generated by the QGIS zonal statistics plugin which produces a value of all asterisks, in this case, e.g.:

```
Id         : 0D4F7142E65527B3E050A00A568A259B
Featcode   : 15014
mean       : ************************
```

The version of pyshp bundled here doesn't handle this properly. The latest version at (https://github.com/GeospatialPython/pyshp) returns a value of None in this case.

But this still causes BlenderGIS to error. It would be better to handle these explicitly in your code, e.g. by setting the value to 0 for if the field value is None.

The bundled version of the shapefile library is also two years old so this should be updated too.

**Comment by domlysz** [comment]
Hi

Thanks for your help. I just fix it, please give it a try.
