### ISSUE TITLE
Dimensions from google maps

### ISSUE THREAD

**Issue by IosifStalin** [domlysz/BlenderGIS#616]
![изображение](https://user-images.githubusercontent.com/36739597/153727803-ccfb6bff-d6c6-4c1f-a237-ec2a75eb4a77.png)
![изображение](https://user-images.githubusercontent.com/36739597/153727826-c4b3bdf6-1797-4aea-bfc5-9e77429de04d.png)
The dimensions of the map do not match the actual dimensions from google maps. How to fix it?

**Comment by pl4sma2389** [comment]
I have noticed this too. Every time I import a basemap, the scale is off by ~1.45x (the imported model is larger than real life). I need to manually scale the model each time.

**Comment by domlysz** [comment]
duplicate #607


That's a side effect of the Mercator projection

https://github.com/domlysz/BlenderGIS/wiki/FAQ#why-my-measurements-on-basemaps-reference-seems-wrong-
