### ISSUE TITLE
Report: Error Cannot reach OpenTopography web service, check logs for more infos

### ISSUE THREAD

**Issue by gamil2** [domlysz/BlenderGIS#619]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by gamil2** [comment]
Report: Error Cannot reach OpenTopography web service, check logs for more infos

**Comment by Andwilcon** [comment]
Same issue

**Comment by lobnico** [comment]
I created a pull request with proper modification. You will need an api key from opentopography.org then put it in settings: https://github.com/domlysz/BlenderGIS/pull/620

**Comment by aplienemann** [comment]
I have my api key, and inserted the info into the prefs. But I can not get it to work.

**Comment by Aruno1** [comment]
Same issue for me

**Comment by lobnico** [comment]
Until pull request is merged, use files from fork

https://github.com/lobnico/BlenderGIS

then in addon settings you will have an api key field. If you have any further problem please let me know.

**Comment by adachis** [comment]
> I have my api key, and inserted the info into the prefs. But I can not get it to work.

You might be adding the API key in the wrong format and/or not to all relevant URLs.  It works fine if you just append &API_Key={YOUR_API_KEY} to the end of the OpenTopography API call URLs.

**Comment by ArsenHere** [comment]
how do you get and enter an API key?

**Comment by thuijzer** [comment]
The fix:
1. Go to https://portal.opentopography.org/ and register / login
2. Goto https://portal.opentopography.org/lidarAuthorizationInfo and select or create a new API key
3. In the Blender GIS plugin edit the `Url template` of the OpenTopo elevation server and after the URL add: `&API_Key=[your key]`

Now the Blender plugin will send your API key to OpenTopo and it should be working again.

**Comment by J-DBox** [comment]
>     3. In the Blender GIS plugin edit the `Url template` of the OpenTopo elevation server and after the URL add: `&API_Key=[your key]`

You lost me at this step. Help would be appreciated

**Comment by lobnico** [comment]
> 

I made a PR; u can use that branch https://github.com/lobnico/BlenderGIS, then put API key in addon settings

**Comment by J-DBox** [comment]
My issue was just that I didn't have the latest Blender & Blender GIS installed. Rookie error. Thank you though! I really appreciate the response.

**Comment by IIRS-1481** [comment]
Error Cannot reach OpenTopography web service, check logs for more

**Comment by lobnico** [comment]
> Error Cannot reach OpenTopography web service, check logs for more

nani?

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/commit/72cbb0507b80c2116fd4252b9082b6beba170a89
