### ISSUE TITLE
reloading addons (F8) doesn't work for BlenderGIS

### ISSUE THREAD

**Issue by mirlip** [domlysz/BlenderGIS#63]
When reloading addons with F8, BlenderGIS will disappear (on windows, didn't test on Linux). Only restarting Blender solves the problem.

**Comment by domlysz** [comment]
know that, can't found a fix so ... just not reload it :)

**Comment by mirlip** [comment]
ok :) Maybe you could ask on IRC (#Blendercoders or #Blenderpython) what is the root of the issue. When programming addons, it's quite handy to be able to test changes after pressing one key.

**Comment by domlysz** [comment]
Fixed with Blender2.8 update. Reloading F8 shortcut does not exists anymore but bpy.ops.script.reload() can be used in Python console without issue.
