### ISSUE TITLE
gis addon

### ISSUE THREAD

**Issue by hassanhn** [domlysz/BlenderGIS#631]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by hassanhn** [comment]
hello 
I import normally basemap
but when we import elevation to get 3d model i have a issue :cannot reach opentopography web service
how can i solve this problem

**Comment by Helzinka** [comment]
Request need API_Key. To get an api_key go to https://portal.opentopography.org/myopentopo

Edit the request : GIS -> preference -> remote data source -> elevation -> OpenTopography SRTM 90m
add this to the end of the request : &API_Key=yourAPI_key
