### ISSUE TITLE
RE-OPENED ERROR : Cannot reach OpenTopography web service #296

### ISSUE THREAD

**Issue by ENKISUMER** [domlysz/BlenderGIS#643]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by ENKISUMER** [comment]
**HI... I GOT THIS ISSUE AFTER EDITING THE prefs.py   
WHAT SHOULD I DO KNOW...IN ORDER MAYBE LATER MANAGE TO DOWNLOAD THE SRTM DATA? 
THANX**

![BLENDER ISSUE](https://user-images.githubusercontent.com/101708946/158774824-f27039ee-2a46-4ea6-b14d-d3803754d5b5.png)

**Comment by relector-tuxnix** [comment]
I appended '&API_Key=my_key' to the end of the connection string under the addons preferences and it worked just fine. Follow the guide at:

https://opentopography.org/blog/introducing-api-keys-access-opentopography-global-datasets

**Comment by LucoSOU** [comment]
@relector-tuxnix Can you give some more specific instructions (or screenshots) on how you appended the connection sting / where it is located in the addons preferences. Would be a amazing!

**Comment by relector-tuxnix** [comment]
![image](https://user-images.githubusercontent.com/1979197/159186832-d0256ff3-6b86-40f8-878e-757fddb28a7d.png)
![image](https://user-images.githubusercontent.com/1979197/159186869-73effb8f-e0df-4af7-b73c-95367b5118ef.png)

**Comment by 151huang** [comment]
> ![图像](https://user-images.githubusercontent.com/1979197/159186832-d0256ff3-6b86-40f8-878e-757fddb28a7d.png) ![图像](https://user-images.githubusercontent.com/1979197/159186869-73effb8f-e0df-4af7-b73c-95367b5118ef.png)
怎么注册账户，一直注册不上
