### ISSUE TITLE
Importing multiple shapefiles

### ISSUE THREAD

**Issue by kevin1437** [domlysz/BlenderGIS#65]
Hi, just wondering if I can import a multiple .shp files at once in Blender, is there any script that works here ?

**Comment by domlysz** [comment]
Sure you can run the operator directly from Blender own Python console.


Just write something like this
```
shpList = [
"path_to_shapefile1",
"path_to_shapefile2",
"path_to_shapefile3"
]

for path in shpList:
    bpy.ops.importgis.shapefile(filepath=path, shpCRS='EPSG:xxxx', fieldElevName='', fieldExtrudeName='', extrusionAxis='Z', separateObjects=False, fieldObjName='')
```

**Comment by kevin1437** [comment]
Thank you very much for your help :)
