### ISSUE TITLE
Can't enable Addon: cannot import name 'prefs'

### ISSUE THREAD

**Issue by dbworth** [domlysz/BlenderGIS#66]
I'm running Ubuntu 14.04  
I installed Blender like so:  
`sudo apt-get install blender`
This is version 2.69.0  

I installed the BlenderGIS addon from ZIP file, as described here:  
https://github.com/domlysz/BlenderGIS/wiki/Install-and-usage

When I tried to enable the addon I got this error:  

> ImportError: no module named 'numpy'

I copied numpy into my addon directory like this:  
```
cd ~/.config/blender/2.69/scripts/addons
sudo cp -r /usr/lib/python2.7/dist-packages/numpy/ ./
```

Now when I try to enable the addon I get this error:  

> ImportError: cannot import name 'prefs'

Here's a screenshot of the error:  
![blendergis_error](https://cloud.githubusercontent.com/assets/949758/23323360/400942ee-fab6-11e6-9ba9-e7746e1e553b.png)

Thanks in advance.

**Comment by domlysz** [comment]
hi,

This version of Blender is too old, you need at least v2.78 (numpy is now shipped with blender). In ubuntu you can get a more recent version through this ppa : ppa:thomas-schiex/blender, or just download the tarball from blender.org, unzip and run it.

**Comment by dbworth** [comment]
Thanks @domlysz .
Would it be worth adding this to your wiki?
