### ISSUE TITLE
Georender Camera Error in Blender 3.1.0

### ISSUE THREAD

**Issue by woidfeeee** [domlysz/BlenderGIS#660]
# **Blender and OS versions**

Blender 3.1.0
OS: Windows 10

# **Describe the bug**

Getting an error message when adding a georender cam no matter which reference system. (see error message below) The camera gets added but the resolution is not set properly. 

 In Blender V 3.0.0 it worked without problems. 

# **How to Reproduce**

Adding a vector or raster object using BlenderGIS - Select the object - Try to add a georender camera

# **Error message**

```
Python: Traceback (most recent call last):
  File "C:\Users\Valen\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlenderGIS-master\operators\add_camera_georef.py", line 167, in execute
    scn.render.resolution_x = dimx / self.target_res
TypeError: bpy_struct: item.attr = val: RenderSettings.resolution_x expected an int type, not float

location: <unknown location>:-1
```

**Comment by domlysz** [comment]
fixed cff82a29b2c0c72e04b946d7734ba690ec65cde8
