### ISSUE TITLE
Cannot get SRTM Data

### ISSUE THREAD

**Issue by desupero** [domlysz/BlenderGIS#662]
# **Blender and OS versions**

31.2 Windows 10 pro 64 bit
# **Describe the bug**

<--Cannot get SRTM Data-->

# **How to Reproduce**

<--by selecting get srtm data-->

# **Error message**

<--Says cannot reach opentopography service-->

<--![image](https://user-images.githubusercontent.com/6705332/167429417-479fb91c-60da-4b16-a3af-5aba9194be6d.png)-->

**Comment by carstenschluter** [comment]
You need to edit the srtm link. now it requires an api. u need to create an opentopography account (it's free) and generate a link for the srtm you want.

after that u just copy the last section of your link, the api key section, and paste it onto the link that blendergis has

to do that go to preferences, addons, blendergis, scroll down till u see remote datasource elevation. then press the gear icon and paste the api key section of the link

**Comment by SithlordSparky** [comment]
this doesnt work even when you add the api keys

**Comment by domlysz** [comment]
Fixed 72cbb0507b80c2116fd4252b9082b6beba170a89
