### ISSUE TITLE
create .prj file when exporting

### ISSUE THREAD

**Issue by mirlip** [domlysz/BlenderGIS#67]
Hi Domlysz,
many GIS programs need a .prj file to import or at least to place the geometry at the right position. Would it be possible to generate this projection file automatically when exporting?

**Comment by domlysz** [comment]
there is already a support for exporting prj file, but it doesn't work because of a missing return statement
it's fixed now

**Comment by mirlip** [comment]
Perfect, it works :) Thank you for the quick fix.
