### ISSUE TITLE
Need 3.1.2 belnder version ?

### ISSUE THREAD

**Issue by francis33** [domlysz/BlenderGIS#670]
Blender 3.1 - Windows 10

I installed the last version of the add-on (2/2/7) yesterday
I can't activate the add-on in the add-on pannel (edit/preferences/add-ons)

The error message reports than i need to have the 3.1.2 blender version.
Is it a bug ? If not, is the 3.1.2 blender version already available ?  

Best.
Francis

**Comment by Failxxx** [comment]
I also noticed this issue. I think it is unintended. The latest release (v2.2.7) provides an `__init__.py` file with `blender` (in `bl_infos`) set to `(3, 1, 2)`. All you have to do is to replace `(3, 1, 2)` with `(2, 83, 0)`.

**Comment by francis33** [comment]
It works perfectly !
Thanks a lot.

Francis

**Comment by AbdelazizSharaf001** [comment]
I had the same issue (ubuntu LTS 22.04)
@Failxxx got the idea
For anybody who didn't download it
- downloading the master branch directly would do the same (it's edited)
