### ISSUE TITLE
Elevation data from CGIAR

### ISSUE THREAD

**Issue by qaisarehman** [domlysz/BlenderGIS#680]
# **Blender and OS versions**
Blender 3.1 OS Windows 10

# **Describe the bug**

I only have a question that is it possible to get the elevation data from this website.
https://srtm.csi.cgiar.org/srtmdata/

if its possible anyone share the process please.
I have seen a tool in unity engine which can get the elevation data from this service!

# **How to Reproduce**

# **Error message**

**Comment by domlysz** [comment]
You can download the tiff file and then import it with the help of the addon
https://github.com/domlysz/BlenderGIS/wiki/Import-georef-raster
