### ISSUE TITLE
Unable to read geotags

### ISSUE THREAD

**Issue by lfdebrux** [domlysz/BlenderGIS#70]
When importing a georaster, I get the error "Unable to read geotags".

This seems to be the culprit code, 'ModelTransformation' should be 'ModelTransformationTag',

and the assignment of transoMatrix is invalid syntax

	def readGeoTags(self):
		'''Extract geo transformation parameters from a geotiff tags'''
		if not self.isTiff or not self.fileExists:
			return
		tif = Tyf.open(self.path)[0]
		#First search for a matrix transfo
		try:
			#34264: ("ModelTransformation", "a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p")
			# 4x4 transform matrix in 3D space
			transfoMatrix = tif['ModelTransformation']
			a,b,c,d,
			e,f,g,h,
			m,n,o,p = transfoMatrix
			#get only 2d affine parameters
			self.origin = xy(d, h)
			self.pxSize = xy(a, f)
			self.rotation = xy(e, b)
		except:
			#If no matrix, search for upper left coord and pixel scales
			try:
				#33922: ("ModelTiepoint", "I,J,K,X,Y,Z")
				modelTiePoint = tif['ModelTiepointTag']
				#33550 ("ModelPixelScale", "ScaleX, ScaleY, ScaleZ")
				modelPixelScale = tif['ModelPixelScaleTag']
				self.origin = xy(*modelTiePoint[3:5])
				self.pxSize = xy(*modelPixelScale[0:2])
				self.pxSize[1] = -self.pxSize.y #make negative value
				self.rotation = xy(0, 0)
			except:
				raise IOError("Unable to read geotags")

**Comment by domlysz** [comment]
Thank you very mutch, it seems I never tested this block, most of the time geotiff don't use the matrix tag.
Can you submit a PR ?
