### ISSUE TITLE
Cannot import the data for comparatively large extend of area

### ISSUE THREAD

**Issue by vivigb** [domlysz/BlenderGIS#733]
# **Blender and OS versions**

# **Describe the bug**

Blender fails when I try to use  a large area 

# **How to Reproduce**

# **Error message**

**Comment by ferengi82** [comment]
I have the same problem, a 600 MB asc file works fine, one with 3GB crashes Blender (Version 3.3.0) without an error message.
The Machine should be more than capable (16core Xeon, 256GB ram ...)
