### ISSUE TITLE
Too slow downloading large basemap

### ISSUE THREAD

**Issue by torchesburn** [domlysz/BlenderGIS#737]
# **Blender and OS versions**
Win 11 latest as of now and my internet is superfast 1gb

# **Describe the bug**

If I select an area and lock it with zoom 11 or something,. Then try to download maps at zoom 20. It looks like it will take at least
10 hours to download and the number on the bar shows 21198645, which is ridiculous because zoom 20 tile by tile does not take that long, its instant. 

I wanted to know is there anything to be done here? Is this a bug?

**Comment by domlysz** [comment]
If you use the lock option with a large extent then you can potentially have a very large number of tiles to download. In your case there are 21 millions tiles to download, so yes it will takes hours and there is nothing ridiculous here... Grabbing a very large area at an high zoom level represents a important amount of data, even if you can download everything I don't think your computer will be able to build a mosaic that represents about 1 billion pixels...

**Comment by torchesburn** [comment]
The point remains that this is an issue. Nobody wants to download 1 billion pixels. We simply want to tile the whole thing and download it in pieces. That was my point about the way this is done. Its completely backwards and doing too much.

**Comment by domlysz** [comment]
I'm sorry I don't understand your point.
Without the lock option it work as expected in a reasonable speed, just downloading the few tiles needed to cover the current extent **using the proper zoom level for this scale, like any other webmap application**.
The lock option is an extra trick to build a large image with an high zoom level, don't use it if you don't need it. If you want to cover thousands kilometers at zoom level 20 where one pixel represents about 0.15cm then it will require to download a very high number of tile of 256px, I can't change this math things ! But what the point to build an image like this ???
Blender is not a Google Earth engine, it need an image on disc to import in the 3d view, we need to build this image beforehand. I'm not sure of what you expect
