### ISSUE TITLE
Unable to setup Blender GIS

### ISSUE THREAD

**Issue by petekhatsu** [domlysz/BlenderGIS#747]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by basiclaser** [comment]
how far did you get? did you download + install it? what do the logs/logfile say?

**Comment by RMATHEWS951** [comment]
I'm in the GSI preferences tab, trying to add the server key and the instructions say to edit the SRTM server URL to add the opentopography server key.  I don't see a URL to edit?  Where is it?

**Comment by petekhatsu** [comment]
I am able to install BlenderGIS. However, unable to add Satellite Imagery
in the Basemaps.

Error message: "No image library available. ImageIO module was not
correctly installed."
My windows: Widows 10
Blender Version: 3.4

Your valuable suggestions will be highly appreciated.

Regards

Pete Khatsu

**Comment by RMATHEWS951** [comment]
I don’t have an answer for you.  I installed the GSI Add-on and I can load the Basemap but not the satellite hight information. I get a cannot find the opentopography server.  I’m going to try downloading the source code and installing from that, instead of using the zip file.
If it works I’ll let you know.
Ron
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by atseewal** [comment]
> 

If Image IO was not correctly installed, you can try manually adding it. Try the instructions from the FAQ for that error:
https://github.com/domlysz/BlenderGIS/wiki/FAQ#how-to-resolve-the-no-imageio-error-

**Comment by atseewal** [comment]
@RMATHEWS951 

Is the error like this one? This is the error that comes up when you try to make the request with an incorrect or missing API key.
![image](https://user-images.githubusercontent.com/39170343/215909780-15c4b53d-15d1-46ae-bd54-1fc53e643880.png)


If you are trying to add a server key you need to go into **GIS** > **Preferences** and enter your Openopography API key into the **Opentopography Api Key** box or enter it in the Api Key box that comes up when you use the get elevation (SRTM) function.

**Comment by RMATHEWS951** [comment]
Re-downloaded the zip (for the 3rd time) and this time it was installed with the API_key window.  Not sure why it didn’t work the first two times but it’s working now.
Thanks very much,
Ron

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by atseewal** [comment]
Glad it's working now! That's pretty weird that it wasn't showing up...
