### ISSUE TITLE
Macbook M1 12.0.1, Blender version 2.83.20

### ISSUE THREAD

**Issue by HamidM9** [domlysz/BlenderGIS#769]
2.83.20 MacOS: 12.0.1 M1 chip
# **Describe the bug**

I have downloaded for intel chip but I have M1 chip, the geoData, baseMap loads but nothing works, zoom and other things. 
Do you have any suggestions?

**Comment by marilynwaldman** [comment]
I am having the same issue with M1.  Logs:


ERROR:BlenderGIS-master:96:Uncaught exception
ValueError: Could not find a format to write the specified file in mode 'i'

**Comment by domlysz** [comment]
fixed https://github.com/domlysz/BlenderGIS/releases/tag/2210
