### ISSUE TITLE
Basemap don't match SRTM

### ISSUE THREAD

**Issue by Majakaram** [domlysz/BlenderGIS#776]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by Majakaram** [comment]
I have the Problem that the Basemap don't match up with the SRTM. In many Youtube Videos this happens automatically.
I just loaded in the Basemap and added the SRTM.
<img width="1512" alt="Bildschirm­foto 2023-04-03 um 10 53 44" src="https://user-images.githubusercontent.com/91199897/229463290-8e5316e0-5ab0-4c51-b531-3c95959f1a36.png">

**Comment by khf9765** [comment]
i have the same issue

**Comment by Owuraqu** [comment]
A very common issue for me and my students too!

**Comment by domlysz** [comment]
The plane should be selected beforehand if you want to apply the relief on it
