### ISSUE TITLE
Won't export shp

### ISSUE THREAD

**Issue by MartinSpongebob** [domlysz/BlenderGIS#78]
I am getting this error when trying to export as a shp-file.

![export_shp](https://user-images.githubusercontent.com/29976714/27954440-4d6f8160-6310-11e7-98c5-94fdfb0b1522.jpg)

**Comment by domlysz** [comment]
Hi,

It's fixed on the _refactoring_ branch

**Comment by baffioso** [comment]
Thanks for the refactoring branch hint.

**Comment by MartinSpongebob** [comment]
Yes - thanks :-)

**Comment by baffioso** [comment]
Seems like the exported .shp points are missing z-value. Th
![image](https://user-images.githubusercontent.com/7534153/27994497-bde80614-64bf-11e7-983e-afe049c1bc32.png)
Tested on Ubuntu 14.04, Blender 2.78, BlenderGIS refactoring branch

**Comment by domlysz** [comment]
work correctly for me, are you sure your version of qgis can report z values (qgis >= 2.14). you can also try to reimport the shp in blender to check if 3d values are here.

**Comment by baffioso** [comment]
I'm using QGIS 2.18.10 and are going through following steps:

- Saving raster DEM from QGIS
- Importing as raw DEM in BlenderGIS
- Creating Delaunay TIN and Sculping
- Exporting sculped TIN as .shp
- Importing .shp and using value tool to inspect Z-value

This process used to work for me, but suddenly the Z-value is gone. 

When I try to reimport .shp in Blender I get this error:
![image](https://user-images.githubusercontent.com/7534153/27996411-d044def0-64e1-11e7-8d8c-5fc3e36b485b.png)

**Comment by domlysz** [comment]
is it possible to join me the blend file to test ?

**Comment by baffioso** [comment]
Her you go:
https://drive.google.com/file/d/0B8iuB3WPu5_sbkt1MmxsS0hFNU0/view?usp=sharing

**Comment by PayamT** [comment]
Anders, You are right. The Z coordinates are not exported using "point" export. I found the following workaround for your data:
1. Exporting the surface as "Line" 2. Importing them as 3D lines in GIS (I use GRASS GIS). 3. Converting the lines to 3D points4. Interpolating them using BSpline or other interpolation techniques ( i suggest regularized splines with tension). 
See attached. Cheers,P



 

    On Sunday, July 9, 2017 4:11 PM, Anders Barfod <notifications@github.com> wrote:
 

 Her you go:
https://drive.google.com/file/d/0B8iuB3WPu5_sbkt1MmxsS0hFNU0/view?usp=sharing—

**Comment by PayamT** [comment]
btw: Instead of "Raw DEM", I suggest importing your surface with "AS DEM" and applying subdivision to enhance surface representation and details (see here). Delaunay is not an accurate surface interpolation at all, specially for scientific purposes.  

    On Sunday, July 9, 2017 5:12 PM, Payam Tabrizian <payam_tabrizian@yahoo.com> wrote:
 

 Anders, You are right. The Z coordinates are not exported using "point" export. I found the following workaround for your data:
1. Exporting the surface as "Line" 2. Importing them as 3D lines in GIS (I use GRASS GIS). 3. Converting the lines to 3D points4. Interpolating them using BSpline or other interpolation techniques ( i suggest regularized splines with tension). 
See attached. Cheers,P



 

    On Sunday, July 9, 2017 4:11 PM, Anders Barfod <notifications@github.com> wrote:
 

 Her you go:
https://drive.google.com/file/d/0B8iuB3WPu5_sbkt1MmxsS0hFNU0/view?usp=sharing—

**Comment by FraknToastr** [comment]
@domlysz Thanks for refactoring branch tip. Now the SHP export is working again. This is an awesome and incredibly useful addon by the way.

**Comment by domlysz** [comment]
The problem come from the up to date pyshp library on refactoring branch

I've opened an issue
https://github.com/GeospatialPython/pyshp/issues/102

A work around is to replace the file shapefile.py in _addons_folder/core/lib_ by the old version from master branch

**Comment by baffioso** [comment]
@domlysz Copying the shapefile.py worked out perfect. Thank you for solving z-value issue and developing this awesome addon!!

**Comment by domlysz** [comment]
refactoring branch is now merged to master with an old version of pyshp lib

**Comment by baffioso** [comment]
Thanks for the quick fix
