### ISSUE TITLE
Impossible to launch it on Mac M2

### ISSUE THREAD

**Issue by Snoopeez** [domlysz/BlenderGIS#781]
# **Blender and OS versions**

- Mac Mini M2 13.3.1 (16 Go Ram)
- Blender 3.4.1

# **Describe the bug**

I did exactly the same steps as on two differents vids on Youtube, everything looks to be ok, save, but when clicking on (...Google...)Basemap > [ OK ],
- Nothing appears
- Blender crashed once

Tested several times in different ways, still this problem.

Maybe ?
- When downloading on mac, Osx automatically de-compress the .zip, I had to re-zip it (looks to be impossible to install non-ziped files/folder, I'm beginner with Blender..) ; maybe the OsX ".zip" that creates "confusion" ?

If I can do/try something... ✋🏻

# **How to Reproduce**

# **Error message**

Log below
[bgis.log](https://github.com/domlysz/BlenderGIS/files/11224563/bgis.log)

**Comment by domlysz** [comment]
Should be fixed with this release
https://github.com/domlysz/BlenderGIS/releases/tag/2210

Please reopen if not
