### ISSUE TITLE
Scene is not georef

### ISSUE THREAD

**Issue by echohunter20** [domlysz/BlenderGIS#785]
# **Blender and OS versions**
2.903

# **Describe the bug**
when get osm from google,it display "Scene is not georef'
Scene is not georef

# **How to Reproduce**

# **Error message**
Scene is not georef

**Comment by noveoko** [comment]
- Ensure you are using the correct add-on or method to import OSM data into Blender. There are several OSM import add-ons available for Blender, so make sure you are using one that is compatible with your version of Blender (2.903).
- Verify that the OSM data you are trying to import is valid and complete. Sometimes incomplete or corrupt OSM data can cause issues during the import process.
- Check the georeferencing settings in Blender. If the OSM data contains geospatial information, you may need to adjust the georeferencing settings in Blender to correctly position the imported objects in the scene.
- Look for any error messages or warnings in Blender's console or log. These can provide more specific details about the issue and help identify the source of the problem.
- Consider updating Blender to the latest stable version. Newer versions of Blender often come with bug fixes and improvements that might resolve the issue you are facing.

**Comment by softyoda** [comment]
Could you provide a screenshot of where to set-up georef of a scene instead of parroting chat-gpt?

**Comment by domlysz** [comment]
https://github.com/domlysz/BlenderGIS/wiki/Georeferencing-management
