### ISSUE TITLE
Find the coordinate of a slected area(Basemap)

### ISSUE THREAD

**Issue by iamelou** [domlysz/BlenderGIS#786]
Currently using Blender 3.5 with BlenderGIS in v2.83

I am trying to get the coordinate from a selected area. For the moment i could find the coordinate of the upper left corner. But what I am looking for is also the right down corner. Or at least a way to get this coordinate. 

To find the upper left corner coordinate i go tu AppData\Local\Temp\blender_XXXXXX\strm_bgis.wld

In the .wld file i found coordinate at the Line 5 and 6 of the file : 
strm_bgis.wld
"0.0002777777777778146
0
0
-0.0002777777777778146
1.6919444444685063
42.60166666666436"

Two last number are lon and lat of upper right corner.

Could I have some help please ?

**Comment by domlysz** [comment]
if your image 1000x1000px then
x2 = 1.6919444444685063 + 1000 * 0.0002777777777778146
y2 = 42.60166666666436 - 1000 * 0.0002777777777778146
