### ISSUE TITLE
Multiple import

### ISSUE THREAD

**Issue by tonilogar** [domlysz/BlenderGIS#79]
Hi and thanks for your work and time.

I'm using your addon with Dem and ortophotos of Catalonia.
I have finished a project of 100 ortophotos, and the *.blend is fine.
I would like to try with a lot of ortophotos, but I can only import one by one image.
The import file *.py...... Is it possible to edit the importation file in order to import multiple files?

Another option that is problematic for me.
Each time I import a raster file, the display mode changes to solid mode.
This gives me problems when there are to many files.
It would be better that display mode does not change to solid mode.
Thanks  for your work and time.
Regards.

Thanks  for your work and time.

**Comment by domlysz** [comment]
Hi,

For multiple import you can write a simple script and run it from Blender's text editor, something like this

```python
import os

folder = "path/to/your/orthophotos"

for f in os.listdir(folder):
	path = folder + os.sep + f
	basename, ext = os.path.splitext(f)

	#just filter files extension
	if ext not in ['.tif', '.jpg', '.png']:
		continue

	#import
	bpy.ops.importgis.georaster(
	importMode = 'PLANE',
	filepath = path,
	rastCRS = 'EPSG:3857'
	)

```

**Comment by PayamT** [comment]
I think you are referring to auto center and change to solid mode after importing. I also had that problem as I am importing and replacing geospatial data in real-time. 
Find op_import_georaster.py in your addon directory and comment out "adjust3Dview(context, bb)" and "showTextures(context)" at the end of the code. This is a very cool feature but is very problematic for batch processing workflows. 
 if newObjCreated: bb = BBOX.fromObj(obj) #adjust3Dview(context, bb)
 #Force view mode with textures #showTextures(context)
 

   

 On Thursday, July 13, 2017 9:31 AM, domlysz <notifications@github.com> wrote:
 

 Hi,For multiple import you can write a simple script and run it from Blender's text editor, something like thisimport os

folder = "path/to/your/orthophotos"

for f in os.listdir(folder):
	path = folder + os.sep + f
	basename, ext = os.path.splitext(f)

	#just filter files extension
	if ext not in ['.tif', '.jpg', '.png']:
		continue

	#import
	bpy.ops.importgis.georaster(
	importMode = 'PLANE',
	filepath = path,
	rastCRS = 'EPSG:3857'
	)

**Comment by domlysz** [comment]
it definitely need an option to disable this feature

**Comment by PayamT** [comment]
I have implemented that in my own gui, wanted to post that issue a while ago. Thought this is very specific to be on gui. There is one caveat in disabling it though, and that is when you import large terrains (if this feature is disabled) you need to zoom back to find your imported raster. It is misleading, you may think something is wrong with projection / import / etc.   

    On Thursday, July 13, 2017 9:49 AM, domlysz <notifications@github.com> wrote:
 

 it definitely need an option to disable this feature—

**Comment by domlysz** [comment]
I think it can take place in the general addon options instead of operator's GUI, so it will be less exposed but available for advanced users

**Comment by tonilogar** [comment]
Thanks for your help and tips.
All of them work perfectly.

I have 4277 files in the folder but the addon only can import 914 files.
Is there a way for import all files?

I try import in diferent folders with this script.
But it doen't function fine.

import os
import bpy
folders_list = ["G:/ortoCatalunya_0.5/tif0", "G:/ortoCatalunya_0.5/tif01", "G:/ortoCatalunya_0.5/tif02", "G:/ortoCatalunya_0.5/tif03", "G:/ortoCatalunya_0.5/tif04"]

for folder in folders_list:
	for f in os.listdir(folder):
		path = folder + os.sep + f
		basename, ext = os.path.splitext(f)

		#just filter files extension
		if ext not in ['.tif']:
			continue
		
		bpy.ops.importgis.georaster(
		importMode = 'PLANE',
		filepath = path,
		rastCRS = 'EPSG:3857'
		)

Regards.

Thanks for your work and time.

**Comment by domlysz** [comment]
what is the error message ?

not to discourage you but I don't think Blender will be strong enough to handle as many objects an large textures image... I think it will be better if you mosaic all your orthophotos into one unique file and reduce the resolution of the resulting image to a more reasonable value, usuable in a 3d software context.

**Comment by domlysz** [comment]
last version now have some usefull options in the addon preference to disable automatic changes in 3dview settings
![selection_001](https://user-images.githubusercontent.com/5639024/28338267-b1e51be0-6c08-11e7-936e-0595450022b4.jpg)

**Comment by tonilogar** [comment]
Thanks for your help domlysz.
The widget for Adjust 3D view and Force textured solid shading is perfect for my job.
I reduce the size of images.
before size 94 mg.
after 12 Kb.
I try import all images but only import 914 files.

**Comment by tonilogar** [comment]
I have 10 ortophotos in folder ortos:
256-100.tif
256-101.tif
256-102.tif
256-103.tif
256-104.tif
256-105.tif
257-100.tif
257-101.tif
257-102.tif
257-103.tif
257-104.tif
257-105.tif
I have 10 dem in folder dem:
256-100.tif
256-101.tif
256-102.tif
256-103.tif
256-104.tif
256-105.tif
257-100.tif
257-101.tif
257-102.tif
257-103.tif
257-104.tif
257-105.tif

I import the orto files.
I can import all dem files automatically to their corresponding orto files whith a script.

Thanks for your help domlysz.

**Comment by tonilogar** [comment]
The problem didn't the a lot of files.
It was a corrupted file.
I can import 4277 ortophoto files.

Thanks for your help domlysz.
I'm enjoying your addon

**Comment by domlysz** [comment]
glad to see it works now!
