### ISSUE TITLE
3.5.1 macOS Basemap not loading

### ISSUE THREAD

**Issue by brandonmenneke** [domlysz/BlenderGIS#791]
# **Blender and OS versions**

Blender 3.5.1 (Apple Silicon)
M1 Max 64GB
macOS Ventura 13.3.1

# **Describe the bug**

GIS Basemap not loading. Map view says downloading but no map imagery appears in the viewport.

# **How to Reproduce**

# **Error message**
No error message.

**Comment by LiangHuangBC** [comment]
same issue , crashed on blender 3.6

**Comment by rowild** [comment]
Same issue here: MacOS 13, Blender 3.6.1
No map appears; when using the number block, an error appears the first time ("...no scale attribute")

**Comment by fenixpoints** [comment]
Ho risolto istallando la versione 362lts per intel col Mac studio e silicon m1ultra

**Comment by gisdirk** [comment]
This has worked for me
[Issue #770](https://github.com/domlysz/BlenderGIS/issues/770#issuecomment-1504570389)

**Comment by domlysz** [comment]
Should be fixed with this release 
https://github.com/domlysz/BlenderGIS/releases/tag/2210
