### ISSUE TITLE
No interactive maps on MacOS Blender 3.5.1

### ISSUE THREAD

**Issue by spdorsey** [domlysz/BlenderGIS#795]
# **Blender and OS versions**

3.5.1

# **Describe the bug**

GIS > Web Geodata > Basemap (OK) gives a frozen interface (zoomable) that does not load map data.

# **How to Reproduce**

Happens every time I use the function

# **Error message**

ERROR:BlenderGIS-master.core.basemaps.mapservice:590:Can't download tile x4095 y4098. Error HTTP Error 404: Not Found
DEBUG:BlenderGIS-master.core.basemaps.mapservice:600:Invalid tile data for request http://mt0.google.com/vt/lyrs=s&x=4095&y=4098&z=13

**Comment by borborich** [comment]
same problem

**Comment by homemade-marco** [comment]
I can't even get to an interactive map any longer. Error: Please install gdal to enable .... It was working this morning. Then not working. 

INFO:BlenderGIS-228:92:###### Starting new Blender session : 2023-06-25 14:15:15
DEBUG:BlenderGIS-228.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-228.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-228.core.checkdeps:34:Pillow available
DEBUG:BlenderGIS-228.core.checkdeps:46:ImageIO Freeimage plugin available
DEBUG:BlenderGIS-228.core.proj.srv:69:http://epsg.io/trans?x=-125.60065466934282&y=48.96801696769026&z=0&s_srs=4326&t_srs=102039
ERROR:BlenderGIS-228:96:Uncaught exception
Traceback (most recent call last):
  File "/***/Application Support/Blender/3.5/scripts/addons/BlenderGIS-228/__init__.py", line 117, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/Applications/Blender.app/Contents/Resources/3.5/python/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/***/Application Support/Blender/3.5/scripts/addons/Baked_Blender_Suite/operators/library_download.py", line 313, in check_for_new_assets
    context.window_manager.bu_props.new_assets += 1
AttributeError: 'WindowManager' object has no attribute 'bu_props'
INFO:BlenderGIS-228:92:###### Starting new Blender session : 2023-06-25 14:54:03
DEBUG:BlenderGIS-228.core.checkdeps:9:GDAL Python binding unavailable
DEBUG:BlenderGIS-228.core.checkdeps:20:PyProj unavailable
DEBUG:BlenderGIS-228.core.checkdeps:34:Pillow available
DEBUG:BlenderGIS-228.core.checkdeps:46:ImageIO Freeimage plugin available

**Comment by shokomon** [comment]
same problem here

**Comment by steho68** [comment]
Had the same issue and found the solution here:
https://github.com/domlysz/BlenderGIS/issues/770
Mac Studio M1 Max
Ventura 13.4.1
Blender 3.6.0

**Comment by Flo-Lynn** [comment]
I have the same problem on MacAir M2, when I click ok nothing loads. There's the zoom level and the coordinates but there's no map.

**Comment by ExtraAir** [comment]
I have the same Problem.
[bgis.log](https://github.com/domlysz/BlenderGIS/files/12388492/bgis.log)
MacBook Pro 16" 2023
Chip Apple M2 Pro
Speicher 16 GB
Startvolume Macintosh HD
macOS 13.4 (22F66)

**Comment by JohnWong** [comment]
Check this out https://github.com/JohnWong/BlenderGIS

1. Fix issue of empty Basemap.
2. Support socks proxy
3. Support pinch gesture for macOS
4. Better map size in Basemap

**Comment by Deliaz** [comment]
@JohnWong When trying to install your add-on I am getting this
<img width="644" alt="image" src="https://github.com/domlysz/BlenderGIS/assets/4865430/302d5228-bf22-4576-b1d7-154eeef51bfc">

**Comment by ncsfoo** [comment]
@JohnWong I was able to install it once but then it crashed as soon as I tried to import a baseman. Now I get the same error as above

**Comment by JohnWong** [comment]
@Deliaz @ncsfoo 
I want to install pysocks in Blender. But it seems to be failed at your machine. Try this solution.

/Applications/Blender.app/Contents/Resources/3.6/python/bin/python3.10 -m pip install pysocks

You may need to replace 3.6 and python3.10 to your local file path

**Comment by domlysz** [comment]
Should be fixed with this release 
https://github.com/domlysz/BlenderGIS/releases/tag/2210
