### ISSUE TITLE
blender says to apply for api key and how do i do that ?

### ISSUE THREAD

**Issue by pandaslayer1** [domlysz/BlenderGIS#798]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by hafidhbadru** [comment]
where i can get api in using blender

**Comment by c-ro** [comment]
https://opentopography.org

**Comment by domlysz** [comment]
in recent version of the addon a dialog is showed with a text box to pu the api key in
