### ISSUE TITLE
3/5 add-ons don't show up in Blender v2.69

### ISSUE THREAD

**Issue by NWRichmond** [domlysz/BlenderGIS#8]
Greetings,

I'm having some trouble installing BlenderGIS in Blender v2.69. The "Set reference cam" and "Import raster georeferenced with world file" add-ons appear and install just fine (see picture), but the other three add-ons in the BlenderGIS package (io_shapefile, terrain_analysis, and delaunay_voronoi) do not.

I looked at the "__init__.py" for the "io_shapefile" add-on, and nothing in the "# Register in File > Import menu" section looked drastically different from the same section in the working "io_import_georaster.py" script, so I can't identify the problem that prevents Blender from adding io_shapefile to the add-ons list.

The only thing I noticed that all the non-working add-ons have in common is that they are in folders with multiple scripts, whereas the working add-ons are standalone scripts.

Any insight would be most appreciated!

![bgis_add-ons](https://cloud.githubusercontent.com/assets/5732000/13158357/8fce3c98-d65a-11e5-9086-29564caac7b6.png)

**Comment by NWRichmond** [comment]
UPDATE: I upgraded to Blender v2.76b; the add-ons still don't show up.

**Comment by domlysz** [comment]
Hi,

You're right, the bug seems to come from the init process of multiples files addons. But I don't know whats wrong.

Can you tel me what is your operating system?

Did the warning message ("multiple addons using the same name") appears before you have tried to install the addons?

Do you have some errors messages reported when you launch Blender from a terminal (or  toggle system console in window menu of Blender)?

Thancks

**Comment by NWRichmond** [comment]
Thank you for your reply! I'm using Ubuntu 14.04.3, and I haven't received any warning messages in either GUI or python console mode. No warning messages appear in the 'Blender User Preferences' interface either.

**Comment by kikislater** [comment]
How do you install Blender, ppa or official repositories or download from blender website ?
Where do you install BlenderGIS ?

**Comment by NWRichmond** [comment]
I installed Blender 2.76b from a ppa (ppa:thomas-schiex/blender), and installed BlenderGIS in: /usr/share/blender/2.76/scripts/addons.

**Comment by kikislater** [comment]
What about gdal python bindings ?

**Comment by NWRichmond** [comment]
GDAL wasn't installed before, but I just installed GDAL 1.10.1 using "sudo easy_install GDAL" yet the scripts mentioned in my original post still don't appear in Blender User Preferences.

**Comment by kikislater** [comment]
It seems the problem should be here ... 
Open python console in Blender and test gdal as Dominic says :
from osgeo import gdal
from osgeo import gdalnumeric_

io_shapefile need gdal instead of import raster does not need gdal

**Comment by domlysz** [comment]
No it can't be that, gdal is an optional dependency, all addons can work without.

Have you try to start blender from a linux terminal and look for errors messages? (Python console within blender doesn't report addons outputs)

**Comment by NWRichmond** [comment]
When launching Blender from terminal, the only messages I see are:

connect failed: No such file or directory
Read new prefs: .../.config/blender/2.76/config/userpref.blend

and then Blender opens without any problems. It's good to hear that gdal is an optional dependency, because I can't seem to get it to work with Blender (ImportError: No module named '_gdal'). I'm not concerned about that at this point, though. I just want to get the plugins working.

Thank you for your continued help with this matter.

**Comment by domlysz** [comment]
ok, try to download the tarball from [blender.org](https://www.blender.org/download/), unzip and copy/paste blenderGIS files into the addons subfolder, and launch this newest install

**Comment by NWRichmond** [comment]
Thank you so much! Downloading the tarball from blender.org fixed the issue; all plugins show up now. I really appreciate all of the help with this.
