### ISSUE TITLE
Blender GIS give error when selecting

### ISSUE THREAD

**Issue by Milkyway1960** [domlysz/BlenderGIS#800]
# **Blender and OS versions**

Blender 3.6, Windows 11
![2023 07 12 08 55 08 blender 1b7pSccfOs](https://github.com/domlysz/BlenderGIS/assets/139322557/52841052-e703-44aa-aed9-b0208c0bdb03)

# **Describe the bug**
I downloaded the GIS addon and in blender go to blenders preferences and install in from the zip file.  I then search for the GIS addon en click the check box.  Blender then give me message as in the picture I attached.   

# **How to Reproduce**

# **Error message**

**Comment by domlysz** [comment]
You try to install the addon on Blender 2.81 but the addon require at least 2.83
