### ISSUE TITLE
Background image scaling problem

### ISSUE THREAD

**Issue by iblueyonder** [domlysz/BlenderGIS#81]
When I use Blender GIS to create a background image for a Blender project, I'm finding that the scale of the image doesn't match its real-world counterparts. As a test, I created a background image of Portland International Airport in Portland, Oregon - a project I'm building in Blender. I measured a runway in Google Earth (see attached screenshot), and it came out to 3354.11 meters. In Blender, the runway on the background image is 4782 meters. If the image is georeferenced in the viewport, shouldn't the two measurements match? Perhaps I'm doing something wrong, but I'd sure like some guidance. Fantastic plugin in every other respect, though! Thanks.

![blender_gis](https://user-images.githubusercontent.com/9486718/28875182-446cad5a-775a-11e7-934a-53694fd80e72.jpg)

![google_earth](https://user-images.githubusercontent.com/9486718/28875183-4486b33a-775a-11e7-8ce5-59ee65c33344.jpg)

**Comment by domlysz** [comment]
it's inherent to web mercator projection : scale factor increase with latitude making the projection conformal

https://en.wikipedia.org/wiki/Mercator_projection#Distortion

multiplying the measured distance by cos(lat) give an approximation of the true distance

4750 * cos(pi * 45.589 / 180) = 3324 m

tools like google earth apply this correction on the fly when measuring

for precision modeling web mercator projection is not suitable, it's a good projection for representing the whole earth but not for local place, use UTM projection instead

**Comment by iblueyonder** [comment]
Thanks for the help. I think I've got it working much better now with UTM.

**Comment by 13Wael13** [comment]
Hi !

Thanks for that graet addon ! Do you have any idea why i can't select UTM projection instead of mercator ?

![Capture d’écran (100)](https://user-images.githubusercontent.com/91062338/133991487-d64475ca-1feb-4a7d-a685-76b4a86b2c0c.png)

**Comment by na** [comment]
@13Wael13 I had the same issue.  After following the guide here: https://github.com/domlysz/BlenderGIS/wiki/How-to-install-GDAL the options became available.

**Comment by alicantsezer** [comment]
Normally you can not see the UTM code there. There is an option on screenshot when you add a basemap export Once you export a base map where you want to be. So you can find your UTM zone code and add it to crs on epsg.io web site. After that you will bee add correct scale basemaps, after that you can delete the first oversized basemap.
![image](https://user-images.githubusercontent.com/35402444/185955649-a0e247a9-cf78-4599-bd53-e8cbb3f2e755.png)
