### ISSUE TITLE
Not view nothing MacBook M1 Pro

### ISSUE THREAD

**Issue by Unagaml** [domlysz/BlenderGIS#817]
Blender version: 3.6.2 MacOS 14.0

After adding the addon to the blender, I started loading the base map by selecting the Google map and satellite type. After I clicked load, nothing appeared on the stage and the camera in the blender switched to 2D mode. I tried several times and even cleared the cache, nothing helped.

<img width="1512" alt="Снимок экрана 2023-10-10 в 13 26 22" src="https://github.com/domlysz/BlenderGIS/assets/92244180/8975afb2-0a6d-4e8a-8d02-4acd0799b25d">

<img width="1512" alt="Снимок экрана 2023-10-10 в 13 27 02" src="https://github.com/domlysz/BlenderGIS/assets/92244180/8f4c2448-207a-4e6b-a0b8-5f759edfc3ea">

**Comment by oka0410** [comment]
I have the same problem

**Comment by Unagaml** [comment]
Maybe you have a way to solve it?

**Comment by sylwesterdigital** [comment]
Try to launch it from the shell/terminal - I have these issues listed: 
```
Blender.app /Applications/Blender.app/Contents/MacOS/Blender 
Read prefs: "/Users/sylwestermielniczuk/Library/Application Support/Blender/3.6/config/userpref.blend"
Device with name Apple M1 Pro supports metal minimum requirements
METAL API - DETECTED GPU: Apple M1 Pro
WARN (bgl): source/blender/python/generic/bgl.c:2662 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.
DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:Pillow unavailable
DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
```

Steps to Resolve Python Dependencies:

Locate Blender's Python: Navigate to Blender's internal Python directory. It's usually located within Blender's installation directory under 2.xx/python. The 2.xx will be your Blender version, e.g., 2.93.

Install Modules: Using pip, you can then install the missing modules. If Blender comes with its own bundled Python (as it does in many cases), you can use its pip to install libraries. Navigate to the bin directory inside the Python directory and run:

bash
Copy code
./pip3 install GDAL PyProj Pillow
If Blender uses the system's Python, you can install the packages normally using pip.

Test: Relaunch Blender and check if the GIS plugin now recognizes the installed modules.

If you encounter issues or are unsure about any steps, consider seeking help from the BlenderGIS community or forum, as they'll likely have experience with these exact requirements.

**Comment by ncsfoo** [comment]
I'm having the same issue. Nothing appears and it locks the application

**Comment by danielgetsthis** [comment]
I'm having the same problem. I'm on an M2 Macbook Pro - Ventura 13.4

**Comment by BengoFett83** [comment]
Same problem here, with M2 MacBook. Tried API key, checking the addon folders, changing cache folder. Anything else someone knows?

**Comment by danielgetsthis** [comment]
This fixed this issue for me. It shows the map now, but any time I try to hone in on a location Blender gives me the rainbow beachball and goes unresponsive. If someone gets past this immediate issue, can you reply and say whether you were able to zoom in on the map?
https://github.com/domlysz/BlenderGIS/issues/770#issuecomment-1504570389

**Comment by BengoFett83** [comment]
It works on Blender 3.1.2
I had the same problem and was curious to see what would happen on my other mac (m1). Straight out the box the addon ran without a problem. I had 3.1.2 installed so i just deleted 3.6 from my laptop and installed the same and it worked.

**Comment by gisdirk** [comment]
> This fixed this issue for me. It shows the map now, but any time I try to hone in on a location Blender gives me the rainbow beachball and goes unresponsive. If someone gets past this immediate issue, can you reply and say whether you were able to zoom in on the map? [#770 (comment)](https://github.com/domlysz/BlenderGIS/issues/770#issuecomment-1504570389)

I second that. This solution has worked for me, too.

**Comment by domlysz** [comment]
fixed https://github.com/domlysz/BlenderGIS/releases/tag/2210
