### ISSUE TITLE
BlenderGIS, no field x API key 

### ISSUE THREAD

**Issue by fpkcimino** [domlysz/BlenderGIS#818]
# **Blender 3.6 ang Blender GIS on win11**

# **BlenderPreferences/addon/Blender GIS/Remote Datasource/Elevation/, there is not the field to insert API key for opentopography nor the edit button, thus the SRTM doesn't work. I can not insert my API key. is there a way to do it by Terminal? 
thanks guys**

# **How to Reproduce**

# **Error message**

**Comment by fpkcimino** [comment]
![W3Dl9tW](https://github.com/domlysz/BlenderGIS/assets/6398715/71c1340a-1357-4cb1-94cd-dee9ae47c40d)

**Comment by domlysz** [comment]
seems its an old version of the addon, please update it
