### ISSUE TITLE
Cannot install addon

### ISSUE THREAD

**Issue by iboates** [domlysz/BlenderGIS#82]
I am trying to install this plugin on Blender portable version 2.78.

I have downloaded the repo and extracted it.  I have gone into "Blender User Preferences" and selected "Install from File".  I am now presented with a file explorer where I navigate to the extracted repo. I have tried selecting every script in here and then clicking on the "Install from file..." bottom at the top-right, however I do not see it in the addon list after that.

Is this the proper procedure to install this or should I be doing something differently? The install guide is very ambiguous, saying only "Use "Install from File" option to install the addon from downloaded zip"

**Comment by domlysz** [comment]
You don't need tout extract the zip file. Just select the zip when install from file
