### ISSUE TITLE
Unable To Download

### ISSUE THREAD

**Issue by hTp34r** [domlysz/BlenderGIS#820]
When I try to click "Download ZIP", it doesn't refer to download link; it shows "Page Not Found" instead.

**Comment by domlysz** [comment]
this button depend on Github itself, dit it works for you now ?

**Comment by hTp34r** [comment]
> this button depend on Github itself, dit it works for you now ?

maybe when I clicked the "download" button then, the network fluctuated. Now it seems OK. Thanks for your reply!
