### ISSUE TITLE
Not getting image on Blender 3.6 MacBook M2

### ISSUE THREAD

**Issue by BengoFett83** [domlysz/BlenderGIS#823]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by BengoFett83** [comment]
After importing the basemap nothing appears and the viewer gets stuck on 2D. Hitting escape solves it but no data is imported.

**Comment by BengoFett83** [comment]
After importing the basemap nothing appears and the viewer gets stuck on 2D. Hitting escape solves it but no data is imported.

**Comment by matkoehl** [comment]
Looks like this is a problem that appears in several discussions now. I desperately look for a solution, too!

**Comment by griffinmcknight** [comment]
This is happening to me as well on my Mac M1. I can select a basemap, but nothing every appears and controls are frozen. ESC closes the add-on properly.

**Comment by domlysz** [comment]
fixed https://github.com/domlysz/BlenderGIS/releases/tag/2210
