### ISSUE TITLE
Blender 4.0 issue with BlenderGIS 2.2.6, ValueError 1-2 args execution context is supported.

### ISSUE THREAD

**Issue by eventxplore** [domlysz/BlenderGIS#834]
Just tried it with Blender 4.0 and got this when pressing E for export,
ValueError 1-2 args execution context is supported.
Works great with Blender 3.6.5.

**Comment by ODON1** [comment]
Same here when running external blender script:

`2023-11-20 14:48:11,823    ERROR bpy_externall-master ERROR: 1-2 args execution context is supported`

**Comment by DasFin235** [comment]
Same here.

Got the following Report:

Python: Traceback (most recent call last):
File "[...]Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 959, in modal adjust3Dview(context, getBBOX.fromObj(obj))
File "[...]Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\utils\bgis_utils.py", line 107, in adjust3Dview bpy.ops.view3d.view_selected(overrideContext)
File "[...]Blender Foundation}Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
File "[...]Blender Foundation}Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported

**Comment by Narnasqueneth** [comment]
![blenderGIS](https://github.com/domlysz/BlenderGIS/assets/64552373/45b144ad-c95e-4a11-9d1b-827c494515a6)

I noticed a comment that said "(Error is with blender not BlenderGIS)" - so what is the solution? Uninstall Blender and reinstall an older version? If so which version?

**Comment by ODON1** [comment]
I installed 3.6.5 again, which works for me.

**Comment by ThatMikaTho** [comment]
> ![blenderGIS](https://user-images.githubusercontent.com/64552373/285293295-45b144ad-c95e-4a11-9d1b-827c494515a6.JPG)
> 
> I noticed a comment that said "(Error is with blender not BlenderGIS)" - so what is the solution? Uninstall Blender and reinstall an older version? If so which version?

I had the same problem with blender 4.0 and uninstalled it. Installed 3.6 and it works without any issue

**Comment by vilda994** [comment]
Also same problem like others (had version 4.0). I installed 3.6 and everything works

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
