### ISSUE TITLE
I don't know why i can't use the template for GIS, heres the error image

### ISSUE THREAD

**Issue by JossJDM** [domlysz/BlenderGIS#842]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**
![Captura de pantalla (84)](https://github.com/domlysz/BlenderGIS/assets/153350686/074d90b6-f985-447a-9c33-34ae66f8e3e5)

**Comment by quentinjeanningros** [comment]
Same for me

**Comment by UnboundGodz** [comment]
https://github.com/domlysz/BlenderGIS/pull/840 <-- This resolves your exporting issues.

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
