### ISSUE TITLE
Using the BlenderGIS shape file import for command line conversion to .blend

### ISSUE THREAD

**Issue by masaverino** [domlysz/BlenderGIS#85]
Could you please provide an example of how to use the BlenderGIS plugin in python command line mode within blender?  I want to import a .shp file and convert to .blend or .obj.   Currently, I am able to import my example .shp file into blender using your BlenderGIS plugin.  Setting "Elevation from field" and "Extrusion from field" to _HGT_AGL_ and CRS to WGS84 latlon produces the correct result in blender.  I will, of course, have to set these parameters in the script.  Typing  bpy.ops.importgis.shapefile_file_dialog at the blender python prompt, which blender says is the import script via tooltips, does not provide much information. 

>>> bpy.ops.importgis.shapefile_file_dialog
# Import ESRI shapefile (.shp)
bpy.ops.importgis.shapefile_file_dialog(filepath="", filter_glob="*.shp")

Thanks in advance for your help.

Mike...

**Comment by domlysz** [comment]
here the signature

`bpy.ops.importgis.shapefile(filepath=path, shpCRS='EPSG:xxxx', fieldElevName='', fieldExtrudeName='', extrusionAxis='Z', separateObjects=False, fieldObjName='')`
