### ISSUE TITLE
BLENDERGIS ISSUE temp_override

### ISSUE THREAD

**Issue by MATTEKTM** [domlysz/BlenderGIS#856]
Hi everyone, I'm new to blendergis and I get a strange error when I press the letter E.
I tried looking to see if anyone had had the same problem as me but I couldn't find anything. If I opened a double ticket, I apologize.
Thanks to those who respond to me
![Uploading 20240108_220340.jpg…]()

**Comment by Hayk470** [comment]
I have the same issue

**Comment by MATTEKTM** [comment]
I have resolved it, i installed blender 3.6 and now it's ok. The issue is only for 4.0 version, try with 3.6 version

**Comment by EnekoJL** [comment]
Thanks, I will install the 3.6 one

**Comment by chocolateriderx** [comment]
I have the same issue. I'm on 4.0 waiting to be fix

**Comment by MATTEKTM** [comment]
Try to install the 3.6 version, with me has worked and now everything is ok.

Il Gio 8 Feb 2024, 05:20 chocolateriderx ***@***.***> ha
scritto:

**Comment by domlysz** [comment]
fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
