### ISSUE TITLE
nodata property

### ISSUE THREAD

**Issue by tonilogar** [domlysz/BlenderGIS#86]
Thanks for your addon again domlyz.
I make a script that import dem images, it to collapse the modifiers and create and aply de material with ortophoto image.
But i want apply de fill no data values and i don't know how write this  in the script.
This nigth i make a link of mega for that you can try the script with images.

Thanks for your time.

This is the script:

import bpy, os

folder = "I:/catalunyaMetOrtoPru/demOrto/"
#suffix = '_OrtoResi_240.tif'
for f in os.listdir(folder):
     pathFiles = folder + f
     path = folder + f
     basename, ext = os.path.splitext(f)
     if pathFiles.find('_Dem.tif') >= 1:              
        bpy.ops.importgis.georaster(importMode = 'DEM',filepath = path,rastCRS = 'EPSG:3857')
        objeto = bpy.data.objects[basename]
        objeto.select = True
        bpy.context.scene.objects.active = objeto
        bpy.ops.object.modifier_apply(apply_as='DATA', modifier='DEM')
        bpy.ops.object.modifier_apply(apply_as='DATA', modifier='DEM.001')
     if pathFiles.find('_Orto.tif') >= 1:              
        img = bpy.data.images.load(pathFiles)
        cTex = bpy.data.textures.new('ColorTex', type = 'IMAGE')
        cTex.image = img
        materialSimple = bpy.data.materials.new(basename)
        objeto.data.materials.append(materialSimple)
        materialSimple.specular_color = (0,0,0)
        materialSimple.specular_intensity = 0
        mtex = materialSimple.texture_slots.add()
        mtex.texture = cTex

**Comment by domlysz** [comment]
Hi,

Just use the fillNodata option like this

```python
bpy.ops.importgis.georaster(importMode='DEM', filepath=path, rastCRS='EPSG:3857', fillNodata=True)```

**Comment by tonilogar** [comment]
Hi, thanks domlysz.
These are the images to test the script.

https://mega.nz/#F!fkhzBDoD!kQhbBuynO5ADhYZRUrIfJg

**Comment by tonilogar** [comment]
My intention is, make a model of terrain and hight quality and extract de normal map, and aply this normal map in a lowpoly.
Then, export this lowpoly with texture orto and normamap of highpoly to unity 3D.
Is posible export with option Raw Dem and make the mesh with splines and faces?

Thanks for your time domlysz.

**Comment by domlysz** [comment]
yes you can triangulate a point cloud from a raw DEM import if you want to avoid using the displace modifier

https://github.com/domlysz/BlenderGIS/wiki/Make-terrain-mesh-with-Delaunay-triangulation

**Comment by tonilogar** [comment]
Thanks domlysz, but i whanted import with mesh.
Enyway i import with 'DEM_RAW' and apply de delaunay after .
