### ISSUE TITLE
Python type error while generating map plane after hitting E 

### ISSUE THREAD

**Issue by Shpaq4Fun** [domlysz/BlenderGIS#861]
# **Blender and OS versions**

Blender 4.0, Windows 11 Home 23H2 22631.3007

# **Describe the bug**

After locating the area, I try to press "E" to generate the plane with the map. After pressing E, empth grey plane appears, and the Report: Error pasted below

# **How to Reproduce**

Select web geodata -> Google, Satellite, press ok -> press G -> type location and zoom (in my case "zakopane", and zoom level 9)-> area appears correctly -> press E to generate -> error appears.

# **Error message**

Python: TypeError: temp_override() takes no positional arguments

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wodec\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\view3d_mapviewer.py", line 959, in modal
    adjust3Dview(context, getBBOX.fromObj(obj))
  File "C:\Users\wodec\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-master\operators\utils\bgis_utils.py", line 108, in adjust3Dview
    with context.temp_override(overrideContext):
SystemError: <built-in method temp_override of Context object at 0x00000222454697C0> returned a result with an exception set

**Comment by PetitCubeDeGlace** [comment]
You need to use the 3.6 version of Blender not the 4
[https://github.com/domlysz/BlenderGIS/issues/836](url)
here you can :
[https://download.blender.org/release/Blender3.6/](url)

**Comment by mymike00** [comment]
Is there a plan to update the plugin to support blender 4.0 as well?

**Comment by bleve97** [comment]
It looks like a fix has been made for this, https://github.com/domlysz/BlenderGIS/commit/49bbf5770f371dfa686aac266805ebd589a62cf7
Any chance a release could be rolled for those of us using 4.0.2 and newer?

**Comment by frankievx** [comment]
> It looks like a fix has been made for this, [49bbf57](https://github.com/domlysz/BlenderGIS/commit/49bbf5770f371dfa686aac266805ebd589a62cf7) Any chance a release could be rolled for those of us using 4.0.2 and newer?

Please.

**Comment by AlertWarn** [comment]
Count me in on this

**Comment by TNT-23** [comment]
I have successfully solved the problem using Blender3.6. Thank you.

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/releases/tag/229

**Comment by TNT-23** [comment]
您的邮件我已收到，会尽快查阅，谢谢！

**Comment by kefonelove** [comment]
Hi! Maybe this video could help https://youtu.be/rR2W5U_GXwc

**Comment by TNT-23** [comment]
您的邮件我已收到，会尽快查阅，谢谢！
