### ISSUE TITLE
Crashing with 4.02 with python errors when using control E over a new location.

### ISSUE THREAD

**Issue by ChuckCarterArt** [domlysz/BlenderGIS#865]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by Zhuwenxiu01** [comment]
![Uploading Screenshot 2024-02-14 at 05.00.31.png…]()

**Comment by Futertimer** [comment]
![775163a2-68eb-4b08-90dd-4ecee75fa17b](https://github.com/domlysz/BlenderGIS/assets/113804928/e38c6dd2-cccc-4022-b61d-7b03223845ad)

**Comment by AlertWarn** [comment]
I have the exact same error.
![Blender Error](https://github.com/domlysz/BlenderGIS/assets/106180115/faa4d0be-9418-4e3b-a936-9735d1998bec)

**Comment by Futertimer** [comment]
Yeah I saw. Use blender 3.6

**Comment by AlertWarn** [comment]
Heck w/ that. Just update the code
#840  solved it for me with double **

**Comment by lilylethe** [comment]
Solved it with [https://github.com/domlysz/BlenderGIS/pull/840/commits/462d96efd47eabdf7b8dfad0c8c5a63a9adf6c4f](this code)

**Comment by Hyakki09** [comment]
How to do that double ** which line, #840 doesn't have any of that mentioned, I think it was edited or deleted.

**Comment by waruthp** [comment]
> How to do that double ** which line, #840 doesn't have any of that mentioned, I think it was edited or deleted.

Yes. I think it was deleted.

**Comment by domlysz** [comment]
fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
