### ISSUE TITLE
Geometry export fails on Blender 4.0.2 ( 'ValueError: 1-2 args execution context is supported')

### ISSUE THREAD

**Issue by jseagull-3sl** [domlysz/BlenderGIS#869]
# **Blender and OS versions**

Blender 4.0.2 on Windows 11 using the 2.2.8 BlenderGIS release.

# **Describe the bug**

This is a duplicate of Issue #830 which was closed by the submitter with no explanation.

Everything works as per the Quick start instructions until pressing E to export geometry, at which point the Google satellite layer disappears and a Python error dialog pops up as shown in the Error Message section 

It appears to be related to [this breaking change](https://projects.blender.org/blender/blender/commit/ac263a9bce53e190d07d679a058a230e91e722be) in how Blender 4.0+ handles context overrides since the `adjust3Dview` function in `bgis_utils.py` uses the deprecated `bpy.ops` method.

# **How to Reproduce**

As above, follow the Quick Start instructions up to pressing 'E'.

# **Error message**
```
ERROR:BlenderGIS-228:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\there\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-228\operators\view3d_mapviewer.py", line 959, in modal
    adjust3Dview(context, getBBOX.fromObj(obj))
  File "C:\Users\there\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlenderGIS-228\operators\utils\bgis_utils.py", line 107, in adjust3Dview
    bpy.ops.view3d.view_selected(overrideContext)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
```

**Comment by jseagull-3sl** [comment]
This appears to be fixed by changing the following code starting at line 103 in `operators/utils/bgis_utils.py`:
# Old Code 
```
if zoomToSelect:
	overrideContext = context.copy()
	overrideContext['area'] = area
	overrideContext['region'] = area.regions[-1]
	bpy.ops.view3d.view_selected(overrideContext)
```
# New Code
```
if zoomToSelect:
	with context.temp_override(area = area , region = area.regions[-1]):
			bpy.ops.view3d.view_selected
```

**Comment by AmeyKuradeAK** [comment]
I have same problem! If you get any solution just comment below

**Comment by jseagull-3sl** [comment]
I replied to the issue with a fix for this particular error. There are
probably other bugs in the plug-in of the same type, but this at least
let's one import map data and conform it to elevation data.

**Comment by AmeyKuradeAK** [comment]
I fixed as per you mentioned still the issue is not solved.

**Comment by jseagull-3sl** [comment]
Looking more closely at this, this bug is already fixed in the current codebase, it's just that the release version is over a year out of date.
