### ISSUE TITLE
Never, ever do a bare 'except'

### ISSUE THREAD

**Issue by sybrenstuvel** [domlysz/BlenderGIS#87]
https://github.com/domlysz/BlenderGIS/blob/4c1a09fbcd88578d2c170c381947c0879e76dae3/operators/io_import_shp.py#L108

Whenever anything goes wrong reading the file (and that could even be a `SyntaxError` or `KeyboardInterrupt`), all context about the exception is discarded, and only a nondescript generic error is shown. This makes it impossible to do any kind of debugging.

Also see http://docs.quantifiedcode.com/python-anti-patterns/correctness/no_exception_type_specified.html

**Comment by domlysz** [comment]
Fixed 3bb7dd7
