### ISSUE TITLE
Error when try to extract map

### ISSUE THREAD

**Issue by GabrieleGiacomelli** [domlysz/BlenderGIS#873]
# **Blender and OS versions**

Blender 4.0 on windows 11

# **Describe the bug**

Everytime i try to extract a portion of map, be on satellite or Map, it gave me an error and then i cannot see the portion of map, it just go completely gray.

# **How to Reproduce**

Choose any position on the map and press E

# **Error message**

![Immagine WhatsApp 2024-03-19 ore 16 03 22_cadc671a](https://github.com/domlysz/BlenderGIS/assets/56293277/ba6d3de8-63ad-4fd6-b19e-29452093fabf)

**Comment by joshua-bouv** [comment]
Use Blender 3.6 instead of 4.0, that got exporting working for me :)

**Comment by RedHaloStudio** [comment]
> # **Blender and OS versions**
> Blender 4.0 on windows 11
> 
> # **Describe the bug**
> Everytime i try to extract a portion of map, be on satellite or Map, it gave me an error and then i cannot see the portion of map, it just go completely gray.
> 
> # **How to Reproduce**
> Choose any position on the map and press E
> 
> # **Error message**
> ![Immagine WhatsApp 2024-03-19 ore 16 03 22_cadc671a](https://private-user-images.githubusercontent.com/56293277/314115413-ba6d3de8-63ad-4fd6-b19e-29452093fabf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTEwNTEsIm5iZiI6MTcxMjY1MDc1MSwicGF0aCI6Ii81NjI5MzI3Ny8zMTQxMTU0MTMtYmE2ZDNkZTgtNjNhZC00ZmQ2LWIxOWUtMjk0NTIwOTNmYWJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA4MTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2Yzk2YzI3YWU0NmQ1ZmUzYzAwNTAwOTBkYzc2NzVkMzE1Yjc1YzYxOWNmMDg3NzFjNTFlMjBlNThjYTZmNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ketr1HguSDWDTM49IZ-OaBJXoz9WXPqTOstwJvrjKo)

try this: https://github.com/RedHaloStudio/BlenderGIS/releases

**Comment by klaasnicolaas** [comment]
@RedHaloStudio Thnx for the changes on your fork, this seems to work fine with Blender 4.1

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
