### ISSUE TITLE
Error prompt when pressing the E key

### ISSUE THREAD

**Issue by Cavintin** [domlysz/BlenderGIS#875]
<img width="839" alt="企业微信截图_a2e03441-fa91-487d-9ece-34283ae42bea" src="https://github.com/domlysz/BlenderGIS/assets/165156395/2bb9635b-755b-4ad9-9035-f8c54453c401">

**Comment by bleve97** [comment]
On 28/03/2024 5:14 am, MWH-VDC wrote:
> I have this error prompt all of a sudden as well. I think my blender 
> updated it self too? I have blender 4.1 now

It's a known bug, we just need the owner to roll a new release. I sent 
an email months ago, but it looks like they've fallen off the Internet.

**Comment by btlkcp** [comment]
same with me, any body to help ?
![image](https://github.com/domlysz/BlenderGIS/assets/165982755/9cc27b14-6769-47a0-aa90-ac122e11d24e)

**Comment by klaasnicolaas** [comment]
Is there a solution for this error in the meantime?

**Comment by btlkcp** [comment]
idk, but now i use blender ver 3.6 (downgrade version), it's work if i press E

**Comment by Diegolisdal** [comment]
Hola, debes modificar el archivo "C:\Users\tu_usuario\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderGIS-master\operators\utils\bgis_utils.py" con un editor (yo utilizo Visual Studio Code).
Debes eliminar del codigo del archivo "bgis_utils.py",  las palabras "overrideContext" de las líneas 108 y 111, deberá quedar:

        with context.temp_override():
	       bpy.ops.view3d.view_selected()
else:
	bpy.ops.view3d.view_selected()



![Captura de pantalla 2024-05-02 125555](https://github.com/domlysz/BlenderGIS/assets/142946030/73afe817-d99c-4330-88a8-1e1f747ed170)

Saludos.

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
