### ISSUE TITLE
export failing

### ISSUE THREAD

**Issue by garcian8** [domlysz/BlenderGIS#877]
# **Blender and OS versions**
blender 4.0 windows 11 pro

# **Describe the bug**
cant export GIS data

when trying to export the view, i get the following message
# **How to Reproduce**

# **Error message**
![image](https://github.com/domlysz/BlenderGIS/assets/165812250/002f4426-d628-404f-860e-c2130cb0492c)

**Comment by CallMeAv** [comment]
Did you find the solution to this?

**Comment by garcian8** [comment]
No I did not

**Comment by PrejudiceNeutrino** [comment]
Download an older version of blender such as 3.6: https://download.blender.org/release/Blender3.6/

**Comment by patdespres** [comment]
I'm facing the same issues. Will be more than happy if someone is having a solution for that
<img width="827" alt="Capture d’écran, le 2024-04-13 à 16 37 22" src="https://github.com/domlysz/BlenderGIS/assets/166954972/faea7015-927b-430a-be87-33d21204df97">

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
