### ISSUE TITLE
MacOS - no basemap

### ISSUE THREAD

**Issue by EnricoCasagr** [domlysz/BlenderGIS#878]
as soon as I hit the gis icona the view goes on top but then nothing happen. I can't move or select anything on the screen, the only thing that I can do is pressing esc to stop the operation. I'm currently using the last version of blander

**Comment by mortonc** [comment]
I am having the same problem. 

Blender GIS: v2.2.8
Blender: 4.1.1
Device: Macbook M1 2020
Mac OS: Sonoma 14.1.1

**Comment by maxwiseman** [comment]
Same issue here. Also on Blender GIS v2.2.8 and Blender 4.1.1. I'm on an M3 Pro MBP running MacOS Sonoma 14.4.1. I wonder if this is just a MacOS thing? Seems to work fine on my Windows 11 PC.

**Comment by domlysz** [comment]
fixed https://github.com/domlysz/BlenderGIS/releases/tag/2210
