### ISSUE TITLE
Don't return {'FINISHED'} from failing operator

### ISSUE THREAD

**Issue by sybrenstuvel** [domlysz/BlenderGIS#88]
https://github.com/domlysz/BlenderGIS/blob/4c1a09fbcd88578d2c170c381947c0879e76dae3/operators/io_import_shp.py#L288

An operator that didn't work should return `{'CANCELLED'}`. Also see [the Blender API documentation](https://docs.blender.org/api/blender_python_api_current/bpy.types.Operator.html#bpy.types.Operator.execute).

**Comment by domlysz** [comment]
Fixed 3bb7dd7
