### ISSUE TITLE
I am unable to load any map model in blender

### ISSUE THREAD

**Issue by AmoghGithub55** [domlysz/BlenderGIS#883]
# **Blender and OS versions**

# **Describe the bug**

# **How to Reproduce**

# **Error message**

**Comment by AmoghGithub55** [comment]
![12332](https://github.com/domlysz/BlenderGIS/assets/147991744/58aefd09-4966-487c-9cf2-99811df2c8fc)

**Comment by domlysz** [comment]
Fixed https://github.com/domlysz/BlenderGIS/releases/tag/229
