### ISSUE TITLE
Basemap not loading

### ISSUE THREAD

**Issue by yakzebude** [domlysz/BlenderGIS#888]
# **Blender and OS versions**

 Blender v. 4.11, macOS Sonoma 14.4, M2 chip

# **Describe the bug**

 After selecting to create the basemap (google & satellite) a blank view appears. The API-Key is already installed. Also hitting esc and disabling the grid won't help either. What can I do to fix this? Thanks in advance!

# **How to Reproduce**

# **Error message**

**Comment by Hbm1g18** [comment]
Is this using [BlenderGIS 2.2.9](https://github.com/domlysz/BlenderGIS/releases/tag/229) from yesterday's release? 
I'm using macOS Sonoma14.4.1 using blender version 2.83. I'm using blenderGIS 2.2.8.
Reverting to the older blender version fixed it for me and I'm able to generate basemaps using satellite imagery.
I haven't tried anything on the newer release yet though.

**Comment by yakzebude** [comment]
> Is this using [BlenderGIS 2.2.9](https://github.com/domlysz/BlenderGIS/releases/tag/229) from yesterday's release? I'm using macOS Sonoma14.4.1 using blender version 2.83. I'm using blenderGIS 2.2.8. Reverting to the older blender version fixed it for me and I'm able to generate basemaps using satellite imagery. I haven't tried anything on the newer release yet though.

Yes, I am currently using the newest version (blender 4.11 and but tried two different GIS-versions (the one from two days ago and tried an older version as well). I'll try to install an older blender version. Thanks for the advice, maybe that'll work. Cheers!

**Comment by domlysz** [comment]
Is it works with this release ?
https://github.com/domlysz/BlenderGIS/releases/tag/2210

**Comment by Hbm1g18** [comment]
@domlysz Just tried this release on Blender 4.1.1 macOS Sonoma 14.4.1
Basemap now works perfectly! Thanks

**Comment by yakzebude** [comment]
@domlysz It works! Thank you)
