### ISSUE TITLE
Apply delaunay  to a 'DEM_RAW'

### ISSUE THREAD

**Issue by tonilogar** [domlysz/BlenderGIS#90]
With this script I import a DEM how 'RAW_DEM'.

import bpy, os

folder = "I:/catalunyaMetOrtoPru/demOrto/1/"
for f in os.listdir(folder):
     pathFiles = folder + f
     path = folder + f
     basename, ext = os.path.splitext(f)
     if pathFiles.find('_Dem.tif') >= 1:              
        bpy.ops.importgis.georaster(importMode = 'DEM_RAW',ftilepath = path,rastCRS = 'EPSG:3857')

How I can apply de delaunay in this code?

Thanks for your time and help domlysz, my programming knowledge is very small.

**Comment by domlysz** [comment]
bpy.ops.tesselation.delaunay()

**Comment by tonilogar** [comment]
Thanks for your help and time domlysz.
Now the script makes a mesh of high quality and a mesh low quality.
Select first the high quality, then select the low quality...and now ...I want to apply a bake of normal map.
How can I apply the bake in this code?
Whith the options ..Bake Mode = Normals 
Selected to Active
And save the normalMap texture in the same folder of the original dem images, with 100 of quality.
Here there are some small test images.

https://mega.nz/#F!G1YhHbyI!bX73NHS-NmoECelKBr2GzA

Thanks for your help and time domlysz.

This is the code:

import bpy, os

folder = "I:/catalunyaMetOrtoPru/demOrto/1/"
for f in os.listdir(folder):
     pathFiles = folder + f
     basename, ext = os.path.splitext(f)
     if pathFiles.find('_Dem.tif') >= 1:              
        bpy.ops.importgis.georaster(importMode = 'DEM_RAW',filepath = pathFiles,rastCRS = 'EPSG:3857')
        bpy.ops.tesselation.delaunay()
        objetos_escena = bpy.data.objects
        for objeto in objetos_escena:
            objeto.select = False
        for objeto in objetos_escena:        
            if objeto.name == basename:
                objeto.select = True
                bpy.ops.object.delete()
        for objeto in objetos_escena:   
            if objeto.name.startswith("TIN"):
                nameHighDem = basename + "High"
                objeto.name = nameHighDem
for f in os.listdir(folder):
     pathFiles = folder + f
     basename, ext = os.path.splitext(f)
     if pathFiles.find('_Dem.tif') >= 1:              
        bpy.ops.importgis.georaster(importMode = 'PLANE',filepath = pathFiles,rastCRS = 'EPSG:3857')
        objetos_escena = bpy.data.objects
        for objeto in objetos_escena:
            if objeto.name == basename:
               nameLowDem = basename + "Low"
               objeto.name = nameLowDem
objetos_escena = bpy.data.objects
for objeto in objetos_escena:
    objeto.select = False
    if objeto.name == nameHighDem:
        objeto.select = True        
    if objeto.name == nameLowDem:
        objeto.select = True

**Comment by domlysz** [comment]
I'm sorry your request is out of BlenderGIS's scope. Please ask your question on blenderartist.org or blender.stackexchange. Also refer to the blender python API documentation : https://docs.blender.org/api/2.79/search.html?q=bake&check_keywords=yes&area=default

**Comment by tonilogar** [comment]
Thanks for your help domlysz.
