### ISSUE TITLE
I cannot activate BlenderGIs

### ISSUE THREAD

**Issue by elizavoinea** [domlysz/BlenderGIS#96]
hello!
i have installed blendergis and it worked.. after that i donțt know what i have actually done, but it doesnțt work anymore.. even if I remove it and try re-install.. 
this error pops up 

<img width="593" alt="captura" src="https://user-images.githubusercontent.com/33983285/35388181-a3181844-01ca-11e8-9cfe-03d1f7f3c228.PNG">

**Comment by sem-geologist** [comment]
Same here. The problem is that differently than advertised in installation instruction, the repo for blender for latest version packs the python, and does not use the python present in os. @domlysz , can something be done about this. I think I will be forced to compile blender to make it use the os python.

**Comment by domlysz** [comment]
Are you on linux or windows? On windows blender uses its own python installation, as i know its not possible to use another install

can you report the error message entirely (the screenshoot above is truncated)

**Comment by sem-geologist** [comment]
I am on linux, did exctly as in install tutorial, added ppa and installed
blender from it. the message is a bit irelevant, the enr of error reports
that `from . import multiarray` fails. that is because blender comes with
internal python 3.6.2; and numpy is not present; my system python is 5.2.3;

**Comment by domlysz** [comment]
wiki updated about the Linux issue
https://github.com/domlysz/BlenderGIS/wiki/Install-and-usage

But not sure is Eliza on Windows could solve here issue ...

**Comment by j-c-c** [comment]
Not sure if this can be addressed again, but had same problem on macOS Mojave. Errors attached, but noted a reference to a file located on a personal driver...? Any help? Thanks!
![BlenderGIS](https://user-images.githubusercontent.com/5588125/62254223-4739bd00-b3f0-11e9-9ca1-39b71c2dcfad.png)
