### ISSUE TITLE
Addon crashes when running blender with background flag

### ISSUE THREAD

**Issue by comlor** [domlysz/BlenderGIS#97]
When running the addon from commandline with background flag(blender -b), I would frequently get the error that nontype keymap does not exist(not verbatim...forget the exact error message).  This is due to the GUI not loading so there are no keymaps.  This is corrected by making the following change to __init__.py in the root of the addon in the register() function.
```
	#shortcuts
	wm = bpy.context.window_manager
	km = wm.keyconfigs.active.keymaps['3D View']
	kmi = km.keymap_items.new(idname='view3d.map_start', value='PRESS', type='NUMPAD_ASTERIX', ctrl=False, alt=False, shift=False, oskey=False)
```

needs to be changed to the following, to handle running in background mode with no gui:
```
       #shortcuts
	wm = bpy.context.window_manager
	kc = wm.keyconfigs.addon
	if kc:
		km = wm.keyconfigs.active.keymaps['3D View']
		kmi = km.keymap_items.new(idname='view3d.map_start', value='PRESS', type='NUMPAD_ASTERIX', ctrl=False, alt=False, shift=False, oskey=False)
```

After this change the keymap is configured when running with gui but the addon will not crash if running in background mode.

**Comment by domlysz** [comment]
Fixed in  8b5760c

Thanks
