### ISSUE TITLE
spaces between DEM's

### ISSUE THREAD

**Issue by comlor** [domlysz/BlenderGIS#98]
When importing multiple DEM's there is small lines between the DEM's.  These DEM's are part of one large dem the was tiled using QGIS.  Each tile is imported into it's own blend file and linked into main blend file.
![tiled_mesh](https://user-images.githubusercontent.com/14832244/36006113-eaa29a88-0cef-11e8-92e7-b1209645a284.png)

**Comment by PayamT** [comment]
Use smooth modifier. 


Sent from Yahoo Mail for iPhone


On Thursday, February 8, 2018, 7:49 PM, comlor <notifications@github.com> wrote:


When importing multiple DEM's there is small lines between the DEM's. These DEM's are part of one large dem the was tiled using QGIS.

**Comment by comlor** [comment]
The smooth modifier seemed to make the gaps worse.  I forgot to mention that each of these tiles is in its own blend file and they are linked to this file.  I tried making everything local(object, data, material) and applied the smooth modifier to each one and the gaps either went away or got worse when i increased the value of the smoothing.

**Comment by PayamT** [comment]
Then try this and let me know the outcome :1. Right after import , go to edit mode. 2. Select all faces 3. From the left toolbar select subdivide and set it to 3 or 4, and go back to object mode.4. See if the surface quality is improved and play with subdivision numbers again
See the surface refinement section in the tutorial below. ptabriz/FOSS4G_workshop 
  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
ptabriz/FOSS4G_workshop
 
Contribute to FOSS4G_workshop development by creating an account on GitHub.
  |   |

  |

  |

 



Sent from Yahoo Mail for iPhone


On Thursday, February 8, 2018, 11:23 PM, comlor <notifications@github.com> wrote:


The smooth modifier seemed to make the gaps worse. I forgot to mention that each of these tiles is in its own blend file and they are linked to this file. I tried making everything local(object, data, material) and applied the smooth modifier to each one and the gaps either went away or got worse when i increased the value of the smoothing.

**Comment by comlor** [comment]
Ok.  I tried what you suggested.  But after doing that when i link to the files they are not being placed properly.  I don't see how the subdivide would fix the gap between different meshes.  My problem does not have to do with surface detail.  I feel like there may be a disconnect between how I am explaining and you are understanding.  I have uploaded my project to a github repo https://github.com/comlor/blender.git.  This contains all files associated with my project.  All blends, DEM's, and textures.
DEM directory - Holds DEM tile Files
texture directory - Holds texture tile files
blends directory - Holds the blend file for each dem
master.blend has all 9 DEM's linked from the external blend files and is where is issue with gaps are.

All the DEM's were originally 1 very large BigTiff DEM(1.6GB).  I created a VRT using QGIS which is where these small DEMs come from.
All DEM's have been imported as RAW DEM and used delaunay triangulation to create the mesh.

I hope this better explains my problem.

**Comment by domlysz** [comment]
This gap is equal to an half of pixel because when importing a raster as DEM the mesh's corners are defined at pixel center to prevent some glitches in the displacement that appears when the vertices are placed at true corner. My advice : merge your tiles and import only one raster, I don't see any advantage to work with tiles in Blender, you will reach memory overflow anyway if you try to import a large amount of data.

However if you want to give it a try it's possible to change this "pixel center" behaviour to delete the gap : in the file _**operators/io_import_georaster.py**_ line 341 replace **`pxLoc='CENTER'`** by **`Loc='CORNER'`**.

**Comment by domlysz** [comment]
just see you use the RAW_DEM method so my proposal fix will not work. But it's the same problem, it create vertices at pixel center. Maybee you can just shift yours meshes using the half pixel distance

**Comment by comlor** [comment]
Ok.  Thank you for your help.  I was have to adjust mesh location by 1 pixel to compensate.  That is easy enough to do now that i know the details.  

The reason I am attempting tiles is I have very large amounts of data to model in 3D and I am creating flyover movies with the data.  I am creating low poly versions of each dem as well and am going to do a LOD system in BGE.  So the high poly meshes will be limited to very close to camera(ie: less than 1km).  Everything else will be low poly

Thank you for your helpl
